### ISSUE TITLE
Can't install via netinstall

### ISSUE THREAD

**Issue by mid-kid** [Steveice10/FBI#1]
I've installed your precompiled FBI.cia, and compiled sockfile for my pc (linux).
But, when trying to install via the network, I get "Install failed! I/O Error 0xb" on my 3ds' screen, and netinstall does not complain.
I don't really have any other debugging info i could give.

**Comment by Steveice10** [comment]
Made some changes and cleaned up some code a bit, and it should work now. Worked for me when I tested it, anyway. Let me know if it works for you and I'll close the issue.

**Comment by mid-kid** [comment]
Thanks, it works now.

**Comment by mid-kid** [comment]
Correction: It workED. It gets stuck at the "Reading info..." stage now.
