### ISSUE TITLE
[Feature Request] Directory filter

### ISSUE THREAD

**Issue by urherenow** [Steveice10/FBI#100]
For us lazy folk who place .cia files in the root (and have a bunch of .bin files from CFW and .sav files from GW, etc.) can you add an option while in SD mode to press L and/or R to toggle between complete listing and listing only .cia files?

**Comment by Steveice10** [comment]
Pressing left/right to quick scroll should suffice, no? Or the options for installing all CIAs in a directory.

**Comment by urherenow** [comment]
There are a few .cia files I just leave on my SD card, but Most are for testing. I usually only install 1 .cia at a time (usually, a fresh build of FBI) and the filter would take 1 button press where left/right would take several since the default also lists all of the directories, on top of the .sav files and what not.

I could probably do it myself, but it would definitely not be up to your standards and not worthy of a pull request.

**Comment by Kikoshi** [comment]
apart from the All Cia installation, how about being able to "pick" a assortment of them to install?

**Comment by Steveice10** [comment]
Added.
