### ISSUE TITLE
QR codes without "http://" or "https://" are not handled.

### ISSUE THREAD

**Issue by sirocyl** [Steveice10/FBI#103]
Attempting to scan such a URL, for instance "example.com/e" fails before connecting, with `0xD8A0A01E` from the HTTP module.
Scanning "http://example.com/e" does the expected behavior (404 from server).

I'd recommend looking in `qrInstallData->urls[index]` for "https://" or "http://", case-insensitive, at the beginning of `qrinstall_open_src()` in `/source/ui/section/qrinstall.c`, and if it doesn't exist, prepend "http://" to the string before continuing in that function.

**Comment by Steveice10** [comment]
...or just put the right prefix in the QR code.

**Comment by sirocyl** [comment]
I'd just like to note, that b1b36b1e78c90ae7f29091f3db58232f11144f13 fixes this issue. Thanks a bunch \o/
