### ISSUE TITLE
[Feature request] Split NAND title's from SD titles

### ISSUE THREAD

**Issue by Favna** [Steveice10/FBI#105]
Currently the (TWL)NAND titles are loaded right under the SD titles. For someone like myself and undoubtedly many others who already have many titles on the SD this is really annoying because while titles are loading scrolling is barely possible and just "lags". 

While the "lag" of scrolling while the titles are loading will stay for the long list of SD titles, by splitting NAND titles from the list of SD titles this still saves a good 10-30 seconds roughly (timed at 13 seconds by holding Right D-pad and started when the first NAND titles showed up).

Hope this can be implemented =)

**Comment by xuefer** [comment]
me too think it's strange to list them together. System titles should be separated from those titles installed which are listed in home as icons. maybe also move SD/Titles/*Install to the top of the menu too

**Comment by Steveice10** [comment]
Added in the form of filtering options.
