### ISSUE TITLE
Getting very low install speed

### ISSUE THREAD

**Issue by Kakoluz** [Steveice10/FBI#106]
last night I was installing some cias, and in certain point, speed decrease, took 9 hours to install 1,7GB.
But i have reinstalled it right now and get 20 mins, this could have be a puntual issue, but it isn´t, because i took like 40 attepmts to get a normal install speed, i get like 0.25MB each 5-10 seconds or less.

I have tried to install older versions, inject it in h&s, stills the same
SD Card is a 32GB SANDISK card from jaunary

It would be great to know the exact speed of installacion

**Comment by Steveice10** [comment]
Have not been able to reproduce... check your SD card for fragmentation, etc., I guess.
