### ISSUE TITLE
FBI/buildtools/3ds/bannertool-linux outdated?

### ISSUE THREAD

**Issue by 3xkrazy** [Steveice10/FBI#107]
Error output:
```
build/banner.bnr
buildtools//3ds/bannertool-linux: /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by buildtools//3ds/bannertool-linux)
buildtools/make_base:286: recipe for target 'build/banner.bnr' failed
make: *** [build/banner.bnr] Error 1
rm build/source/core/default.shbin.c
```
Replacing FBI/buildtools/3ds/bannertool-linux
with a fresh build from
https://github.com/Steveice10/bannertool.git
seems to complete the build with no errors.

**Comment by Steveice10** [comment]
Probably something related to your system if building it yourself works. Check that your environment is up to date.
