### ISSUE TITLE
Issue with installing games under my region

### ISSUE THREAD

**Issue by jem4687** [Steveice10/FBI#108]
I just setup a9lh with luma3ds and have been trying to use Shameless with FBI to install some stuff and for some reason can only install things that have a region of ALL, my 3ds is set to region USA and for some reason those don't work. I have tried turning on luma3ds region emulator and still no luck. I have asked HouseBreaker (shameless creator) and Plailect and both directed me to you. When installing  things using QR code I get to about 99% complete and then get this error 

Failed to Install: 0xD8E0806A
Level: Permanent (27)
Summary: Invalid argumet (7)
Module: AM(32)
Desc: Cert signature or hash check failed (106)

Any ideas on how to fix this region issue?

**Comment by Steveice10** [comment]
Likely beyond my help; the AM service is simply rejecting your CIA with that error.
