### ISSUE TITLE
Attempting to build results in a error

### ISSUE THREAD

**Issue by deadair3210** [Steveice10/FBI#109]
Attempting to build the current source as of 5/22 results in a error about too many arguments to the function httpcinit

$ make
build/source/core/default.shbin.c
build/source/core/default.shbin.o
build/source/main.o
source/main.c: In function 'main':
source/main.c:61:5: error: too many arguments to function 'httpcInit'
     httpcInit(0);
     ^
In file included from c:/devkitPro/libctru/include/3ds.h:42:0,
                 from source/main.c:3:
c:/devkitPro/libctru/include/3ds/services/httpc.h:23:8: note: declared here
 Result httpcInit(void);
        ^
make: *** [build/source/main.o] Error 1
rm build/source/core/default.shbin.c

**Comment by urherenow** [comment]
git clone https://github.com/smealum/ctrulib (don't do this in your FBI directory)
make ( in /ctrulib/libctru)
make install

**Comment by deadair3210** [comment]
Is there any sort of build guide for this, as I have run into another error.

undefined reference to `C3D_SafeDisplayTransfer'

**Comment by urherenow** [comment]
on the main page (and README.md): "Requires devkitARM and citro3d to build"

Install citro3d

**Comment by deadair3210** [comment]
Sorry about the newb questions, thought i had citro3d installed but forgot i had reinstalled devkitarm which wiped out all my installed libs

**Comment by CHOUAiB** [comment]
any solution for:

output/FBI.elf
build/source/core/screen.o: In function `screen_load_texture':
c:\devkitPro\msys\home\SERVER\3DS\FBI-master\FBI-master/source/core/screen.c:358: undefined reference to `C3D_SafeDisplayTransfer'
collect2.exe: error: ld returned 1 exit status
make: *** [output/FBI.elf] Error 1
rm build/source/core/default.shbin.c

-reinstall DevKitArm + ctrulib + citro3d and no success on compiling.

any idea how to fix this?

thanks

**Comment by urherenow** [comment]
Ummm... The last sentence doesn't tell you?

**Comment by urherenow** [comment]
You need to BUILD the latest source of ctrulib and citro3d and such and "make install", not simply install the latest released versions.

**Comment by CHOUAiB** [comment]
i did all what you said and always no luck :-(

**Comment by CHOUAiB** [comment]
i will try it on linux maybe windows 10 x64 is not suitable for compiling FBI.

**Comment by urherenow** [comment]
I build on Windows 10 64 bit.

**Comment by CHOUAiB** [comment]
Thanks. now it works fine

first install/update libs then download fbi src and compile.

**Comment by CHOUAiB** [comment]
thanks urherenow it works just fine.
