### ISSUE TITLE
Can not repair title.db on ique3ds

### ISSUE THREAD

**Issue by PTgame** [Steveice10/FBI#11]
I lost the title.db of my ique3ds.But unfortunately The ique3ds is not have Data Management -> Nintendo 3DS -> Software this option. because it is have no eshop in this.so is that another way to repair it?

**Comment by Steveice10** [comment]
If you had one before, how did you get it?

**Comment by PTgame** [comment]
The ique3ds is sale with two build in game (mario kart 7 and super mario bro 3d),so when it out of factory it have the title.db.But when you initialize or format it,the title.db will lost and can not be repaired like other verision.so i want find a way to repair it without normal way.

**Comment by PTgame** [comment]
![aaaa17fejw1ev1yv36jkxj21w02io1ky](https://cloud.githubusercontent.com/assets/13781513/9266555/5726eaee-4275-11e5-8731-539aa08ef765.jpg)

**Comment by PTgame** [comment]
In Data Management -> Nintendo 3DS there is only have a Extra data management.not have software management.

**Comment by Steveice10** [comment]
If you can't obtain software or regenerate the title.db through the settings, I have no idea how to help you then, sorry. :/
