### ISSUE TITLE
[Feature request] Sound notification after finished installation

### ISSUE THREAD

**Issue by outofrange** [Steveice10/FBI#111]
It would be nice to have some *bing* playing after the installation of one (or multiple) CIA file(s) is done.

This would not only allow to do some other business without looking at the 3DS, but would also make it easier to cope with #89, since it has been reported that only the screen freezes, not the installation process itself.

**Comment by Steveice10** [comment]
Going to have to decline; I'd rather not complicate things with a sound effect system for such a minor addition.
