### ISSUE TITLE
Some title is not listed as title but as code

### ISSUE THREAD

**Issue by xuefer** [Steveice10/FBI#112]
Most installed cia listed as English/Japanese title. but the following are not:

```
0004000****D0000 CTR-P-AGGW
0004000****E6000 CTR-P-BMPK
```
Is this cia issue or FBI issue? but FBI isn't listing itself using title
FBI is ```000400000F800100```

**Comment by Steveice10** [comment]
If it's listed as a title ID, either something is preventing it from retrieving the title's data (I believe I've seen this happen sometimes when a title is installed in emuNAND and viewed on sysNAND, or vice versa), or the title doesn't have any data included.

**Comment by xuefer** [comment]
It's installed in emuNAND and viewed on emuNAND
I have the health&safty apps injected/replaced by FBI while installing another up to date FBI as FBI. is that the reason causing FBI to show as code only?

**Comment by Steveice10** [comment]
Possibly. Do also note that the name it attempts to retrieve is based on the system language, if it's possible your system language wouldn't have titles for some applications.
