### ISSUE TITLE
Extract the needed config for citra

### ISSUE THREAD

**Issue by poutros** [Steveice10/FBI#115]
The config file is currently extracted like this:
https://github.com/citra-emu/citra/wiki/Home-Folder

Although you can skip quite a few steps and dump a decrypted ctrnand with decrypt9wip, the process of extracting the config file is still linux only and requires using the command line. It is extracted using this tool: https://github.com/3dshax/3ds but it would be good to have it directly extracted from FBI. The process would be
FBI->System Save Data->00010017->Extract config file for citra
The current option Browse Save Data errors out on this id btw.

**Comment by Steveice10** [comment]
I don't currently plan on adding special functions for certain specific use cases like citra's. Plus, you should be able to accomplish this with either save data browsing or NAND browsing (I'm not 100% familiar with what exactly citra needs).

**Comment by poutros** [comment]
>  if it errors trying to browse the save data, I wouldn't be able to dump from it anyway.

Not true since JKSM is able to dump some saves that FBI doesn't seem to be able to like StreetPass Mii Plaza. Plus, you can already access, delete and copy the file that contains the config file using FBI itself. You would need to implement a way to extract it the way 3dsfuse does.

**Comment by Steveice10** [comment]
What I'm saying is if it errors opening it with the browser, it'll error when I open it to dump a file. If another tool is able to do it, there may be something I can do to fix it if you get me the error information.

**Comment by poutros** [comment]
> What I'm saying is if it errors opening it with the browser, it'll error when I open it to dump a file.

But you can already dump the file that contains the needed file through FBI itself.

Basically, there is a file at CTR NAND->data\(id1)\sysdata\00010017\ named 00000000. That file is in the IVFC format and Citra needs the bare file content. That bare file content is currently extracted using 3dsfuse but that is a linux and command line only option and lacks proper usage documentation besides the first link I posted. I will open another issue related to fbi not being able to dump some saves.

**Comment by Steveice10** [comment]
Just because the file can be seen in the CTR NAND doesn't mean it won't error trying to access its contents through the standard archive system.
