### ISSUE TITLE
Crash to home menu when attempting to install and delete tickets

### ISSUE THREAD

**Issue by deadair3210** [Steveice10/FBI#116]
As of the latest version (2.2.3), FBI will crash to the home menu or in some rare cases freeze on a black screen when attempting to install and delete a large amount of tickets at a time. Attempted to install a folder of tickets and delete afterwards on a O3DS and an O3DS XL both on 11.0 A9LH and got the same result each time, barring one time on the xl at which the app froze on a black screen and had to be forced to power off

**Comment by deadair3210** [comment]
This did not happen with 2.2.1, meant to put that in the issue but forgot

**Comment by Steveice10** [comment]
Is this with or without CDN installation?

**Comment by deadair3210** [comment]
This is without CDN installation, and happens before the tickets start installing. The older version used to lag for a while, but would eventually continue to ask to install and then proceed to install the tickets. 2.2.3 crashes when the old versions would lag but proceed

**Comment by Steveice10** [comment]
Have you tried 2.2.2? Would help to narrow it down if you could.

**Comment by deadair3210** [comment]
i will try it and get back to you

**Comment by deadair3210** [comment]
Ticket install seems to work fine in 2.2.2, while crashing to home menu and forcing the system to restart.

**Comment by Steveice10** [comment]
This build should fix your issue then:

https://www.dropbox.com/s/ufvyl5o7n4c4ykn/FBI.zip?dl=1

**Comment by deadair3210** [comment]
Trying now

**Comment by deadair3210** [comment]
Seems to be installing the tickets fine! Thanks
