### ISSUE TITLE
Auto-update?

### ISSUE THREAD

**Issue by PokeAcer549** [Steveice10/FBI#118]
Surely some sort of update option or auto-update check via SpotPass would be possible, so that users wouldnt have to constantly check? :P

**Comment by PokeAcer549** [comment]
Auto-Update could be based from GitHub - a file in the repo that says the latest link and it's version.
And not everyone checks the GBATemp thread religiously.

**Comment by OTFree** [comment]
Quick question, what tempGBA thread is it posted? I can't find it.

**Comment by Steveice10** [comment]
@PokeAcer549 If you needed an update for a fix or feature, wouldn't you be watching for one?

**Comment by Steveice10** [comment]
Ehh... why not. Added.
