### ISSUE TITLE
FBI is unable to dump some saves

### ISSUE THREAD

**Issue by poutros** [Steveice10/FBI#119]
Games:
StreetPass Mii Plaza:
```
Result code:0xC8804478
Level: Status (25)
Summary: Not found (4)
Module: FS (17)
Desc: Doesn't exist/Failed to open (120)
```
JKSM works fine on this title.

Any system title:
```
Result code:0xE0C046F8
Level: Usage (28)
Summary: Not supported (6)
Module: FS (17)
Desc: Unsupported operation (760)
```
JSKM works with most if not all of them(have only tested with a few ones)

**Comment by Steveice10** [comment]
Those do not have normal save data. What you're looking for is under the "System Save Data" menu, which is different. JKSM must simply expose them in the same way.
