### ISSUE TITLE
Could not initialize AM services

### ISSUE THREAD

**Issue by CSOmini** [Steveice10/FBI#12]
When I want to install any .cia there is "Could not initialize AM services". Deleting a .cia works, but installing isn't working. Could you make an installation guide or could you help me? I only got Homebrew, no flashcard.

**Comment by Steveice10** [comment]
How are you launching FBI? .CIA? .3DS? Ninjhax 1.x? Ninjhax 2.x? Also, what firmware version?

**Comment by CSOmini** [comment]
Firmware is 9.9E. I'm using tubehax. I launch with homebrew, so I think I
use .3DS
Am 21.08.2015 10:36 schrieb "Steven Smith" <notifications@github.com>:

**Comment by urherenow** [comment]
Emunand? If your sysnand is 9.9, then FBI can never work for you. Nothing above 9.2 has kernel access.

**Comment by CSOmini** [comment]
I haven't got any flashcard and no emunand. Well... then, thanks for your
help.
Am 21.08.2015 15:43 schrieb "urherenow" <notifications@github.com>:

**Comment by Steveice10** [comment]
Resolved. FBI currently does not work through Ninjhax 2.0/tubehax/ironhax.

**Comment by giooooo11** [comment]
hi i need help i have my new 3ds and intstall fbi and pasta but when i wanna installa cia this happend to me say install failed could not initialize a, service plis awnder me
