### ISSUE TITLE
Would the built-in updater work with injected H&S?

### ISSUE THREAD

**Issue by dbw-holic** [Steveice10/FBI#121]
I have been keeping FBI in an injected hs.app and its working well for me.
Just wondered if I re-inject this to my hs.app, and I process an update, would it actually work for that? 
Or it needs to be a standalone version? 

Many thanks.

**Comment by Steveice10** [comment]
It won't. There's no way, as far as I know, that I would be able to make it work with injected H&S. If you run the updater option from H&S, it'll just install the standalone version, assuming there's a newer version out than reported by the version string in the top left of the top screen.
