### ISSUE TITLE
Always getting black screen

### ISSUE THREAD

**Issue by Shadowxp13** [Steveice10/FBI#124]
I'm using a New 3DS in 10.7U with oothax.
When i try to launch FBI 2.0 in the homebrew launcher, it only gives me a black screen.
I know that SVCHAX sucess rate is really low on my version, but with a FBI 1.4 build using svchax from zoogie (gbatemp user) works normally. This happens with all launcher that i have, what should i do?

**Comment by urherenow** [comment]
Install the .cia and stop using the .3dsx.

**Comment by Shadowxp13** [comment]
I'm on 10.7 and don't wanna downgrade, so cia version isn't an option

**Comment by urherenow** [comment]
Downgrading and using CFW is your ONLY option. FBI is of no use to you otherwise. Either way, this isn't a bug.

**Comment by mariomadproductions** [comment]
"FBI is of no use to you otherwise" is clearly untrue. Which was the last version to work?
