### ISSUE TITLE
Crash when suspending FBI (pressing home button) while installing CIA

### ISSUE THREAD

**Issue by Cruel** [Steveice10/FBI#125]
I believe this can be prevented with respective AM Stop/Resume calls in APT callback, though I haven't tested yet myself.

**Comment by Steveice10** [comment]
CDN installations shouldn't encounter this problem anymore. However, AM does not provide commands to stop/resume CIA installation. Using the stop/resume commands for titles provided by am:net wouldn't work either, as I would also need access to the content installation handle(s) in use during the CIA installation to stop/resume them as well.
