### ISSUE TITLE
Dump nds game's saves

### ISSUE THREAD

**Issue by poutros** [Steveice10/FBI#127]

**Comment by TuxSH** [comment]
You can use [TWLSaveTool](https://github.com/TuxSH/TWLSaveTool/releases/tag/v1.1_pmd_eos_stub) for that task :yum:

**Comment by poutros** [comment]
@TuxSH That's actually what I am using but given how FBI can already mange 3ds game saves, it would be nice to have it manage nds saves. Maybe even add dsiware save support.

**Comment by TuxSH** [comment]
Oh ok.

**Comment by Steveice10** [comment]
Added for game cards, although I only have so many games to test with, so use with caution.
