### ISSUE TITLE
Lasted build doesn't work

### ISSUE THREAD

**Issue by Matsumot0** [Steveice10/FBI#13]
Hi, since your lasted "update for citrus" build #3ec9c0b, FBI crash on my o3ds eur sysnand 4.5/emunand 9.9 under Cakes cfw. Anyway the first and second build of 1.4.9 works fine.

I don't know if you're already aware of this problem.
Good job for this great homebrew :+1:

**Comment by Steveice10** [comment]
I'm aware of this issue, I just haven't been able to fix it yet.

**Comment by Steveice10** [comment]
Fixed yesterday.
