### ISSUE TITLE
Region/Country discrepancy 

### ISSUE THREAD

**Issue by TheDgtl** [Steveice10/FBI#131]
Saw someone posted an issue here about 0xD8E3FBFD: https://gbatemp.net/threads/release-fbi-open-source-cia-installer.386433/page-137#post-6402442

Took a look at what FBI was doing in regards to the Seed stuff and just realized it seems to be mixing up Country/Language codes.

https://github.com/Steveice10/FBI/blob/master/source/core/util.c#L275

There's an array of Region strings, based on the CFG_Region enum from the looks of it, but the code is then calling CFGU_GetSystemLanguage, which will return CFG_Language. So in this users case, their system is probably set to Russian, which returns 10, which is higher than CFG_REGION_TWN (6)

**Comment by Steveice10** [comment]
Thanks for pointing that out, don't know how I missed it.

**Comment by Cruel** [comment]
Oh, guess that explains why it usually failed (my console language is portuguese) lol.

Though have you ever encountered a title where the country code in this url mattered? Seems to give me the seed with any two letters.

**Comment by Steveice10** [comment]
I noticed that, but kept the country code stuff in just in case it ever matters.
