### ISSUE TITLE
Allow batch usage of the seed command for games

### ISSUE THREAD

**Issue by deadair3210** [Steveice10/FBI#132]
Add an option for updating the seed for all games installed, or at least a subset. Useful for things such as CIAngel and freeshop where the eshop is not wanted to be opened for one reason or another. It become tedious to have to select each game and fix the seed, and if a large list of games are downloaded at once, the user might not even remember which games need it vs not needing it

**Comment by Steveice10** [comment]
CIAngel and freeShop now install the seed automatically, as does FBI when a title with a seed is installed. Not sure if this would really be necessary.

**Comment by deadair3210** [comment]
Opened this issue before freeshop added seed support. Thanks for responding to it anyway
