### ISSUE TITLE
[Suggesstion] [File Manager]Make Y button menu a universal option menu

### ISSUE THREAD

**Issue by dogtopus** [Steveice10/FBI#133]
Merge file and directory options into one menu, do operations based on current selection.
The current design (split file and dir options) is a little bit weird IMO (and I almost `rm -rf /`'d my SD card thanks to that *cough*)

**Comment by Steveice10** [comment]
How do you "accidentally" almost delete your SD when you have to press Y to open the directory menu, it shows the directory being operated on, and you have to select delete and confirm it?

**Comment by dogtopus** [comment]
Well, I tried to delete a empty directory in the root of SD card and I somehow thought the Y menu was the normal option menu and... BOOM

**Comment by Steveice10** [comment]
Once again, though, it shows the path on the top screen.

**Comment by Steveice10** [comment]
If anything, I might bring back the use of the "." entry to act on directories, as I'd like to keep A as the action button.

**Comment by Steveice10** [comment]
Should be easier to understand now.
