### ISSUE TITLE
Problem with the menu on FBI.

### ISSUE THREAD

**Issue by GambitK** [Steveice10/FBI#135]
FBI acts as if I have "up" pressed on the D-PAD. If I go down and let go it will go to the first option of the menu. 
I can select options if I hit A on any of them but the selection doesn't stay still until it has reached the top option of the current menu.
I have a n3ds on arm9lh, latest luma3ds, and sysnand 10.6

**Comment by Steveice10** [comment]
Are you sure you aren't accidentally pressing left (page scroll up), up on the circle pad, or touching the screen?

**Comment by GambitK** [comment]
The only recent change that I have made is move from Sysnand+Emunand to Updated sysnand. FBI was installed on Emunand the first time. I have tried without success:

1) Reinstall FBI.
2) Install the original Health app and install FBI again.
3) Recreate the injected FBI app with the original hs.app.
4) Tested the older version and it has the same problem. 

It would seem that the problem is FBI, the thing is that if I start DevMenu or SaveDataFilter it doesn't happen. On the homemenu it doesn't happen, or in games either. 
What could be causing this?

**Comment by Steveice10** [comment]
Does this happen on any other *homebrew* applications?

**Comment by GambitK** [comment]
No, In the video I show DevMenu opened without the issue.

With the testing build: On the top left it reads: 0x40000000 without any button pressed.

When I hit down it changes to: 0x40000080 and when released it goes back to 0x40000000.
When I hit right it changes to: 0x40000010 and when released it goes back to 0x40000000.
When I hit up it changes to: 0x40000040 and when released it goes back to 0x40000000.

Seems like is not moving from reading button input.

**Comment by Steveice10** [comment]
DevMenu is not homebrew software, it's from the Nintendo SDK. I meant something created with ctrulib.

**Comment by GambitK** [comment]
After trying to calibrate the circle pad seems like it has some issues for some reason. The down only goes up to half.
I'm going to try and replace it and see if that's the issue.
Thanks for your time and help.
