### ISSUE TITLE
Possible enhancement when using "Install and delete CIA"

### ISSUE THREAD

**Issue by TheNain38** [Steveice10/FBI#136]
When using the option "Install and delete CIA", could it be possible to install, AND delete the CIA at the same time, so, it would not require double the space on the SD card? Also, you won't be able to abort this one, without destroying the CIA.

It'll be useful for persons running low on SD card space

**Comment by Steveice10** [comment]
No, it isn't.

**Comment by TheNain38** [comment]
Why exactly? I mean, what are the limitations? You can't read a sector, then free it, and write at that same place in a stream fashion? (Because you can install CIAs using the network, so, that means you can install one in a streaming fashion, no? (Except if you download it entirely, and then install it, but it's not efficient then))

**Comment by Steveice10** [comment]
I can't delete a file without deleting the whole thing.
