### ISSUE TITLE
Logs or Button Config

### ISSUE THREAD

**Issue by alaindesjardins** [Steveice10/FBI#141]
I was installing titles from CDN and one failed (possibly because titles larger than 2GB fail) so I picked up my console to read the title ID to see what it was and I hit the right bumper when picking it up so the dialog closed and it moved on to the next ticket.  Is it possible to re-assign button mapping so I don't hit bumpers by accident when picking up my console?  What about a log file for what FBI does so I can read it in the event it freezes, crashes or I make a mistake like hitting the button?

**Comment by Steveice10** [comment]
Just don't hit the button. Not really enough of an issue to warrant these changes.
