### ISSUE TITLE
(2.3.0) Failed to update FBI

### ISSUE THREAD

**Issue by Yoshistar95** [Steveice10/FBI#147]
As 2.3.1 was released, I wanted to update it to that version, but I get this message after it tries to download/install the new version:

Failed to update FBI.  
Result code: 0xE0E046BE  
Level: Usage (28)  
Summary: Invalid argument (7)  
Module: FS (17)  
Desc: Invalid path / Inaccesible archive (702)

Gonna try QR instead, hope that one works.

**Comment by Yoshistar95** [comment]
(stupid edit button doesn't work on 3DS)

Nothing happened when I installed it through QR, 2.3.0 is the only version I have which can do this, am I forced to get the .cia manually?

**Comment by Committee** [comment]
latest release note:

- Fix updating from installed FBI.

Yes you will have to manually update.
