### ISSUE TITLE
Batch CIA install count Incorrect 

### ISSUE THREAD

**Issue by RohitJones** [Steveice10/FBI#148]
When you install a number of CIA files in a folder, during installation, the currently installing CIA's count starts from 0 instead of 1.
Example: if there are 5 CIA files in a folder, during batch install the count of CIAs is displayed as follows.
Installing 0/5
Installing 1/5
Installing 2/5
Installing 3/5
Installing 4/5

Installation complete!

**Comment by Steveice10** [comment]
Intended.
