### ISSUE TITLE
Trying to do anything with Jam With The Band fails

### ISSUE THREAD

**Issue by PokeAcer549** [Steveice10/FBI#149]
Attempting to import, export or erase Jam With The Band (Band Bros DX.) fails. It's likely because of the 8MB chip inside the cart - other things such as TWLTool do not work either (beta code was added in an attempt to try to fix this but it failed).

Would support be possible?

EDIT for the ~~idiots~~ people who wanted to know: I'm using A9LH to boot Luma3DS with an 11.0 sysNAND

**Comment by v0idst4r** [comment]
What cfw are you using when installing it? (Yes I know this has nothing to do with answering your question)

**Comment by Ketchup901** [comment]
Why are you asking it then?

**Comment by v0idst4r** [comment]
Because I'm curious. I'm also friends with the OP so I don't think he'd mind telling me..

**Comment by ihaveamac** [comment]
kind of the wrong place to ask...

**Comment by v0idst4r** [comment]
Maybe it'll help resolve the issue who knows

**Comment by urherenow** [comment]
The question is more than relevant. What CFW? Sysnand or emunand? Updated sysnand on a9lh? FBI on home menu or HBL? These questions should have been answered in the original post.

**Comment by v0idst4r** [comment]
Mhm

**Comment by PokeAcer549** [comment]
No, it's really not relevant. I am using FBI with escalated privileges, that's all that matters for DSi Support. My issue is regarding the 8MB chip in those carts...

**Comment by v0idst4r** [comment]
You're in sysnand correct?

**Comment by PokeAcer549** [comment]
...HOW DOES THAT AFFECT MY USAGE OF A DSi GAME VIA FBI

**Comment by v0idst4r** [comment]
BECAUSE YOU CANT INSTALL DSI SHIT ON EMU

**Comment by PokeAcer549** [comment]
....
How old are you? Can you actually read?
1. Jam With The Band/Band Bros DX is a DSi CARTRIDGE GAME
2. I am putting an issue about SAVEDATA ACCESS on the DSi CARTRIDGE GAME.
3. You can install DSiWare on emuNAND, you just have to copy to sysNAND (and that's why you get an A9LH 11.0 sysNAND)

**Comment by v0idst4r** [comment]
Check your skype man -_-

**Comment by master861** [comment]
Thit your install it with fbi if yes is it listet on fbi on titles tab if it listet ther press a then your should see this 
Launch title
delete title
delete title and ticket

**Comment by PokeAcer549** [comment]
... :facepunch:

**Comment by weirdal3333** [comment]
Does this only happen with that specific game, or does it affect other games with the 8mb chip in them?
If I can find an 8mb chip game, I'll look at it on my end as well (I have the same setup).

**Comment by PokeAcer549** [comment]
No no no, silly GitHub; yes it happens with most 8MB save-chip games.

**Comment by Steveice10** [comment]
Importing to 8MB flash is explicitly disabled, so it should definitely error, but exporting should try to do it like it does with other flash chips. What exactly is the result of trying to export this game's save?

**Comment by PokeAcer549** [comment]
I believe it fails, I'll try now.

**Comment by Steveice10** [comment]
The exact error it fails with would be helpful.

**Comment by PokeAcer549** [comment]
It just freezes on 0.00 B / 0.00 B, and refuses to exit until you open home menu.

**Comment by Steveice10** [comment]
Judging by [this](https://github.com/profi200/savegame-manager/blob/master/arm9/source/auxspi.h#L41), it seems this game uses some kind of extra protection against reading the save chip, and there isn't really much info out there on what it is or how to bypass it.

**Comment by PokeAcer549** [comment]
Damn... I'm guessing nobody wants to RE it :P

**Comment by Normmatt** [comment]
the english one uses the ds equivalent of card2 commands to read/write to saves... so the normal eeprom/flash stuff will never work.

The japanese release did use an 8mb eeprom but the usa/eur release used 16mb card2.

**Comment by Steveice10** [comment]
In that case, I think I'll have to simply close this as won't/can't fix.
