### ISSUE TITLE
Possible to report New 3DS flags from exheader?

### ISSUE THREAD

**Issue by vaguerant** [Steveice10/FBI#150]
Sorry if this is outside scope, but would it be possible to report the CPU speed, L2 cache and RAM mode flags of titles when viewing them in FBI? e.g. Games like Super Smash Bros. for Nintendo 3DS, Monster Hunter 4, Xenoblade Chronicles all use N3DS features to various degrees, but I'm not aware of any convenient way to check a) whether a game is enhanced or b) in what way, using current tools. Perhaps this would be a useful addition to the other details currently listed like title ID, version and product code?

**EDIT:** If this would produce a delay when loading titles, it could alternatively be added to a separate "detailed view" in the selection menu if that's preferable.

**Comment by Steveice10** [comment]
Not planned, as it would require more complex CIA file parsing to find if a CIA even contains an NCCH and access its exheader, plus the situation where a CIA might have multiple.

**Comment by vaguerant** [comment]
Ah, too bad, but thanks.
