### ISSUE TITLE
Export Save from Scribblenauts Unlimited does not work

### ISSUE THREAD

**Issue by xadox-1st** [Steveice10/FBI#151]
I am not able to backup the save file from Scribblenauts Unlimited 00040000000a5b00.

The Savefile is called Savecard.dat.
Like also with other SaveManagers, like JKSM or SDF, FBI is not able to backup/copy the file.

> Result code: 0xD900458B
Desc: Invalid RomFS or save data block hash (395)

SaveDataFiler log:

> === File Tree ===/+--Savecard.dat=== File Copy ===
CopyFile: save:/Savecard.dat => sdmc:/filer/UserSaveData/20160630071107/00000a5b/Savecard.dat (410180 Byte)
  [VerificationFailed:D900458B] File broken: [0x000000CA00 - 0x00000125FF]
  [VerificationFailed:D900458B] File broken: [0x0000018600 - 0x000001A1FF]
  [VerificationFailed:D900458B] File broken: [0x000001C400 - 0x000002F7FF]
  [VerificationFailed:D900458B] File broken: [0x0000031A00 - 0x00000567FF]
  [VerificationFailed:D900458B] File broken: [0x0000058800 - 0x0000064243]

**Comment by Steveice10** [comment]
As the error message and SaveDataFiler logs say, the save is probably broken.

**Comment by xadox-1st** [comment]
Actually the game plays fine. It loads the savegame like it should.

**Comment by Steveice10** [comment]
Well, if SaveDataFiler is having issues and FBI as it is has issues, it's not likely this is an issue I can fix.

**Comment by xadox-1st** [comment]
Ok.
