### ISSUE TITLE
Just a very simple UI-related suggestion

### ISSUE THREAD

**Issue by flarn2006** [Steveice10/FBI#153]
You know how it says "A: Select, START: Exit" at the bottom of the screen? Well it appears you're using the built-in system font. That font actually contains a lot of system symbols in the Unicode Private Use Area. There's a nice "A button" symbol at U+E000 that you can use there. I'd recommend having it say "A - Select | START - Exit" only with U+E000 (, which looks like a magnifying glass on Github for some reason) instead of the A at the beginning.

By the way, if you want to see a list of all the symbols, go to [this page](https://sites.google.com/site/comjacker/games/nintendo-symbols). If you open it in the 3DS browser ([QR code](http://i.imgur.com/OUkNTQF.png)), you can actually see the symbols.

**Comment by Steveice10** [comment]
The problem is it seems that certain buttons, like start and select, don't have font glyphs, which would have given the biggest advantage by saving space. If I'm not going all the way with glyph buttons, then I might as well keep it as-is to retain source code string readability.

**Comment by flarn2006** [comment]
Oh okay, that makes sense. Just thought I'd suggest it in case you didn't know those glyphs were there.
