### ISSUE TITLE
Failed to delete content 0xC92044FA

### ISSUE THREAD

**Issue by digo94** [Steveice10/FBI#155]
Since when I started to use the FBI (version 1.4.x), always had the following error when trying to delete some games.

> **Error**
> **Failed to delete content.**
> Result code: 0xC92044FA
> Level: Status (25)
> Summary: Canceled (9)
> Module: FS (17)
> Desc: < unknown > (250)
> **Okay (Any Button)**

I tried to rename the files, yet the error persists, having to use the computer to delete the file.

> **Error**
> **Failed to perform rename.**
> Result code: 0xC92044FA
> Level: Status (25)
> Summary: Canceled (9)
> Module: FS (17)
> Desc: < unknown > (250)
> **Okay (Any Button)**

**Comment by digo94** [comment]
titleid 0004000000057600
![1 rayman](https://cloud.githubusercontent.com/assets/20273548/16549849/bb469160-4179-11e6-94ea-4a15b330648c.jpg)

--

titleid 00040000000CCE00
![2 dk](https://cloud.githubusercontent.com/assets/20273548/16549851/bb5d91bc-4179-11e6-866a-aa5618417deb.jpg)

--

titleid 00040000000A2D00
![3 mickey](https://cloud.githubusercontent.com/assets/20273548/16549850/bb5d0e2c-4179-11e6-80c3-6f212d51223c.jpg)

**Comment by Steveice10** [comment]
If they aren't already in the root, could you try putting files that don't work in the SD card root directory and deleting them?

**Comment by digo94** [comment]
I found the cause of the error. The file attribute was set to "Read-only".

![read-only](https://cloud.githubusercontent.com/assets/20273548/16715059/7071c6ea-46ac-11e6-9faa-b95a4039889c.png)

Sorry for the inconvenience, but taking advantage, there would be a way to implement a function that allows this type of file is deleted or renamed? Or just handle the error, and display an alert message. Many downloads are being distributed as "Read-only".

**Comment by Steveice10** [comment]
I've added these attributes to the information display on the top screen, and I've added a description for the error code. Unfortunately, it seems I can't actually add a way to change these attributes from FBI, as FS returns "Unsupported operation" errors.
