### ISSUE TITLE
Seed import failed

### ISSUE THREAD

**Issue by Monotek18** [Steveice10/FBI#156]
I have a problem with the Seed import function, it say "error 404"
![img_20160710_102055928](https://cloud.githubusercontent.com/assets/20025273/16712515/e661d4c6-4689-11e6-8389-53a320b790f4.jpg)
![img_20160710_102059624](https://cloud.githubusercontent.com/assets/20025273/16712516/f40bcf5a-4689-11e6-90c1-79e50d3ce3de.jpg)
![img_20160710_102102976](https://cloud.githubusercontent.com/assets/20025273/16712523/21203864-468a-11e6-9e36-3ba4503480c7.jpg)

Normal ? I did something wrong ?
It's with Pokemon saphir alpha (I don't have the ticket)

**Comment by ihaveamac** [comment]
I'm pretty sure this game doesn't have a seed.

**Comment by Monotek18** [comment]
It's like that for every game.
Or maybe I am dumb and I don't know what is "Seed" ?
I thinked it was a thing to install a ticket, but no.
Hum maybe the dev should add an "Ticket installer" when you select a title in the Title list.
Or a thing to install every ticket I don't have. (A mass ticket downloader)

**Comment by Steveice10** [comment]
* A seed is what is used to decrypt the second layer of encryption on many newer 9.6+ titles.
* Ticket cannot be downloaded, nor will I be implementing a fake ticket generator for various reasons.
