### ISSUE TITLE
Suggestion: Search function for titles

### ISSUE THREAD

**Issue by shad00m** [Steveice10/FBI#157]
Is it possible to add a search or at least sort function in the titles menu?
I'm trying to delete a couple of games I don't like anymore but scrolling takes quite some time as the games are scattered all around
thank you :)

**Comment by Steveice10** [comment]
I currently don't plan to add this. The problem with sorting is that I'd have to actually load all of the information before I can sort it, which would take a long time. Searching would be problematic for the same reason, as things like names wouldn't be available to search until all the information is loaded, and by that time, scrolling is no longer really an issue.
