### ISSUE TITLE
2.3.3 make failed

### ISSUE THREAD

**Issue by LITTOMA** [Steveice10/FBI#158]
make log:
> output/FBI.elf
> fatal: Not a git repository (or any of the parent directories): .git
> build/source/core/screen.o: In function `screen_load_texture`:
> /FBI-2.3.3/source/core/screen.c:`353`: undefined reference to `C3D_SafeDisplayTransfer`
> collect2.exe: error: ld returned 1 exit status
> make: *** [output/FBI.elf] Error 1

which version of citro3d did you used?

**Comment by urherenow** [comment]
Don't ask. Just update both citro3d and ctrulib. Pretty much any time you have compiling errors.

**Comment by LITTOMA** [comment]
Both of them have been up to date.

**Comment by urherenow** [comment]
Just now updated to the latest source. Builds fine. If you're sure ctrulib and citro3d are updated, delete your FBI directory and clone again.

Git clone --recursive <url>
