### ISSUE TITLE
Sort "Install and delete all CIAs"

### ISSUE THREAD

**Issue by digo94** [Steveice10/FBI#159]
When using the option "Install and delete all CIAs" would be more effective order by size (smallest to largest) instead of ordering by name.

For example, I put five .cia games in SD Card and the available space is 1GB.

Within the SD Card I have the following .cia games:

Game A - 1GB
Game B - 2GB
Game C - 1GB
Game D - 1GB
Game E - 1GB

If I install in order of size (from lowest to highest) will be able to install all games up to 1GB. In alphabetical order would fail to install the Game B on, because there will be no space available.

Order by Name:
Game A - 1GB (Installation OK)
Game B - 2GB (Fail, no space available)
Game C - 1GB (Fail, due to Game B)
Game D - 1GB (Fail, due to Game B)
Game E - 1GB (Fail, due to Game B)

Order by Size:
Game A - 1GB (Installation OK)
Game C - 1GB (Installation OK)
Game D - 1GB (Installation OK)
Game E - 1GB (Installation OK)
Game B - 2GB (Fail, no space available)

Another solution would be to continue installing other .cias, even if there is a fail on the way.

**Comment by Steveice10** [comment]
CIAs already continue to install despite one failing.
