### ISSUE TITLE
Issue Upgrading from 1.4.17 to 2.3.3

### ISSUE THREAD

**Issue by mdfntr** [Steveice10/FBI#161]
I have a N3DS XL (US) running the latest firmware (11.0-33). I am booting from SysNAND with A9LH and Luma3DS v5.5 and Homebrew Menu v1.1.0.

The old version of `FBI.3dsx` alongside `FBI.smdh` in `/3ds/FBI` works properly and displays version 1.4.17.

If I remove (both) these files and replace them with `FBI.3dsx` from the 2.3.3 release, FBI panics with the message "Failed to acquire kernel access."

What is going on here? Am I missing a component?

**Comment by urherenow** [comment]
why are you using HBC from a9lh? Load up 1.4.17 and if it actually installs stuff (not sure if 2.3.3 is failing) then use it to install the .cia of 2.3.3. It will work perfectly fine from the home menu.

**Comment by Steveice10** [comment]
The old version of FBI probably doesn't actually work to install anything when run as a 3dsx on that firmware. The difference is the new FBI informs you of the problem early on.

**Comment by mdfntr** [comment]
Good to know! Thanks for the information. It was sitting around in the /3ds folder and I was trying to see if it worked or not and trying to keep everything up to date.
