### ISSUE TITLE
3dsx FBI behaving improperly when it should have elevated access

### ISSUE THREAD

**Issue by twocows** [Steveice10/FBI#162]
I have a stock 9.2.0-20U sysnand (no a9lh) set up on my o3ds. I'm attempting to use the 3dsx version of FBI (latest release) to install the cia version of FBI (latest release) to sysnand. In order to do this, I believe I need some form of signature check patching so that FBI can install the title.

1. Doing this using minipasta, 3dsx FBI seems to act as though it doesn't have the access that it should have; selecting fbi.cia just brings up delete/rename/etc. and it doesn't seem to have access to ctr-nand
2. Doing this using Cakes CFW (latest stable version) with enable emunand off and disable signature patches on, 3dsx FBI crashes immediately when loaded

I recall doing this several months ago with an older version of FBI and not having any issues. I do have emunand set up on it now (I didn't back then), but I'm not loading that in this process at all, so I can't imagine it would affect anything.

I can provide additional information if it would be useful.

**Comment by Steveice10** [comment]
The problem is something that seems to be related to some recent changes in ctrulib messing with svchax, failing to get the service permissions it needs. See https://github.com/aliaspider/svchax/issues/4

**Comment by twocows** [comment]
Do you know what the most recent release of FBI is that doesn't have this issue? I take it I can use an older version of FBI.3dsx to install the current version of FBI.cia onto sysnand just fine.

**Comment by Plailect** [comment]
This should have been fixed with https://github.com/Steveice10/FBI/pull/179, please test.

**Comment by twocows** [comment]
Yep, seems to be working now using 2.4.2.
