### ISSUE TITLE
screen.c:358: undefined reference toC3D_SafeDisplayTransfer'   - make: *** [output/FBI.elf] Error 1

### ISSUE THREAD

**Issue by CHOUAiB** [Steveice10/FBI#165]
is there any solution for:

output/FBI.elf
build/source/core/screen.o: In function screen_load_texture': c:\devkitPro\msys\home\SERVER\3DS\FBI-master\FBI-master/source/core/screen.c:358: undefined reference toC3D_SafeDisplayTransfer'
collect2.exe: error: ld returned 1 exit status
make: *** [output/FBI.elf] Error 1
rm build/source/core/default.shbin.c

-reinstall DevKitArm + ctrulib + citro3d and no success on compiling.

any idea how to fix this?

thanks

**Comment by CHOUAiB** [comment]
btw i'm using windows to compile FBI

**Comment by Steveice10** [comment]
Build and install citro3d from the latest source.
