### ISSUE TITLE
Use connection keep-alive header!

### ISSUE THREAD

**Issue by ksanislo** [Steveice10/FBI#170]
Please add the keep alive header for http when using titledb, you're causing far too many new connections without it. Check the http 3ds-example update I posted a few days ago for the details if you need more info.

**Comment by Steveice10** [comment]
Pardon my lack of HTTP knowledge in some areas. Is this sufficient? https://github.com/Steveice10/FBI/commit/ac4646613f4fb9f6fb895913b8ef17643313f8ce

**Comment by ksanislo** [comment]
Replied to the commit, oops, re-pasting here:

Yeah, that should be plenty... the 3DS has support enabled by default, you just need the header to advertise to the server you can support it. There shouldn't be any surprises while using it, it just makes httpc hold the socket for a few seconds in case there's another request. It should make the image loading dramatically faster.

You might however consider switching to using the SMDH icons that can be provided over the API instead of collecting the PNG images independently. In the /v0/ implementation they're just zlib compressed then base64 encoded, in /v1/ they're going to be uncompressed base64 and you can just use Transfer-Encoding: gzip on the whole stream instead.

**Comment by Steveice10** [comment]
I wasn't aware that the API provided SMDH icons; what endpoint are they served from?

**Comment by ksanislo** [comment]
Yeah, /v0/ got a bit hackey as I added more things on to it. The upcoming /v1/ is a full rewrite thats a bit more of a standard REST style API, and provides much faster responses. It will maintain compatibility with all the /v0/ URLs as they are however, so existing releases written against it shouldn't have any trouble.

Let me know if you have any problems or have any direction about other features you'd like to see implemented in the backend.

**Comment by Steveice10** [comment]
The only thing that comes to mind is, as I've brought up before, exposing the TMD version value as an API field, allowing clients to easily check if the version on TitleDB is newer than the one installed.

I think I'll be waiting for API v1 to tweak FBI's support a bit more, as it sounds like it'll be easier to use, plus I don't want the additional dependency of zlib for decompressing icons. I'll be leaving this issue open as a reminder.

**Comment by ksanislo** [comment]
Alright, /v1/ is probably still a few weeks away since I really only have a few hours a week I can throw at this. The Keep-Alive header alone is plenty to make /v0/ much better with how you're doing things right now.

Either way, zlib really does need to be a requirement though, even on just a regular CIA transfer over HTTP, enabling gzip encoding for the stream will reduce the transfer size by 25% or more.

**Comment by Steveice10** [comment]
I assume HTTPC doesn't support gzip encoding, then? I suppose using zlib for downloads overall would be fair, it's just that I hesitate to add it simply for icon data alone.

**Comment by ksanislo** [comment]
Yeah, httpc doesn't support it on it's own, but it does handle chunked encoding cleanly, so all you have to do is add the accept encoding header, and buffer and decompress with zlib as its read. The only real trick with it for CIA installing is that you have to watch your output buffering to make sure you don't give the AES engine an incomplete block to work with.

Many web servers won't consider a .cia to be a compressible object, but for testing its simple enough to define on your own Apache based server with an .htaccess file of:

AddOutputFilterByType DEFLATE application/x-3dsarchive
AddType application/x-3dsarchive .cia

It will be fully supported for all connections from TitleDB at /v1/, including CIA proxying. I don't know if its enabled or disabled right now, I've been playing with a lot of different ideas while testing things lately.

**Comment by ksanislo** [comment]
Can we get compression/zlib support added yet? With GitHub discontinuing TLS 1.1 support, the titledb site is going to have to pick up a lot of the slack via proxying, and I _really_ need compression on .cia downloads to deal with the bandwidth requirement for that.
