### ISSUE TITLE
FbI work on 11.0.x ?

### ISSUE THREAD

**Issue by matak33** [Steveice10/FBI#171]
you know FbI work in 11.0.x with homebrew laucher ? 

thanks 

Mataka.

**Comment by matak33** [comment]
Sorry for my bad english i'm swiss.

**Comment by MagicInventor** [comment]
nope

**Comment by ShayBox** [comment]
Any tutorial on how i can downgrade? i dont really want to hardmod...

**Comment by urherenow** [comment]
Lots on GBA temp. This site isn't a support forum. And you either need another hacked 3DS, or you need to hard mod.
