### ISSUE TITLE
install failed 

### ISSUE THREAD

**Issue by guyec** [Steveice10/FBI#174]
help :C

**Comment by Steveice10** [comment]
Can you provide some details? Failed how? An error? If so, what error?

**Comment by guyec** [comment]
install failed!
freeShop-1.2,2.cia
Source:SOURCE_AM_START_CIA_INSTALL (0x13)
Module: MODULE_NN_OS (0x6)
Level: LEVEL_PERMANENT (0x1b)
Summary: SUMMARY_WRONG_ARGUMENT (0x8)
Description: DESCRIPTION_INVALID_COMMAND (0x2f)
Press Start to continue

**Comment by Steveice10** [comment]
You're on a very outdated version of FBI. Regardless, that likely means you're on a firmware not supported by the 3dsx version of FBI v1.
