### ISSUE TITLE
Compile error make: *** [build/source/core/screen.o] Error 1

### ISSUE THREAD

**Issue by Sev501** [Steveice10/FBI#175]
Hi,
I've updated to the latest citro3d components and compiled FBI but this is what I get...
Also already tried cloning fresh FBI folder but same deal...

> build/source/core/screen.o
> source/core/screen.c: In function 'screen_init':
> source/core/screen.c:143:5: error: too few arguments to function 'Mtx_OrthoTilt'
>      Mtx_OrthoTilt(&projection_top, 0.0, 400.0, 240.0, 0.0, 0.0, 1.0);
>      ^
> In file included from e:/Downloads/Games/3ds/CFW/repo/devkitPro/libctru/include/citro3d.h:12:0,
>                  from source/core/screen.c:7:
> e:/Downloads/Games/3ds/CFW/repo/devkitPro/libctru/include/c3d/maths.h:454:6: note: declared here
>  void Mtx_OrthoTilt(C3D_Mtx* mtx, float left, float right, float bottom, float top, float near, float far, bool isLeftHanded);
>       ^
> source/core/screen.c:144:5: error: too few arguments to function 'Mtx_OrthoTilt'
>      Mtx_OrthoTilt(&projection_bottom, 0.0, 320.0, 240.0, 0.0, 0.0, 1.0);
>      ^
> In file included from e:/Downloads/Games/3ds/CFW/repo/devkitPro/libctru/include/citro3d.h:12:0,
>                  from source/core/screen.c:7:
> e:/Downloads/Games/3ds/CFW/repo/devkitPro/libctru/include/c3d/maths.h:454:6: note: declared here
>  void Mtx_OrthoTilt(C3D_Mtx* mtx, float left, float right, float bottom, float top, float near, float far, bool isLeftHanded);
>       ^
> make: *** [build/source/core/screen.o] Error 1
> rm build/source/core/default.shbin.c

Was wondering if there would be any input for this error. Thanks!

**Comment by Steveice10** [comment]
Fixed.

**Comment by Sev501** [comment]
Thanks!
