### ISSUE TITLE
Copy & Paste files: error after the first one

### ISSUE THREAD

**Issue by ederenzi78** [Steveice10/FBI#178]
Here is the test case:
1) Copy file A
2) Paste
3) Copy file B
4) Paste --> Error. I don't remember the error code but it's like if I didn't have done copy (step 3)
After that, if I repeat step 3, the paste command works correctly.
The problem occurs on 2.4.1 but not on 2.3.3
Thanks

**Comment by Steveice10** [comment]
I'll need the error code.

**Comment by ederenzi78** [comment]
OK, here is the entire message:
Failed to paste content.
Result code: 0xC8804465
Level: Status(25)
Summary: Not found(4)
Module: FS(17)
Desc: Archive not mounted (101)

Here are the actions:
1) Go to SD, create a new folder in root named Test
2) Go to CTR NAND/private. Copy movable.sed
3) Go to SD/Test. Paste.
4) Go to CTR NAND/dbs. Copy ticket.db
5) Go to SD/Test. Paste --> Error

The error is deterministic.

Thanks

**Comment by Steveice10** [comment]
Can you try this build?

https://www.dropbox.com/s/xqt4j4zkx6i2one/FBI.zip?dl=1

**Comment by ederenzi78** [comment]
Tried. I don't get any error, but it get stuck. I get the screen with the pasting progress but it stays at 0/1, 0.00B / 0.00B.

**Comment by Steveice10** [comment]
Alright. Got another build that should fix it this time. Same link as before.

https://www.dropbox.com/s/xqt4j4zkx6i2one/FBI.zip?dl=1

**Comment by ederenzi78** [comment]
The file is not on dropbox anymore :-D

**Comment by Steveice10** [comment]
My bad... link updated.

**Comment by ederenzi78** [comment]
OK. Now it works. Thanks
