### ISSUE TITLE
Deleting CIAs sometimes fail

### ISSUE THREAD

**Issue by m45t3r** [Steveice10/FBI#18]
Sometimes deleting all CIAs from a directory fails. Generally, only the first CIA in the directory fails to be deleted with the following error:

    Dbelete failed!
    xxxxx.cia
    No such file or directory
    Press start to continue.

This is easy to reproduce if you create a new empty directory and put only one CIA in there. Trying to delete in ``Delete CIA`` mode, pressing both **A** or **X** fails for the same reason.

P.S.: this may happen only with some filenames, I don't know. I only had ``blargSnes.cia`` in the directory and it didn't not work, at least.

**Comment by Steveice10** [comment]
Not sure if this is my issue or not. It's an error from the stdio remove function, and I don't see how it could be passing the path in wrong. If you can, check the path it shows on the deleting screen and see if it's correct.

**Comment by m45t3r** [comment]
The path actually seems to be correct.

The strange think is that only the first CIA in the directory listing fails to delete. If I have lots of CIAs in one directory, all of them except for the first is deleted (well, except when everything works and all CIAs are deleted).

And after rebooting my 3DS, the file deletion seemed to work. Strange.

**Comment by m45t3r** [comment]
I am using CTRXplorer as a workaround to delete CIAs in my 3DS, it seems to work reliable.

Strange thing is, it seems to use the exactly same ``remove()`` from ``stdio.h`` as far I can see: https://github.com/d0k3/CTRXplorer/blob/master/source/ctrcommon_x/fs_x.cpp#L115
