### ISSUE TITLE
Problem creating a folder inside a renamed folder

### ISSUE THREAD

**Issue by svanheulen** [Steveice10/FBI#184]
Using 2.4.2
I went into `/Decrypt9` folder, selected `<current directory>` then `Rename` and changed the name to `files9`
Next I selected `<current directory>` then `New folder` and named it `D9Game`
After that I saw a folder called `files9D9Game` inside the current folder. When I went to the SD root I saw a folder called `files9` and another called `files9D9Game`. When I went into the `files9` folder again, the `files9D9Game` was no longer in there.
I was then able to delete the one on the SD root and create the `/files9/D9Game` folder just fine. So I think it's only a problem when you rename the folder you're in and then try making new folder inside it without leaving the folder first.

**Comment by Steveice10** [comment]
Does this build resolve the issue?

https://www.dropbox.com/s/lc5lr4stvxtzi64/FBI.zip?dl=0

**Comment by svanheulen** [comment]
Yes it did, thanks!
