### ISSUE TITLE
Error compiling FBI

### ISSUE THREAD

**Issue by laerciomotta** [Steveice10/FBI#185]
FBI]# make
build/source/core/screen.o
source/core/screen.c: In function 'screen_init':
source/core/screen.c:143:5: error: too many arguments to function 'Mtx_OrthoTilt'
     Mtx_OrthoTilt(&projection_top, 0.0, 400.0, 240.0, 0.0, 0.0, 1.0, true);
     ^
In file included from /root/devkitPro/libctru/include/citro3d.h:12:0,
                 from source/core/screen.c:7:
/root/devkitPro/libctru/include/c3d/maths.h:72:6: note: declared here
 void Mtx_OrthoTilt(C3D_Mtx* mtx, float left, float right, float bottom, float top, float near, float far);
      ^
source/core/screen.c:144:5: error: too many arguments to function 'Mtx_OrthoTilt'
     Mtx_OrthoTilt(&projection_bottom, 0.0, 320.0, 240.0, 0.0, 0.0, 1.0, true);
     ^
In file included from /root/devkitPro/libctru/include/citro3d.h:12:0,
                 from source/core/screen.c:7:
/root/devkitPro/libctru/include/c3d/maths.h:72:6: note: declared here
 void Mtx_OrthoTilt(C3D_Mtx* mtx, float left, float right, float bottom, float top, float near, float far);
      ^
make: ** [build/source/core/screen.o] Erro 1

My libctru is in last version of the https://github.com/smealum/ctrulib.git

**Comment by Steveice10** [comment]
Build and install the latest citro3d source.
