### ISSUE TITLE
Weird Error... Install Failed!

### ISSUE THREAD

**Issue by iGamethatGame** [Steveice10/FBI#186]
Alright so I load up HBL and Open up FBI and I try to install a CIA. but then it gives me a weird error.

Install failed!
NTRCFWLoader.cia
Source: SOURCE_AM_START_CIA_INSTALL (0x13)
Module: MODULE_NN_OS (0x6)
Level: LEVEL_PERMANET (0x1b)
Summary: SUMMARY_WRONG_ARGUMENT (0x8)
Description: DESCRIPTION_INVALID_COMMAND (0x2f)
Press Start to continue.

Anyone know how to fix this error? It would be very helpful :)

**Comment by Steveice10** [comment]
You're using a very outdated version of FBI on a firmware unsupported by the old 3dsx version.
