### ISSUE TITLE
Can't delete save from cartridge

### ISSUE THREAD

**Issue by suzsuzuki** [Steveice10/FBI#187]
I'm using version 2.4.2 and can't delete save file from Triforce Heroes. After delete the save, when return the save stills there. I used to delete without problem in 2.3.3 version.

I'm in a new 3DS with Luma3DS 11.0

**Comment by Steveice10** [comment]
What are you doing to delete the save data? Deleting the files it contains? Are there any errors?

**Comment by suzsuzuki** [comment]
in main menu I go to Titles, Tri Force Heroes, Browse Save Data...
There are w files, Image_1.bin and Save Data.bin. I delete the first
one without error, then back to main menu, back again to browser save
data and the file stills there. It happens sometimes,  eventually I
can delete the file but I don't know why sometimes I can't.

2016-08-21 17:27 GMT-03:00, Steven Smith <notifications@github.com>:

**Comment by Steveice10** [comment]
Does this build resolve the issue?

https://www.dropbox.com/s/ed8g1chua3lloj0/FBI.zip?dl=1

**Comment by suzsuzuki** [comment]
Yep! Now I can delete the save at the first try! Tested several times and worked. Thanks!

**Comment by urherenow** [comment]
Is a commit coming for this?

**Comment by Steveice10** [comment]
My bad, thought I already had.
