### ISSUE TITLE
Can't install CIA via QR code.

### ISSUE THREAD

**Issue by FerAsdev** [Steveice10/FBI#188]
When I try install a cia game via QR code I get the next error:

Failed to install from URL.
http://hec.su/dF69
Result code: 0xD963F808
Level: Permanent (27)
Summary: Internal (11) 
Module: Application (254)
Desc: Bad data (8)

What does it mean? I am banned or something like that? 

Edit: More details,
New 3DS, 11.0.0.3-U with CFW Luma 5.5

**Comment by Steveice10** [comment]
Try using the actual ticket URL instead of putting it through a shortener.

**Comment by FerAsdev** [comment]
It works, thanks a lot!
