### ISSUE TITLE
Failed to open text color config: Function not implmented.

### ISSUE THREAD

**Issue by Aidas1000** [Steveice10/FBI#189]
Recently I have installed Stickerhax on my NEW 3DS XL Firmware 11. I wanted to install a cia using FBI. But of course I get the kernel access error. So I got the FBI.3dsx and renamed it to boot.3dsx and placed it in the root of my SD. But then I get a different error: Failed to open text color config: Function not implemented. Does anyone know what's wrong?

**Comment by Steveice10** [comment]
I assume this has to do with launching it as boot.3dsx causing RomFS access problems. Either way, running it as boot.3dsx won't help; if you're on 11.0.0, it simply won't work as a 3dsx.
