### ISSUE TITLE
Fbi installer invalid signature (0x6a)

### ISSUE THREAD

**Issue by Savior93** [Steveice10/FBI#19]
I changed my sd and with this new sd card I receive this error when I try to install some cia that was converted with my first sd "descript invalid signature (0x6a)" ,but if I try to install a cia that was converted with this new sd the process go ok,but sometimes the game start,sometimes the 3ds freeze or say "shut down the 3ds",how can I resolve this problem? (Sorry for my bad english,I'm italian ^^ )

**Comment by Steveice10** [comment]
Check the validity of your CIA. Not an FBI issue if the 3DS Application Manager gives back an error when giving it your CIA.
