### ISSUE TITLE
Compile Error.

### ISSUE THREAD

**Issue by JumperGerald** [Steveice10/FBI#192]
When I try and make this file I get the following:
fatal: Not a git repository (or any of the parent directories): .git
build/source/core/default.shbin.c
build/source/core/default.shbin.o
build/source/main.o
build/source/core/clipboard.o
build/source/core/linkedlist.o
build/source/core/screen.o
build/source/core/spi.o
build/source/core/util.o
build/source/json/json.o
build/source/quirc/decode.o
build/source/quirc/identify.o
build/source/quirc/quirc.o
build/source/quirc/version_db.o
build/source/stb_image/stb_image.o
build/source/svchax/svchax.o
build/source/ui/error.o
build/source/ui/info.o
build/source/ui/list.o
build/source/ui/mainmenu.o
build/source/ui/prompt.o
build/source/ui/ui.o
source/ui/ui.c: In function 'ui_draw_top':
source/ui/ui.c:141:57: error: expected expression before ',' token
     snprintf(verText, 64, "Ver. %d.%d.%d", VERSION_MAJOR, VERSION_MINOR, VERSION_MICRO);
                                                         ^
make: *** [build/source/ui/ui.o] Error 1
rm build/source/core/default.shbin.c

C:\Users\Gerald\Documents\3ds\Projects\FBI>make
fatal: Not a git repository (or any of the parent directories): .git
build/source/ui/ui.o
source/ui/ui.c: In function 'ui_draw_top':
source/ui/ui.c:141:57: error: expected expression before ',' token
     snprintf(verText, 64, "Ver. %d.%d.%d", VERSION_MAJOR, VERSION_MINOR, VERSION_MICRO);
                                                         ^
make: *** [build/source/ui/ui.o] Error 1

**Comment by Steveice10** [comment]
Make sure you have the git repository properly cloned so it can retrieve version information.
