### ISSUE TITLE
Can't open presents after closing via start btn with parental controls active.

### ISSUE THREAD

**Issue by JumperGerald** [Steveice10/FBI#193]
If you have parental controls  active, install and exit fbi with the start button the banners for everything disappears and you can't open the gifts. Pressing home button to exit works fine or opening another application after you close fbi via start btn then open another program it will restore functionality.

**Comment by Steveice10** [comment]
The start button exit is really mainly there for the 3dsx version; there isn't much I can do about the problems a sudden exit will cause on the home menu.
