### ISSUE TITLE
[Feature] QR Code for latest CIA version

### ISSUE THREAD

**Issue by weirdal3333** [Steveice10/FBI#194]
Is there a way to make a static QR Code that always points to the latest version of FBI
Maybe point it to a static symbolic link to the latest version?
Or run a script on the next release that updates a dynamic QR Code?

I attached the current latest version of FBI (2.4.2) as a static QR Code if anyone's interested.

![fbi_qr](https://cloud.githubusercontent.com/assets/3537180/18194647/1c5151ce-70b5-11e6-8430-29cc0463da4c.png)
https://github.com/Steveice10/FBI/releases/download/2.4.2/FBI.cia

**Comment by ihaveamac** [comment]
not really necessary since FBI has a feature to update itself.

**Comment by weirdal3333** [comment]
I didn't see that option in a previous version (It's a feature added in 2.2.6)

**Comment by Steveice10** [comment]
As @ihaveamac said, there already is one at the link he mentioned.
