### ISSUE TITLE
Correct SD/NAND installation selection logic

### ISSUE THREAD

**Issue by rboninsegna** [Steveice10/FBI#196]
While 81cb06aad7e4fcff11b1bd706ee6f27b23496b85 does happen to fix the installation of developer apps, it wrongly assumes any titleid ending in 2 should go to internal storage
(not true: DLCs and demos also use the last byte but are SD apps (and so Download Play apps which go to NAND))

So here's some selection logic that's more accurate and should be a drop-in replacement for the multiple duplicate choices seen in that commit:

```
FS_MediaType titleIdToDestination (u64 titleId) {
	if ((titleId >> 32) &  0x0004800) //DSiWare (any kind)
		return MEDIATYPE_NAND;
		
	else if ((titleId >> 32) &  0x00040010) //System (apps, applets, modules, kernels, CFAs)
		return MEDIATYPE_NAND;
		
	else if ((titleId >> 32) == 0x00040001) //Download Play
		return MEDIATYPE_NAND;
		
	else if ((titleId >> 32) == 0x00040000 && (titleId % 0x100000000) != 0x00) //NAND developer app
		return MEDIATYPE_NAND;
	
	else return MEDIATYPE_SD; //SD application, title incremental update, DLC, demo
}
```

Enjoy! :)

**Comment by Steveice10** [comment]
Could you provide examples of what you're referring to with DLC and demos? I haven't found any DLC title IDs that set the last byte to 2.

**Comment by rboninsegna** [comment]
1: I was thinking more of the formal allocation of titleids (looking at the future, no matter how hypothetical) rather than usage as of yesterday; but FWIW, according to the titlekey website, there are 5 titles worth of Japanese Home themes (0004008c-0000820[0-4]) 😃 

2: It's certainly correct that "applications ending in 02" go to NAND: however, the current version of your code based on a single bitmask would select for internal storage any _title_ ending in 02 (not just "applications", ie 00040000-*)!

**Comment by Steveice10** [comment]
Will this suffice?

https://github.com/Steveice10/FBI/commit/71e670edde3d513eb739dbd30d5df4df8e68a201

**Comment by rboninsegna** [comment]
Yep, looks good (actually, I don't even think 0003????-* titles are usable on the 3DS; the "porting" from DSi would mean the container is switched)
