### ISSUE TITLE
AM Service

### ISSUE THREAD

**Issue by JulianBrady** [Steveice10/FBI#197]
whenever I try to install CIAs, an error appears saying that the AM Service could not be initialized.

**Comment by Steveice10** [comment]
What firmware version, and what method of launching FBI (3dsx/3ds/cia)?

**Comment by JulianBrady** [comment]
I'm using the latest firmware on my old 3ds. And I used the 3dsx version.

**Comment by Steveice10** [comment]
FBI is not compatible with the latest firmware as a 3dsx.
