### ISSUE TITLE
New ctrcommon uiSelectFile() function doesn't play nice with FBI...

### ISSUE THREAD

**Issue by d0k3** [Steveice10/FBI#2]
... because it not now uses L and R buttons to scroll, which are also used to change mode and destination in FBI. I'm assuming the change in uiSelectFile() was intended, so I'm opening the issue here instead of in the ctrcommon GitHub.

**Comment by Steveice10** [comment]
Fixed in https://github.com/Steveice10/ctrcommon/commit/9ba98a99525d9443ffef2392a819e958a2c0fffe
