### ISSUE TITLE
CIA File failed to install

### ISSUE THREAD

**Issue by correllroy** [Steveice10/FBI#201]
I'm getting this error and before u ask NO it's not CIA File my friend tested it on his 3ds and it works fine and installed no error. I'm on LUMA CFW A9LH and heres error description

Failed to install CIA file
Result Code: 0xD8E0806A
Level: Permanent (27)
Summary: Invalid Argument (7)
Module: AM (32)
Desc: Cert signature or hash check failed (106)

No its not CIA file, please help

**Comment by Steveice10** [comment]
The best advice I can think of would be to check for differences between the setup on your 3DS and your friend's, and see if there's any that might cause problems.

**Comment by Thantelius** [comment]
Maybe the **System DATE** is the big difference...
;)

**Comment by correllroy** [comment]
Issues was resolved. It was SD Card that had fake storage.

**Comment by pittman1** [comment]
Correllroy, Im having the same problem so could you perhaps explain to me how you fixed it?

**Comment by correllroy** [comment]
I just bought a new 128 micro sd card from new egg.
