### ISSUE TITLE
Does installing any CIA allow me to play online?

### ISSUE THREAD

**Issue by rpalmon** [Steveice10/FBI#202]
Hello, does installing any cia allow me to play online to the corresponding game?

**Comment by dogtopus** [comment]
No you still need a network connection 😃

**Comment by rpalmon** [comment]
So if I install a cia, and have an internet connection, I could play online with the game that I installed? e.g., lets say I installed a Mario Kart 7 cia, could I play online with that game?

**Comment by Steveice10** [comment]
Probably. Not something you should be opening an FBI issue ticket for though.
