### ISSUE TITLE
(Feature Request) Warning when over the 300 title limit

### ISSUE THREAD

**Issue by Zetchzie** [Steveice10/FBI#203]
So would it be possible for FBI to give a warning when your at the 300 limit or stop you from installing anymore games till more space is free. It seems ppl are reaching the limit after bulk installs (not knowing the many titles they installed exceeded that limit ) and there previous games go missing.

**Comment by Steveice10** [comment]
The only problem I see with this is time. I'd have to retrieve the full list of titles and load the SMDH of each one to check for the home menu visibility flag, as if a title doesn't have the flag set, it doesn't count toward that 300 limit.
