### ISSUE TITLE
Japanese text not displayed on upper screen when viewing Titles 

### ISSUE THREAD

**Issue by ederenzi78** [Steveice10/FBI#204]
The object says it all.
Thanks!

**Comment by Steveice10** [comment]
Can you provide a screenshot so I can get an idea of exactly what's going on?

**Comment by ederenzi78** [comment]
![wp_20160930_001](https://cloud.githubusercontent.com/assets/20660471/18995937/bab90f52-872e-11e6-9817-63439a0b50d0.jpg)
Here it is. It seems that text from japanese games is not displayed properly (neither in the Title list nor in the upper screen box).
Thanks

**Comment by dogtopus** [comment]
It is probably a CIAngel (or make_cdn_cia) issue since I cannot reproduce it using either freeShop or 3ds titlekeys + FBI

**Comment by Steveice10** [comment]
Very likely to be a problem with whatever you installed it from. If the title list is displaying the title ID, that means the application name was empty.

**Comment by ederenzi78** [comment]
I tried installing with FreeShop and have the same behaviour. Moreover, the title is displayed correctly in JKSM. I still think it's an FBI issue.
