### ISSUE TITLE
[Feature request] Creating CIAs from installed content

### ISSUE THREAD

**Issue by d0k3** [Steveice10/FBI#206]
I might miss something, so this might not be possible, but I'll put this up for discussion anyways. Is it possible to include a feature in FBI that would allow creating .CIA files from content already installed on the system (NAND and SD)?

I'm pretty sure I'm telling you nothing new, but the TMD is provided, the ticket is in the ticket.db, the CIA certs can be built from certs.db (just copy data from the correct locations) and metadata can be built from the CXI content (or it even is elsewhere, no idea). Other than that, creating a .CIA is a pretty straightforward process, inserting contents just means appending data. Where things could get difficult (perhaps) is decryption of the .icon in ExeFS.

**Comment by Steveice10** [comment]
I suppose having NAND access does make this possible... the difficult parts would probably be parsing the databases manually and putting everything together.

**Comment by d0k3** [comment]
As for parsing databases... the only place where this would get ugly is fetching the ticket from the ticket.db, but for them, simply the whole file can be parsed (same as D9 does when searching for titlekeys / tickets). The certificates in the cert.db are at fixed locations (always the same, on all consoles).

As for putting everything together - there is code for that in D9 already. D9 can dump game cartridges to CIAs and convert any NCCH or NCSD to CIA. 

See here: https://github.com/d0k3/Decrypt9WIP/blob/master/source/decryptor/game.c#L817-L940
And here: https://github.com/d0k3/Decrypt9WIP/blob/master/source/decryptor/game.c#L942-L1084
For installed content -> CIA conversion, most of the stuff that I do here would not be required.  


Here:

**Comment by Gliscor** [comment]
And here we are, watching two geniuses doing their magic. God Bless them.

**Comment by d0k3** [comment]
Alright, continuing from here. D9 adds that feature in this commit:
https://github.com/d0k3/Decrypt9WIP/commit/c5e4a6802e16c71dfa9eeb0ab454442c00621447
(allows to build CIAs from installed content)

I still think that feature would be much better in FBI. Why? For once, D9 had some bad design decisions in the past which won't allow it to do the same for stuff installed on TWL or NAND. Also, FBI can actually display meta info for installed stuff, not forcing users to find out the title ID on their own.

I also know that code could be better readable, but I'll help porting it if I can.

**Comment by Steveice10** [comment]
I actually completely forgot about the SD and was thinking about the NAND. Now that you bring up SD though, having to work with encrypted title data from FBI might present a problem.

**Comment by d0k3** [comment]
The stuff on SD uses keyslot 0x34, the keyX being unknown. The keyY can easily be generated from the movable.sed, and the iv is generated from the path of the file.

I see how the unknown key is a problem, but  tbh, I was hoping there would be some system function that does the decryption of the stuff installed on SD. There actually should, cause otherwise the system wouldn't even be able to display icons and banners for SD installed stuff. This goes over my head, though, I'm a lot more familiar with ARM9 than with that system internal stuff.

**Comment by Steveice10** [comment]
Title decryption is usually handled on the ARM9 side, presenting the ExeFS, RomFS, etc. as filesystem archives over PXI. You can piece some bits together and autogenerate the rest, like neobrain did with braindump, but it isn't really enough to create a full, proper dump.
