### ISSUE TITLE
Freeze at viewing titles

### ISSUE THREAD

**Issue by CaiMiao** [Steveice10/FBI#208]
I don't know the reason why this would happen. I filtered and confirmed that I froze when I was viewing titles on my SD.

**Comment by NinjaBoyLao** [comment]
extremely large SD cards with multiple titles installed can cause a very long load time while FBI reads them all, how long did you wait before deciding it "froze"?

**Comment by NinjaBoyLao** [comment]
by large i mean 32GB+

**Comment by CaiMiao** [comment]
about 2 or 3 seconds

**Comment by NinjaBoyLao** [comment]
give it about 10-15, that's what it takes me. possibly this could be improved but idk. possibly this could also be an issue with your system in particular. how big is your sd card and how many titles you got on it?

**Comment by Zetchzie** [comment]
this only happens if you scroll through the list quickly before it loads then it freezes. i got a 128gb microsd with 80+ games

**Comment by CaiMiao** [comment]
@NinjaBoyLao, 32gb, not so many titles.

@Zetchzie I never scrolled then freezes. Maybe there's a broken title but I can't just find out which it is.

**Comment by Steveice10** [comment]
Is this still an issue?

**Comment by CaiMiao** [comment]
@Steveice10 Yes it seems I have a broken title, when I clear all Patch/DLC titles it works now.
