### ISSUE TITLE
Failed to set syscore CPU time limit: D8E05BF4

### ISSUE THREAD

**Issue by Stiggia** [Steveice10/FBI#210]
launching fbi from hbl give me this whithin a black screen

My Error is as follows:
"Fbi has encountered a fatal error!"
"Failed to set syscore CPU time limit: D8E05BF4"
"Press any button to exit."

i'm using the latest version on 9.2 i have CFW

**Comment by Steveice10** [comment]
Are there any unusual characteristics to the environment you're running FBI in? It seems that, for whatever reason, the syscore CPU time limit maximum is lower than usual.

**Comment by Stiggia** [comment]
> Are there any unusual characteristics to the environment you're running FBI in?

I have a lot of problem actually and whatever i look for a solution i end i a new one

**Comment by Stiggia** [comment]
I'm actually in a wiered situation:
-I don't have healt and safety app on my home
-injectig fbi give me succes but no fbi appear on reboot
-using hbl give me the error i posted

looks like there's no way for me to lauch fbi

**Comment by Stiggia** [comment]
I solved following this http://emulators128.rssing.com/chan-51395358/all_p220.html
Open FBI from hbl and install fbi.cia
