### ISSUE TITLE
[Feature Request] Option to sort titles different ways

### ISSUE THREAD

**Issue by Nazosan** [Steveice10/FBI#213]
Once one has a lot of software installed going through the list in the title menu to find something to delete or whatever can be a real hassle.  The sorting always felt pretty random (though upon searching I see that it's sorted by title ID?)  This makes it really hard if you only know the actual name of the software though.  While there are probably times where it is beneficial to sort by the title ID, I'm not sure if this makes a good default.  Regardless, if the user could simply select among different ways to sort this would be most ideal (preferably with some way to change the default if the default isn't going to be something more intuitive.)  This could really help a lot with actually managing the installed titles on a system via FBI instead of having to use something else.

**Comment by Steveice10** [comment]
Currently not very feasible. Sorting by name would require loading the SMDH data to get the title names, which makes up the bulk of loading times. Either you'd have to wait for the entire list to be populated before it was sorted, or put up with a constantly shifting and difficult to use list until it's done loading.

**Comment by Nazosan** [comment]
Perhaps look at FreeShop's own implementation?  It seems to have some means of doing this.  Sorting after loading is quite acceptable though.  I was actually originally thinking in terms of something you could press to apply a sort filter after the loading completed.

**Comment by Steveice10** [comment]
Had an idea of how I might be able to do sorting well; no guarantees of if I'll be able to pull it off or when, since I'm working on a lot of internal changes right now, but I'll reopen this for now.
