### ISSUE TITLE
[Feature Request] Delete Unused Tickets?

### ISSUE THREAD

**Issue by Zetchzie** [Steveice10/FBI#214]
Ive had my n3ds for awhile and i did a transfer from my o3ds so i have tickets from old stuff cluttering it so is it possible to delete all tickets that are no longer are needed idk what is what unless 3ds deletes tickets after an uninstall.

**Comment by Haaroon** [comment]
+1
Perhaps the first step would be to delete the ticket from the system when the item is uninstalled from FBI? 

Is there a difference between eShop legit tickets and home-brew installed tickets?

**Comment by deadair3210** [comment]
No difference, that's part of the point. Nintendo can't tell the difference unless they cross reference the ticket database with what the servers say you should have

**Comment by Haaroon** [comment]
Ahh ok cool. Thanks for that. 

But since we dont know if they are going to do implement, or have it already doing its check, shouldnt we implement something incase?

**Comment by james-d-elliott** [comment]
tikSweep already does exactly this.

**Comment by Steveice10** [comment]
Added.
