### ISSUE TITLE
Option for CIAs to "Install just the Ticket" aka Soft Installing

### ISSUE THREAD

**Issue by cheatfreak47** [Steveice10/FBI#215]
After System Transfers or CTRNAND Transfers, tickets are cleared, but contents are still installed. 
Allowing users to install tickets out of CIA files would enable them to "soft install" games so they will show up on the home menu again.

Old FBI would do this I think when the contents are already installed, but I'm not sure it was deliberate. (it'd just throw and already installed error)

As of now if a title is already installed in this way, it seems to just fully install the title and the ticket, overwriting the old copy of the game (redundantly) and user saves.

It'd also be nice if it could "check for seed" when it does a ticket install but that's not really necessary, it'd just be nice. :P

**Comment by Steveice10** [comment]
Why not just install the ticket as its own file?

**Comment by cheatfreak47** [comment]
Because most users don't know how to separate the ticket from the CIA.

**Comment by Steveice10** [comment]
But why not just get a ticket file instead of a CIA in the first place?

**Comment by cheatfreak47** [comment]
Need I remind you that some games aren't on the CDN at all?
If a guy needs to install a ticket so his game that already has installed content on the SD card, and the only place to get the ticket is a CIA file, it'd be convenient to be able to just use the CIA file, and seperating tickets from CIAs is certainly less than intuitive.

This is an issue I run into helping users fairly often, usually related to CTR Transfers, System Transfers, and Region Changing.

**Comment by Steveice10** [comment]
Ideally, you would have dumped the ticket files from the NAND beforehand to reinstall afterward, to, among other things, keep the legitimate tickets intact.

**Comment by cheatfreak47** [comment]
Yeah but most of the tutorials and guides online don't instruct users to do that at all, and once you've made the change, going back to get those files (even with a nand backup) can become a rather long and drawn out process.

Many users keep their CIAs on their computer, so having some way of just sticking the ticket on from a full CIA content package would probably be quite a bit faster, and even more convenient for homebrew and custom titles (think VC injects, stuff like that, where the tickets aren't easily available, or useful in most cases)

Like I said, people used to do this all the time when transferring from one hacked 3DS to another hacked 3DS, as the System Transfer would only transfer the legitimate eShop tickets. It used to be done with Network Install, and you would get an error after just the ticket was installed stating the content already exists.

**Comment by shawnz** [comment]
I would also like this, or at least a way to install a CIA while keeping existing saves. I think it is a very unintuitive behaviour that installing a CIA will clobber your existing saves.

**Comment by Steveice10** [comment]
Why are you installing a CIA for something you already have installed on your 3DS? Otherwise, if you previously uninstalled the game, that's when your save got deleted.

Also, this is a really old issue that was closed over 3 years ago.

**Comment by shawnz** [comment]
I had to restore my NAND which apparently got rid of all the tickets. I had CIA files handy at the time but not ticket files. I did not realize at that time that installing the CIAs again would erase my saves.

I can file a new issue if you feel this is something worth addressing.

**Comment by Steveice10** [comment]
This is probably not something that will be addressed as I don't know of any way to tell the 3DS OS not to clear save data when reinstalling an app. If you haven't already reinstalled everything, I would recommend getting ctrtool or a similar tool on your PC and extracting the tickets from your CIAs to install alone.

**Comment by urherenow** [comment]
Installing CIAs doesn’t erase saves. Restoring your NAND does.

**Comment by shawnz** [comment]
Interesting. I didn't realize that. Thank you for the information everyone and thanks for your work on this project Steveice10.
