### ISSUE TITLE
CIA file failed to install

### ISSUE THREAD

**Issue by Lefuden** [Steveice10/FBI#216]
Have followed the Plailect guide for my old 3DS, running Luma3DS A9LH and FBI is cia, not H&S.

Failed to install cia file
Result Code: 0xC960454B
Level: Status (25)
Summary: Internal (11)
Module: FS (17)
Desc: Bus Error / TWL partition invalid (331)

**Comment by deadair3210** [comment]
Try reinserting your SD card, I got that error because my SD card had come loose

**Comment by Steveice10** [comment]
Definitely sounds like an SD problem. Try doing as @deadair3210 suggested and see what happens.

**Comment by Lefuden** [comment]
Pretty sure my SD card is corrupt, will try the same cia file on a new SD card once I can afford one.

**Comment by Lefuden** [comment]
Confirmed my old SD card was corrupted. Got a new one and it worked.

**Comment by deadair3210** [comment]
Before totally giving up on the old card, might plug it into a computer and zero it and then reformat it. Might fix the corruption if there is any
