### ISSUE TITLE
Undefined Reference when build

### ISSUE THREAD

**Issue by kurocygnus** [Steveice10/FBI#217]
I was trying to build the release 2.4.2 because I was testing something, but It give me this error even without my modifications:

`output/FBI.elf
build/source/main.o: In function `cleanup':
/home/kuro/Downloads/FBI-2.4.2/source/main.c:30: undefined reference to `pxiDevExit'
build/source/main.o: In function `romfsExit':
/home/kuro/devkitPro/libctru/include/3ds/romfs.h:79: undefined reference to `romfsUnmount'
build/source/main.o: In function `romfsInit':
/home/kuro/devkitPro/libctru/include/3ds/romfs.h:57: undefined reference to `romfsMount'
build/source/main.o: In function `main':
/home/kuro/Downloads/FBI-2.4.2/source/main.c:61: undefined reference to `pxiDevInit'
build/source/ui/section/networkinstall.o: In function `networkinstall_open_dst':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/networkinstall.c:162: undefined reference to `AM_DeleteTicket'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/networkinstall.c:140: undefined reference to `AM_DeleteTicket'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/networkinstall.c:141: undefined reference to `AM_InstallTicketBegin'
build/source/ui/section/networkinstall.o: In function `networkinstall_close_dst':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/networkinstall.c:186: undefined reference to `AM_InstallTicketFinish'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/networkinstall.c:209: undefined reference to `AM_InstallTicketAbort'
build/source/ui/section/qrinstall.o: In function `qrinstall_wait_update':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/qrinstall.c:109: undefined reference to `swkbdInit'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/qrinstall.c:111: undefined reference to `swkbdSetFeatures'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/qrinstall.c:112: undefined reference to `swkbdSetHintText'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/qrinstall.c:115: undefined reference to `swkbdInputText'
build/source/ui/section/update.o: In function `update_check_update':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/update.c:190: undefined reference to `httpcSetSSLOpt'
build/source/ui/section/update.o: In function `update_open_src':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/update.c:43: undefined reference to `httpcSetSSLOpt'
build/source/ui/section/task/listtitledb.o: In function `task_populate_titledb_download':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/task/listtitledb.c:29: undefined reference to `httpcSetSSLOpt'
build/source/ui/section/task/listtitledb.o: In function `task_populate_titledb_thread':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/task/listtitledb.c:120: undefined reference to `AM_GetTitleInfo'
build/source/ui/section/task/listpendingtitles.o: In function `task_populate_pending_titles_from':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/task/listpendingtitles.c:25: undefined reference to `AM_GetPendingTitleCount'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/task/listpendingtitles.c:28: undefined reference to `AM_GetPendingTitleList'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/task/listpendingtitles.c:33: undefined reference to `AM_GetPendingTitleInfo'
build/source/ui/section/task/listtitles.o: In function `task_populate_titles_add_twl':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/task/listtitles.c:119: undefined reference to `AM_GetTitleInfo'
build/source/ui/section/task/listtitles.o: In function `task_populate_titles_from':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/task/listtitles.c:274: undefined reference to `AM_GetTitleList'
build/source/ui/section/task/listtitles.o: In function `task_populate_titles_add_ctr':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/task/listtitles.c:20: undefined reference to `AM_GetTitleInfo'
build/source/ui/section/task/listtickets.o: In function `task_populate_tickets_thread':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/task/listtickets.c:27: undefined reference to `AM_GetTicketCount'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/task/listtickets.c:30: undefined reference to `AM_GetTicketList'
build/source/ui/section/task/dataop.o: In function `task_data_op_thread':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/task/dataop.c:159: undefined reference to `aptSetSleepAllowed'
build/source/ui/section/task/dataop.o: In function `task_data_op':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/task/dataop.c:192: undefined reference to `aptSetSleepAllowed'
build/source/ui/section/action/installcdn.o: In function `action_install_cdn_restore':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:184: undefined reference to `AM_InstallTitleResume'
build/source/ui/section/action/installcdn.o: In function `action_install_cdn_suspend':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:178: undefined reference to `AM_InstallTitleStop'
build/source/ui/section/action/installcdn.o: In function `action_install_cdn_open_src':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:63: undefined reference to `httpcSetSSLOpt'
build/source/ui/section/action/installcdn.o: In function `action_install_cdn_start':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:268: undefined reference to `AM_InstallTitleBegin'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:272: undefined reference to `AM_InstallTitleAbort'
build/source/ui/section/action/installcdn.o: In function `action_install_cdn_update':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:223: undefined reference to `AM_InstallTitleFinish'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:224: undefined reference to `AM_CommitImportTitles'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:238: undefined reference to `AM_InstallTitleAbort'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:238: undefined reference to `AM_InstallTitleAbort'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:238: undefined reference to `AM_InstallTitleAbort'
build/source/ui/section/action/installcdn.o: In function `action_install_cdn_restore_copy':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:171: undefined reference to `AM_InstallContentResume'
build/source/ui/section/action/installcdn.o: In function `action_install_cdn_suspend_copy':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:161: undefined reference to `AM_InstallContentStop'
build/source/ui/section/action/installcdn.o: In function `action_install_cdn_close_dst':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:135: undefined reference to `AM_InstallContentFinish'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:150: undefined reference to `AM_InstallContentCancel'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:148: undefined reference to `AM_InstallTmdAbort'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:132: undefined reference to `AM_InstallTmdFinish'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:137: undefined reference to `AM_InstallTitleFinish'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:138: undefined reference to `AM_CommitImportTitles'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:139: undefined reference to `AM_InstallTitleBegin'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:140: undefined reference to `AM_CreateImportContentContexts'
build/source/ui/section/action/installcdn.o: In function `action_install_cdn_open_dst':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:121: undefined reference to `AM_InstallTmdBegin'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:123: undefined reference to `AM_InstallContentBegin'
build/source/ui/section/action/installcdn.o: In function `action_install_cdn_onresponse':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:358: undefined reference to `swkbdInit'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:359: undefined reference to `swkbdSetHintText'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcdn.c:362: undefined reference to `swkbdInputText'
build/source/ui/section/action/urlinstall.o: In function `action_url_install_open_dst':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/urlinstall.c:157: undefined reference to `AM_DeleteTicket'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/urlinstall.c:135: undefined reference to `AM_DeleteTicket'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/urlinstall.c:136: undefined reference to `AM_InstallTicketBegin'
build/source/ui/section/action/urlinstall.o: In function `action_url_install_open_src':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/urlinstall.c:65: undefined reference to `httpcSetSSLOpt'
build/source/ui/section/action/urlinstall.o: In function `action_url_install_close_dst':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/urlinstall.c:181: undefined reference to `AM_InstallTicketFinish'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/urlinstall.c:204: undefined reference to `AM_InstallTicketAbort'
build/source/ui/section/action/launchtitle.o: In function `action_launch_title_update':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/launchtitle.c:17: undefined reference to `APT_PrepareToDoApplicationJump'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/launchtitle.c:21: undefined reference to `APT_DoApplicationJump'
build/source/ui/section/action/rename.o: In function `action_rename':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/rename.c:22: undefined reference to `swkbdInit'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/rename.c:24: undefined reference to `swkbdSetInitialText'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/rename.c:25: undefined reference to `swkbdSetHintText'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/rename.c:28: undefined reference to `swkbdInputText'
build/source/ui/section/action/installtickets.o: In function `action_install_tickets_open_dst':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installtickets.c:112: undefined reference to `AM_DeleteTicket'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installtickets.c:113: undefined reference to `AM_InstallTicketBegin'
build/source/ui/section/action/installtickets.o: In function `action_install_tickets_close_dst':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installtickets.c:120: undefined reference to `AM_InstallTicketFinish'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installtickets.c:132: undefined reference to `AM_InstallTicketAbort'
build/source/ui/section/action/newfolder.o: In function `action_new_folder':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/newfolder.c:20: undefined reference to `swkbdInit'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/newfolder.c:22: undefined reference to `swkbdSetHintText'
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/newfolder.c:25: undefined reference to `swkbdInputText'
build/source/ui/section/action/deleteticket.o: In function `action_delete_ticket_update':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/deleteticket.c:29: undefined reference to `AM_DeleteTicket'
build/source/ui/section/action/installcias.o: In function `action_install_cias_open_dst':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/installcias.c:142: undefined reference to `AM_DeleteTicket'
build/source/ui/section/action/deletependingtitles.o: In function `action_delete_pending_titles_delete':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/deletependingtitles.c:43: undefined reference to `AM_DeletePendingTitle'
build/source/ui/section/action/deletetitle.o: In function `action_delete_title_update':
/home/kuro/Downloads/FBI-2.4.2/source/ui/section/action/deletetitle.c:33: undefined reference to `AM_DeleteTicket'
build/source/core/screen.o: In function `screen_get_string_size_internal':
/home/kuro/Downloads/FBI-2.4.2/source/core/screen.c:635: undefined reference to `fontGlyphIndexFromCodePoint'
/home/kuro/Downloads/FBI-2.4.2/source/core/screen.c:635: undefined reference to `fontGetCharWidthInfo'
/home/kuro/Downloads/FBI-2.4.2/source/core/screen.c:610: undefined reference to `fontGlyphIndexFromCodePoint'
/home/kuro/Downloads/FBI-2.4.2/source/core/screen.c:610: undefined reference to `fontGetCharWidthInfo'
/home/kuro/Downloads/FBI-2.4.2/source/core/screen.c:617: undefined reference to `g_sharedFont'
build/source/core/screen.o: In function `screen_draw_string_internal':
/home/kuro/Downloads/FBI-2.4.2/source/core/screen.c:718: undefined reference to `fontGlyphIndexFromCodePoint'
/home/kuro/Downloads/FBI-2.4.2/source/core/screen.c:718: undefined reference to `fontCalcGlyphPos'
/home/kuro/Downloads/FBI-2.4.2/source/core/screen.c:695: undefined reference to `fontGlyphIndexFromCodePoint'
/home/kuro/Downloads/FBI-2.4.2/source/core/screen.c:695: undefined reference to `fontGetCharWidthInfo'
/home/kuro/Downloads/FBI-2.4.2/source/core/screen.c:742: undefined reference to `g_sharedFont'
build/source/core/screen.o: In function `screen_init':
/home/kuro/Downloads/FBI-2.4.2/source/core/screen.c:146: undefined reference to `fontEnsureMapped'
/home/kuro/Downloads/FBI-2.4.2/source/core/screen.c:108: undefined reference to `g_sharedFont'
build/source/core/spi.o: In function `spi_execute_command':
/home/kuro/Downloads/FBI-2.4.2/source/core/spi.c:165: undefined reference to `PXIDEV_SPIMultiWriteRead'
build/source/core/util.o: In function `util_import_seed':
/home/kuro/Downloads/FBI-2.4.2/source/core/util.c:290: undefined reference to `httpcSetSSLOpt'
build/source/svchax/svchax.o: In function `get_threads_limit':
/home/kuro/Downloads/FBI-2.4.2/source/svchax/svchax.c:188: undefined reference to `svcGetResourceLimit'
/home/kuro/Downloads/FBI-2.4.2/source/svchax/svchax.c:189: undefined reference to `svcGetResourceLimitCurrentValues'
/home/kuro/Downloads/FBI-2.4.2/source/svchax/svchax.c:190: undefined reference to `svcGetResourceLimitLimitValues'
collect2: error: ld returned 1 exit status
buildtools/make_base:430: recipe for target 'output/FBI.elf' failed
make: *** [output/FBI.elf] Error 1
`

**Comment by dogtopus** [comment]
Please check your version of ctrulib. The version that included in DevkitPro is really old and FBI needs a more recent version to build

**Comment by kurocygnus** [comment]
Already got the source on smea's github, but still happened. Going to try again anyway. Thanks.
