### ISSUE TITLE
Error at compile

### ISSUE THREAD

**Issue by kingzhe2011** [Steveice10/FBI#218]
`In file included from source/main.c:5:0:
source/core/clipboard.h:6:1: error: unknown type name 'FS_Archive'
 FS_Archive clipboard_get_archive();
 ^
source/core/clipboard.h:9:31: error: unknown type name 'FS_Archive'
 Result clipboard_set_contents(FS_Archive archive, const char* path, bool contentsOnly);
                               ^
In file included from source/main.c:7:0:
source/core/util.h:43:1: error: unknown type name 'FS_Path'
 FS_Path* util_make_path_utf8(const char* path);
 ^
source/core/util.h:44:26: error: unknown type name 'FS_Path'
 void util_free_path_utf8(FS_Path* path);
                          ^
source/core/util.h:46:1: error: unknown type name 'FS_Path'
 FS_Path util_make_binary_path(const void* data, u32 size);
 ^
source/core/util.h:48:18: error: unknown type name 'FS_Archive'
 bool util_is_dir(FS_Archive archive, const char* path);
                  ^
source/core/util.h:49:24: error: unknown type name 'FS_Archive'
 Result util_ensure_dir(FS_Archive archive, const char* path);
                        ^
source/core/util.h:57:1: error: unknown type name 'FS_MediaType'
 FS_MediaType util_get_title_destination(u64 titleId);
 ^
source/core/util.h:74:26: error: unknown type name 'FS_Archive'
 Result util_open_archive(FS_Archive* archive, FS_ArchiveID id, FS_Path path);
                          ^
source/core/util.h:74:47: error: unknown type name 'FS_ArchiveID'
 Result util_open_archive(FS_Archive* archive, FS_ArchiveID id, FS_Path path);
                                               ^
source/core/util.h:74:64: error: unknown type name 'FS_Path'
 Result util_open_archive(FS_Archive* archive, FS_ArchiveID id, FS_Path path);
                                                                ^
source/core/util.h:75:25: error: unknown type name 'FS_Archive'
 Result util_ref_archive(FS_Archive archive);
                         ^
source/core/util.h:76:27: error: unknown type name 'FS_Archive'
 Result util_close_archive(FS_Archive archive);
                           ^
In file included from source/main.c:12:0:
source/ui/section/task/task.h:18:5: error: unknown type name 'FS_MediaType'
     FS_MediaType mediaType;
     ^
source/ui/section/task/task.h:29:5: error: unknown type name 'FS_MediaType'
     FS_MediaType mediaType;
     ^
source/ui/section/task/task.h:39:5: error: unknown type name 'FS_MediaType'
     FS_MediaType mediaType;
     ^
source/ui/section/task/task.h:59:5: error: unknown type name 'FS_Archive'
     FS_Archive archive;
     ^
source/ui/section/task/task.h:146:51: error: unknown type name 'FS_MediaType'
     bool (*filter)(void* data, u64 extSaveDataId, FS_MediaType mediaType);
                                                   ^
source/ui/section/task/task.h:157:5: error: unknown type name 'FS_Archive'
     FS_Archive archive;
     ^
source/ui/section/task/task.h:198:45: error: unknown type name 'FS_MediaType'
     bool (*filter)(void* data, u64 titleId, FS_MediaType mediaType);
                                             ^
source/ui/section/task/task.h:230:47: error: unknown type name 'FS_Archive'
 Result task_create_file_item(list_item** out, FS_Archive archive, const char* path, u32 attributes);
                                               ^
source/main.c: In function 'cleanup_services':
source/main.c:18:5: warning: implicit declaration of function 'socExit' [-Wimplicit-function-declaration]
     socExit();
     ^
source/main.c:25:5: warning: implicit declaration of function 'pxiDevExit' [-Wimplicit-function-declaration]
     pxiDevExit();
     ^
source/main.c:26:5: warning: implicit declaration of function 'ptmuExit' [-Wimplicit-function-declaration]
     ptmuExit();
     ^
source/main.c:28:5: warning: implicit declaration of function 'cfguExit' [-Wimplicit-function-declaration]
     cfguExit();
     ^
source/main.c: In function 'init_services':
source/main.c:36:8: warning: implicit declaration of function 'R_SUCCEEDED' [-Wimplicit-function-declaration]
     if(R_SUCCEEDED(res = srvGetServiceHandle(&tempAM, "am:net"))) {
        ^
source/main.c:40:33: warning: implicit declaration of function 'cfguInit' [-Wimplicit-function-declaration]
            && R_SUCCEEDED(res = cfguInit())
                                 ^
source/main.c:42:33: warning: implicit declaration of function 'ptmuInit' [-Wimplicit-function-declaration]
            && R_SUCCEEDED(res = ptmuInit())
                                 ^
source/main.c:43:33: warning: implicit declaration of function 'pxiDevInit' [-Wimplicit-function-declaration]
            && R_SUCCEEDED(res = pxiDevInit())
                                 ^
source/main.c:47:23: warning: implicit declaration of function 'socInit' [-Wimplicit-function-declaration]
                 res = socInit(soc_buffer, 0x100000);
                       ^
In file included from source/main.c:9:0:
source/ui/error.h:13:29: warning: implicit declaration of function 'MAKERESULT' [-Wimplicit-function-declaration]
 #define R_FBI_OUT_OF_MEMORY MAKERESULT(RL_FATAL, RS_OUTOFRESOURCE, RM_APPLICATION, RD_OUT_OF_MEMORY)
                             ^
source/main.c:49:23: note: in expansion of macro 'R_FBI_OUT_OF_MEMORY'
                 res = R_FBI_OUT_OF_MEMORY;
                       ^
source/ui/error.h:13:40: error: 'RL_FATAL' undeclared (first use in this function)
 #define R_FBI_OUT_OF_MEMORY MAKERESULT(RL_FATAL, RS_OUTOFRESOURCE, RM_APPLICATION, RD_OUT_OF_MEMORY)
                                        ^
source/main.c:49:23: note: in expansion of macro 'R_FBI_OUT_OF_MEMORY'
                 res = R_FBI_OUT_OF_MEMORY;
                       ^
source/ui/error.h:13:40: note: each undeclared identifier is reported only once for each function it appears in
 #define R_FBI_OUT_OF_MEMORY MAKERESULT(RL_FATAL, RS_OUTOFRESOURCE, RM_APPLICATION, RD_OUT_OF_MEMORY)
                                        ^
source/main.c:49:23: note: in expansion of macro 'R_FBI_OUT_OF_MEMORY'
                 res = R_FBI_OUT_OF_MEMORY;
                       ^
source/ui/error.h:13:50: error: 'RS_OUTOFRESOURCE' undeclared (first use in this function)
 #define R_FBI_OUT_OF_MEMORY MAKERESULT(RL_FATAL, RS_OUTOFRESOURCE, RM_APPLICATION, RD_OUT_OF_MEMORY)
                                                  ^
source/main.c:49:23: note: in expansion of macro 'R_FBI_OUT_OF_MEMORY'
                 res = R_FBI_OUT_OF_MEMORY;
                       ^
source/ui/error.h:13:68: error: 'RM_APPLICATION' undeclared (first use in this function)
 #define R_FBI_OUT_OF_MEMORY MAKERESULT(RL_FATAL, RS_OUTOFRESOURCE, RM_APPLICATION, RD_OUT_OF_MEMORY)
                                                                    ^
source/main.c:49:23: note: in expansion of macro 'R_FBI_OUT_OF_MEMORY'
                 res = R_FBI_OUT_OF_MEMORY;
                       ^
source/ui/error.h:13:84: error: 'RD_OUT_OF_MEMORY' undeclared (first use in this function)
 #define R_FBI_OUT_OF_MEMORY MAKERESULT(RL_FATAL, RS_OUTOFRESOURCE, RM_APPLICATION, RD_OUT_OF_MEMORY)
                                                                                    ^
source/main.c:49:23: note: in expansion of macro 'R_FBI_OUT_OF_MEMORY'
                 res = R_FBI_OUT_OF_MEMORY;
                       ^
source/main.c:54:8: warning: implicit declaration of function 'R_FAILED' [-Wimplicit-function-declaration]
     if(R_FAILED(res)) {
        ^
source/main.c: In function 'cleanup':
source/main.c:69:32: warning: passing argument 1 of 'APT_SetAppCpuTimeLimit' makes pointer from integer without a cast [-Wint-conversion]
         APT_SetAppCpuTimeLimit(old_time_limit);
                                ^
In file included from /devkitPro/libctru/include/3ds.h:20:0,
                 from source/main.c:3:
/devkitPro/libctru/include/3ds/services/apt.h:119:8: note: expected 'Handle * {aka long unsigned int *}' but argument is of type 'u32 {aka long unsigned int}'
 Result APT_SetAppCpuTimeLimit(Handle* handle, u32 percent);
        ^
source/main.c:69:9: error: too few arguments to function 'APT_SetAppCpuTimeLimit'
         APT_SetAppCpuTimeLimit(old_time_limit);
         ^
In file included from /devkitPro/libctru/include/3ds.h:20:0,
                 from source/main.c:3:
/devkitPro/libctru/include/3ds/services/apt.h:119:8: note: declared here
 Result APT_SetAppCpuTimeLimit(Handle* handle, u32 percent);
        ^
source/main.c: In function 'init':
source/main.c:102:5: error: too few arguments to function 'APT_GetAppCpuTimeLimit'
     APT_GetAppCpuTimeLimit(&old_time_limit);
     ^
In file included from /devkitPro/libctru/include/3ds.h:20:0,
                 from source/main.c:3:
/devkitPro/libctru/include/3ds/services/apt.h:120:8: note: declared here
 Result APT_GetAppCpuTimeLimit(Handle* handle, u32 *percent);
        ^
source/main.c:103:44: warning: passing argument 1 of 'APT_SetAppCpuTimeLimit' makes pointer from integer without a cast [-Wint-conversion]
     Result cpuRes = APT_SetAppCpuTimeLimit(30);
                                            ^
In file included from /devkitPro/libctru/include/3ds.h:20:0,
                 from source/main.c:3:
/devkitPro/libctru/include/3ds/services/apt.h:119:8: note: expected 'Handle * {aka long unsigned int *}' but argument is of type 'int'
 Result APT_SetAppCpuTimeLimit(Handle* handle, u32 percent);
        ^
source/main.c:103:21: error: too few arguments to function 'APT_SetAppCpuTimeLimit'
     Result cpuRes = APT_SetAppCpuTimeLimit(30);
                     ^
In file included from /devkitPro/libctru/include/3ds.h:20:0,
                 from source/main.c:3:
/devkitPro/libctru/include/3ds/services/apt.h:119:8: note: declared here
 Result APT_SetAppCpuTimeLimit(Handle* handle, u32 percent);
        ^
source/main.c:109:5: warning: implicit declaration of function 'AM_InitializeExternalTitleDatabase' [-Wimplicit-function-declaration]
     AM_InitializeExternalTitleDatabase(false);
     ^
buildtools/make_base:450: recipe for target 'build/source/main.o' failed
make: *** [build/source/main.o] Error 1`

**Comment by urherenow** [comment]
Update your ctrulib. When you build the latest ctrulib, be sure to "make install"

**Comment by kingzhe2011** [comment]
thank you i got it
