### ISSUE TITLE
Error When Installing CIA File

### ISSUE THREAD

**Issue by BannerBomb** [Steveice10/FBI#219]
Top Screen says

Name: CTGP-7.cia
Attributes: Hidden
Size: 2.14 MiB
Title ID: 0004000003070C00
Version: 5120 (5.0.0)
Region: Region Free
Installed Size: 2.44 MiB
###### SD: 480.0 KiB, CTR NAND: 262.6 MiB

Bottom Screen Says

-----------------------------------------------------
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Error

-----------------------------------------------------
Failed to install CIA file.
Result code:0xD8E0806A
Level: Permanent (27)
Summary: Invalid argument (7)
Module: AM (32)
Desc: Cert signature or hash check failed (106)

> Also the CIA was downloaded from its original site which is [dshack](http://dshack.org)
> Also I am on System *Ver. 10.5.0-30U*
> Running *Browser Hax* **&** *Menu Hax*
Does anyone know how to fix this?

**Comment by Committee** [comment]
Are you on CFW? Are you running FBI as a CIA or through the Homebrew Menu?

No CFW - You won't be able to install this cia

**Comment by BannerBomb** [comment]
@Committee im running it through Homebrew Menu

**Comment by Committee** [comment]
Do you have cfw? If not you cannot install any cia.

**Comment by Steveice10** [comment]
I noticed that the top screen says the SD only has 480KiB free, so this might be some weird error code from not having enough free space. Try freeing up some space on the SD card before installing.
