### ISSUE TITLE
Can't install CIA

### ISSUE THREAD

**Issue by AustinYQM** [Steveice10/FBI#220]
Level: Permanent (27)
Summary: <not sure I remember it>
Module: AM (32)
Desc: Invalid NCCH (37)

I am getting this error when trying to install 3ds pokemon games as cias. I don't think the .cia file is the problem as other people using the same source have no run into this problem (As far as I know).

**Comment by AustinYQM** [comment]
I get this error on X/Y/Sun/Moon but not ORAS, for some reason.

**Comment by ihaveamac** [comment]
this is most likely an issue with Gateway and how it does signature check patches, not FBI itself. Gateway only patches the check for the first content of CIAs. your best bet would probably to install CIAs like this under a different custom firmware.

**Comment by AustinYQM** [comment]
Do you have a suggestion on one that has the best success rate with FBI and .cias ?

**Comment by ihaveamac** [comment]
Luma3DS (technically anything that isn't Gateway, pretty much)

**Comment by AustinYQM** [comment]
Cool. Thanks a lot.

**Comment by AustinYQM** [comment]
For anyone seeing this: switching to another CFW did it (used Luma3ds). Thanks for the help, closing issue.
