### ISSUE TITLE
Pasting a larger file over an existing one in ExtData stalls

### ISSUE THREAD

**Issue by svanheulen** [Steveice10/FBI#221]
You can't resize files in ExtData archives, they actually need to be deleted and recreated. So if you try copying a larger file over an existing one of the same name in an ExtData archive, FBI will just stall at a certain percentage.

It would be this section that would need to change: https://github.com/Steveice10/FBI/blob/master/source/ui/section/action/pastefiles.c#L152-L156

But you would need to know the archive type and it doesn't look like you can get that information from the parameters provided to that function.

**Comment by Steveice10** [comment]
Should be fixed.
