### ISSUE TITLE
Error 0xC8804478  with injectable FBI

### ISSUE THREAD

**Issue by MegaHomme** [Steveice10/FBI#222]
Hi o/
I'm currently using Plailect guide to hack my 3DS, have installed al9h and luma, then inject FBI to health&safety.
But now when I try to install a cia, I got this error : http://i.imgur.com/F3vnL0r.jpg
Any help ? :/

**Comment by james-d-elliott** [comment]
Probably a bad SD card

**Comment by Steveice10** [comment]
Is this still an issue?
