### ISSUE TITLE
source code how make error

### ISSUE THREAD

**Issue by fdisk123** [Steveice10/FBI#223]
hi o,
i use fbi in a9l crack system,Using the remote installation of the FBI,but the connection is to slow.i want to modify the socket buffer to speed up, source code buffer defore is 256K.
modify finish. not to compile. in make file an error occurred,error message:
<
 BendeMacBook-Pro:fbi ben$ make
fatal: Not a git repository (or any of the parent directories): .git
Makefile:59: buildtools/make_base: No such file or directory
make: *** No rule to make target `buildtools/make_base'.  Stop.
>
i can try annotation makefile the last row cod.has new error,
<
BendeMacBook-Pro:fbi ben$ make
fatal: Not a git repository (or any of the parent directories): .git
make: *** No targets.  Stop.
>
now i can't build.

any help ?

**Comment by fdisk123** [comment]
devkitARM and citro3d is install ok

**Comment by urherenow** [comment]
You're not typing make from the right directory

**Comment by fdisk123** [comment]
very happy your reply,Can you talk about in detailed specific operation?
so i am javaer,c++ so bad.
thanks !

**Comment by james-d-elliott** [comment]
Sounding like you downloaded the source direct instead of doing git clone --recursive git@github.com:Steveice10/FBI.git

**Comment by Steveice10** [comment]
Exactly that, you need to close the repository recursively.
