### ISSUE TITLE
FBI Eternal Nintendo 3DS screen

### ISSUE THREAD

**Issue by RLilligant** [Steveice10/FBI#226]
This error happens when trying to load FBI while i have NTR booted, the only way i can turn off my 3DS after the bug happens is by removing the battery
i'm on 11.2.0-35

**Comment by urherenow** [comment]
sysnand or emunand? a9lh? Launched from installed .cia or from HBL?

Holding the power button >10 seconds will ALWAYS turn off a system, unless your power button doesn't work at all.

**Comment by RLilligant** [comment]
Sysnand / Luma / .cia
i held it for 15sec and didn't worked
my power button works as normal, i tested it after i removed the battery and turned on the 3DS

**Comment by urherenow** [comment]
a9lh? If not, you CAN'T run FBI.

**Comment by RLilligant** [comment]
yes a9lh

**Comment by urherenow** [comment]
Had to re-read the OP. This problem doesn't happen when you don't run NTR first? If not, it may be some conflict with network functions.

**Comment by RLilligant** [comment]
Yes it doesn't happen when doesn't run NTR

**Comment by urherenow** [comment]
Then this is not an FBI issue; rather an incompatability (or a bug in ntr). The simple solution is don't use FBI with ntr. Use it first.
