### ISSUE TITLE
[Enhancement] Please add an option to Export/Import Saves (From Titles Menu)

### ISSUE THREAD

**Issue by ImReallyShiny** [Steveice10/FBI#227]
I KNOW theres a Export, Import and Delete saves option but thats only for TWL carts! Theres a Browse Save option for CTR carts and cia's but please add a Export/Import option to quickly backup saves - If this gets added it would be a life-saver, I myself tried to get this working but since I mostly have knowledge on CPP and C# and not C I couldnt get it going.

Please add them :)

**Comment by Steveice10** [comment]
Just choose browse save data and copy the root to a location on your SD card.

**Comment by ImReallyShiny** [comment]
I 100% understand that thats how easy it is to do but having a import/export option would be sooo handy to me!
If you can - Send me action.c code I could use to export and import the saves and ill impliment it and compile it for my own personal use - I would just find it super handy and I bet im not the only one who thinks so.

**Comment by Steveice10** [comment]
It's pretty much the exact same thing though, just through more generalized means. Instead of making unnecessary extra functions specific to save data, this is just as easy, works for any filesystem, and you can choose to output the data wherever you want.

**Comment by ImReallyShiny** [comment]
I get that man but imo its a much better way as you dont need to go around making folders and stuff like that - You can click a few buttons and boom you exported - Click a few more boom you imported.
Also in some menus where theres nothing in the top screen you shouldnt have it remove the FBI logo I dont see the point.
