### ISSUE TITLE
Just a couple of compiler warnings

### ISSUE THREAD

**Issue by urherenow** [Steveice10/FBI#228]
build/source/quirc/identify.o
source/quirc/identify.c: In function 'flood_fill_seed':
source/quirc/identify.c:287:25: warning: 'y' may be used uninitialized in this function [-Wmaybe-uninitialized]
    row = q->pixels + (y + 1) * q->w;
                         ^
source/quirc/identify.c:281:4: warning: 'x' may be used uninitialized in this function [-Wmaybe-uninitialized]
    for (i = left; i <= right; i++)
    ^
source/quirc/identify.c: In function 'test_grouping':
source/quirc/identify.c:975:6: warning: 'best' may be used uninitialized in this function [-Wmaybe-uninitialized]
  int best;
      ^
source/quirc/identify.c:983:19: warning: 'best_score' may be used uninitialized in this function [-Wmaybe-uninitialized]
   if (!j || score < best_score) {
                   ^
source/quirc/identify.c:976:6: note: 'best_score' was declared here
  int best_score;

**Comment by Steveice10** [comment]
Fixed.
