### ISSUE TITLE
Add "Paste (Overwrite)" option

### ISSUE THREAD

**Issue by Plailect** [Steveice10/FBI#231]
I'm currently taking advantage of the latest FBI release's functionality where the pasted file will retain the overall file size of the previous file due to overwriting instead of deleting first. 

The commit https://github.com/Steveice10/FBI/commit/69d81786b7af8d336f85fd20446715e6e10f2100 has fixed this bug, but I have no other easy way of replicating this functionality.

Could I get a separate option to replicate the old behavior?

**Comment by Steveice10** [comment]
What exactly is the use case for the old behavior?

**Comment by Plailect** [comment]
One can paste a DSiWare `.app` onto another DSiWare `.app` (overwriting the first bytes but leaving the file size the same) as long as the app you are pasting onto is larger than or equal to the app you are trying to paste, and the system will launch it just fine.

**Comment by Steveice10** [comment]
Ah... That's unintended behavior. I feel like a specialized tool would be more suited for that purpose, and such an operation doesn't really have a place in the FBI file browser.
