### ISSUE TITLE
Issue compiling

### ISSUE THREAD

**Issue by phoen1x74** [Steveice10/FBI#232]
Hi steveice. I'm trying to modify the code of this to make it work with slowhax, so legit CIA installing on 11.0 and 11.1 could be done. I'm getting this error when I compile it however, with and without my modified code. I have the requirements installed with devkitPro. `build/source/ui/section/update.o
In file included from /home/ben/devkitPro/libctru/include/3ds.h:13:0,
                 from source/ui/section/update.c:5:
source/ui/section/update.c: In function 'update_open_src':
source/ui/section/update.c:43:152: error: too few arguments to function 'httpcGetResponseStatusCode'
             if(R_SUCCEEDED(res = httpcSetSSLOpt(context, SSLCOPT_DisableVerify)) && R_SUCCEEDED(res = httpcBeginRequest(context)) && R_SUCCEEDED(res = httpcGetResponseStatusCode(context, &updateData->responseCode))) {
                                                                                                                                                        ^
/home/ben/devkitPro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
In file included from /home/ben/devkitPro/libctru/include/3ds.h:45:0,
                 from source/ui/section/update.c:5:
/home/ben/devkitPro/libctru/include/3ds/services/httpc.h:113:8: note: declared here
 Result httpcGetResponseStatusCode(httpcContext *context, u32* out, u64 delay);
        ^
In file included from /home/ben/devkitPro/libctru/include/3ds.h:13:0,
                 from source/ui/section/update.c:5:
source/ui/section/update.c: In function 'update_check_update':
source/ui/section/update.c:193:33: error: too few arguments to function 'httpcGetResponseStatusCode'
            && R_SUCCEEDED(res = httpcGetResponseStatusCode(&context, &responseCode))) {
                                 ^
/home/ben/devkitPro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
In file included from /home/ben/devkitPro/libctru/include/3ds.h:45:0,
                 from source/ui/section/update.c:5:
/home/ben/devkitPro/libctru/include/3ds/services/httpc.h:113:8: note: declared here
 Result httpcGetResponseStatusCode(httpcContext *context, u32* out, u64 delay);
        ^
buildtools/make_base:450: recipe for target 'build/source/ui/section/update.o' failed
make: *** [build/source/ui/section/update.o] Error 1`

**Comment by Steveice10** [comment]
Make sure you have a build of the latest ctrulib git.
