### ISSUE TITLE
Can't install CIA's

### ISSUE THREAD

**Issue by wixerzp** [Steveice10/FBI#233]
When I try to install any CIA with FBI, it goes to 100% and then displays this error message : "Failed to install CIA file. Result code: 0xC92044FA Level: Status (25) Summary : Canceled (9) Module: FS (17) Desc: <unknown> (250)"

**Comment by Steveice10** [comment]
Looks to be a FAT operation denied error. Maybe run a disk check on your SD card just in case, or check free space?
