### ISSUE TITLE
Who turned out the lights?

### ISSUE THREAD

**Issue by idgrepthat** [Steveice10/FBI#234]
You probably need to use consoleinit since users aren't likely to sit through 1 hour of black screen during waithax (if it's even running).

Hint: you'll need to call gfxSetScreenFormat(GFX_TOP, GSP_BGR8_OES) after waithax to restore the top panel to 24bit color since libctru puts it in bgr565.

**Comment by Steveice10** [comment]
Yeah I was planning on that (and have since done it), but just didn't have enough time and wanted to get the basic support commit out.
