### ISSUE TITLE
'ui_draw_top': error

### ISSUE THREAD

**Issue by Erdest** [Steveice10/FBI#235]
source/ui/ui.c: In function 'ui_draw_top':
source/ui/ui.c:141:57: error: expected expression before ',' token
     snprintf(verText, 64, "Ver. %d.%d.%d", VERSION_MAJOR, VERSION_MINOR, VERSION_MICRO);
                                                         ^
make: *** [build/source/ui/ui.o] Error 1

I installed both devkitARM and citro3d + ctrulib and tried many times to build it with the command make but cant pass over this error.

**Comment by urherenow** [comment]
Github isn't a help forum. Use gbatemp if you don't have an actual bug to report.

With that said, did you clone and then build the latest citro3d and ctrulib, or did you simply grab the latest releases?

You need to build the latest tourself and "make install".

**Comment by Steveice10** [comment]
Make sure you actually clone the git repository; otherwise the version variables will be empty and it will error like that.

**Comment by urherenow** [comment]
or, if you simply tried to update from a previous clone, don't forget the following commands:

git pull origin master
git submodule update --init --recursive
git fetch --all
