### ISSUE TITLE
FBI Network Install

### ISSUE THREAD

**Issue by initPRAGMA** [Steveice10/FBI#236]
Since you deleted one of the most useful features im kinda stuck now.
Can you make it show our 3DS's IP somewhere onscreen? Its why I used that option because it showed the IP.

**Comment by Steveice10** [comment]
The purpose of this feature was not to show your IP, nor is there any reason FBI would need to show your IP.

**Comment by initPRAGMA** [comment]
Right but it is handy for NTRViewer and other tools like FTP.

**Comment by Steveice10** [comment]
Doesn't the 3DS FTP server display the IP itself?

**Comment by initPRAGMA** [comment]
Probs does but I dont use it was just an example.

**Comment by james-d-elliott** [comment]
It does, and takes a moment to start.

**Comment by dogtopus** [comment]
A good alternative would be mtheall/ftpd if you just want the IP address.
