### ISSUE TITLE
Permission error while using servefiles.py

### ISSUE THREAD

**Issue by waynelimt** [Steveice10/FBI#237]
Hi, I followed the README.md accompanying the servefiles.py on instructions on how to use the script, but encountered an error while executing the script: [Execution Output](https://s24.postimg.org/69epayepx/permissionerror.png)

How can I get to solving this issue? I already installed qrcode & netifaces. Thanks.

**Comment by Steveice10** [comment]
I think the issue is that the number of CIAs you're including exceeds the limit of a QR code size. Try splitting that into parts.

**Comment by waynelimt** [comment]
ok thank you. it worked after I removed some of the files. One thing though, the script has one more dependency, which is Image.

**Comment by Steveice10** [comment]
Looks like I missed that because it was included with my installation, thanks.
