### ISSUE TITLE
FBI 1.4.16 reports incorrect amount of free space on SD card (always around 138 MB)

### ISSUE THREAD

**Issue by Jaitsu** [Steveice10/FBI#24]
At the moment, FBI's calculation of free space seems to be broken, at least in 1.4.16. Not sure about earlier versions. In 1.4.16 it's reporting 137.86MB (144556032 bytes) free; in my H&S 1.4.8 copy on the same system, I see 1253.97 MB (1314881536 bytes) which is correct.

O3DS, SysNAND 9.0.0/EmuNAND 10.3.0, problem present on both.

**Comment by urherenow** [comment]
Well, maybe that will lead to the reason it doesn't work at all on N3DS.

**Comment by Steveice10** [comment]
Should be fixed with 1.4.17.
