### ISSUE TITLE
CIA Installation crash

### ISSUE THREAD

**Issue by deviouswatch** [Steveice10/FBI#240]
I installed a9lh on an o3DS in accordance with [this guide](https://3ds.guide/installing-arm9loaderhax), with a manual software [update to 9.2](https://3ds.guide/9.2.0-ctrtransfer). I'm attempting to clone to a 2DS with [this guide](https://3ds.guide/dsiware-downgrade-(app-injection-and-second-3ds)). I lost DSiWare functionality so attempted to install the cias from [this guide](https://3ds.guide/troubleshooting#twl_broken).

SO now that the context is out of the way, I successfully installed HB and Luma updater by CIA. now when I try to install a CIA it asks me to confirm, freezes instantly then crashes to the menu with the following message "An error has occurred forcing the software to close. The system will now restart(Unsaved data may be lost)"

All software was latest version on install except for the hax itself as per the guide. Just to clarify that this is the o3DS with the issue. Any operation my FBI now causes it to crash to menu followed by the reboot.

**Comment by Steveice10** [comment]
Can you check your SD card's free space and integrity?

**Comment by deviouswatch** [comment]
So found a work around - I remounted FBI on H&S and it worked to fix the error in the meantime. The self installed CIA still won't install though. WIll submit Luma logs when I get back home

**Comment by Steveice10** [comment]
If it works as a fresh H&S install, have you tried removing the standalone version and reinstalling it?

**Comment by daviidx** [comment]
Hello!
Find a similar problem ...
FBI 2.4.4 stops when I try to install MK7 Legit cia and the console restarts.
However, with fbi 2.4.2 injected into H&S, MK7 was installed without any error.
My console has updated arm9lh and luma.

**Comment by Steveice10** [comment]
Can you try this build?

https://www.dropbox.com/s/vonz9n06i7jrrww/FBI.zip?dl=1

**Comment by suzsuzuki** [comment]
I had a similar problem after update from 2.4.2 to 2.4.4. Crash after install cias like TWLoader. Your new build in this post solved my problem

**Comment by Steveice10** [comment]
Alright. Closing, then.

**Comment by suzsuzuki** [comment]
Ok, sorry but it didn't solve my problem at all. Crashed again.

**Comment by daviidx** [comment]
[https://www.dropbox.com/s/vonz9n06i7jrrww/FBI.zip?dl=1](url)
It works.
Installed fbi 2.4.4 independently.
MK 7 legit cia was installed correctly.

**Comment by daviidx** [comment]
It works.
Installed fbi 2.4.4 independently.
MK 7 legit cia was installed correctly.

**Comment by daviidx** [comment]
It works.
FBI 2.4.4 Installed independently.
MK 7 legit cia was installed correctly.

**Comment by suzsuzuki** [comment]
Ok, I can't post the dmp file because it didn't exist on SD card. I think it's an SD access problem because when I try to copy a file from SD it crashes too... Here a photo whe I try to copy a file. The only workaround for me was inject in HS the version 2.4.2
![20161220_163641](https://cloud.githubusercontent.com/assets/20933693/21363406/a157d23e-c6d3-11e6-875b-64a515d2ecb8.jpg)

**Comment by suzsuzuki** [comment]
I also have an New3DS and it happens too... with the latest FBI version 2.4.4

**Comment by Steveice10** [comment]
Can you redownload 2.4.4 now? I've updated the release with what should be a fix.

**Comment by suzsuzuki** [comment]
Thanks now seems to be fixed!!

**Comment by deviouswatch** [comment]
File no longer available on dropbox, doesn't seem like the code is committed yet, any chance you can put it back up?
