### ISSUE TITLE
The new theme directory location doesn't seem to work.

### ISSUE THREAD

**Issue by StateOfException** [Steveice10/FBI#241]
Title says it all, really.

I've relocated the contents of /fbitheme/ to /fbi/theme, but FBI doesn't load the theme in question.

**Comment by Steveice10** [comment]
And you're sure you have the latest? If you somehow managed to download it within the 5 or so minutes between when I first released 2.4.4 and when I reuploaded it to put in that last minute change, you might have to redownload it.
