### ISSUE TITLE
Bring back network install

### ISSUE THREAD

**Issue by witheld9** [Steveice10/FBI#242]
QR code installs don't fit in my workflow at all. I can't imagine any workflow here they fit in, for testing it's much much easier to press "network install" and then use a script.

**Comment by Steveice10** [comment]
With the latest FBI, if you've scanned a QR code from servefiles pointing to your compiler output at least once, you can just leave the script running in the background and press X in the QR code installer to repeat the last request. Works just fine for me when developing.
