### ISSUE TITLE
[Suggestion] Add warnings on CTRNAND/TWLNAND operation

### ISSUE THREAD

**Issue by MelonGx** [Steveice10/FBI#243]
http://gbatemp.net/threads/just-heard-that-one-noob-deleted-everything-in-ctrnand-with-fbi.453551/

**Comment by Steveice10** [comment]
....why do I need a warning to tell someone that deleting everything on their NAND is a bad idea?

**Comment by MelonGx** [comment]
....because not all the noobs have enough IQ or common sense.

**Comment by Steveice10** [comment]
Yes, but then I'd have to add warnings to everything that could potentially cause damage. Which... includes almost all of FBI's features. Installing a bad CIA, deleting a system title, etc.

**Comment by PokeAcer549** [comment]
Maybe just put a little "Careful with poking around with your NAND" message? Or, you know, have a keycombo that enables it - don't keep the keycombo private, but still.

**Comment by Steveice10** [comment]
Added.
