### ISSUE TITLE
Impossible to network install large directories now

### ISSUE THREAD

**Issue by witheld9** [Steveice10/FBI#244]
Large directories of CIA files generate massive QR codes that are impossible to scan- or even larger than your monitor.

**Comment by witheld9** [comment]
![snapshot27](https://cloud.githubusercontent.com/assets/13049028/21378940/734dcbc6-c707-11e6-8881-0a06a8b5d9fa.png)

An example of an impossible QR code

**Comment by Steveice10** [comment]
How is it "impossible", exactly?

**Comment by witheld9** [comment]
The camera doesn't have the resolution to scan that, and adding more files would make it larger than my monitor, making it further impossible to scan.

**Comment by svanheulen** [comment]
Using single character file names, the most I can put in a QR before FBI stops being able to read it is around 9. If I lower the QR error correction to the minimum, I can get it to recognize a QR with about 15 files.

The strange thing is that even the example QR above is actually smaller then the ones used for Ninjhax: https://smealum.github.io/ninjhax2/JL1Xf2KFVm/qri/N3DS_U_26624_usa_9221_installer_0.png So it's not impossible for the 3DS to read QRs of that size.

**Comment by Steveice10** [comment]
Shouldn't be much of an issue now, as QR codes are no longer the main method of local network installation.
