### ISSUE TITLE
[Not an issue, but a question] Which part of the code is used to fetch banner data from NTR carts?

### ISSUE THREAD

**Issue by Alerdy** [Steveice10/FBI#245]
I was wondering, which part of the source code in FBI is used to fetch the banner data of the NTR cart? We need to bring the code over to TWLoader, which is an .nds rom loader that runs in CTR mode. It has the option to launch cartridges, and that works fine. But we need to use the code used in FBI to fetch the banner data (name, publisher, icon) of the NTR cart to display it. If you could show where it is, that would be great.

**Comment by Steveice10** [comment]
https://github.com/Steveice10/FBI/blob/master/source/ui/section/task/listtitles.c#L139
