### ISSUE TITLE
Remote install - Network unavailable

### ISSUE THREAD

**Issue by laymain** [Steveice10/FBI#249]
Hi,

~~Could you please enable HTTP redirection following when remotly installing CIAs?~~

**Comment by Steveice10** [comment]
Can you elaborate? Installs over HTTP should already follow redirects.

**Comment by laymain** [comment]
Ok it seems that's not the problem, I have misread.
I have the following error:

```
Failed to install from QR code.

Result code: 0xD8A0A046
Level: Permanent (27)
Summary: Invalid state (5)
Module: HTTP (40)
Desc: Network unavailable (70)
```

**Comment by Steveice10** [comment]
It's probably exactly what it sounds like. You don't seem to be connected to a network, or at least it isn't working properly.

**Comment by laymain** [comment]
My network is properly working but I'll have a try with another app to check if it is has a link with FBI or with my console. Closing for now, I'll reopen (or ask for) if needed
