### ISSUE TITLE
Sort Title By ID? In NAND

### ISSUE THREAD

**Issue by Syphurith** [Steveice10/FBI#25]
As you might already know, if there is some SD application in the NAND (wrongly installed) there would be black squares. I accidentally have some in a NAND dump, and after I removed all those whose title ID starts with 00040000 all the black squares got wiped out as expected.
Finding all those out in the NAND list is possible, but quite boring sometimes, and the mistakes made would brick the NAND (fortunately i was purging those out of the EmuNAND).
The FBI installer is quite a good tool for manage those. Eh so could please ever think of that in some release after? I don't mean to ask for that immediately.
Also i've heard you're developing the memchunkhax2. Good luck to you, and throw the ETAs away!

**Comment by Steveice10** [comment]
Titles will be sorted by ID in the rewrite.
