### ISSUE TITLE
Newest version of FBI(with slowhax) issue on 11.0.0-33U

### ISSUE THREAD

**Issue by Burningocean2012** [Steveice10/FBI#251]
Hello,I made an account to ask for help with my error.

Sorry if that other Issues topic covers it,I have asked about this on r/3dhacks and GBATemp but no answers for 3 days.My errors are just a little different.Most of them are the same error for all options.It all started after waithax was added to FBI.

When i use it I just get an error not allowing me to do anything now.No lists populate and all I can do is turn off the 3ds.I will attach a .txt file detailed all the errors I get.
I even tried repairing my 3ds db files which caused me alot of trouble having to re download all my games.

Entry points tried:Basehax,Steelhax and Soundhax.

[FBI Issues.txt](https://github.com/Steveice10/FBI/files/677954/FBI.Issues.txt)

**Comment by Steveice10** [comment]
The system save data error is normal, as I can't get access to that via 3dsx. As for the rest of the errors, they're already fixed in source. For now, use the last build linked in this issue: https://github.com/Steveice10/FBI/issues/247#issuecomment-269695934

**Comment by urherenow** [comment]
@burningocean2012 and lesson learned (I hope)... If during troubleshooting or testing, you think you need to "fix" or delete a file, BACK IT UP FIRST. Back up your whole  (m)SD card. Including your emunand, If you use one (or more). Back up your sysnand as well.

Sorry for replying to a closed issue @SteveIce10, but it needed to be said.
