### ISSUE TITLE
FBI fatal error

### ISSUE THREAD

**Issue by Ecko3351** [Steveice10/FBI#254]
I seem to be getting this weird error when I install CIA files. Not all the time but once and awhile it shows up. It started popping up once I did a system memory format, but the CIA files install just fine even with the error.
 
![img_0490](https://cloud.githubusercontent.com/assets/24849211/21575302/99c98e34-cecd-11e6-9411-24651093d56b.JPG)

A9HL Luma3d 6.6
New 3ds 11.2

**Comment by Steveice10** [comment]
And this is with the latest version of FBI?

**Comment by Ecko3351** [comment]
Yes, its on 2.4.5

**Comment by Steveice10** [comment]
And out of curiosity, are you using the option to install AND delete at the same time?

**Comment by Ecko3351** [comment]
Yes.

**Comment by Ecko3351** [comment]
I don't know if this is a problem but my kernel and firm shows 2.52-0 when i open up 3dsident. I installed like 50 games and everything so I don't see a problem...

Sorry I'm still new to all of this.

**Comment by Steveice10** [comment]
Does this build resolve the issue?

https://www.dropbox.com/s/0vxd6e7rdjcbyv9/FBI.zip?dl=1

**Comment by Ecko3351** [comment]
I will give it a shot now.

**Comment by Ecko3351** [comment]
I installed a few VC games and looks like there's no error! Thank you :)
