### ISSUE TITLE
(semi issue) Regarding failed CIA tickets

### ISSUE THREAD

**Issue by Sharanbasav** [Steveice10/FBI#255]
In issue 247, i said that all the CIA installations were failing and I gave the error code, to which you replied that I should delete the ticket and try again. Well the thing is that the FIRST CIA that I downloaded ( the one which it gave an signature check fail) wasn't legit. The second one was legit, but the ticket failed to install. I deleted the ticket and installed the CIA again, but it still failed. I'm guessing this is not FBIs fault. But do you think the bad ticket is somewhat stuck in my system and it refuses to take anything else? Should i use another SD card?

**Comment by urherenow** [comment]
Ummm... Tickets are in NAND.

**Comment by Sharanbasav** [comment]
Whoops
