### ISSUE TITLE
Add a magic packet to FBI network install

### ISSUE THREAD

**Issue by miltoncandelero** [Steveice10/FBI#259]
Hello.

I was thinking about a way to discover the 3ds automatically on the network and a method that works somewhat reliably is try to connect to all IP adresses on port 5000 and if the connection doesn't time out we found FBI.

The problem is, there is no way to connect to fbi network install without FBI waiting for you to pass the network adresses for the .CIA and .TIK transfer.

The idea would be to have a "magic packet", lets say, if the payload FBI recieves on port 5000 is "Ping", it responds "Pong" and then keeps waiting for another connection.

Could it be done? or I am talking nonsense?

**Comment by Steveice10** [comment]
I'd rather require the user to explicitly specify what device they're connecting to, for security among other things. Plus, scanning the network like that doesn't sound like a good strategy.
