### ISSUE TITLE
Network install not working on release 2.4.6

### ISSUE THREAD

**Issue by TheAquaSheep** [Steveice10/FBI#261]
Attempted Boop, SocketPunch and servefiles.py - all failed to transfer when using Network Install -> URL.

I couldn't Downgrade the FBI to a lower version but had the old H&S inject on the SD card from installing A9LH(FBI version 2.4.2). This works with SocketPunch. I can test the other programs also work on 2.4.2 if needed.

**Comment by Steveice10** [comment]
Do you have anything on your network blocking port 8080?

**Comment by TheAquaSheep** [comment]
I confirmed being able to access the HTTP server, started by servefiles.py,  on port 8080 using a browser on another device connected to the same WLAN.

I am successfully installed a different .cia to a different 3DS by going through the python script and pasting into an interactive window - at which point I realised that there was a fault in the script and that I just needed to use the latest version!

Apologies for the false issue.
