### ISSUE TITLE
Can't compile :(

### ISSUE THREAD

**Issue by LexXxe** [Steveice10/FBI#262]
Hi, i try compile FBI and show me this message

`make: git: Command not found
Building for 3DS...
build/3ds-arm/source/core/default.shbin.c
build/3ds-arm/source/core/default.shbin.o
build/3ds-arm/source/main.o
build/3ds-arm/source/core/clipboard.o
build/3ds-arm/source/core/linkedlist.o
build/3ds-arm/source/core/screen.o
build/3ds-arm/source/core/spi.o
build/3ds-arm/source/core/util.o
source/core/util.c: In function 'util_http_open_ranged':
source/core/util.c:658:128: error: expected expression before ',' token
         snprintf(agent, sizeof(agent), "Mozilla/5.0 (Nintendo 3DS; Mobile; rv:10.0) Gecko/20100101 FBI/%d.%d.%d", VERSION_MAJOR, VERSION_MINOR, VERSION_MICRO);
                                                                                                                                ^
make: *** [build/3ds-arm/source/core/util.o] Error 1
rm build/3ds-arm/source/core/default.shbin.c`

i hope you can help me, thanks 

PS: i have installed citro3d and lastest lubctru

**Comment by dogtopus** [comment]
Install git and try to clone the repository, rather than just download the source code archive
