### ISSUE TITLE
2.4.6 Network Install Issue

### ISSUE THREAD

**Issue by ManlyDonut** [Steveice10/FBI#263]
2.4.4 (the version I updated from) I've had no trouble with network installing. Note, I use SocketPunch, which hasn't been updated since June, so I'm aware it may be the reason. My issue is, the moment SocketPunch tries to connect to FBI, FBI locks up completely and I have to hard reset my 3DS. 

I appreciate your work on FBI, and I hope I'm not coming off as whining.

**Comment by Steveice10** [comment]
The old method of network installation is no longer supported.
