### ISSUE TITLE
TitleDB Feature Request

### ISSUE THREAD

**Issue by rpalmon** [Steveice10/FBI#264]
It would be nice if there was a feature where the TitleDB menu could check for updates. The color of the text would be Blue. Apps you have would be below the updates that you have available. You should check out Homebr3w Browser which has that feature.

**Comment by Steveice10** [comment]
Homebr3w keeps a cache of update dates, which I don't want to do. I'd rather be able to retrieve the version from TitleDB and compare it to the locally installed version. I requested this a while back, but I don't think it's been added since.
