### ISSUE TITLE
Build Error on latest master

### ISSUE THREAD

**Issue by phoen1x74** [Steveice10/FBI#266]
Have the latest ctrulib, devkitpro, and devkitarm. 
```
source/ui/ui.c: In function 'ui_draw_top':
source/ui/ui.c:144:57: error: expected expression before ',' token
     snprintf(verText, 64, "Ver. %d.%d.%d", VERSION_MAJOR, VERSION_MINOR, VERSIO
                                                         ^
buildtools/make_base:573: recipe for target 'build/3ds-arm/source/ui/ui.o' failed

```

**Comment by urherenow** [comment]
Fresh clone with --recursive?

**Comment by Steveice10** [comment]
Make sure you have git and actually cloned the repository instead of downloading a zip.

**Comment by fr3quency** [comment]
Lol every noob is creating a new 'Issue'. Don't you feel ashamed for wasting the dev's time with your silly "Issues"?

**Comment by KamikazePlatypus** [comment]
Fresh cloned with --recursive and I'm getting this same error.

**Comment by Steveice10** [comment]
The error indicates that the version flags aren't properly set, meaning that it isn't able to run git and ask for the current tag.
