### ISSUE TITLE
FBI can't recognise a .cia

### ISSUE THREAD

**Issue by charlopian** [Steveice10/FBI#268]
Hello, I'm aware this issue has been raised before and fixed- using safehax on my 3dsxl i can't get the latest release of FBI to install a particular game backup cia. It just shows as an archive, with the option to delete, rename, copy, etc. In the previous thread you posted a link that seems to have helped people in the past but this is no longer available

**Comment by Steveice10** [comment]
Are you on 11.2.0?

**Comment by charlopian** [comment]
Yes

**Comment by Steveice10** [comment]
11.2.0 is not officially supported yet by FBI.
