### ISSUE TITLE
Request: Install, delete and launch

### ISSUE THREAD

**Issue by Jolty95** [Steveice10/FBI#269]
Most times when I intall a CIA I just want to install and delete, al later, go to root screen to press Start to close and later, open the installed cia. Could you add an option to install, delete and launch?

Thanks for all :)

**Comment by Steveice10** [comment]
I feel like these chains are getting a bit complicated; I'd have to have install, install and launch, install and delete, and install, delete, and launch.

**Comment by Jolty95** [comment]
Oh, sorry...I just thought it was a good idea. Sorry and thanks for all :)
