### ISSUE TITLE
Crash upon "install all cias" in a directory

### ISSUE THREAD

**Issue by DreamingEmma** [Steveice10/FBI#271]
This seems to be occurring consistently. I'm trying to install a directory with a bunch of DS-forwarder CIAs and one VC-inject CIA, but when I click "install all cias" or "install and delete all cias" FBI crashes and I get the system message that "An error has occurred, forcing the software to close. The system will now restart. (Unsaved data may be lost.)"

Installing or installing/deleting the cias individually works as normal.

**Comment by Steveice10** [comment]
If you have Luma3DS, can you enable the ErrDisp option and show me the error information it gives when the crash happens?

**Comment by DreamingEmma** [comment]
`An exception occurred

Processor: ARM11 (core 1)
Exception type: data abort
Current process: FBI`

Crash dump:
`dec0 adde feca adde 0200 0100 0b00 0100
0300 0000 4c02 0000 5c00 0000 3000 0000
8801 0000 1000 0000 e0bf ad87 0005 1607
8066 7927 00ba 997f 0000 0000 d887 1108
0000 0000 0000 0000 0000 0000 0000 0000
0888 1108 0000 0000 0000 0000 78ce 1308
0c08 1100 1c60 1100 1000 0020 0500 0000
0d10 0000 e3bf ad87 0007 0000 c00a bdee
c00a bdee 0820 90e5 0c30 90e5 3f10 81e2
3f20 82e2 3f10 c1e3 3f20 c2e3 3f30 83e2
0220 81e0 3f30 c3e3 0330 82e0 0300 80e0
0320 d0e5 0000 0000 0000 0000 d0ce 1308
10eb 1200 0000 0000 0000 0000 0000 0000
0000 0000 d0ce 1308 e005 1408 0010 0000
e4b6 1000 0010 0000 0000 0000 d4ce 1308
0000 0000 931c becb 5b03 0000 0000 0000
0000 0000 0000 0000 0000 0000 2600 a300
0000 0000 0010 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 ec0b 1300 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 4642 4900
0000 0000 0001 800f 0000 0400 `

**Comment by Steveice10** [comment]
I need the register values; basically, everything on the top screen. Taking a picture of the screen would suffice.

**Comment by DreamingEmma** [comment]
Updated with the register values

**Comment by DreamingEmma** [comment]
Also, this crash came from using "install all cias", not "install and delete all cias".

**Comment by Steveice10** [comment]
Would you mind sending me some of the DS forwarder CIAs to look at? Shouldn't be a problem since they're just homebrew forwarders, not actual games or apps.

**Comment by Steveice10** [comment]
Given the nature of the error and the fact that I can't reproduce it with my own CIAs, this is likely an issue of a bad CIA file somewhere in your batch.
