### ISSUE TITLE
Error when using hostednetwork in Win7 to execute servefiles

### ISSUE THREAD

**Issue by Catamo** [Steveice10/FBI#272]
Hello. First of all thank you for all the effort. Now to the point.

I came across the error because I access internet in my 3DS using Win7 hostednetwork AP. To put it in another way, I don't have WiFi so I share internet from the laptop. When doing this another connection is added so I have Local Area Network 1 and Local Wireless Connection 2 (this is an example), each with different IPs. The first, the one with access to internet, have an ip like this: 10.13.x.x And the second, the one that gets the shared internet from the first, has an ip like this: 192.168.x.1

When I run: **python servefiles.py <3DS IP> <Cia Filename>**. All works at first, but then it gets stuck really quickly and throws an error that says something about the host interrupted the conection. So I deactivated the firewall of my pc, did a fresh install of Python 3 and got the same error.

Then I noticed that the script took the 10.13.x.x ip instead of the 192.168.x.1, the later being the one from the Wireless connection that communicated the 3DS and the laptop. So I begun to meddle with the  script to test if this was the problem and changed some of the code in line 33:

`baseUrl = [(s.connect(('8.8.8.8', 53)), s.getsockname()[0], s.close()) for s in [socket.socket(socket.AF_INET, socket.SOCK_DGRAM)]][0][1] + ":8080/"`

For:

`if len(sys.argv) == 4:
        baseUrl = sys.argv[3] + ":8080/"
else:
        baseUrl = [(s.connect(('8.8.8.8', 53)), s.getsockname()[0], s.close()) for s in [socket.socket(socket.AF_INET, socket.SOCK_DGRAM)]][0][1] + ":8080/"`

I did this with the purpose of setting manually the host IP in cases like mine where there are various IPs. And the good part is that it worked. Right now the CIA is being installed.

I guess that there is a better way to solve this problem but I have little knowledge of python. So I will be waiting your response.

Hope I helped, happy new year.

**Comment by Steveice10** [comment]
Added a host IP argument to servefiles.
