### ISSUE TITLE
servefiles.py single file mode 404 in Linux

### ISSUE THREAD

**Issue by keeyeong** [Steveice10/FBI#274]
Changing this

payload += baseUrl + quote(os.path.basename(directory))

to this

payload += baseUrl + quote(os.path.basename(directory)) + "\n"

Solves it

**Comment by Steveice10** [comment]
As a Linux user myself, I have not had this issue. Are you using the latest version of both the script and FBI?

**Comment by keeyeong** [comment]
After seeing your comment, I went and tested it a bit more extensively. I'm on FBI 2.4.6 and servefiles.py on branch master.

Under a specific directory for a specific file, it happens!

```
$ servefiles.py 192.168.192.80 PoSuLEGITCIA.cia
Preparing data...

URLS:
192.168.192.20:8080/PoSuLEGITCIA.cia

Opening HTTP server on port 8080...
Sending URL(s) to 192.168.192.80:5000...
192.168.192.80 - - [10/Jan/2017 00:03:17] code 404, message File not found
192.168.192.80 - - [10/Jan/2017 00:03:17] "GET /PoSuLEGITCIA.cia�� HTTP/1.1" 404 -
Shutting down HTTP server...

```
I noticed the trailing characters in the GET, and that seems to be solved appending "\n" to the URL sent to FBI.

Seems to only affect the files PoMoLEGITCIA.cia and PoSuLEGITCIA.cia. Other CIAs i tested works fine.

Surrounding the output URL + their lengths (and the encoded one) with quotes shows no trailing characters in the generated URL to FBI:

```
URLS:
payload = "192.168.192.20:8080/PoSuLEGITCIA.cia", length=36
payloadBytes = "192.168.192.20:8080/PoSuLEGITCIA.cia", length=36
```
Also the URL works with Chrome on my laptop, so the problem is probably from FBI's request?

**Comment by keeyeong** [comment]
Its definitely about the length of the filename:

```
$ touch aaaaaaaaaaaa.cia
$ servefiles.py 192.168.192.80 aaaaaaaaaaaa.cia 
Preparing data...

URLS:
192.168.192.20:8080/aaaaaaaaaaaa.cia

Opening HTTP server on port 8080...
Sending URL(s) to 192.168.192.80:5000...
192.168.192.80 - - [10/Jan/2017 00:28:23] code 404, message File not found
192.168.192.80 - - [10/Jan/2017 00:28:23] "GET /aaaaaaaaaaaa.cia�� HTTP/1.1" 404 -
Shutting down HTTP server...
$
```

I managed to reproduce the problem with an empty file with the exact amount of characters in its name. Adding one more a to the file name and it works:

```
$ mv aaaaaaaaaaaa.cia aaaaaaaaaaaaa.cia 
$ servefiles.py 192.168.192.80 aaaaaaaaaaaaa.cia 
Preparing data...

URLS:
192.168.192.20:8080/aaaaaaaaaaaaa.cia

Opening HTTP server on port 8080...
Sending URL(s) to 192.168.192.80:5000...
192.168.192.80 - - [10/Jan/2017 00:31:49] "GET /aaaaaaaaaaaaa.cia HTTP/1.1" 200 -
Shutting down HTTP server...
$ 
```

I hope this is a good lead!

**Comment by Steveice10** [comment]
Does this build of FBI resolve the issue?

https://www.dropbox.com/s/td2odty6h2w23hn/FBI.zip?dl=1

**Comment by keeyeong** [comment]
Seems like it does!

BTW, love the new network install method, way faster than before.
