### ISSUE TITLE
The new startup animation clashes really badly with just about any custom theme.

### ISSUE THREAD

**Issue by StateOfException** [Steveice10/FBI#276]
Title says it all, really. It's pretty slick- but is there any way it could be made to pull colour settings from the configuration file?

It's not really a dealbreaker, by any stretch- but it does look a bit jarring, particularly if the user's using a not-white theme.

**Comment by Steveice10** [comment]
Not possible; the logo data is fixed, displayed by the home menu, and out of FBI's control post-compile. You'd have to compile FBI yourself with an edited logo.

**Comment by Steveice10** [comment]
Does this look any better? Although I can't make the logo themeable like the rest of FBI, I can try to improve the transition into custom themes.

https://www.dropbox.com/s/51epeo46zfw7kfp/FBI.zip?dl=1
