### ISSUE TITLE
Suggestion to change the shebang line for the servefiles.py script

### ISSUE THREAD

**Issue by waynelimt** [Steveice10/FBI#277]
Hi, the installation of python for everyone is different (whether on Windows/Linux), and the shebang line is causing my installation of python to fail and not work -> "Unable to create process using '/bin/python servefiles.py ...."
not everyone's python executable is in /bin/python, so for suggestion, i think the shebang line "#!/usr/bin/env python3" is more compatible across different platforms. if you can change the shebang line for the script to be included in the future releases it will be good.

**Comment by Steveice10** [comment]
I changed it to use env, but I'd rather keep it using python, not python3; if for whatever reason you only have python3, just explicitly run the script with that command.
