### ISSUE TITLE
FBI 2.4.7 hangs on splash screen when using a custom TID

### ISSUE THREAD

**Issue by MegaPramuk** [Steveice10/FBI#279]
First, the splash screen looks really nice when launched from home menu!
But unfortunately, it breaks launching 2.4.7 for me since I've manually set the TID to be 0x00000 so it's listed directly as the second item in DevMenu (first being the CTR card).
I've tried launching it from both home menu and DevMenu with both hanging on the splash screen (home menu) or black screen (DevMenu).
Version 2.4.6 worked fine for me with the TID, so could it be that the splash screen uses a hardcoded TID and therefore fails to launch?
I don't know anything about the splash screen format used by the 3DS so it might sound farfetched.

**Comment by Steveice10** [comment]
You shouldn't be using 0x00000 since that's NATIVE_FIRM's unique ID, but I'll look into it.

**Comment by MegaPramuk** [comment]
According to [3dbrew](https://www.3dbrew.org/wiki/Title_list#00040130_-_System_Modules) the NATIVE_FIRM's unique ID is `0x01002` with `00040130` being the high ID. 
So NATIVE_FIRM shouldn't be affected any way, unless I'm misunderstanding something.

**Comment by Steveice10** [comment]
NATIVE_FIRM's low title ID is 00000002, which is a unique ID component of 0x00000 and a variation component of 0x02.

**Comment by Steveice10** [comment]
To confirm, have you made sure that building it manually without the title ID change works fine?

**Comment by MegaPramuk** [comment]
Yeah, if I don't change the ID I can run it just fine.
I've also just did some tests, which may or may not help.

- Compile 2.4.6 again with only the `UNIQUE_ID` constant changed -> launched
- Compile 2.4.7 with no custom splash but changed `UNIQUE_ID` -> didn't launch
- Copy the 2.4.7 meta folder and Makefile into 2.4.6 (with `UNIQUE_ID` changed) and compiled -> launched

**Comment by Steveice10** [comment]
Two things:
* When you tested 2.4.6 with 2.4.7's meta and Make file, did you also pull the latest buildtools submodule into 2.4.6?
* Have you tried a unique ID other than 00000 just in case? Something close to what it was originally or otherwise known to be a reasonable choice.

**Comment by Steveice10** [comment]
Closing this due to age and the fact that changing the unique ID seems to work fine for me.
