### ISSUE TITLE
Option to delete cia file after it is installed (delete option won't work on v1.4.17)

### ISSUE THREAD

**Issue by lprot** [Steveice10/FBI#28]
That options will be extremely useful as if you wrote a bunch of cia and you want to install them all - you need space in the process...

**Comment by Steveice10** [comment]
There is a mode to delete CIA files from the SD card.

**Comment by lprot** [comment]
I mean it'd be great like if for example on the card there is 3 cia's and you run install all. Now it installs all them. It'd be nice if it installs cia #1 then delete it, then install #2 and delete it and so on...

**Comment by Committee** [comment]
An automated delete when you use the Install All CIAs in Selected Folder option?

**Comment by lprot** [comment]
Yeah.

**Comment by lprot** [comment]
Looks like it can be just one more option. Like install and autoremove all cia in selected folder. The key of the process is that you need to delete cia just after it is installed. Not after all installed as it makes no sense.

**Comment by lprot** [comment]
btw I just tried to manually remove hblauncher_loader.cia and FBI reported it can't find it. I had 88 xorpad files in the root of SD... Dunno what caused that error though... Will take a look in that more.

**Comment by lprot** [comment]
Delete function just won't work. Tried on a bunch of other cia's. FBI 1.4.7 installed from cia to rxtools emunand 10.3 o3ds xl. Install option works just fine.

**Comment by Mrrraou** [comment]
After installation, a CIA can't be deleted by FBI from SD card. You have to close the app and restart it to being able to delete the CIA file from the app.
