### ISSUE TITLE
how to remote install

### ISSUE THREAD

**Issue by h2y** [Steveice10/FBI#280]
thanks at first.

I can't install after v2.4.2 via SocketPunch. <https://github.com/Olmectron/SocketPunch/releases>

**Comment by Steveice10** [comment]
Use the included servefiles.py script or any other tool that supports the new network installation method. The old method is no longer supported.

**Comment by h2y** [comment]
I can enter the installing interface by the python script now, but I the progress is still 0%, console has no output.

Probebly it is my own's question. I'll try again.
