### ISSUE TITLE
[Feature Request] Browse Save Data for GBA cias

### ISSUE THREAD

**Issue by greenDarkness** [Steveice10/FBI#281]
Would it be possible to implement save extraction for GBA games injected into the virtual console? 
Thanks for all your work with FBI!
Error:
Failed to open file listing archive.
Result code: D900458A
Level: Permanent (27)
Summary: Wrong Argument (8)
Module: FS (17)
Desc: <unknown> (394)

**Comment by Steveice10** [comment]
Looks like your save data is either messed up (bad hash) or it's some weird error from some kind of quirk with GBA saves. Either way, if it won't open, it won't open.

**Comment by greenDarkness** [comment]
Thanks for the response. Hmm, I know that the save is good since it can be extracted via Decrypt9WIP with a few tries. I think it's probably a weird quirk. Is there any way you'd consider looking it over?
