### ISSUE TITLE
CIA signature and hash check fail

### ISSUE THREAD

**Issue by Peetey** [Steveice10/FBI#286]
I'm trying to install a patched japanese Fire Emblem CIA on my Luma 6.6 FW 11.0 USA N3DSXL but I get the following error upon completion:

Failed to install CIA File.
Result code: 0xD8E0806A
Level: Permanent (27)
Summary: Invalid argument (7)
Module: AM(32)
Desc: Cert signature or hash check failed (106)

I tried deleting unused tickets and making sure my SD has enough space but the problem persists.

**Comment by Steveice10** [comment]
Are you certain the CIA is valid? Not much I can do if the system won't accept your CIA.

**Comment by AzizBlooper** [comment]
@Peetey u must downgrade to 9.2 and install arm9....look at this fantastic video https://youtu.be/r4NFrReiBjw this was help me a lot!!!thx to this guy...and he show how to install Emunand to...check it out...it easier trick

**Comment by AzizBlooper** [comment]
U also can install LEGIT and PIRATE CIA too...such Mario maker and many more

**Comment by ihaveamac** [comment]
@AzizBlooper if you read the main issue they are already using luma.

@Peetey sounds like the CIA is corrupt somewhere. make sure it's valid or get another.

**Comment by Peetey** [comment]
I tried installing with other installers and the same problem persists. I believe it has to do with the CIA itself now. Thanks.
