### ISSUE TITLE
A minor issue with installing

### ISSUE THREAD

**Issue by OfficialBrony** [Steveice10/FBI#287]
So 2.4.7 has a bug?? I haven't had this issue on the previous release, but the issue I am facing on 2.4.7 is that when the CIA is installed, sometimes I will have to go into the System Settings and exit to restart the system (N3DSXL Luma+A9LH) because I can't unwrap the present icon. I can smash "A" a hundred times or just press "Unwrap" a hundred times but I can't do nothing unless I restart my system. 
Not a huge deal, but its still a bug that was not on the previous release.

**Comment by Steveice10** [comment]
That shouldn't have anything to do with FBI, as FBI itself just passes the CIA data to the system and doesn't do anything related to the home menu or unwrapping the icon.

**Comment by OfficialBrony** [comment]
ok
