### ISSUE TITLE
Warnings with latest devkitARM release

### ISSUE THREAD

**Issue by urherenow** [Steveice10/FBI#290]
Couldn't grab all of the warnings but here is an example:

source/stb_image/stb_image.h:1359:44: warning: this 'for' clause does not guard... [-Wmisleading-indentation]
       #define CASE(a,b)   case COMBO(a,b): for(i=x-1; i >= 0; --i, src += a, dest += b)
                                            ^
source/stb_image/stb_image.h:1371:10: note: in expansion of macro 'CASE'
          CASE(3,2) dest[0]=stbi__compute_y(src[0],src[1],src[2]), dest[1] = 255; break;
          ^~~~
source/stb_image/stb_image.h:1371:82: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'for'
          CASE(3,2) dest[0]=stbi__compute_y(src[0],src[1],src[2]), dest[1] = 255; break;
                                                                                  ^~~~~
source/stb_image/stb_image.h:1359:44: warning: this 'for' clause does not guard... [-Wmisleading-indentation]
       #define CASE(a,b)   case COMBO(a,b): for(i=x-1; i >= 0; --i, src += a, dest += b)
                                            ^
source/stb_image/stb_image.h:1372:10: note: in expansion of macro 'CASE'
          CASE(4,1) dest[0]=stbi__compute_y(src[0],src[1],src[2]); break;
          ^~~~
source/stb_image/stb_image.h:1372:67: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'for'
          CASE(4,1) dest[0]=stbi__compute_y(src[0],src[1],src[2]); break;
                                                                   ^~~~~
source/stb_image/stb_image.h:1359:44: warning: this 'for' clause does not guard... [-Wmisleading-indentation]
       #define CASE(a,b)   case COMBO(a,b): for(i=x-1; i >= 0; --i, src += a, dest += b)
                                            ^
source/stb_image/stb_image.h:1373:10: note: in expansion of macro 'CASE'
          CASE(4,2) dest[0]=stbi__compute_y(src[0],src[1],src[2]), dest[1] = src[3]; break;
          ^~~~
source/stb_image/stb_image.h:1373:85: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'for'
          CASE(4,2) dest[0]=stbi__compute_y(src[0],src[1],src[2]), dest[1] = src[3]; break;
                                                                                     ^~~~~
source/stb_image/stb_image.h:1359:44: warning: this 'for' clause does not guard... [-Wmisleading-indentation]
       #define CASE(a,b)   case COMBO(a,b): for(i=x-1; i >= 0; --i, src += a, dest += b)
                                            ^
source/stb_image/stb_image.h:1374:10: note: in expansion of macro 'CASE'
          CASE(4,3) dest[0]=src[0],dest[1]=src[1],dest[2]=src[2]; break;
          ^~~~
source/stb_image/stb_image.h:1374:66: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'for'
          CASE(4,3) dest[0]=src[0],dest[1]=src[1],dest[2]=src[2]; break;
                                                                  ^~~~~
source/stb_image/stb_image.h: In function 'stbi__create_png_image_raw':
source/stb_image/stb_image.h:4049:17: warning: this 'for' clause does not guard... [-Wmisleading-indentation]
                 for (k=0; k < nk; ++k)
                 ^
source/stb_image/stb_image.h:4053:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_sub)          cur[k] = STBI__BYTECAST(raw[k] + cur[k-filter_bytes]); break;
             ^~~~
source/stb_image/stb_image.h:4053:95: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_sub)          cur[k] = STBI__BYTECAST(raw[k] + cur[k-filter_bytes]); break;
                                                                                               ^~~~~
source/stb_image/stb_image.h:4049:17: warning: this 'for' clause does not guard... [-Wmisleading-indentation]
                 for (k=0; k < nk; ++k)
                 ^
source/stb_image/stb_image.h:4054:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_up)           cur[k] = STBI__BYTECAST(raw[k] + prior[k]); break;
             ^~~~
source/stb_image/stb_image.h:4054:84: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_up)           cur[k] = STBI__BYTECAST(raw[k] + prior[k]); break;
                                                                                    ^~~~~
source/stb_image/stb_image.h:4049:17: warning: this 'for' clause does not guard... [-Wmisleading-indentation]
                 for (k=0; k < nk; ++k)
                 ^
source/stb_image/stb_image.h:4055:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_avg)          cur[k] = STBI__BYTECAST(raw[k] + ((prior[k] + cur[k-filter_bytes])>>1)); break;
             ^~~~
source/stb_image/stb_image.h:4055:113: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_avg)          cur[k] = STBI__BYTECAST(raw[k] + ((prior[k] + cur[k-filter_bytes])>>1)); break;
                                                                                                                 ^~~~~
source/stb_image/stb_image.h:4049:17: warning: this 'for' clause does not guard... [-Wmisleading-indentation]
                 for (k=0; k < nk; ++k)
                 ^
source/stb_image/stb_image.h:4056:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_paeth)        cur[k] = STBI__BYTECAST(raw[k] + stbi__paeth(cur[k-filter_bytes],prior[k],prior[k-filter_bytes])); break;
             ^~~~
source/stb_image/stb_image.h:4056:139: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_paeth)        cur[k] = STBI__BYTECAST(raw[k] + stbi__paeth(cur[k-filter_bytes],prior[k],prior[k-filter_bytes])); break;
                                                                                                                                           ^~~~~
source/stb_image/stb_image.h:4049:17: warning: this 'for' clause does not guard... [-Wmisleading-indentation]
                 for (k=0; k < nk; ++k)
                 ^
source/stb_image/stb_image.h:4057:13: note: in expansion of macro 'CASE'
             CASE(STBI__F_avg_first)    cur[k] = STBI__BYTECAST(raw[k] + (cur[k-filter_bytes] >> 1)); break;
             ^~~~
source/stb_image/stb_image.h:4057:102: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'for'
             CASE(STBI__F_avg_first)    cur[k] = STBI__BYTECAST(raw[k] + (cur[k-filter_bytes] >> 1)); break;
                                                                                                      ^~~~~
source/stb_image/stb_image.h:4049:17: warning: this 'for' clause does not guard... [-Wmisleading-indentation]
                 for (k=0; k < nk; ++k)

Is -Wmisleading-indentation some anal coding style checks built into the latest toolset? I looked at a couple of those cases, and they look ok to me...

**Comment by Steveice10** [comment]
It's related to how stb_image defines and uses some of its macros. I've added the flag to ignore this warning.
