### ISSUE TITLE
more build issues

### ISSUE THREAD

**Issue by urherenow** [Steveice10/FBI#291]
getting rid of that new style check left me with enough buffer to grab the remaining 2 problems:

X:\Projects\FBI>make clean
rm: cannot lstat `build/3ds-arm': Permission denied
make: *** [clean] Error 1

Not sure why this is happening, even when running the command prompt as administrator.

and:

source/json/json.c:146:13: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
             value->_reserved.object_mem = (*(char **) &value->u.object.values) + values_size;
             ^~~~~
source/json/json.c: In function 'json_parse_ex':
source/json/json.c:408:25: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
                         (*(json_char **) &top->u.object.values) += string_length + 1;
                         ^
Of course it happily finishes.

**Comment by Steveice10** [comment]
For the first error, try deleting your build folder and see if it ever happens again. For the second, I'll address it when I can later today.

**Comment by urherenow** [comment]
Not at home so I'll have to try tomorrow. I could swear I has the first error starting from scratch+make clean since I was stupid and kept my projects folder inside of devkitArm/

Didn't think running the upgrade would wipe out the whole devkitpro tree and start me from scratch 😖

Won't make that mistake again...

**Comment by Steveice10** [comment]
The warnings should be ignored now.

**Comment by urherenow** [comment]
Tried again from scratch. No errors initially. make clean still gives me: rm: cannot lstat `build/3ds-arm': Permission denied

any ideas?

**Comment by Steveice10** [comment]
All I can really suggest is check to make sure you have the right permissions on the build folder and its contents.

**Comment by urherenow** [comment]
running as administrator, and no errors on anything else. really strange...
