### ISSUE TITLE
Possible title data parsing issue

### ISSUE THREAD

**Issue by fattard** [Steveice10/FBI#292]
Is there a known reason on why it seems to not parse correctly the title meta data from the IDs in the attached image?

![img_20170127_040042899_hdr](https://cloud.githubusercontent.com/assets/1159052/22361923/50ce7ab6-e43d-11e6-8608-7192ad6f3d52.jpg)

Those are the only ones (from my installed titles) that appears to have blank meta data.
The Data Management do display titles names correctly.

System Info:
O3DS XL (11.2.0-35U + A9LH + Luma3DS) 
System Language: Portuguese

BTW, version 2.4.8 is a build from my own fork, but this issue applies to all official releases from 2.X.X

**Comment by Steveice10** [comment]
I imagine it might be because the title's Portuguese title, description, and publisher are empty.

**Comment by fattard** [comment]
You are right. By changing the system language to English, the data is parsed correctly.
So, altough this is mostly a title issue, I would recommend to try reading title data from default system region language (English as a fallback in U and E regions).

I can try to implement this stuff and send you a PR later..

**Comment by Steveice10** [comment]
Can you try this build? It should fall back to a default language based on your region if the title for your language is empty.

https://www.dropbox.com/s/t16uhlqszg39nhu/FBI.zip?dl=1

**Comment by fattard** [comment]
I can confirm it works for region U device.
This is probably what Data Management does too.

**Comment by Steveice10** [comment]
Changes pushed.
