### ISSUE TITLE
Unable to run CIA build with official CTR SDK

### ISSUE THREAD

**Issue by Krzycho666** [Steveice10/FBI#293]
I'm trying to load any custom build CIA made with official SDK, but everytime I get:
```
Failed to install CIA file.
Result code: 0xD8E0806A
Level: Permanent (27)
Summary: Invalid argument (7)
Module: AM (32)
Desc: Cert signature or hash check failed (106)
```

I'm running Luma, and FBI 2.4.6. They install fine on devkit, but they don't on CFW. Is that actually possible to load those app's on this device? I wanted to play with official SDK without owning devkit. Maybe there is something that can be done to run them? I also tried to run FBI injected to Health app - but the result was thesame, so as using DEV MEN app.

**Comment by Krzycho666** [comment]
Funny. I was looking for a solution for a weeks now, and soon after posting this I've found that option in Luma3DS, that I can  set deleloper features to UNITINFO enabling CFG_UNITINFO. After that, installing CIA made with official SDK works perfectly =]

**Comment by Steveice10** [comment]
Yeah, you normally can't install dev unit CIAs on a retail system.

**Comment by Krzycho666** [comment]
Is there any way to build CIAs ( without any extra convertions after ) in order to make them runnable on non-dev console?
