### ISSUE TITLE
Simple servefiles drag support

### ISSUE THREAD

**Issue by Remnence** [Steveice10/FBI#294]
I created a simple bat file that prompts for your 3DS IP and calls servefiles with the correct syntax to upload the cia file or folder dropped on it easily. I figured I'd submit it here if you guys want to use it or include it in future releases.
```
@ECHO OFF
set /p DSIP="Enter the IP of your 3DS: "
python %~dp0servefiles.py %DSIP% "%~1"
pause

**Comment by Steveice10** [comment]
Could you add this as a file in the serve files directory and submit a pull request?

**Comment by Remnence** [comment]
Done. Made a few changes to handle dropping multiple cias as well.
