### ISSUE TITLE
Cant download ANY CIAs

### ISSUE THREAD

**Issue by pkmnlovr74** [Steveice10/FBI#295]
Every time I attempt to install a CIA, it gets the error 
Result code: 0xD8E0806A
Level: Permanent (27)
Summary: invalid argument (7)
Module: AM (32)
Desc: Cert signature or hash check failed (106)

I have tried to download cias from qr codes, from the SD directly, and from the database and none of them work, please help

**Comment by Steveice10** [comment]
Are you running a CFW?

**Comment by pkmnlovr74** [comment]
I am using soundhax

**Comment by pkmnlovr74** [comment]
if that's not the same thing, let me know

**Comment by Steveice10** [comment]
You need to run a signature patching CFW like Luma3DS to install anything but legit, signed CIAs.
