### ISSUE TITLE
[Request] Allow exit via START from anywhere

### ISSUE THREAD

**Issue by d0k3** [Steveice10/FBI#297]
As written above. Leaving FBI via START is quite convenient, but as of now it works only from the main screen. Is it possible to make it work from anywhere? As long as there is no operation in progress, ofc.

**Comment by Steveice10** [comment]
I'd actually rather keep this to the main menu. One reason is that freeing the resources of views on the stack other than the current one could be problematic, unless I make things a bit more complicated than I'd really like them to be.
