### ISSUE TITLE
Failed to Install CIA

### ISSUE THREAD

**Issue by Dracnea** [Steveice10/FBI#299]
Failed to install CIA file.
Result code: 0xD8E0806A
Level Permanent(27)
Summary: Invalid Argument(7)
Module: Am(32)
Desc: Cert signature or hash check failed(106)

I have this issue with every CIA I attempt to install. Running soundhax version of ninjhax with a 11.1.0-34U 2DS. Any help on this issue please, I'd like to get FBI up and running for myself. 

Thanks

**Comment by dogtopus** [comment]
You need a CFW in order to install non-legit CIAs

**Comment by Dracnea** [comment]
Is their a CFW for my current software version? I didn't even know what it was until now, I'm quite new to this

**Comment by Dracnea** [comment]
did some more research and it looks like I cant, I can wait as long as needed if they ever make something, I could downgrade but id also rather not brick my 2DS nor do i have any older versions of the 3ds software on hand from other devices, so looks like I'm stuck here wise

**Comment by Dracnea** [comment]
If I get something with 9.2 I would be able to get cfw, cia's and other decrytpers/game dumpers then correct?

**Comment by dogtopus** [comment]
Issue tracker is not a discussion forum. If you have any questions regarding to CFW, please post it elsewhere (e.g. gbatemp)
