### ISSUE TITLE
[Request] No Age-Restriction Version?

### ISSUE THREAD

**Issue by ZalexZTK** [Steveice10/FBI#300]
As the title suggests, would you be able to modify the code so that there is no Age-Restriction? I myself am asking for a port, not to change the whole application for everyone else. There are some people like me who are in a situation where this would be very useful. I'm stuck using the FBI injectable to get around this, but a port of FBI without any age locks would be fantastic.

**Comment by deadair3210** [comment]
Why do you need the age restriction removed, why not just turn off the Parental Controls

**Comment by ZalexZTK** [comment]
If it was that simple, I would've done it. I'm not going into detail, as I've told this story numerous times, but basically, I have controls stuck on there for a while, so I'm requesting a little ease of access.

**Comment by deadair3210** [comment]
The hard part about having two builds is it means that the program has to be built and bug checked twice

**Comment by ihaveamac** [comment]
not exactly, the parental controls level is just in the smdh/icon.

**Comment by deadair3210** [comment]
Icon is part of cia build, and as far as I know, so it would at least take two builds of that

**Comment by ihaveamac** [comment]
still no code changes. though I don't know if this is worth it still.

**Comment by Steveice10** [comment]
I would just turn off parental controls if you don't want age restrictions, but if you really want a version of FBI without parental controls support, remove "ratingrequired" from the flags list in the Makefile and compile.
