### ISSUE TITLE
Can't get remote installs to work

### ISSUE THREAD

**Issue by JohnTitor95** [Steveice10/FBI#301]
How exactly can i remotely install files? I've tried running the python file from command prompt, but nothing seems to happen. I tried creating my own batch file copy and pasting from the drop cias here.bat in the code section, this brings up the prompt asking for my 3ds IP, but after inputting IP, it says servefiles.py is unexpected here or something like that.

**Comment by Garro** [comment]
It seems using SocketPunch crashes FBI so I guess it's an issue with the latest update.

**Comment by Steveice10** [comment]
Read the servefiles README file; it tells you how to use it.

Also, SocketPunch not working is not an FBI bug. A few versions back, the network installation protocol was revised, and SocketPunch uses the old protocol.

**Comment by JohnTitor95** [comment]
Sorry, Issue isn't closed. I read the readme, it doesn't work. I told you this already. Never tried socketpunch, already knew about new protocol. Using the readme file, i get the above result.

**Comment by Steveice10** [comment]
It works just fine. You've tried running it in Command Prompt with "python servefiles.py <3DS IP> <CIA file>"?

**Comment by JohnTitor95** [comment]
yes. I get an error about servefiles.py being unexpected.

**Comment by Steveice10** [comment]
I'm not sure what exactly that means, could you post the exact error message?

**Comment by JohnTitor95** [comment]
It's just "servefiles.py was unexpected at this time"

**Comment by RainThunder** [comment]
Could you post the exact command, or the content of your batch file?

A quick Google search point me to [this answer](http://stackoverflow.com/questions/7769591/was-unexpected-at-this-time),

**Comment by JohnTitor95** [comment]
The command i use is cd to where servefiles,py is located, then i use "python servefiles.py (3ds IP) (filename)", and the batch i use is the batch from the latest github commit.

**Comment by urherenow** [comment]
Do any of your files exist in a path with spaces in it?

**Comment by JohnTitor95** [comment]
Yes.

**Comment by urherenow** [comment]
Umm... well... If you didn't get my point, try moving the .py file and .cia and try using it from a path with no spaces in it.
