### ISSUE TITLE
Remove old versions

### ISSUE THREAD

**Issue by glats** [Steveice10/FBI#302]
Hi everyone,
By mistake I installed a new FBI version via FBI Installer and now I have two FBI in Home Menu.
So the question is... How I can remove the old version?
Thanks for advanced

**Comment by Steveice10** [comment]
Find it in the title menu and delete it.

**Comment by glats** [comment]
@Steveice10 Sorry but I can't find the option to delete. When I press the icon I can only move it across the home menu but nothing more.

**Comment by deadair3210** [comment]
Go to the FBI that is the latest, go into Titles, find the other one, and select Delete Title

**Comment by deadair3210** [comment]
Or better yet, download something like Homebr3w , delete both copies, and then redownload it

**Comment by glats** [comment]
@deadair3210 I will try those options thank you
