### ISSUE TITLE
QR Install & Update do not work

### ISSUE THREAD

**Issue by Minxxe** [Steveice10/FBI#303]
So i tried to update FBI but it gave me this error after some wating (sorry for the bad quality): https://i.imgur.com/3OyEfEN.jpg
after that the update in FBI didn't work i downloaded the version 2.4.7 and it gives me the same error.
QR/Network Install do not work either.

Using: N3DS EmuNAND 11.3.0-36E with Luma3DS

**Comment by Steveice10** [comment]
This error generally indicates a problem with your internet connection. Check your Internet settings and make sure you can connect with other apps.

**Comment by Minxxe** [comment]
Every other app can connect to the internet it's only happening in FBI.

**Comment by Steveice10** [comment]
Well, that error usually means the HTTP service couldn't establish a connection, so it doesn't seem likely to be an issue with FBI itself.

**Comment by Minxxe** [comment]
Update: Got it working by removing the static ip address and dns.
