### ISSUE TITLE
Prompt to overwrite if CIA with the same title ID is installed

### ISSUE THREAD

**Issue by gnmmarechal** [Steveice10/FBI#307]
Just an idea for a feature. If a CIA with the same Title ID is installed, prompt to ask if it should be overwritten. Or only if the name/short desc/long desc differ? Idk. I figured this would be a cool addition.

**Comment by Steveice10** [comment]
FBI already overwrites by default.

**Comment by gnmmarechal** [comment]
I know that. Because some CIAs might be different apps AND share a Title ID, I thought it'd be a good idea to TELL or ASK before doing so. That's what I mean.

**Comment by Steveice10** [comment]
That two CIAs would share a title ID is itself a problem that should be corrected, and isn't really something I think FBI should have to consider.
