### ISSUE TITLE
Small Bug?

### ISSUE THREAD

**Issue by clasher58** [Steveice10/FBI#309]
When I go open the FBI application then press start to exit the home menu all of the game/application logos for the top screen disappear this can be fixed by restarting the system, but is is there a way to fix this?

**Comment by urherenow** [comment]
No such issue here. I'd start by backing up your SD, then re-format then copy everything back. If you still have issues, try another SD or change themes if you're using one.

**Comment by Steveice10** [comment]
Yeah, I cannot reproduce this issue.
