### ISSUE TITLE
SUGGESTION: Updater for titledb apps.

### ISSUE THREAD

**Issue by miltoncandelero** [Steveice10/FBI#312]
Would it be too hard to make to have fbi update all your title db apps?

Not need to check if there is an update or not, just redownload all of them. 

Check for all the titledb apps installed and queue all of them into the remote install.

(got the idea from [here](https://www.reddit.com/r/3dshacks/comments/5vinlm/3ds_hacking_qa_general_dmca_edition/de7ea0n/) )

**Comment by Blaxou** [comment]
Agree! I don't think that's that difficult to achieve this as all embers are present in FBI already. I really hope it can be added!

**Comment by Steveice10** [comment]
Just select the  in the TitleDB menu and choose to install them if you want to update apps.

**Comment by miltoncandelero** [comment]
Over 20 homebrew apps I have installed, it takes a lot of time to do it manually. FBI can create a list of all my homebrew apps installed.

**Comment by Blaxou** [comment]
I think it would simplify everyone's life a lot as some of us have a lot of Homebrew apps and going through all of the apps to update them (supposing there is one) takes a hell lot of time without even counting that some apps may not have an update (and therefore being updated for no reason and wasting time). If we had this functionality, we wouldn't have to worry, even if it unnecessarily apps as it would be automated.

**Comment by urherenow** [comment]
https://github.com/LiquidFenrir/MultiUpdater

**Comment by Steveice10** [comment]
I suppose having a lot of apps would create a reasonable need for such a feature. Here's a test build if you want to try it out. Open the TitleDB menu, select any title, and choose "Update All".

https://www.dropbox.com/s/tccewgrsuh8ezok/FBI.zip?dl=1

**Comment by Blaxou** [comment]
@urherenow It only allows to update GodeMode9 / Hourglass 9 / Decrypt 9. Theses are *Luma Payloads*... That's not what we want.
@Steveice10 Thanks a lot ! Gotta try this out and give you a feedback :D

**Comment by Blaxou** [comment]
@Steveice10  Works fine !
Would be cool to have some infos on the top screen like :

**Updating HomebrewApp1(OldVersion > LatestVersion) ... Done !**
**Updating HomebrewApp2 (OldVersion > LatestVersion) ...**

And a separated menu would be perfect too

I don't know if it is done on this test build but to make things faster it should verify if an update is usefull (if the Homebrew app isn't on the lastest version)

Otherwise, very nice work !

**Comment by Steveice10** [comment]
I've wanted to add new version detection, but as far as I know TitleDB still doesn't provide the version number as part of the API's app information.

**Comment by Blaxou** [comment]
Are you in contact with @ksanislo? It would be great to ask him about implementing version if possible. By the way, I thought about a feature that could be very good if implemented:
*Receiving notifications as a Homebrew App update comes out*

(I know this isn't easy to achieve and needs to collaborate with @ksanislo but it would be pretty handy, and I just wanted to present the idea ;) )

**Comment by ksanislo** [comment]
@Steveice10 check the new API on the github page, you'll find there is version information now, as well as a lot more features as well. Only a handful of extra things like screenshots and associated assets are left to finish up.

**Comment by Steveice10** [comment]
@ksanislo Is it possible to:
 * Filter the CIA view, not just the Entry view, by category.
 * Show only the latest versions of apps in the resulting list, not all versions.

**Comment by ksanislo** [comment]
@Steveice10 There's no filtering support out of the current table, best practice to reduce server load would be to just pull the full entry and cia tables in un-nested views, excluding any fields you don't want, and just process things locally. It's a lot easier to support the traffic load without the extra joins on the server side. As for old versions, again locally is probably best for now based on either version string or time. They should be delisted from the server side, but there's nobody actively moderating that aspect of the listings at the moment.

**Comment by Steveice10** [comment]
Alright. I've updated FBI to use the new API, and the update function now only updates titles with higher version numbers on TitleDB.

**Comment by Blaxou** [comment]
Is it the same link?

**Comment by Steveice10** [comment]
I hadn't uploaded a new build, but it is up at the same link now if you want to try it.

**Comment by ksanislo** [comment]
@Steveice10 Before you release a new build using the updated API, can you please make sure your app is properly supporting gzip or deflate encoding? The bandwidth used can be dramatically reduced with negligible server load if the clients support compression. 

https://en.wikipedia.org/wiki/HTTP_compression

You should request compression for all API and download requests, though currently most downloads won't be returned with compression from most web servers since they see .cia as an incompressible bin type (It's actually quite compressible, but the stock apache/nginx settings don't try. I'll enable compression as an option for anything proxied back from TDB itself though.)

**Comment by Blaxou** [comment]
There is still five Homebrew apps that are being updated each time I *Update All* apps. Is it because TitleDB doesn't provide their version? Also, it woud be great in the future to add the *name* of the Homebrew app being updated and it's *current version* and *goto version* ;)

**Comment by Steveice10** [comment]
Just pushed an update to display app information during TitleDB installations. A build is at the same link as before, so let me know if it works alright.

**Comment by Blaxou** [comment]
Ok, going to try this out ;(

**Comment by Blaxou** [comment]
* ;)

**Comment by Blaxou** [comment]
Hello, after almost one month of testing, I noticed some bugs, first of all , it keeps updating 5 same titles anyway, here there are with their ID :

- 2048 3D (000400000FFCF00)
- 2048 Libretro (000400000BAC0B00)

Then it throws this error :
> Failed to install from URL.
https://3ds.titledb.com/v1/cia/676/...
Result code : 0xD963F807
Level : Permanent (27)
Summary : Internal (11)
Module : Application (254)
Desc : Bad data (7)

- 3DeMore (0004000001D40400)
- 3DS Binary Decimal Converter (000400000F002100)
- 3DS Controller (000400000F0FC200)

I checked and I have **none** of them installed (and it says that I have the version 0.0.0 installed).

I just realised that they are the **5 first entries in TitleDB** and it's surely linked to that fact ;)

Hope it can ce fixed and can't wait until 3.0.0 comes out :D

**Comment by Steveice10** [comment]
@ksanislo Is there no way to retrieve the actual title version value contained in the CIA? "version" seems to be something different.

**Comment by ksanislo** [comment]
@Steveice10 There's no direct way to do it. It might be possible to parse all of the .cia headers and step over things to find the correct point in the right data block for it, but to be honest, it requires more time than I'm willing to throw at it to figure it out from scratch. If someone else wants to write a proper parser for things, I'd be more than willing to merge it back into the TDB tree.

**Comment by Steveice10** [comment]
Pull request submitted: https://github.com/ksanislo/TitleDB/pull/8

**Comment by Blaxou** [comment]
Nice ! Can't wait for @ksanislo to merge it 👍

**Comment by MissPotato** [comment]
[Homebr3w by Wolvan ](https://github.com/Wolvan/Homebr3w/releases)has a feature like this. Actually, it's the main selling point for me.

**Comment by ksanislo** [comment]
@MissPotato  You're correct. Technically everything required to handle updates is already present in titledb, and in a manner that works with more legacy apps than the patch referenced above. FBI also doesn't bother cross-referencing the descriptive info about projects or URL tables, so I'm not particularly keen on bothering to port in additional things for just the way it does things alone.

**Comment by Steveice10** [comment]
@ksanislo Why should I have to keep a cache of installation dates when titles have a perfectly good version field and I've already submitted a pull request to add it to the JSON information?

**Comment by Blaxou** [comment]
Hey ! So apparently @ksanislo didn't take a look at your PR ... Is it there any other way around ?
