### ISSUE TITLE
servefiles errors

### ISSUE THREAD

**Issue by Remnence** [Steveice10/FBI#313]
Error on every line with file=sys.stderr. After editing out the arguments I was able to run the script.

**Comment by Steveice10** [comment]
This is fixed already for the next release, and is caused by a break in Python 2 compatibility.

**Comment by Lapan** [comment]
When will the fix be released? I went back to the old version of servefiles for now since there hasn't been an new release with the fix in a while.

**Comment by Steveice10** [comment]
The next release is waiting on a pull request to TitleDB being accepted.
