### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by Jolty95** [Steveice10/FBI#314]
Good morning sir!
I found some code that is useless and can be deleted:

- source/core/linkedlist.c [L53](https://github.com/Steveice10/FBI/blob/master/source/core/linkedlist.c#L53)    

    -  `if(index < 0 || index >= list->size) {` should be ` if(index >= list->size) {` because index is an `unsigned int` so we don't have to check if index is less than zero because it will be never less.

- source/stb_image/stb_image.h [L4725](https://github.com/Steveice10/FBI/blob/master/source/stb_image/stb_image.h#L4725) 

   - `req_comp >= 3` is always true
   - [L5960-L5962](https://github.com/Steveice10/FBI/blob/master/source/stb_image/stb_image.h#L5960) can be `char c =  (char) stbi__get8(z);`

There are also anothers smalls compilers warnings in [L5165-L5159](https://github.com/Steveice10/FBI/blob/master/source/stb_image/stb_image.h#L5165) and small ones using cppcheck that are worthless to write all here :P

Thanks for all. Hope this help you a bit :)

**Comment by Steveice10** [comment]
The first one has been taken care of, the others I'm going to leave alone since stb_image is outside drop-in image code and I'd like to leave it as provided.

**Comment by Jolty95** [comment]
Thanks @Steveice10  👍  :)
