### ISSUE TITLE
Applications freeze after fbi is opened

### ISSUE THREAD

**Issue by jupitteer** [Steveice10/FBI#315]
opening and closing the 3ds seems to fix this.

**Comment by Steveice10** [comment]
I've never experienced this myself, and I'm not sure why that would happen. Are you certain FBI is the cause?

**Comment by jupitteer** [comment]
Yes, I am.

**Comment by jupitteer** [comment]
I am on o3ds btw.

**Comment by Steveice10** [comment]
It might help if you could use Luma3DS to get a crash report when an application crashes from this issue.

**Comment by jupitteer** [comment]
it doesn't crash though, it just freezes. When loading an application after using fbi, it either plays the loading screen forever or black screens.
