### ISSUE TITLE
servefiles.py crashes when sending cia

### ISSUE THREAD

**Issue by dragos240** [Steveice10/FBI#318]
I think this is due to a system update or something, but I can't figure out what's wrong. servefiles.py was working fine and then I tried again the next day and now it crashes. What I did to cause the crash:

1. run the below command
2. hit "Yes(A)" on the console
3. Crash

The output of running `servefiles.py 192.168.1.102 Pocket-NLSE.cia` is as follows:
```
Detecting host IP...
Preparing data...

URLs:
192.168.1.101:8080/Pocket-NLSE.cia 

Opening HTTP server on port 8080
Sending URL(s) to 192.168.1.102 on port 5000...
192.168.1.102 - - [11/Mar/2017 16:02:55] "GET /Pocket-NLSE.cia HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.102', 52823)
Traceback (most recent call last):
  File "/usr/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/usr/lib/python3.6/http/server.py", line 639, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.6/http/server.py", line 800, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.6/shutil.py", line 76, in copyfileobj
    fdst.write(buf)
  File "/usr/lib/python3.6/socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
An error occurred: [Errno 104] Connection reset by peer
```

I usually use the remote install feature of FBI for testing my programs. Sending files via ftp and installing them through FBI works for now, but is slightly less convenient.

**Comment by Steveice10** [comment]
Working fine here. Is your network connection stable, and is the CIA valid?

**Comment by dragos240** [comment]
The CIA definitely is valid. I sent a CIA that worked the other day using the tool and it gave this result. The router should be working fine, but I'll restart it just in case that's the issue. Just restarted the router, the problem persists. What version of Python are you using? This machine's running 3.6. I have a feeling it might be Python related but I can't be sure.

**Comment by Steveice10** [comment]
I'm also running Python 3.6. The last thing I would think to check is whether you're on the latest FBI version.

**Comment by dragos240** [comment]
I just updated to 2.4.8 and downloaded the latest servefiles.py with it to make sure it wasn't that FBI needed to update. Unfortunately, after FBI crashed just now (this happened after I hit Home and closed FBI while it was stalling after the error on the PC end), my 3DS won't boot up anymore. I haven't the slightest clue why this is.

**Comment by dragos240** [comment]
A suggestion: Have FBI detect when the connection is unexpectedly dropped so that it can cleanly exit. The current behavior assumes the file transfer completes successfully.

**Comment by Steveice10** [comment]
Added a better timeout value.
