### ISSUE TITLE
FBI black screen

### ISSUE THREAD

**Issue by TheBunnyCoder** [Steveice10/FBI#322]
I was looking through TitleDB, and I scrolled down a bit, but when I scrolled up onto "Minesweeper 2DS", the bottom screen turned black (the top screen remained normal), and no buttons were working. I had to hold the power button to turn it off.

**Comment by Steveice10** [comment]
Does this still occur on this build?

https://www.dropbox.com/s/0prpbglrzdq3uj2/FBI.zip?dl=1

**Comment by TheBunnyCoder** [comment]
From what I can tell, nope.
