### ISSUE TITLE
Install feature is missing from my 3ds xl

### ISSUE THREAD

**Issue by eilanzier** [Steveice10/FBI#323]
Hi there,

thanks for releasing such a wonderful too, i have just updated and install fbi recently to the latest version 2.4.8 however my cia files are not being recognized as installable. FBI simply gave me the following 4 option
Delete/Rename/Copy/Paste 

However, this issue don't happen to all CIA file and these files that is not installable does not have any image in their respective cia file preview thus it made me believe its as though they are not recognised by FBI library or not recognised as a cia file by FBI

**Comment by eilanzier** [comment]
1 more point to highligh would be i have tried using fbi 2.4.5/2.4.6/2.4.7/2.4.8 and this issue is surfacing in all the versions.

**Comment by Steveice10** [comment]
Check that your CIAs are valid and your SD card doesn't have any filesystem issues.
