### ISSUE TITLE
Can I make FBI show as download play?

### ISSUE THREAD

**Issue by apsol2** [Steveice10/FBI#328]
In this post( https://www.reddit.com/r/3dshacks/comments/40s1md/does_fbi_show_up_as_download_play/ 
 ), they say FBI can show as download play. 
I have 2 old 3ds colsoles and one of them has FBI installed but the other doesn't because its firmware is 11.4 and I can't install homebrew on it. 
I need to make the other one download play FBI from the one which has it. Can you tell me how to do so?

**Comment by urherenow** [comment]
Lol.

Do you normally speak English? When you run homebrew, your activity log shows that you were using download play. That's all that thread is saying.

TL;DR 

No. Never.

**Comment by dogtopus** [comment]
Even if FBI has this feature, if you are not on a CFW it will not work because FBI is not signed by Nintendo
