### ISSUE TITLE
Cant install CIA?

### ISSUE THREAD

**Issue by XCalibruh** [Steveice10/FBI#329]
im trying to install a CIA i downloaded off a website, i extracted it and put in the password and transfered it to my sd card. When i go to install it, i have no install option, i get everything else. On the top screen it has the name and Attribute (being archive) thats it nothing else. My other CIA work thought. Im on Luma3ds CFW on 11.4 any help would be appreciated

**Comment by urherenow** [comment]
Are you being serious right now? If other cia files install, and this one doesn't, then the problem is the CIA file. This is not a help forum.

**Comment by Steveice10** [comment]
Yeah, that generally means the CIA is invalid; it can't read the metadata and thus isn't detected as a CIA to install.
