### ISSUE TITLE
Fix "receive an app over the network"

### ISSUE THREAD

**Issue by mueee** [Steveice10/FBI#33]
When I have install prompts enabled, I consistently get the following error if I do not accept quickly enough:
```
Install failed!
Source: SOURCE_FSFILE_WRITE (0x1c)
Module: MODULE_NN_AM (0x20)
Level: LEVEL_USAGE (0x1c)
Summary: SUMMARY_INVALID_ARGUMENT (0x7)
Description: DESCRIPTION_MISALIGNED_SIZE (0x3f2)
```

This should be fixable by sending some confirmation through the socket, such as "FBI.READY" (or "FBI.DENY" if the transfer is denied, then transfer utilities could cleanly exit.)
I believe that some code directly inside [this if statement, before `app::install()`](https://github.com/Steveice10/FBI/blob/master/source/main.cpp#L78) should fix the problem (or there might be a better location to fix it)

I would fix it myself and do a pull request, but I have never written C++ before and I have no idea where the socket stuff is coming from.

Edit: forgot to mention that I'm running FBI 1.4.17

**Comment by Committee** [comment]
Disable the prompts?

**Comment by mueee** [comment]
When at the screen that says `Waiting for peer to connect...`, there is also text that says `Prompts: Enabled` (or Disabled) and `Press A to toggle prompts.`

**Comment by Steveice10** [comment]
Should be resolved by the rewrite, once it is complete.
