### ISSUE TITLE
Failed to install CIA from internet when URL contains spaces

### ISSUE THREAD

**Issue by Jerry-Shaw** [Steveice10/FBI#330]
When there are spaces in the URL, no matter what kind is it, " ", "%20" or "+". The CIA won't be requested both using QR code or manually input URL. It gives back HTTP code of 400.

**Comment by Steveice10** [comment]
You're sure the URL is correct? Have you tried it in a web browser?

**Comment by Jerry-Shaw** [comment]
Yep, all kinds of browsers can download it, I put them on my own server of IIS.
Here is an example:
http://ftp.oobase.com/Rom/3DS/[USA]Quest of Dungeons.cia 
or
http://ftp.oobase.com/Rom/3DS/[USA]Quest%20of%20Dungeons.cia

Just create a QR code, and the same result. But browsers can.

**Comment by Jerry-Shaw** [comment]
But once I changed the file name with no spaces in it, it installed.

**Comment by Steveice10** [comment]
Do you have access to the server this is hosted on, and if so, are there any logs you could check to see if the URL being requested by FBI is correct?

**Comment by Jerry-Shaw** [comment]
Yup, I checked the logs, but cannot find those with http-code of 400. Only the correct ones are logged.

**Comment by Jerry-Shaw** [comment]
Couldn't be a problem only matters with IIS? I just looked over internet, noticed that the 400 error won't be logged by IIS.

**Comment by Steveice10** [comment]
If possible, you could find somewhere else to temporarily upload a CIA with a space in the name and try that, just to check whether it's really FBI or not.

**Comment by Jerry-Shaw** [comment]
OK, I will try it and tell you the result.

**Comment by Jerry-Shaw** [comment]
@Steveice10 I told two friends to test in local network, both failed with HTTP code 400 when there are spaces in URLs. One worked on Nginx, the other is on Apache, both of them are under Window platform.

**Comment by Steveice10** [comment]
Do they have logs of the failing requests?

**Comment by Jerry-Shaw** [comment]
Seems like not captured. We may need to try some other methods to log the network actions.

**Comment by Jerry-Shaw** [comment]
@Steveice10 Hi, I just tested with Fiddler installed and monitored, but NO HTTP traffic event was captured at all when requested the CIA and FBI got this error: 
![fbi error](https://cloud.githubusercontent.com/assets/13212198/25076252/9365223c-2351-11e7-89b0-f6d6efbf5068.png)

**Comment by Jerry-Shaw** [comment]
@Steveice10 I may find the problem.
The characters caused the request failed are "[" and "]", not spaces.
I just tried "http://192.168.1.100:8080/F%20B%20I.cia" with success, but when trying "http://192.168.1.100:8080/[F%20B%20I.cia", it failed as the picture showed. URL "http://192.168.1.100:8080/F B I.cia" is unescaped and will cause 400. 
Any ideas?

**Comment by Jerry-Shaw** [comment]
Yes, confirmed.
The URL need to be encoded when requesting.
Example as followed:
Failed: http://192.168.1.100:8080/[USA]Gunman%20Clive%202.cia
Succeed: http://192.168.1.100:8080/%5bUSA%5dGunman%20Clive%202.cia

**Comment by Steveice10** [comment]
Yeah, FBI expects you to input a properly encoded URL.
