### ISSUE TITLE
SUGGESTION: mark signed and forged tickets in the Ticket list

### ISSUE THREAD

**Issue by ederenzi78** [Steveice10/FBI#335]
In the ticket list it would be nice to show if a ticket is "original" (signed by Nintendo) or forged / fake signed . Moreover, I don't know if it's possible to show the title name linked to every ticket.
Thanks!

**Comment by Steveice10** [comment]
I can't detect whether tickets are forged or not from userland, and don't want to slow down the ticket loading by retrieving title names. Even then, it would only show those of installed titles, in which case you could manage the title and do things like deleting it and its ticket from the title list.
