### ISSUE TITLE
Freezing when starting to install?

### ISSUE THREAD

**Issue by Davidchao23** [Steveice10/FBI#336]
Hello, I have an O3DS(2DS) on 11.3 A9LH and recently formatted my SD Card to have a 64 kb cluster size instead of 32 kb. I sucessfully got all my stuff back from a backup, and tried installing a CIA in FBI, however when I tried installing it, FBI froze my 2DS, causing me to turn it off. I tried with another CIA and same results occurred. Any solution?

**Comment by Steveice10** [comment]
Never experienced this before. Did it work fine with a 32kb cluster size, and do other apps like the eShop seem to work fine?

**Comment by Davidchao23** [comment]
It worked fine with a 32kb cluster size, however I have yet to tried other stuff with this, I'm gonna see if freeShop works in the mornin'

**Comment by Davidchao23** [comment]
On freEshop, I tried installing a game and it took a while for it to start on Installing Seed and Installing TMD.

**Comment by Steveice10** [comment]
Have you tried leaving FBI installing for a while to make sure it's actually frozen and not just taking a while?

**Comment by Davidchao23** [comment]
I did for almost 10 minutes. I saw that the time never started moving and stayed at the same time it froze. Not sure if this was a solution or not, but I reformatted my SD Card to a 32 kb cluster size. I only did this because I saw there was a glitch with my GBA games in 64 kb.

**Comment by Steveice10** [comment]
If 32kb works fine, I'll have to chalk it up to some 3DS system issue. FBI goes through the usual services to access the filesystem, so changing the filesystem like that should not impact FBI directly.

**Comment by Davidchao23** [comment]
Umm, now I got a new problem,
FBI tells me that it can't install CIA files, as it gives me the result code of 0xC960454B. Any solution? I tried formatting my SD card and backing up my stuff

**Comment by urherenow** [comment]
Please make a thread on a support forum. This space is for bugs/suggestions in the FBI code, not for support.

**Comment by Steveice10** [comment]
Can you post the full error output?

**Comment by Davidchao23** [comment]
Failed to install CIA file.
Result code: 0xC960454B
Level: Status (25)
Summary: Internal (11)
Module: FS (17)
Desc: Bus error / TWL partition invalid (331)

The weird thing is that I successfully installed two 8mb cias

**Comment by Steveice10** [comment]
It definitely looks like there's something wrong with your SD card. Do you have any others you could try to make sure?

**Comment by Davidchao23** [comment]
I tried with my 4gb SD Card, and it worked on installing a GBA cia

**Comment by Steveice10** [comment]
Maybe try running a disk check on it and see if it fixes any errors. If you just formatted it though I doubt that would help.

**Comment by Davidchao23** [comment]
Yeah, I already tried that, it said there's nothing wrong with the SD Card.
