### ISSUE TITLE
System settings are broken from installing ARM9LoaderHAX, can not access FBI.

### ISSUE THREAD

**Issue by ToadillerYT** [Steveice10/FBI#338]
My system settings are broken and I need to access FBI. Stevice10 could you use my branch of FBI to make a version of FBI that has no restrictions?

**Comment by ToadillerYT** [comment]
I meant fork sorry

**Comment by Steveice10** [comment]
Many people have previously requested the ability to restrict access to FBI using parental controls. The system settings being broken is a rare and unique situation, and as such does not warrant a change in this capability.
