### ISSUE TITLE
Can't remotely install titles unlees i use qr code

### ISSUE THREAD

**Issue by TriforceOfPwnage** [Steveice10/FBI#340]
I can't remotely seem to install title over network anymore i keep getting an this error
Failed to install from URL.
http://10.0.0.2:8080/_myciafilehere_
Result code: 0xD8A0A049
Level: Permanent (27)
Summary: Invalid State (5)
Module: HTTP (40)
Desc: unknown (73)
Any ideas?
Im on A9LH Luma3DS v7.0.5
EDIT: QR code installs work fine just over network doesn't work

**Comment by Steveice10** [comment]
Sounds like a network error. Make sure your PC is hosting the CIA data properly and that the necessary port is accessible.
