### ISSUE TITLE
lasturls is not cleared before being written to

### ISSUE THREAD

**Issue by bakugo** [Steveice10/FBI#341]
1. Try to remote install from `http://example.com/longerfilename.cia`
2. Try to remote install from `http://example.com/filename.cia`
3. Use "Repeat last request", url will be `http://example.com/filename.ciame.cia`

**Comment by Steveice10** [comment]
Does this build resolve the issue?

https://www.dropbox.com/s/ud043nac79nl2ax/FBI.zip?dl=1

**Comment by bakugo** [comment]
It does, thanks.
