### ISSUE TITLE
Suggestion: Integrate Homebrew Launcher loader?

### ISSUE THREAD

**Issue by StateOfException** [Steveice10/FBI#342]
Given the ongoing banwave/new status quo, there's been a new surge in demand for 3dsx homebrew, under the impression that just using that is more likely to help CFW users avoid detection.

This idea was prompted by a 3ds.guide variant recommended on the Nintendo Hacking Discord, which suggests leaving H&S-injected FBI as the *only* homebrew available from Home Menu, and sticking with something like SoundHax to boot into HBL for other homebrew. This is no longer a good solution on 11.4 (and above), obviously- no free HBL entrypoints exist anymore.

Given the relatively small size of the hblauncher_loader code, and the fact that FBI would, assuming this solution remains popular, be the only viable homebrew entrypoint available to users taking this route, it seems like it'd be extremely helpful to have this functionality integrated into FBI.

Obviously, there's no guarantee that avoiding CIA homebrew altogether is any more effective than placebo. But demand probably exists for something like this, regardless.

**Comment by Steveice10** [comment]
Not happening; just use hblauncher_loader. I doubt consolidating apps into FBI would help prevent bans at all, especially since FBI itself would be logged whenever you ran it to launch 3dsx homebrew.

**Comment by dogtopus** [comment]
If you really want a reliable entry point, just buy a oot3d. It's like $20 and you get a virtually permanent HBL entry point
