### ISSUE TITLE
Remote Install Freezes at 0%

### ISSUE THREAD

**Issue by jimmyz66** [Steveice10/FBI#343]
Hi,

I have a new 3DS XL on 11.4 system, I just have my boot9strap updated to 1.2, and luma updated to 8.0.

Somehow FBI remote install stuck at 0% no matter which .cia I was trying to install. I tried with some large .cia files ~1GB or themely.cia which is only 1.8 MB.

FBI's QR scan install still works for the same themely version. Local installation using .cia from SD card also works.

I also tried with SocketPunch1.2.5 and Boop. My 3DS had no response after punched with SocketPunch, and also no response to any button, I could only restart it.  When using Boop, remote install asks for confirmation and after hitting "Yes", the progress freezes at 0%, and can't be canceled by B button, I can only exit using Home button.

This issue was not happening before my B9S & Luma updates.

Please let me know if there is any possible solution to this issue.

Thanks a lot!

**Comment by Steveice10** [comment]
I would make sure that your PC isn't blocked from communicating on the port being used to serve the CIA over HTTP.

Additionally, if it only started after updating other software, that doesn't really suggest its necessarily an FBI-caused problem.

**Comment by jimmyz66** [comment]
Hi Steve,
Thanks.
The issues is not from FBI side. I guess Windows firewall just suddenly started to block the transmission somehow.
FBI remote install works now after refreshing program's access through Windows firewall, and opening with admin.
