### ISSUE TITLE
FBI not installing CIAs

### ISSUE THREAD

**Issue by meeeeee** [Steveice10/FBI#345]
When I try to install a CIA using FBI on CFW, I get the error:

Failed to install CIA file.
Result code: 0xD9004589
Level: Permanent (27)
Summary: Wrong argument (8)
Module: FS (17)
Desc <unknown> (393)

I'm not sure why I got this error, and I need help with installing CIAs with FBI.

**Comment by Steveice10** [comment]
Sounds like one or more of your title database files is broken. Try opening Data Management in the Settings app, letting it repair databases if it asks to do so, and installing your CIA again.

**Comment by meeeeee** [comment]
I opened Data Management, but nothing popped up. Is there a way to repair databases manually, perhaps by replacing or adding files to my micro-SD card?
