### ISSUE TITLE
One small bug of "Remote install > Repeat last request" ?

### ISSUE THREAD

**Issue by a5723797** [Steveice10/FBI#346]
Dear sir

Everytime I try to execute this command, it will append 3 letters "est" to the end of the last request url (eg. with http://abc/xyz.cia as the last request, it will try http://abc/xyz.ciaest ) , causing a 404 not found result. Please kindly investigate & fix this if it's a bug.  I am using FBI version 2.4.8. 

Thanks for all your effort.

UPDATE: It happens when the previous install process gets finished without user cancellation

**Comment by Steveice10** [comment]
I believe this has been fixed in the latest source. Can you test this build to confirm?

https://www.dropbox.com/s/ud043nac79nl2ax/FBI.zip?dl=1

**Comment by a5723797** [comment]
Ok, Will try and report the result. Thanks a lot!

**Comment by a5723797** [comment]
Yes, it works fine with this version. Thank you very much!
