### ISSUE TITLE
FAILED TO INSTALL FROM URL?!

### ISSUE THREAD

**Issue by projorx** [Steveice10/FBI#347]
Hello need help.. I'm using FBI and I'm trying to install some cias. But always have an error with the remote instalations. I was tryed to install that cias with sd card navigating to the folder of cias but for unknow reason I can't because I don't have the options of install and delete  or install.. I don't have any option in the fbi to install the cias. I'm looking for a solution for that and I was think in reinstall it again but don't know how can I do that because it's my first time using cfw on my 3ds. So it's another posibility but the objective it's solve that. I will write you here the error of my 3ds screen when I scan a qr code, please help me ASAP I don't understand what I'm doing wrong..

Failed to install from URL.
https://github.com/DanTheMan827/tik...
Result code: 0xE0E083EC
Level: Usage (28)
Summary: Invalid argument (7)
Module: AM (32)
Desc: Invalid size (1004)

**Comment by Jerry-Shaw** [comment]
Never seen this before. Have you tried the latest commit?

**Comment by projorx** [comment]
I tryed with the last version of FBI if you are telling that. And I understand that you never seen this before.. But the question is, what can I do? I'm worried about that..

**Comment by projorx** [comment]
Problem was solved! Don't buy kingston MICRO SDHC CARD!!!!! That's the problem.. Card was shit for that.. Btw thanks for try to help! ^^
