### ISSUE TITLE
Can't shutdown 3ds if i install a cia

### ISSUE THREAD

**Issue by Seba201x** [Steveice10/FBI#348]
If i install any cia with fbi i can't turn off my 3ds normally, i have to force the shut down pressing the power button

**Comment by Steveice10** [comment]
Can you elaborate on why you can't turn it off normally?

**Comment by Seba201x** [comment]
Maybe its because i have fbi injected as h&s, let me try with fbi installed normally

**Comment by Seba201x** [comment]
Yes @Steveice10 was that, if i use FBI injected as h&s i can´t turn off the 3ds normally, but if i install fbi normally and i install some cia i can turn off the 3ds without problems
