### ISSUE TITLE
Bug: CDN contents cannot be installed with FBI as a .3dsx

### ISSUE THREAD

**Issue by Hikari-chin** [Steveice10/FBI#349]
Under the [new Homebrew Menu](https://github.com/fincs/new-hbmenu) and Rosalina, which provides .3dsx applications the same permissions as .cia applications, FBI can install local CIAs and direct links to CIAs correctly, but attempting to install CDN contents will yield this error: 

![hltzufs](https://user-images.githubusercontent.com/25443872/27559609-203cdfe6-5a8f-11e7-84fc-2c44566e0338.png)

This occurs right after the "installing ticket" screen, and afterwards FBI will report "Install finished." as if it completely properly. 

Here's some more information about the 0xD963F805 error code: 

`Module: Application (254) | Description: String too big? This error is returned when service name length is greater than 8. (srv) (5) | Summary: Internal (11) | Level: Permanent (27)`

Additionally, the latest release does not return to the Homebrew Menu cleanly when exiting; it kills the HB Menu and returns to the Home Menu. This is because a new homebrew runflag was necessary for returning cleanly to the Homebrew Menu under Rosalina; this can be fixed by updating to a recent ctrulib commit and recompiling FBI; no code changes necessary.

**Comment by Steveice10** [comment]
This looks more like an issue with the environment (possibly the app you're running under?) than FBI. It's unable to create the thread it needs to execute the task.

**Comment by Hikari-chin** [comment]
Got it. To resolve the issue with not exiting cleanly, do you think you could make a point release or recompile and modify 2.4.8's attachments?

**Comment by Steveice10** [comment]
I suppose I could simply reupload the last release compiled against the latest ctrulib. I'll get around to it sometime fairly soon.

**Comment by Hikari-chin** [comment]
Thanks!

**Comment by Steveice10** [comment]
Can you confirm that this build fixes the 3DSX exiting issue?

https://www.dropbox.com/s/1qmjowxpqdo8jmn/FBI.zip?dl=1

**Comment by Hikari-chin** [comment]
It does; it returns to the Homebrew Menu cleanly. Thanks!

**Comment by Steveice10** [comment]
Thanks for testing. I've updated the official 2.4.8 release build.

**Comment by Hikari-chin** [comment]
@Steveice10 Just letting you know, this issue *was* indeed an environment issue, and was fixed [here](https://github.com/AuroraWright/Luma3DS/commit/3d8f62d38fc9b0b98dfba71f35ee3a878a3dbce0).
