### ISSUE TITLE
FBI Install error

### ISSUE THREAD

**Issue by BannerBomb** [Steveice10/FBI#35]
when i try to install any cia file it goves me some <code>Invalid_Command</code> error ill give u more info when i get home btw im on software version v10.5.0.30U & wat happens if i install a MT-FOP?

**Comment by urherenow** [comment]
FBI doesn't work as a .3dsx on 10.5. Try injecting it to health and safety, or see if you can install FBI.cia with NASA.

**Comment by BannerBomb** [comment]
i try to run NASA but it freezes on a glitched screen
