### ISSUE TITLE
Crashdump after using FBI

### ISSUE THREAD

**Issue by LioMajor** [Steveice10/FBI#350]
new3DS XL FW 11.2 / boot9strap 1.2
Luma3DS 8.0 latest nightlie

After FBI was running, exit with START Button or Home Button > Shutting Console down > Console crashes

**Comment by Steveice10** [comment]
Can you check whether this build has the same issue?

https://www.dropbox.com/s/qw5mriul9rdwosn/FBI.zip?dl=1

**Comment by LioMajor** [comment]
Start Button > Exit no crash, but still when shutting down console >> [Dumpfile](http://www102.zippyshare.com/v/RHZrOcbj/file.html)

**Comment by Steveice10** [comment]
If the crash is happening after FBI has exited, are you certain its the cause?

**Comment by LioMajor** [comment]
Without starting FBI no crash, probably still a problem related to b9s 1.2 / luma3ds.

**Comment by Steveice10** [comment]
Did this issue occur on previous versions of Luma3DS? Or in general, did anything change when the crashes started occurring?

**Comment by LioMajor** [comment]
The problem started after switching from a9lh to b9s.

**Comment by Steveice10** [comment]
I can't reproduce this myself on my N3DS (11.4.0-37U, Luma3DS v8.1, boot9strap v1.2), so I'm going to go ahead and conclude this probably isn't an FBI problem.
