### ISSUE TITLE
GUI Freeze + Graphical Issue

### ISSUE THREAD

**Issue by PerfectCrumpet** [Steveice10/FBI#351]
So everytime I boot FBI after a random period of time usually between 1-3 mins the GUI freezes completley and Lines appear on the top screen it most of the time does not effect installation if it is already in progress I just wait 20 mins before shutting off the 3DS and when it boots the software has loaded. However with larger software it freezes as soon as it starts installing (Not just a GUI freeze).

**Comment by wilhitewarrior** [comment]
I've been having the same issue.

**Comment by Steveice10** [comment]
Does this build work any better?

https://www.dropbox.com/s/p7sjfkjp72qc7sq/FBI.zip?dl=1

**Comment by wilhitewarrior** [comment]
So far, so good for me. It successfully installed a 1.05 GB cia without incident when before it never made it past 100 MB. Thanks so much, man. Both for the help and making this app to begin with. You rock :)

**Comment by Steveice10** [comment]
Alright. Updated the 2.4.8 release build.
