### ISSUE TITLE
Bugs using citro3d "next" to build FBI

### ISSUE THREAD

**Issue by Jerry-Shaw** [Steveice10/FBI#352]
1. Randomly screen blinks when listing titles
2. Randomly freezes on listing titles, or even worse causes system hangs (Home button not work)

Found the issues long ago when the master branch of citro3d could not be compiling under the latest commit of ctrulib. But it could be fixed doing a re-declare on these deprecated functions in ctrulib and using the master branch of citro3d to build FBI.

Not sure what would be the matter. It could only be related with citro3d "next", but, at least now, we should still using the master branch of citro3d to build FBI.

Building environment: Win10 x64, latest commit of ctrulib and FBI, both master and next version of citro3d.
Tested on both of my N3DSXL (USA) and N3DSLL (JPN).

Need more test on building under Linux.

**Comment by Steveice10** [comment]
It isn't a matter of redeclaing deprecated functions; it builds fine with the latest ctrulib and citro3d master branch, but apparently has some bad freezing issues on O3DS systems.

**Comment by Steveice10** [comment]
I seem to have pinpointed the source of the issue, and have opened an issue ticket in the citro3d repository: https://github.com/fincs/citro3d/issues/34

**Comment by Jerry-Shaw** [comment]
Hmm... I see. So we could only wait for the citro3d to fix it.

**Comment by DeathAngel74** [comment]
This resolves the issues with next branch of citro3ds and latest ctrulib.
[FBI.zip](https://github.com/Steveice10/FBI/files/1126242/FBI.zip)
Installing ctrulib 97b6149+citro3d master 3ae31ad, then building FBI f7ac0c4 worked. Thanks @frozenchen

**Comment by Steveice10** [comment]
Yeah, I just reverted the release download to one built against ctrulib 1.2.0 and citro3d master until this is resolved.

**Comment by DeathAngel74** [comment]
Coil beans. Thanks Steve

**Comment by DeathAngel74** [comment]
Cool lol. On mobile

**Comment by Steveice10** [comment]
Can someone test if this build against the latest ctrulib and the citro3d next branch works?

https://www.dropbox.com/s/jr5wcosuf4rz4d9/FBI.zip?dl=1

**Comment by DeathAngel74** [comment]
i'll test it out. Im install latest ctrulib from 7 hours ago ATM. will
report back

**Comment by FrozenChen** [comment]
@Steveice10 No freezes on titles, system hangs nor screen blinks so far. Havent seen any new issue.

**Comment by DeathAngel74** [comment]
seems fine so far

**Comment by Steveice10** [comment]
Glad it seems to be working now. Next release will be built against these versions.

**Comment by Jerry-Shaw** [comment]
haha, that'll be great. 😃
