### ISSUE TITLE
Boot9strap + Luma 8.0-8.1 FBI install cias slowly

### ISSUE THREAD

**Issue by InFeX90** [Steveice10/FBI#354]
Before, i use to install cias fast, like 800 mb in 5 min, with a speed of 1.2 mbps, now it says 39~40 kbps and it takes more than 5 hours to install something around 800 mb, why it happens?

**Comment by james-d-elliott** [comment]
Try h2testw on the SD card. It wont only tell you if the card is fake, but also if it's unrelated to cfw which I think is the case.

**Comment by InFeX90** [comment]
Thanks for the quick reply, I'll check it and I'll update you soon, now I'm doing the test, seems like it's gonna be really a slow one... in any case it's weird, I installed B9S to this o3DS 1 month ago and it's happening this now, like if it came from nowhere.

**Comment by james-d-elliott** [comment]
It could just be that it's a 4GB SD card, advertised as 32GB (for example), so when you've used 4GB it writes over itself. Often that sort of thing is slow. So as you fill it, the more problems you see. Could also be that it just has a fault in certain areas.

**Comment by InFeX90** [comment]
![image](https://user-images.githubusercontent.com/29247850/27815118-59aee36a-6047-11e7-8754-727c9d0ce427.jpg)
That's what I got

**Comment by james-d-elliott** [comment]
Well, I have no idea. Might be cluster/allocation size. Should be set to 32kb.

**Comment by InFeX90** [comment]
You mean format it with this???
![image](https://user-images.githubusercontent.com/29247850/27821286-626e2ea0-6067-11e7-8224-1676bd9644fd.jpg)
Because I did it... damn...  what's going on then?

**Comment by Steveice10** [comment]
If it came out of nowhere without updating FBI, it probably isn't an FBI issue. I can't reproduce it on my end anyway. Sounds more like an SD card issue, but if you tested and formatted it, I'm not sure what might be causing it. Maybe try with a completely different SD card just in case?

**Comment by Robloxboi123456789** [comment]
This is a VERY old post but, your all wrong about what it is!!

**Comment by Robloxboi123456789** [comment]
It actually depends on what DS model you have and what type of model it is, it also depends on how they have been updating FBI overtime, they have actually made the downloads take longer time!
