### ISSUE TITLE
Petition: Revert recent changes to FBI 2.4.8

### ISSUE THREAD

**Issue by FrozenChen** [Steveice10/FBI#355]
The recent changes made for 2.4.8 FBI (citro3d changes) caused fbi .cia version to be highly unstable (tested on two n3ds), causing the problem described in #352 and #353 , you have to be quick to do installs before FBI crashes the console and having to force shutdown. Since the 2.4.8 in releases is the most used one(latest release), lots of users will end up having the same problems.

Can the changes to the 2.4.8 files in releases be reverted [until the problem with citro3d next branch is fixed](https://github.com/fincs/citro3d/issues/34)?

**Comment by Jerry-Shaw** [comment]
Hey, I compiled FBI under the master version of citro3d, all works fine up till now.

**Comment by FrozenChen** [comment]
That doesnt matter, the point is the latest release in releases was updated recently, it was compiled using the next branch (implied by the problems it causes)

**Comment by Steveice10** [comment]
Changes have been reverted.
