### ISSUE TITLE
Cannot Access FBI>Titles for 2.4.8

### ISSUE THREAD

**Issue by kamenrider-darkglass** [Steveice10/FBI#356]
Explanation of the issue:
When trying to access FBI>Titles on 2.4.8, the screen freezes. Version 2.4.7 does not have this problem as I have tested it myself, so there must be something in the 2.4.8 version that's causing this. Every 1 in 5 times it doesn't freeze, so check it again if things seem fine at first.

**Comment by Jerry-Shaw** [comment]
Please see https://github.com/Steveice10/FBI/issues/352

**Comment by Steveice10** [comment]
Redownload 2.4.8.
