### ISSUE TITLE
White screen + installer stops - 2.4.8

### ISSUE THREAD

**Issue by IlPrescelto** [Steveice10/FBI#357]
Hi, i have the same issue described here (i'm not that user https://gbatemp.net/threads/fbi-bugging-out.475886/  ).
While i navigate the FBI menu, FBI keeps freezing while i'm moving inside the menu. This problem accours even when it is installing games. Plus, when installing games, sometimes it crashes while installing them (install bar not fulled and FBI crash/freeze).
As suggested in that forum, i'll install 2.4.7 but i want to report this anyway.

**Comment by Steveice10** [comment]
Redownload 2.4.8.
