### ISSUE TITLE
Won't work on 10.5

### ISSUE THREAD

**Issue by CiroMeiraLins** [Steveice10/FBI#36]
Won't work on 10.5

**Comment by urherenow** [comment]
Not as .3dsx. Wirks as a .cia. Use NASA to install the .cia.

And maybe look at closed issues before making a new one.

**Comment by CiroMeiraLins** [comment]
If NASA won't work on 10.5 either how do you expect it to work?

**Comment by urherenow** [comment]
Are you talking about emunand or sysnand? If it's sysnand, then of course nothing will work. Emunand, I'm not aware of nasa not working, but you should have installed it to sysnand before creating your emunand in the first place.

**Comment by CiroMeiraLins** [comment]
Bouth of then, it won't work on Sys eather on Emu.
