### ISSUE TITLE
[Feature Request] LED notification when finished installing

### ISSUE THREAD

**Issue by RS55** [Steveice10/FBI#360]
Well that, a notification for when you finish installing one or more .cia is possible? (When left to install with 3DS closed) I'm sorry if what I'm asking for is difficult or impossible to do.

**Comment by Steveice10** [comment]
I don't believe there are currently any functions available to accomplish this other than pushing an actual notification to your notification list, and I'd rather not be spamming people's notifications with install completion notices.

**Comment by RS55** [comment]
@Steveice10 Actually I was referring to something more like the Sapphire sysmodule of arc13 added to the Freeshop, which only turns on the LED to indicate that the game has already been downloaded, in this case it would be that the game was no longer installed.

**Comment by Steveice10** [comment]
I'd rather not have to risk messing with MCU like freeShop does.

**Comment by RS55** [comment]
I forgot that detail, true.
