### ISSUE TITLE
After updating to 2.4.9, built-in FBI updater display an error message

### ISSUE THREAD

**Issue by onmyouji** [Steveice10/FBI#365]
I'm on Old 3DS firmware 11.5 running Luma 8.1

After updating FBI to 2.4.9, when I tried to run FBI built-in updater, I received this error message. Usually when there's no new update available, FBI just displays that there's no new update.

![img_20170714_074340](https://user-images.githubusercontent.com/8424198/28193756-5f6373dc-6869-11e7-93ec-b2afc3cb085d.jpg)

**Comment by Steveice10** [comment]
Fixed in https://github.com/Steveice10/FBI/commit/5ba133f3caf265a2019cf98dec2cefa758b3de8d
