### ISSUE TITLE
Duped Titles in TitleDB

### ISSUE THREAD

**Issue by killerfurze** [Steveice10/FBI#366]
I updated FBI and went to TitleDB and many titles were duplicated a decent amount. Not all, I have a few photos, [here](http://imgur.com/T8xzlhd)

**Comment by Steveice10** [comment]
TitleDB returns multiple versions of the same app, and expects the client to filter them out. Code is in place to do so based on title version, pending a merge of [this pull request to TitleDB](https://github.com/ksanislo/TitleDB/pull/8).

**Comment by Steveice10** [comment]
An alternative has been implemented based on the time at which the app was updated.
