### ISSUE TITLE
Camera capture does not show on o3ds

### ISSUE THREAD

**Issue by CodyMKW** [Steveice10/FBI#367]
After updating using the qr code scanner does not show what the camera is capturing on the top screen it just shows a black screen

**Comment by Steveice10** [comment]
Does this build make any difference for you?

https://www.dropbox.com/s/o07dw0doatciqrs/FBI.zip?dl=1

**Comment by CodyMKW** [comment]
seems to work now for me after installing that one

**Comment by Steveice10** [comment]
Alright, thanks for testing. I've pushed the fix to source.
