### ISSUE TITLE
Icon font glitch

### ISSUE THREAD

**Issue by NinjaBoyLao** [Steveice10/FBI#368]
The icon for the CIA version of FBI, installed to my O3DSXL's SysNAND, running Luma3DS 8.1, appears at a casual glance to now say "FRI" instead of "FBI". This issue was present in previous releases but I held out on creating this in the hope that it would fixed on its own, it has now bothered me long enough.

**Comment by Steveice10** [comment]
Could you provide a screenshot?

**Comment by Dark124** [comment]
Most likely just looks like it says FRI

**Comment by Steveice10** [comment]
Yes, but I need to see under what circumstances. This is likely from icon scaling for the 24x24 icon.

**Comment by NinjaBoyLao** [comment]
working on it right now, sorry i had to sleep and ive been busy all day

**Comment by NinjaBoyLao** [comment]
[top1](https://lh3.googleusercontent.com/eXyS5SV0NsowmTn15an7tJAxIu0_6hWelOdnrlafdKS7GVLx8kXSjRTR4KwSK1Ke9U-vdZqZyVa6iAq7On4OlrTsLeYENz9sVfOEir-eFhAeh-ApReovUQ0J_gwLuPS593mCusojZzGL-82c_ZsHAjl370FyjZnxoS5aJ8CwxwJX0XF6xe63dcXz58opv37PyfRJETIHGZx9CRYgOwwhnaxV33PjhQplIG4oDrJvRFUwNFsWFbkQq7Jc6YT7iyX-XGzZdxBRpc1083Va2a_LgzIGaezfGExrtUpo-mm7ikmsgQDbkPKQWI-pQXDUorTlVf6gWC2MHxG4UW8OHx0zwLYO3yawl6N6yIUW4xFfQddAz67P8j-zV-8Zz7WrtVBuQeySY4dhzZwwcys33KMSN1DdBoqPRJ2ms4hmjkUXi0WwLz4vqO0EZYTmL2YBZ0GQLYnDOw-6L3MwkTadw_olfLjGHXpyYiekSGDr7H8MND7XYkVRnyE6m1J2qG2piCQBIA_QF2rgQkFRk1RntCGdDvvv-MT9NT7juU5CV3ixTNz4Hv_CXQzLH_azZtZmK6eKFGYNFiIEOhfbA9yPcBOrOD39PAb0tAaxKu5G85jsTeWSAaKC9XDay7XeGg=w400-h240-no)
[bottom1](https://lh3.googleusercontent.com/3t52ZXNAnE2X5uI_DVkCIqkWt09xh_ZdNX5yvqtyCfzYqJirnb80ssfuBMTVx0OX8QJ0tUwp5mTItcI2YE-B8wJCWEkoxQy3667bQzahC53hhAutbNxrllV9Wes_N_A03JAVTb0O49CbT6-pSZhleTXrJVecTWDQ3FOhNkAp2RlKOUAQD1Krm5QQNDEHFf-sChFcAkVRY-nHu0z52lZVtNA0-DQit2gEitUcPz64rzQ89usdhC0kcIdL9qC-RWgu65YUK-xlq1Wy40Xg5HsTDFSvNbHd7Yuftz-IY_Yg3RLFr9rEWWrNT2X3F8DNY3vlvwvKvThJwL2OpD5mIUyfMrf_8hwvPCn9kmfxUIj4s2L7E9QYSKlgoZU8UO_WdCcOHF9JosYWCgjl1PreHXcoV_JsfT_jtFiBsowSmJl13ZkSEd_Nmjs2CGxjN4jkd1NVsW89RHYC3Gt-tu7iUmFct88Yqz1wggWOKVxae0i87asYuEYrZjQ30yl1DAoXxpvWpoP2lkU05sAy9DTylld_uV2nU7XT1P-LaAOALGMoiFAlQluSuBw16uAz69ljZfB5xpbTUz1_TwSkQ3dpi5gTLwxAHz1tGY-nPVKS4y-lXe09rADKwThHPrHsuA=w320-h240-no)
[top2](https://lh3.googleusercontent.com/B7dMR4rwmCPgO2T_3TxApIN_OOqMVyuY97zi94MowXNDmP4d1_5-7D8UiL7sX7XEktxmPGd_uN-18WsNqZe967Z34r7SbCM8psBfK7_tTJ1rrYzwGK9j_EtXBVCfDpxPkXP6Y4lRYGL6bsuvBM4ViYHZJjzPmk7zRyDYssOXOLN1CYFfANUC1ucEoIvEDWUkE74FcRxsrt0IaRWNQs1vJ917sL6IrKmXpCHJma_Wh18tfbABGeUe5sEnVkoATD4CRzpn-SrYiFTMC9eJx5rhTo1n2CFwF1K8hfXKXE0O5z8-vrGK22H1CLES_MrDbDvO_72Oxd3gbvoe71ukCODwZcq7-4mVGyUGQOv5AADR6UF136vC47RVe_7eX8UNfSkV3bFDB_Pm1TsZ0fHJgMP9qxCrPZ0NT-gC4_RIyGKfCfFco_Gtg9F6jMbPTEfj-eDow2f-eXoKnL2rdpkuRWPufcCOxv3yIcxQVoTSz8g4JiorVVitOOZ-9jOqT0-ih-t-UBEjg-AXITcGTwBcXtTte7mRjZjKdT5D_xVAYOMge7dT39XYtg3KXUN6UxjHVVoD0X4yhsPG0E7Giss1ESoIp11uHZ79Pa2P6ryI1LDkWulSv1GFQXUVgg=w400-h240-no)
[bottom2](https://lh3.googleusercontent.com/EcdKzH4Kxj5FipddkiKlCgj8hcIpDEBoLeilRXE0osVV44vBOyFiEKE8HFkbHQXQWeAOV6L4JV3GGd6YNTHyOlQIkEBE8iNTEKAKuBafBx29x9YF4BF-W1nzO4ce8C4-w2oeI4OAZPpdaSFJlogFRJXOBbVf_cxgEST3WHVtA_XMTBA_WOUd8dyy-s4G3xBtaXM2v9ikEf6NsIWWlS1SCsIx4epk1u5oNyQctY0lPyFMdbmdd7WifELB9fTIiG46qCe0PH87VcafH7s0harYEpr9KKbY5nTKIuPaN824LPAnzqa38BY9hxeIc5hflHaDPBF6yvtdjheC2o1EHQpvBiJoUB7LboXUWPrIpex3PrcWc6cIlsf8778Nd9J7xpIKn3-uvYVHHcmSzlzmxHEGotmznWRcQfD_C7oN_LeIjnY00BSNGscm4BzdoZ7n860xKOQ1riGZ7Uk6SFFAdR0E-1pUv-aq7pzzprFETTMHxJDBqnW64xFVrj8ishuniPewOgC8mLcOO0MhY4osJDFCJtdhoXjoXIud9FvDjf1_6gWypxlBnmlupXsQDy1xhi9eUfnVEk2f2UzNzL14iB_XxmvXYXMNjtOR1l_KLD7UD6N659VirHtUSA=w320-h240-no)

theme doesn't seem to affect it

**Comment by NinjaBoyLao** [comment]
oh boy i just looked at those and that's not what i see when i look at my screen. crap. i took those with luma is there another screenshot method that's more accurate

**Comment by NinjaBoyLao** [comment]
[this is what i see](https://lh3.googleusercontent.com/ov7QKpTLnRFU1clElrnLNeqt_SkoeBWZprLM3QaygiORFsFsvhzXrJScelZzoSWby8cTanI8jwRfQV6JftU8O78g8eYDfhIBU16LCA_tAiHH0wdFp5cxwTmRsXla8nuGdqIyPFHQcZ6mO3N2r6ufW4BT02TmDrrE3cIbANs2y7VHBKFp58xjzSsLJr_-OTRN7gH0HhUzocGg2RB6cLoGfku7JXIMcNC4sgjcZVhESxgt27inaCmKz55AIi7PE_5mdigHAn-auejZCPy8FXzRem7Md-Tl3LrGHs6CO1MMddCrm5b6nUGPbNPFro-xluQ57auTIokteomKn6ozfKcYwgjGwNfODzkgkZnUekj0fEC7spLukI9bkuu2LWUrmNd2o0fUNqVUJKmhm01mngxkNugWW92fugUT8S7JhJxWLDFvrRr-vVqVwpUl9yIovzVKp1u6D3d7eWQsSOqvjruBn9hoqw72T8ZchNESBbUn94NWKnOQNLMVGwYuduPSumLApk079Bh6UHobp9e8HO2zu0Og-VDZkA-mdmo8knhMoUy4cAWoHm2lS5lnpuwDr-gUg84Wx_OVcr9MFN2EUPvf3Q6b_LOLdteyzsEc43BUGsa_evEVyMG_TieDaQ=w434-h770-no)

sorry about that

**Comment by Steveice10** [comment]
I'm unable to view any of those images.

**Comment by Steveice10** [comment]
Just checked the home menu at the largest icon size, the home menu at the smallest icon size, the System Settings Data Management menu, and the homebrew launcher, and all four read "FBI" just fine. Plus, I can't view your images to see what you're seeing.

**Comment by NinjaBoyLao** [comment]
im really sorry about that. heres what ive got. ![3dshdr](https://user-images.githubusercontent.com/16899151/28244864-19ea6060-69c5-11e7-9788-854f3e3b1a30.jpg)

**Comment by NinjaBoyLao** [comment]
here are the screenshots, they don't look the same as what i see but it still isn't very clear that thats a B and a I and not an R and a T
![bottom1](https://user-images.githubusercontent.com/16899151/28244880-7afa4b72-69c5-11e7-9f30-32dd8b2f9bfd.jpg)
![bot_0001](https://user-images.githubusercontent.com/16899151/28244881-88bc0458-69c5-11e7-8f8a-9bd962c16fab.jpg)

**Comment by dogtopus** [comment]
I can barely reproduce the "FRT behavior". Maybe the actual behavior differs from different screen types?
I tried this on a O3DS with TN screen. It behaved more like the screenshot rather than what @NinjaBoyLao saw.

**Comment by Steveice10** [comment]
I can't really help it if it isn't fully visible with power saving mode on. That's just how the icon turns out when scaled down to 24x24.

**Comment by Steveice10** [comment]
Try this build and let me know if it looks any better.

https://www.dropbox.com/s/ak594e4dqyaaefp/FBI.zip?dl=1

**Comment by NinjaBoyLao** [comment]
Yessir preparing to try now

**Comment by NinjaBoyLao** [comment]
Hmmm.. if anything, it's a bit worse on size "5", and no change on size "4".. However when touching and dragging the icon at size "4" it's quite clear, where before touching and dragging made no difference. I made sure to do a reboot between uninstalling the stock version and installing the test version too, so it's hopefully not a cached icon issue. 

Turning off power saving mode makes it the slightest bit clearer, exactly like the screenshot from luma. I prefer power-saving though, it gives me a significant boost in battery life. I suspect this is because power saving mode filters out blue a bit, and the icon just so happens to be a blue that gets filtered.

Do you reckon you could make the font slightly slightly bolder, or slightly more blue? I understand this is your project and the aesthetic direction is entirely up to you. I also greatly respect your work on it and mean no insult at all by asking.

**Comment by Steveice10** [comment]
How about now? I made the base icon's font thicker.

https://www.dropbox.com/s/mhr8gcoz857o95m/FBI.zip?dl=1

**Comment by Steveice10** [comment]
@NinjaBoyLao Have you been able to check the revised icon's appearance?

**Comment by Steveice10** [comment]
Going to assume that the new icon won't have this issue.

**Comment by dogtopus** [comment]
I can confirm that the new icon works perfectly on every resolutions.

**Comment by NinjaBoyLao** [comment]
Also confirming this, sorry all for the long absence.
