### ISSUE TITLE
FBI Fails To Check For Update

### ISSUE THREAD

**Issue by MKWPlayer1337** [Steveice10/FBI#369]
I updated from version 2.4.8 to 2.4.9. Whenever I check for updates using version 2.4.9, I get this error message.

Details are here:

Failed to check for update.
Result code: 0xD963F806
Level: Permanent (27)
Summary: Internal (11)
Module: Application (254)
Desc: Parse failed (6)

Is this a known bug? I know that version 2.4.9 is only 20 hours old, so if something screwed up here or there, it's ok. I just wanted to inform you since no other posts about this were found here.

Pls let me know soon. Thx

**Comment by onmyouji** [comment]
Duplicate of #365

**Comment by MKWPlayer1337** [comment]
Oh. My bad. I didn't check the closed issue. I'm going to close it now.

**Comment by lilcruz6ix9ine** [comment]
How do I fix this
