### ISSUE TITLE
error open CTR NAND Fbi V.2.4.9 in homebrew launcher rosalina

### ISSUE THREAD

**Issue by MAXAITA** [Steveice10/FBI#370]
When you try open de CTR NAND in  fbi version 2.4.9 in mode  homebrew launcher rosalina v2.0.0

Error
failed to open file listing archive
Result code : 0xD9004676
Level: Permanent (27)
Summary: Wrong argument (8)
Module: FS (17)
Desc: Archive permission denied (630)

**Comment by Steveice10** [comment]
Enable ARM9 access patching in the Luma3DS settings.
