### ISSUE TITLE
Multiple entries on TitleDB

### ISSUE THREAD

**Issue by Boured** [Steveice10/FBI#371]
I just updated and when I go to TitleDB to get some new games or apps and stuff it shows multiple versions of the app. I can count 33 TWLoaders on this which I can tell is not normal at all. My friend says it's because old versions are being shown and if that's the case I hope it gets fixed.

**Comment by Dark124** [comment]
It's clearly being fixed look at commits

**Comment by Steveice10** [comment]
This has already been taken care of.
