### ISSUE TITLE
feature request: option to turn off screen to conserve power when remote installing.

### ISSUE THREAD

**Issue by Jimmy-Z** [Steveice10/FBI#373]
I see retroarch can turn off the lower screen so I hope this is possible, if not, lower the brightness to the lowest level?

And offer some notification when completed like making sound or calling some remote CGI? I'm actually using an ugly fix for the later, after the real URLs that I want to install, I append another URL which is a CGI sending a push notification to phone.

**Comment by Steveice10** [comment]
Couldn't you just lower the brightness from the home menu? Also, I feel like power conservation options would fit better as a CFW feature, rather than being implemented on a per-application basis.

**Comment by Jimmy-Z** [comment]
Yes it fits better as an OS feature, but after all 3DS is not running an ordinary OS, and installing big CIA files is not a common scenario for 3DS, and I guess it's to complicated to implement this in CFW.

That been said, if I could write this, would you accept the PR?

**Comment by Steveice10** [comment]
It really shouldn't be that difficult of a feature to implement in CFW.

If you can implement it in a clean way, I suppose I wouldn't have too many objections to pulling it in. I had trouble thinking about what to do when an error occurs while the screen is off, etc., but I suppose you could just add a global screen toggle and rely on the user to turn it back on later and see the error.

**Comment by Jimmy-Z** [comment]
Please don't laugh if my ideas are wrong.

If implementing it in CFW, CFW would maintain something like an inactivity timer in the background and when it shot CFW shutdown the screen, but usually games wouldn't need that, and probably hazardous like if you're watching a long cinematic sequence without any input, so it would need a switch which is off by default, and when you started a CIA install, you set it on, and set it back to off when the install finished.

It would work more like a general OS/app relationship, but again 3DS is not running an ordinary OS, I really couldn't think of another scenario which would need this OS feature, and it would be simpler to implement it in FBI.

If implementing it in FBI, your idea sounds even simpler, no need to add an option item then, just a hint message like "press X to turn off/on the screen" during install is enough.

**Comment by Steveice10** [comment]
It wouldn't have to be an OS/app relationship; you could simply have a CFW feature that allows the user to toggle the screen on and off at will.

**Comment by Jimmy-Z** [comment]
Oh that makes sense... rosalina is a thing, I'm not used to think that way yet.
