### ISSUE TITLE
2.4.10 Freezing

### ISSUE THREAD

**Issue by conjure86** [Steveice10/FBI#379]
Hi there,

FBI 2.4.10 is freezing on launch intermittently on a brand new New 3DS XL, running 11.5. Luma 8.1

**Comment by Steveice10** [comment]
Can you check whether this occurs with earlier versions?

**Comment by pnhearer** [comment]
This occurs for me as well but only if I load up NTR CFW prior to opening FBI. Rebooting 3DS alleviates this problem.

**Comment by pnhearer** [comment]
--Sorry for the double post--
Forgot some relevant info
Hardware : Japanese New 3DS LL
Sys: 11.5.0-38J
Homebrew:
-Luma
NTR CFW
FBI 2.4.10

**Comment by Steveice10** [comment]
I would suggest not running FBI in NTR CFW, then.

**Comment by pnhearer** [comment]
Agreed. That has been my work around.
