### ISSUE TITLE
Would you consider uploading a health and safety injectable for each FBI update?

### ISSUE THREAD

**Issue by fennectech** [Steveice10/FBI#380]

**Comment by ihaveamac** [comment]
likely not happening given that it was always a crappy method, and rosalina makes this obsolete.

**Comment by pbanj** [comment]
Don't forget you can use godmode9 to inject pretty much anything you want into health and safety. So there is literally 0 reason to include 3(regions) premade injected ones.

**Comment by fennectech** [comment]
Rosalina?     Im just updating to bootstrap9 xD   Will have to hit the gargler

**Comment by Steveice10** [comment]
As mentioned, H&S injection is pretty much obsolete by now. Either way, it has never been my intention to support anything related to H&S injection in an official way.

**Comment by fennectech** [comment]
That is totally rad!   Thank you for telling me this
