### ISSUE TITLE
Bad HTTP user agent string

### ISSUE THREAD

**Issue by mtheall** [Steveice10/FBI#381]
I notice this in my logs:

    "GET /%7Emtheall/ftpd.cia HTTP/1.1" 200 576448 "-" "Mozilla/5.0 (Nintendo 3DS; Mobile; rv:10.0) Gecko/20100101 FBI/VERSION_MAJOR.VERSION_MINOR.VERSION_MICRO"

Looks like the problem is with your macros:

    #define MAKE_HTTP_USER_AGENT(major, minor, micro) ("Mozilla/5.0 (Nintendo 3DS; Mobile; rv:10.0) Gecko/20100101 FBI/" #major "." #minor "." #micro)
    #define HTTP_USER_AGENT MAKE_HTTP_USER_AGENT(VERSION_MAJOR, VERSION_MINOR, VERSION_MICRO)

It should be like this:

     #define HTTP_USER_AGENT ("Mozilla/5.0 (Nintendo 3DS; Mobile; rv:10.0) Gecko/20100101 FBI/" #VERSION_MAJOR "." #VERSION_MINOR "." #VERSION_MICRO)

**Comment by Steveice10** [comment]
That does not compile.

	In file included from /opt/devkitpro/libctru/include/3ds.h:13:0,
		         from source/core/util.c:7:
	source/core/util.c: In function 'util_http_open_ranged':
	source/core/util.c:687:92: error: stray '#' in program
	  ("Mozilla/5.0 (Nintendo 3DS; Mobile; rv:10.0) Gecko/20100101 FBI/" #VERSION_MAJOR "." #VERSION_MINOR "." #VERSION_MICRO)
		                                                             ^
	/opt/devkitpro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
	 #define R_SUCCEEDED(res)   ((res)>=0)
		                      ^~~
	source/core/util.c:749:102: note: in expansion of macro 'HTTP_USER_AGENT'
	 R_SUCCEEDED(res = httpcAddRequestHeaderField(context, "User-Agent", HTTP_USER_AGENT)))
		                                                             ^~~~~~~~~~~~~~~
	<command-line>:0:15: error: expected ')' before numeric constant
	/opt/devkitpro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
	 #define R_SUCCEEDED(res)   ((res)>=0)
		                      ^~~
	source/core/util.c:687:93: note: in expansion of macro 'VERSION_MAJOR'
	 ("Mozilla/5.0 (Nintendo 3DS; Mobile; rv:10.0) Gecko/20100101 FBI/" #VERSION_MAJOR "." #VERSION_MINOR "." #VERSION_MICRO)
		                                                             ^~~~~~~~~~~~~
	source/core/util.c:749:102: note: in expansion of macro 'HTTP_USER_AGENT'
	 R_SUCCEEDED(res = httpcAddRequestHeaderField(context, "User-Agent", HTTP_USER_AGENT)))
		                                                             ^~~~~~~~~~~~~~~
	source/core/util.c:687:111: error: stray '#' in program
	 tendo 3DS; Mobile; rv:10.0) Gecko/20100101 FBI/" #VERSION_MAJOR "." #VERSION_MINOR "." #VERSION_MICRO)
		                                                             ^
	/opt/devkitpro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
	 #define R_SUCCEEDED(res)   ((res)>=0)
		                      ^~~
	source/core/util.c:749:102: note: in expansion of macro 'HTTP_USER_AGENT'
	 R_SUCCEEDED(res = httpcAddRequestHeaderField(context, "User-Agent", HTTP_USER_AGENT)))
		                                                             ^~~~~~~~~~~~~~~
	source/core/util.c:687:130: error: stray '#' in program
	 rv:10.0) Gecko/20100101 FBI/" #VERSION_MAJOR "." #VERSION_MINOR "." #VERSION_MICRO)
		                                                             ^
	/opt/devkitpro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
	 #define R_SUCCEEDED(res)   ((res)>=0)
		                      ^~~
	source/core/util.c:749:102: note: in expansion of macro 'HTTP_USER_AGENT'
	 R_SUCCEEDED(res = httpcAddRequestHeaderField(context, "User-Agent", HTTP_USER_AGENT)))
		                                                             ^~~~~~~~~~~~~~~
	make: *** [buildtools/make_base:603: build/3ds-arm/source/core/util.o] Error 1

**Comment by mtheall** [comment]
Sorry I assumed VERSION_MAJOR etc were macros themselves. I don't see where they are defined.

**Comment by Steveice10** [comment]
They're defined in the command line arguments to the compiler.

**Comment by mtheall** [comment]
Okay I see it now in the Makefiles. github search was useless for finding it. I was able to verify that the generated user-agent string is correct.
