### ISSUE TITLE
Reproducible GPU freeze after launching NSMB2

### ISSUE THREAD

**Issue by AuroraWright** [Steveice10/FBI#382]
This could also be a citro3d bug, but I have no idea.  On a 11.5E N3DS XL, opening NSMB2 (tried both my cart and the .cia conversion), letting it get to its main menu (with the 1 player/2 player selection), pressing HOME, closing the game with X, then launching the cia version of FBI (that I self compiled with latest dkA/ctrulib/citro3d) leads to a freeze, with no exceptions occurring (so it seems to be a GPU freeze). Doing the same thing with another game (among those I have) or with nothing being launched prior to FBI, it works fine.

EDIT: I confirm this issue occurring on a O3DS XL as well, with older FBI.

**Comment by Steveice10** [comment]
Reproduced with [JKSM](https://github.com/J-D-K/JKSM/) and [mGBA](https://github.com/mgba-emu/mgba/), so this is not an issue specific to FBI or citro3d. My guess would be NSMB2 itself either doing something bad or just doing something that ctrulib handles improperly.

**Comment by AuroraWright** [comment]
Ah I see. sf2dlib is a wrapper around citro3d, so it might still be it.

**Comment by Steveice10** [comment]
Did not realize it had changed over to citro3d.
