### ISSUE TITLE
Rosalina interferes with install of CIA files

### ISSUE THREAD

**Issue by dubbz82** [Steveice10/FBI#383]
On an installation of a CIA file with the latest build of FBI, if you pull up the Rosalina menu, it will cause the installation to cancel out and fail.  Not sure if this is more of an FBI issue or a Rosalina issue.  

Steps to reproduce the issue:
1. Start installation of a CIA
2. Pull up Rosalina, with or without changing any options within it
3. Exit Rosalina.  The install will say it was canceled.

**Comment by Steveice10** [comment]
I'm fairly certain this is a result of the "B" button press to exit the Rosalina menu also being caught by FBI and cancelling the CIA installation. Not an FBI problem.
