### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by GrowingLK** [Steveice10/FBI#384]
When using the FBI to install the game, encounter running the installation package immediately prompts an error. Try to replace the game a number of different installation packages, or the same error.
![3dserror](https://user-images.githubusercontent.com/18570357/29697978-f25480e6-8984-11e7-9e83-6c1412862a2c.jpg)

**Comment by urherenow** [comment]
And? It already tells you that you have a bad .cia file. How are you launching FBI? HBL? Without a9lh?
http://3ds.guide

**Comment by GrowingLK** [comment]
我的3DS 使用的是B9S。下载了多个不同的CIA 都是这个提示。如果是CIA的错误，我自己在尝试一下吧。多谢你的回复。

**Comment by GrowingLK** [comment]
My 3DS is using B9S. Download a number of different CIA are the tips. If it is CIA wrong, I try it now. Thank you for your reply.

**Comment by Steveice10** [comment]
It's probably either that the CIAs are bad or there's something wrong with your SD card.
