### ISSUE TITLE
FBI can't reinstall existing titles via the network

### ISSUE THREAD

**Issue by AuroraWright** [Steveice10/FBI#385]
When installing a cia from the SD card, it's possible to reinstall the same title (I suppose FBI uninstalls it and reinstalls it automatically). However, using the "receive URLs over the network" feature, installation fails because the title already exists.

**Comment by Steveice10** [comment]
When you get the "title already exists" error, can you check if the title is actually still installed? Because the title deletion is being performed right here: https://github.com/Steveice10/FBI/blob/master/source/ui/section/action/installurl.c#L178

**Comment by AuroraWright** [comment]
The error is: 0xC8E083FC (Level: Status, Summary: Invalid Argument, Module: AM, Desc: Already Exists).

**Comment by Steveice10** [comment]
When you installed from the SD card, was the CIA the exact same as you had already installed, or was it a different build? I've found that this error doesn't pop up if, for example, you rebuild a homebrew application and try installing it over an existing installation. SD card installation and network installation are performing essentially the same steps, just with a different source, so I don't see why this issue would occur only via network installation unless there were some other variable.

Also, is this a NAND title or an SD title? If it's a NAND title, this may be problematic as, unless I'm mistaken, you can only refresh the SD title database.

**Comment by Juanito9001** [comment]
sometines i had that error, but i dont know why... when i do the next procediment (shutdown the 3ds, retire the battery, wait 30 seconds, reinsert battery and reboot 3ds, adjust time and day and connect to internet) the fbi let me install without problems... really... thats odd

**Comment by AuroraWright** [comment]
Turns out this only happens with AGB_FIRM titles after you reboot after playing that specific title (not sure why). Everything else works, so I'd say it's not FBI's problem after all.
