### ISSUE TITLE
Suggestion: Add latest title version and latest title version size in TitleDB

### ISSUE THREAD

**Issue by DevShadd** [Steveice10/FBI#387]
All I'm requesting is to add in latest title version and latest title version size in the title database on the top of the screen (similar to the installed version and the size of the installed version) just to make checking for updates easier. This isn't much of a hassle to add either.

**Comment by Steveice10** [comment]
Still waiting on a PR to TitleDB to go through. See https://github.com/Steveice10/FBI/issues/312 and https://github.com/ksanislo/TitleDB/pull/8
