### ISSUE TITLE
Regression: QR codes for github raw cias not working on latest FBI

### ISSUE THREAD

**Issue by Jolty95** [Steveice10/FBI#389]
Title says it. Some users (me included) have notice that some QR's codes pointing cias are throwing an 404 error when they worked on previous version of FBI.
Here you can find an example of an QR code that worked before:
![TWLoader GUI code](https://raw.githubusercontent.com/wiki/Robz8/TWLoader/images/qr/gui.png)
but now shows 404 error.

URL from that QR: https://github.com/Jolty95/TWLoader-update/blob/master/TWLoader.cia?raw=true

Thanks!

**Comment by Steveice10** [comment]
I'm guessing it might be an issue with following redirects, as that URL redirects twice until it reaches https://raw.githubusercontent.com/Jolty95/TWLoader-update/master/TWLoader.cia

Will investigate.

**Comment by Jolty95** [comment]
Thanks @Steveice10

**Comment by Steveice10** [comment]
Looking into it further, it actually seems to be an issue related to URL encoding. FBI encodes the URL to "https://github.com/Jolty95/TWLoader%2Dupdate/blob/master/TWLoader.cia?raw=true", which when visited returns a 404 error; however, my browser automatically converts the %2D back into a dash in the address bar, and that works fine. Perhaps GitHub doesn't like URLs encoded that way?

**Comment by Jolty95** [comment]
Thanks for finding the issue :) Does https://github.com/Steveice10/FBI/commit/5be2bc0694a3846c92f1dbfb0ba41de26f7617df fix this?

**Comment by Steveice10** [comment]
Yes.
