### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by 3xkrazy** [Steveice10/FBI#39]
Hi,

I'm getting FBI compile errors with the latest libctru and citro3d installed.

`build/source/ui/section/task.o
In file included from /home/hle/.bin/devkitPro/libctru/include/3ds.h:13:0,
                 from source/ui/section/task.c:8:
source/ui/section/task.c: In function 'task_load_titles':
source/ui/section/task.c:322:34: warning: implicit declaration of function 'AM_GetTitleList' [-Wimplicit-function-declaration]
             if(R_SUCCEEDED(res = AM_GetTitleList(&titleCount, mediaType, titleC
                                  ^
/home/hle/.bin/devkitPro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c:327:42: warning: implicit declaration of function 'AM_GetTitleInfo' [-Wimplicit-function-declaration]
                     if(R_SUCCEEDED(res = AM_GetTitleInfo(mediaType, titleCount,
                                          ^
/home/hle/.bin/devkitPro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c: In function 'task_load_pending_titles':
source/ui/section/task.c:447:26: warning: implicit declaration of function 'AM_GetPendingTitleCount' [-Wimplicit-function-declaration]
     if(R_SUCCEEDED(res = AM_GetPendingTitleCount(&pendingTitleCount, mediaType,
                          ^
/home/hle/.bin/devkitPro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c:447:81: error: 'AM_STATUS_MASK_INSTALLING' undeclared (first use in this function)
 CEEDED(res = AM_GetPendingTitleCount(&pendingTitleCount, mediaType, AM_STATUS_M
                                                                     ^
/home/hle/.bin/devkitPro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c:447:81: note: each undeclared identifier is reported only once for each function it appears in
 CEEDED(res = AM_GetPendingTitleCount(&pendingTitleCount, mediaType, AM_STATUS_M
                                                                     ^
/home/hle/.bin/devkitPro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c:447:109: error: 'AM_STATUS_MASK_AWAITING_FINALIZATION' undeclared (first use in this function)
 tleCount(&pendingTitleCount, mediaType, AM_STATUS_MASK_INSTALLING | AM_STATUS_M
                                                                     ^
/home/hle/.bin/devkitPro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c:450:34: warning: implicit declaration of function 'AM_GetPendingTitleList' [-Wimplicit-function-declaration]
             if(R_SUCCEEDED(res = AM_GetPendingTitleList(&pendingTitleCount, pen
                                  ^
/home/hle/.bin/devkitPro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c:453:17: error: unknown type name 'AM_PendingTitleEntry'
                 AM_PendingTitleEntry* pendingTitleInfos = (AM_PendingTitleEntry
                 ^
source/ui/section/task.c:453:60: error: 'AM_PendingTitleEntry' undeclared (first use in this function)
                 AM_PendingTitleEntry* pendingTitleInfos = (AM_PendingTitleEntry
                                                            ^
source/ui/section/task.c:453:81: error: expected expression before ')' token
     AM_PendingTitleEntry* pendingTitleInfos = (AM_PendingTitleEntry*) calloc(pe
                                                                     ^
In file included from /home/hle/.bin/devkitPro/libctru/include/3ds.h:13:0,
                 from source/ui/section/task.c:8:
source/ui/section/task.c:455:42: warning: implicit declaration of function 'AM_GetPendingTitleInfo' [-Wimplicit-function-declaration]
                     if(R_SUCCEEDED(res = AM_GetPendingTitleInfo(pendingTitleCou
                                          ^
/home/hle/.bin/devkitPro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c:469:81: error: request for member 'version' in something not a structure or union
                       pendingTitleInfo->version = pendingTitleInfos[i].version;
                                                                       ^
In file included from /home/hle/.bin/devkitPro/libctru/include/3ds.h:13:0,
                 from source/ui/section/task.c:8:
source/ui/section/task.c: In function 'task_load_tickets':
source/ui/section/task.c:527:26: warning: implicit declaration of function 'AM_GetTicketCount' [-Wimplicit-function-declaration]
     if(R_SUCCEEDED(res = AM_GetTicketCount(&ticketCount))) {
                          ^
/home/hle/.bin/devkitPro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c:530:34: warning: implicit declaration of function 'AM_GetTicketList' [-Wimplicit-function-declaration]
             if(R_SUCCEEDED(res = AM_GetTicketList(&ticketCount, ticketCount, 0,
                                  ^
/home/hle/.bin/devkitPro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c: In function 'task_install_cia':
source/ui/section/task.c:838:37: warning: passing argument 1 of 'AM_CancelCIAInstall' makes pointer from integer without a cast [-Wint-conversion]
                 AM_CancelCIAInstall(ciaHandle);
                                     ^
In file included from /home/hle/.bin/devkitPro/libctru/include/3ds.h:30:0,
                 from source/ui/section/task.c:8:
/home/hle/.bin/devkitPro/libctru/include/3ds/services/am.h:74:8: note: expected 'Handle * {aka long unsigned int *}' but argument is of type 'Handle {aka long unsigned int}'
 Result AM_CancelCIAInstall(Handle *ciaHandle);
        ^
In file included from /home/hle/.bin/devkitPro/libctru/include/3ds.h:13:0,
                 from source/ui/section/task.c:8:
source/ui/section/task.c:839:41: error: too few arguments to function 'AM_FinishCiaInstall'
             } else if(R_SUCCEEDED(res = AM_FinishCiaInstall(ciaHandle))) {
                                         ^
/home/hle/.bin/devkitPro/libctru/include/3ds/result.h:9:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
In file included from /home/hle/.bin/devkitPro/libctru/include/3ds.h:30:0,
                 from source/ui/section/task.c:8:
/home/hle/.bin/devkitPro/libctru/include/3ds/services/am.h:81:8: note: declared here
 Result AM_FinishCiaInstall(u8 mediatype, Handle *ciaHandle);
        ^
buildtools/make_base:270: recipe for target 'build/source/ui/section/task.o' failed
make: *** [build/source/ui/section/task.o] Error 1`

Any thoughts?

**Comment by Steveice10** [comment]
My [pull request](https://github.com/smealum/ctrulib/pull/261) has yet to be excepted, so for now you will need to use my fork of ctrulib.
