### ISSUE TITLE
Why is FBI So Slow?

### ISSUE THREAD

**Issue by OfficialBrony** [Steveice10/FBI#391]
I still use Shameless sometimes because it seems like it gets some games (even the newest ones) before FreeShop does. But man, FBI downloads the title so slowly. 
For example, I am downloading Minecraft for the 3DS and its just under 500MB for the game. I am supposed to get speeds up to 80mb/s (this is what I get on my PS4, laptop, PC, Wii U and Switch).
I have a software on my PC to check what devices are using the most bandwidth, using it whilst only my N3DSXL is connected to the Internet and downloading titles from the eShop. 
My N3DSXL downloads at about 40-60(ish)MB/s while downloading titles with FBI by scanning QR codes drops it to just 2.5mb/s (3 or 4 if lucky). 
I know it is not my Internet connection, nor is it the fact that I am far away from my Modem (I have other 1 gigabit routers expanding throughout my house to get fast Internet while my Modem is in the basement. 
I am on the newest version of FBI. I check for updates every few days and only update when there is an update avail.

**Comment by dogtopus** [comment]
Because Wifi NIC in 3DS sucks. Period.

**Comment by OfficialBrony** [comment]
Well, I get faster speeds downloading from the eShop than when I use FBI to download titles from QR codes from Shameless?

**Comment by dogtopus** [comment]
Don't know how you get 40-60MB/s download speed on a 3DS. Considering the hardware performance of a 3DS (SD card, Wifi, etc.) even 4-6MB/s would be considered really fast. Sure freeshop *is* a little bit faster than FBI but the difference is not that huge.

**Comment by Steveice10** [comment]
2.5 MB/s is pretty standard for a N3DS's top speed.

**Comment by OfficialBrony** [comment]
Lol
