### ISSUE TITLE
Installing specific game does not work

### ISSUE THREAD

**Issue by IngeniousDefault** [Steveice10/FBI#393]
Hi there.

I bought a Japanese game on the Nintendo eShop and created a CIA file with Godmode9. I wanted to install it again with FBI however I got the following error message.

Failed to install CIA file
Result code: 0xD8E08065
Level: Permanent (27)
Summary: Invalid argument (7)
Module: AM (32)
Desc: Error type -1 (101)

My setting:
Japanese 3DS (Old model)
FW: 11.6
FBI version 2.4.12 (3dsx and CIA)
Luma 8.1.1
boot9strap 1.2

**Comment by Steveice10** [comment]
Sounds like it might be a problem with your CIA, specifically the ticket part. Are you sure it's valid? If so, make sure your SD card filesystem is good and try completely removing both the app and its ticket from your previous installation.

**Comment by IngeniousDefault** [comment]
I re-downloaded the game from the eShop and used Godmode 9 again to get a new cia. It still does not work.

**Comment by Steveice10** [comment]
Do other CIAs work? Using a CIA generated exactly the same way doesn't really change anything.

**Comment by IngeniousDefault** [comment]
Yeah, other games like Metroid: Samus Returns and Miitopia do work.

**Comment by Steveice10** [comment]
I would say it probably has something to do with either a unique aspect of the game in question or a problem with the generated CIA, then.
