### ISSUE TITLE
[Feature Request] QR Scan 3DSX

### ISSUE THREAD

**Issue by TurtleP** [Steveice10/FBI#394]
Something useful to add would be the ability to scan a QR Code that contains a 3dsx and it would be written to the SD card under 3ds (or a step further and make the directory based on the filename and write it there).

**Comment by Steveice10** [comment]
As FBI is primarily a title manager, I don't really have plans to include 3DSX management functions.

**Comment by Steveice10** [comment]
Added. When determining the name to use for the folder and 3dsx file, it first checks for a Content-Disposition header in the HTTP response and tries to extract a file name from there. If that fails, it falls back on determining the file name from the URL.
