### ISSUE TITLE
Suggestion: FTP Client

### ISSUE THREAD

**Issue by kade-robertson** [Steveice10/FBI#397]
Currently the only existing FTP client is FileKong, which doesn't seem to work for FTPS or SFTP, and I would personally find it convenient to be able to browse an FTP server for CIAs and being able to copy between them for backups of saves, etc.

**Comment by urherenow** [comment]
1) there is no reason to need sftp for a 3ds. You transfer personal info back and forth?
2) have you even googled 3ds ftp? Never even heard of file Kong and I can name 3 clients off the top of my head.

**Comment by kade-robertson** [comment]
I'd love links for 3DS FTP clients that let you download files from an FTP server and to a 3DS. Key here being the 3DS is **not** a server. ftpd, FTP-3DS, FTPony, FTBrony, FTP-GMX, etc are all FTP servers, not clients.

**Comment by urherenow** [comment]
Ah... now I see what you want. Sounds like a completely separate project though, not a simple addition to FBI.

**Comment by Steveice10** [comment]
An FTP client would probably belong in a separate app, not FBI.
