### ISSUE TITLE
I can't install CIA's

### ISSUE THREAD

**Issue by GrouchMeister** [Steveice10/FBI#399]
FBI Boots up 
(I am running 11.3.0-36)
It runs then when I go to intsall free shop it brings this up 
Level: Permanent (27)
what does that mean****

**Comment by urherenow** [comment]
You need kernel access. Get b9s installed. Http://3ds.guide

**Comment by Steveice10** [comment]
I need the full error message, not just the level value.

**Comment by JorgeProGamer** [comment]
Hello Steve.

**Comment by crapthings** [comment]
i have b9s but i still can't install cia

because how to install ?  11.6.0.39u

**Comment by AzizBlooper** [comment]
Did u upgrade that b9s? Before update to 11.6

**Comment by crapthings** [comment]
@AzizBlooper  yes

**Comment by AzizBlooper** [comment]
Have you update luma too?

**Comment by crapthings** [comment]
yes ive followed all a9 to b9 guide

and i can enter godmode and luma

but no fbi，i cant install cia no homebrew launcher

**Comment by urherenow** [comment]
Huh? If you followed the guide you wouldn't have any problem. Use The Rosalina menu. Github isn't a support forum and I'm now 99.9% sure the problem is that you can't follow directions.

**Comment by crapthings** [comment]
@urherenow 

i can open Rosalina menu, but what next ?

**Comment by urherenow** [comment]
This. Is. NOT. a. support. forum.

Please close this and ask on gbatemp if you can't figure it out. Sounds like you can at least launch the homebrew launcher... did you use download play for that? You need to.

The 3dsx should go in a folder named the same exact way (caps matters)

3ds/fbi/fbi.3dsx

Or

3ds/FBI/FBI.3dsx

It would have been correct if you had just properly extracted the 3ds folder from the zip file...
