### ISSUE TITLE
1.4.2 turns to a black screen when resumed after returning to the Home Menu

### ISSUE THREAD

**Issue by Jaitsu** [Steveice10/FBI#4]
Title pretty much sums it up. If I open FBI, return to the Home Menu, and then resume it (without closing it), all text on-screen disappears, leaving two black screens. Can still return to the home menu and re-start it, though. Not sure whether or not it's still responding behind those black screens, but given the nature of the program I'd rather not experiment. 

(also - occasionally I run into an issue where it fails to boot in the first place, with a white dot blinking on the left of the top screen, and then it won't work until I reboot the 3DS, but I'll save reporting that one for when I know how to reliably repro it)

**Comment by Steveice10** [comment]
This is a known issue with ctrcommon's GPU code.

**Comment by Steveice10** [comment]
Fixed.
