### ISSUE TITLE
Error when installing .cia files

### ISSUE THREAD

**Issue by birdscool** [Steveice10/FBI#400]
Failed to install CIA file.
Result code: 0xD8E0806A
Level: Permanent (27)
Summary: Invalid argument (7)
Module: AM (32)
Desc: Cert signature or hash check failed (106)

N2DSXL, latest firmware, latest Luma, latest b9s, latest version of FBI. 30gb free on my SD card. I get this error for any .cia I try to install.

(apologies if this isn't the proper place for this kind of issue)

**Comment by Steveice10** [comment]
Could be a problem with your CIAs, or maybe your SD card? It can be difficult to pin down for certain why the AM service is rejecting a VIA.

Have you tried installing a CIA known to work? Perhaps FBI itself?

**Comment by birdscool** [comment]
Weird, older CIAs install properly. You're right that it's likely a problem with the CIAs, but it's strange that the last 5-6 CIAs I've downloaded (including homebrew) won't install. Not sure what's up with that.

Anyways, thank you. I'll find a workaround.

**Comment by Steveice10** [comment]
That is pretty weird. Maybe they're somehow getting corrupted when you copy them over to your SD card, perhaps due to filesystem errors? Whatever the cause, I hope you manage to get it working.
