### ISSUE TITLE
FBI fails to update

### ISSUE THREAD

**Issue by xavkno** [Steveice10/FBI#404]
I just tried to update FBI from version 2.4.9 but when i click update it say's:
Failed to check for update.
Result code: 0xD963F806
Level: Permanent (27)
Summary: Internal (11)
Module: Application (254)
Desc: Parse failed (6)

Any help would be appreciated,
Thank you in advance.

**Comment by Steveice10** [comment]
I think 2.4.9 might have been the version with broken updating. Just update manually by installing the latest CIA this time.

**Comment by lilcruz6ix9ine** [comment]
How do I fix this

**Comment by Nek** [comment]
+1

**Comment by urherenow** [comment]
@Nek @lil ruz6ix9ine download the latest release and install it. Want newer? Build it yourself. Either way, this is not a support forum, and you need to stop replying to CLOSED issues anyway. 6months ago this was closed. You seriously had to go out of your way just to be here.

**Comment by urherenow** [comment]
Dang phone keyboard... wanted to tag @lilcruz6ix9ine

**Comment by Nek** [comment]
No need to be rude. I even have an excuse. It was 4 in the morning. Having said that, I'm sorry and I didn't mean to piss you off. I'll pay extra attention not to post meaningless comments on the closed issues in the future.

**Comment by eclipsemod** [comment]
jerk@urherenow dood, theres no reason to be a rude jerk. He just asked a simple question. If the question annoys you so much why even bother??
