### ISSUE TITLE
Retry after download(install from CDN) failed ?

### ISSUE THREAD

**Issue by a5723797** [Steveice10/FBI#405]
Could it be possible to ask for a retry or cancel when a remote install download failed ? 
While installing from CDN, after the main part(relatively large) finished downloading, 
the next part (relatively small) occasionally failed due to unknown reason (network, server...etc).
And the only action we can take now is to give up all the done part and re-do the install (and re-download).
It will save a lot time(when the man part is large) if it's possible to ask for a retry or just to cancel,
in case the next step failed.
Could it be possible to add this function ? Thanks

**Comment by Steveice10** [comment]
I added a retry function, however unfortunately, all it did in CDN installations was throw immediate errors due to the previous failure. You have to redo the entire installation.
