### ISSUE TITLE
SUGGESTION: An decrypted and extracted version of FBI

### ISSUE THREAD

**Issue by IncognitoJoe** [Steveice10/FBI#406]
I only want this for ui updates... but I am pretty new to the haxing of the 3ds, and have tried a million and 10 times using this method --- https://gbatemp.net/threads/tutorial-how-to-decrypt-extract-rebuild-3ds-cia-cxi-files.383055/ --- but I only get the files in .bin format.... sorry for the struggle and I completely understand if you do not want to do it....

**Comment by dogtopus** [comment]
If you only want to modify the assets, just download them from this repository (I believe they are under the `romfs/` directory), modify as you wish, and put the modified assets under the `fbi/theme` directory on your 3ds sd card

**Comment by IncognitoJoe** [comment]
oh I will try that when I get home... I am at school

**Comment by IncognitoJoe** [comment]
Should I make that dir if I do not have it...
