### ISSUE TITLE
TLS error with Let's Encrypt certificate

### ISSUE THREAD

**Issue by connesc** [Steveice10/FBI#407]
I get the following error when trying to install a remote file over HTTPS if the TLS certificate has been issued by [Let's Encrypt](https://letsencrypt.org/):

```
Result code: 0xD8A0A03C
Level: Permanent (27)
Summary: Invalid state (5)
Module: HTTP (40)
Desc: Failed to verify TLS certificate (60)
```

Here is a test case to reproduce the error: [Checkpoint.3dsx](https://share.connesc.eu.org:30443/Bh1nTICZ/Checkpoint.3dsx)

![QR Code](https://user-images.githubusercontent.com/1195681/33254696-57b0e7b8-d34a-11e7-8ba5-cf998e795df2.png)

Maybe something is missing in the bundled certificate authorities?

**Comment by Steveice10** [comment]
I don't bundle certificate authorities, I just disable SSL verification: https://github.com/Steveice10/FBI/blob/master/source/core/util.c#L729

If it's still erroring, I can only assume the 3DS HTTP service doesn't like your SSL setup for some reason.

**Comment by connesc** [comment]
OK, I see. TLS is handled by the 3DS itself, which is [known to be incompatible](https://letsencrypt.org/docs/certificate-compatibility/#known-incompatible) with Let's Encrypt.
Thanks!
