### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Paper-Bart-Simpson** [Steveice10/FBI#409]
Despite your warning, i would like to know if your in the know about this stuff and if you could check occasionally. (PLZ DONT CLOSE TILL READING!!!!!!!)

**Comment by Steveice10** [comment]
If you want to make a suggestion, you can open an issue ticket for it. There doesn't need to be a single issue for suggestions to be posted in, assuming that's what you're trying to do as you didn't suggest anything yet.

**Comment by Paper-Bart-Simpson** [comment]
How?
