### ISSUE TITLE
Build Error!

### ISSUE THREAD

**Issue by tigerhu67** [Steveice10/FBI#41]
Hello Author:
       I got an issues when i build the lastest code:

Makefile:53: buildtools/make_base: No such file or directory
make: *** No rule to make target `buildtools/make_base'.  Stop.

it seems that there is no make_base file in the reslease version(both in1.4.17 and master)
counld you help me?

**Comment by urherenow** [comment]
Do you have the latest devkitArm installed properly?

**Comment by tigerhu67** [comment]
yes! 
[devkitARM]
Version=45
File=devkitARM_r45-i686-linux.tar.bz2

**Comment by dogtopus** [comment]
Please run `git submodule update --init` and try again

**Comment by tigerhu67** [comment]
@dogtopus  thank you very much!
but.....
a new error came. below:
--------------------------------------------------------------------------------
build/source/default.shbin.o
build/source/lodepng.o
build/source/main.o
build/source/screen.o
source/screen.c: In function 'screen_init':
source/screen.c:125:25: warning: implicit declaration of function 'fontEnsureMapped' [-Wimplicit-function-declaration]
     Result fontMapRes = fontEnsureMapped();
                         ^
source/screen.c:131:5: error: unknown type name 'TGLP_s'
     TGLP_s* glyphInfo = fontGetGlyphInfo();
     ^
source/screen.c:131:25: warning: implicit declaration of function 'fontGetGlyphInfo' [-Wimplicit-function-declaration]
     TGLP_s* glyphInfo = fontGetGlyphInfo();
                         ^
source/screen.c:131:25: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
source/screen.c:132:38: error: request for member 'nSheets' in something not a structure or union
     glyphSheets = calloc(1, glyphInfo->nSheets * sizeof(C3D_Tex));
                                      ^
source/screen.c:133:33: error: request for member 'nSheets' in something not a structure or union
     for(int i = 0; i < glyphInfo->nSheets; i++) {
                                 ^
source/screen.c:135:21: warning: implicit declaration of function 'fontGetGlyphSheetTex' [-Wimplicit-function-declaration]
         tex->data = fontGetGlyphSheetTex(i);
                     ^
source/screen.c:135:19: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
         tex->data = fontGetGlyphSheetTex(i);
                   ^
source/screen.c:136:44: error: request for member 'sheetFmt' in something not a structure or union
         tex->fmt = (GPU_TEXCOLOR) glyphInfo->sheetFmt;
                                            ^
source/screen.c:137:30: error: request for member 'sheetSize' in something not a structure or union
         tex->size = glyphInfo->sheetSize;
                              ^
source/screen.c:138:31: error: request for member 'sheetWidth' in something not a structure or union
         tex->width = glyphInfo->sheetWidth;
                               ^
source/screen.c:139:32: error: request for member 'sheetHeight' in something not a structure or union
         tex->height = glyphInfo->sheetHeight;
                                ^
source/screen.c: In function 'screen_get_string_size_internal':
source/screen.c:515:24: warning: implicit declaration of function 'fontGetInfo' [-Wimplicit-function-declaration]
     float h = scaleY * fontGetInfo()->lineFeed;
                        ^
source/screen.c:515:37: error: invalid type argument of '->' (have 'int')
     float h = scaleY * fontGetInfo()->lineFeed;
                                     ^
source/screen.c:536:44: error: invalid type argument of '->' (have 'int')
                 h += scaleY * fontGetInfo()->lineFeed;
                                            ^
source/screen.c:539:35: warning: implicit declaration of function 'fontGetCharWidthInfo' [-Wimplicit-function-declaration]
             lineWidth += scaleX * fontGetCharWidthInfo(fontGlyphIndexFromCodePo
                                   ^
source/screen.c:539:56: warning: implicit declaration of function 'fontGlyphIndexFromCodePoint' [-Wimplicit-function-declaration]
             lineWidth += scaleX * fontGetCharWidthInfo(fontGlyphIndexFromCodePo
                                                        ^
source/screen.c:539:90: error: invalid type argument of '->' (have 'int')
  += scaleX * fontGetCharWidthInfo(fontGlyphIndexFromCodePoint(code))->charWidth
                                                                     ^
source/screen.c: In function 'screen_draw_string':
source/screen.c:578:17: error: 'GLYPH_POS_CALC_VTXCOORD' undeclared (first use in this function)
     u32 flags = GLYPH_POS_CALC_VTXCOORD | (baseline ? GLYPH_POS_AT_BASELINE : 0
                 ^
source/screen.c:578:17: note: each undeclared identifier is reported only once for each function it appears in
source/screen.c:578:55: error: 'GLYPH_POS_AT_BASELINE' undeclared (first use in this function)
     u32 flags = GLYPH_POS_CALC_VTXCOORD | (baseline ? GLYPH_POS_AT_BASELINE : 0
                                                       ^
source/screen.c:591:44: error: invalid type argument of '->' (have 'int')
                 y += scaleY * fontGetInfo()->lineFeed;
                                            ^
source/screen.c:594:13: error: unknown type name 'fontGlyphPos_s'
             fontGlyphPos_s data;
             ^
source/screen.c:595:13: warning: implicit declaration of function 'fontCalcGlyphPos' [-Wimplicit-function-declaration]
             fontCalcGlyphPos(&data, fontGlyphIndexFromCodePoint(code), flags, s
             ^
source/screen.c:597:20: error: request for member 'sheetIndex' in something not a structure or union
             if(data.sheetIndex != lastSheet) {
                    ^
source/screen.c:598:33: error: request for member 'sheetIndex' in something not a structure or union
                 lastSheet = data.sheetIndex;
                                 ^
source/screen.c:602:35: error: request for member 'vtxcoord' in something not a structure or union
             draw_quad(currX + data.vtxcoord.left, y + data.vtxcoord.top, currX 
                                   ^
source/screen.c:602:59: error: request for member 'vtxcoord' in something not a structure or union
             draw_quad(currX + data.vtxcoord.left, y + data.vtxcoord.top, currX 
                                                           ^
source/screen.c:602:86: error: request for member 'vtxcoord' in something not a structure or union
 quad(currX + data.vtxcoord.left, y + data.vtxcoord.top, currX + data.vtxcoord.r
                                                                     ^
source/screen.c:602:111: error: request for member 'vtxcoord' in something not a structure or union
 d.left, y + data.vtxcoord.top, currX + data.vtxcoord.right, y + data.vtxcoord.b
                                                                     ^
source/screen.c:602:133: error: request for member 'texcoord' in something not a structure or union
 ord.top, currX + data.vtxcoord.right, y + data.vtxcoord.bottom, data.texcoord.l
                                                                     ^
source/screen.c:602:153: error: request for member 'texcoord' in something not a structure or union
 a.vtxcoord.right, y + data.vtxcoord.bottom, data.texcoord.left, data.texcoord.t
                                                                     ^
source/screen.c:602:172: error: request for member 'texcoord' in something not a structure or union
  + data.vtxcoord.bottom, data.texcoord.left, data.texcoord.top, data.texcoord.r
                                                                     ^
source/screen.c:602:193: error: request for member 'texcoord' in something not a structure or union
 om, data.texcoord.left, data.texcoord.top, data.texcoord.right, data.texcoord.b
                                                                     ^
source/screen.c:604:26: error: request for member 'xAdvance' in something not a structure or union
             currX += data.xAdvance;
                          ^
make: *** [build/source/screen.o] Error 1

**Comment by urherenow** [comment]
This is for issues with the software, not a support forum. Mind opening a thread on gbatemp?

**Comment by tigerhu67** [comment]
@urherenow  don't mind!

**Comment by Steveice10** [comment]
Make sure you have the latest ctrulib (for now from my fork, since my PR still hasn't been pulled) and citro3d.

**Comment by urherenow** [comment]
Was just about to say that since I built it myself. From the root of your projects folder (wherever you like to extract your source files) do a "git clone --recursive https://github.com/Steveice10/ctrulib", then "cd ctrulib", then "cd libctru", then "make install". Then you can build FBI.

But then if any other projects you use give you trouble, you'll have to reinstall the appropriate official release of ctrulib.
