### ISSUE TITLE
error downloading from qr code

### ISSUE THREAD

**Issue by samsnts** [Steveice10/FBI#412]
"Failed to install from URL.
https://api.titledb.com/v0/proxy/000400000F12EE00
Result code: 0xD8A0A3C
Level: Permanent (27)
Summary: Invalid state (5)
Module: HTTP (40)
Desc: Failed to verify TLS certificate (60)

same error while loading TitleDB

**Comment by Steveice10** [comment]
TitleDB is working fine for me. Likely a problem with your connection.
