### ISSUE TITLE
[Suggestion] Zip/Unzip file

### ISSUE THREAD

**Issue by fraf** [Steveice10/FBI#413]
Particularly useful for large amount of cia virtual console roms. Unzipping only before for installing.
Save lot of room on SDCard.

**Comment by james-d-elliott** [comment]
Does zipping actually save much space? I thought CIA's were already compressed pretty well.

**Comment by fraf** [comment]
234 cia files in a folder (~2,8GB) => the zipped folder ~1.4GB
Reduced by half.

It worths it

**Comment by legoj15** [comment]
But since it would have to unzip, wouldn't that make the size problem even worse? because now you have 1.4GB compressed + the 2.8GB that would be unzipped on the SD card

**Comment by fraf** [comment]
I unzip (and install) only one file.
I then keep the zip file and delete the unzipped one.

That's the idea.

**Comment by Steveice10** [comment]
Why not just only put a CIA file on your SD card when you're going to install it, then?

**Comment by fraf** [comment]
With 3DS we have to think mobility. No internet, no pc, no card reader.
SD Card is like my 3DS hard drive. Archive once, install/uninstall unlimited times.
Furthermore, n3ds is not suitable for sd card ejection (need screw drivers)

**Comment by Steveice10** [comment]
I don't think this is something I'm going to add. Too much added complexity for little benefit. You really should just install what you want to install and delete the CIAs off of your SD card afterwards.
