### ISSUE TITLE
[Feature Request] Option to not reinstall existing titles

### ISSUE THREAD

**Issue by Lesik** [Steveice10/FBI#414]
When selecting a whole folder for installation, it would be nice if already installed titles could be skipped. Not by default, but as an option.

That way you could have all your cia files in `cias/` and when you receive several new cias you can just put them in the same folder, and do a bulk installation of that folder, without having to wait for all the existing cias to be installed again.

Thank you.

**Comment by Steveice10** [comment]
I would recommend either putting the new CIAs in a separate directory or not keeping already-installed CIAs on your SD card, as it would just double the space each title takes up.
