### ISSUE TITLE
Internet access required for remote install option?

### ISSUE THREAD

**Issue by Jmelz** [Steveice10/FBI#415]
Does FBI require internet access to use the remote install features? Seems like methods of blocking internet access to the 3DS do not allow apps like BOOP to work with CIA transfers. The initial 'install from received URL' message works, showing the correct filename, but after selecting yes, the filesize never updates, and then an error code appears with the HTTP module for invalid state.

**Comment by Jmelz** [comment]
Rather not resort to methods like this: https://gbatemp.net/threads/update-regarding-the-recent-3ds-banwave.471781/page-291#post-7346389

Seems there should be some way to still have traffic without allowing internet traffic - or does the 3ds only allow traffic with successful repeated connection test pings or something similar?

**Comment by Steveice10** [comment]
It only needs to be able to connect to your PC. I think the 3DS in general has a problem with networks without Internet access.
