### ISSUE TITLE
[Bug] Error when Loading Home Menu during download

### ISSUE THREAD

**Issue by SirNapkin1334** [Steveice10/FBI#417]
When installing a CIA, if you are to press the HOME button, and suspend FBI (in latest release), after the menu loads it gives an arm11 error on the bottom screen, saying "The Game Cartridge was removed. Press any button to reboot." I'd assume this is the same error that appears on taking out a gamecart while playing on that cart.

**Comment by Steveice10** [comment]
Unable to reproduce on latest experimental branch source, so I'll just assume it's probably fixed?

**Comment by SirNapkin1334** [comment]
Perhaps, I'll check it again if I can.
