### ISSUE TITLE
Error while downloading omega ruby cia

### ISSUE THREAD

**Issue by fanboy23333** [Steveice10/FBI#418]
I trie downloading the hame but it says on the top screen
Name: Pokemon - Omega Ruby (EUR).cia
                   Attributes: None
Size 1.77 GiB
Version: 3072 (3.0.0)
Region: Region free
Installed size : 1.77 GiB
---------
Lower screen
---------
Failed to install cia file
Result code: 0xD8E0806A
Level: Permanent (27)
Summary: invalid argument (27)
Module: AM(32)
Desc : cert signature or hash check failed (106)

**Comment by fanboy23333** [comment]
Sorry for the spelling mistakes

**Comment by Steveice10** [comment]
Either you aren't in a CFW environment with signature checks patched, there's something wrong with your CIA, or there might be something wrong with your SD card.
