### ISSUE TITLE
Can't re install tickets after ctr tranfert and tickets copy

### ISSUE THREAD

**Issue by MysticTalion** [Steveice10/FBI#419]
Hey, I just did a ctr transfert to 11.5, so it put all my downloaded games and their saves, in gm9/out/ctrtansfert_tickets

When I tried to re install all the tickets from eshop and uknown folders, but after declining installing with the cdn, i'm supposed to re install them normally, I always get this error

Result code : 0xD8E08065
Level : Permanent (27)
Summary : Invalid argument(7)
Module : AM(32)
Desc : Error type -1 (101)

My console is an old 3ds cfw luma 3ds v9.0
Sysnand v11.6.0-39E
Even TikShop can't resolve my problem..

Can someone help me ?

**Comment by Steveice10** [comment]
Sorry for the delayed response. The only conclusion I can draw is that for whatever reason the AM service doesn't like your tickets, especially considering it happens with another app as well. Perhaps they're invalid?
