### ISSUE TITLE
Network Folder Disappeard

### ISSUE THREAD

**Issue by MattyMetroid** [Steveice10/FBI#422]
hi im on ver 116.39E and i have the latest firmware CFW fbi ver2.4.14
i recently installed the update and when i tried finding my ip the network folder has vanished.
i really need it to get my ip address..
please fix this issue

**Comment by urherenow** [comment]
in the meantime if you want to avoid reinstalling older versions, just keep an older .3dsx version. It wouldn't hurt to grab your MAC address from system settings and use it to assign a static IP in your router either.

**Comment by MattyMetroid** [comment]
Good idea :).
Yeah il stay away from old versions thank you.

**Comment by Steveice10** [comment]
If you are referring to the network installer, it is now the option to receive URLs over the network under "Remote Install".

**Comment by MattyMetroid** [comment]
Yeh I noticed that but I still cant see the Network Folder to see the ip

Sent from my Windows Phone
________________________________

**Comment by Steveice10** [comment]
When you select the option I mentioned, you should see your IP on screen like before.

**Comment by MattyMetroid** [comment]
Il try later an let you know.

Sent from my Windows Phone
________________________________
