### ISSUE TITLE
Text is too small in CHT devices

### ISSUE THREAD

**Issue by roytam1** [Steveice10/FBI#423]
CHT devices(Sell officially in Hong Kong and Taiwan) has smaller font size (20x24px) than others (25x30px) for more spaces to contain larger amount characters. (Source: converted bitmap from official cbf_zh-Hant-TW.bcfnt / cbf_std.bcfnt with ctr_FontConverter)

Possible solution to deal with such situation:
check width of "あ" with fontGetCharWidthInfo, CHT devices will return smaller value. Since ideograph is square, so normally width == height. (CHECK: does it return "24" in C/J/U/E? and does it return "19" in T?)
and then adjust scale factor before print.

Cross-post: 
https://github.com/BernardoGiordano/PKSM/issues/654
https://github.com/fincs/new-hbmenu/issues/35

![2018-01-08_23-54-05 481_top](https://user-images.githubusercontent.com/1192577/34679068-b76278d0-f48c-11e7-8e80-a8a781b7443d.png)
![2018-01-08_23-54-05 481_bot](https://user-images.githubusercontent.com/1192577/34679072-ba3f20f8-f48c-11e7-866d-f07f16d2d87c.png)

**Comment by fincs** [comment]
For reference, this is how I fixed it in new-hbmenu: https://github.com/fincs/new-hbmenu/commit/79e2e67edf04ed2484ef9a27b8175386f71f621f

**Comment by roytam1** [comment]
@Steveice10 I tried to fix it:

````
diff --git a/source/core/screen.c b/source/core/screen.c
index b5d9ece..3d95c21 100644
--- a/source/core/screen.c
+++ b/source/core/screen.c
@@ -25,6 +25,8 @@ static C3D_Mtx projection_bottom;

 static C3D_Tex* glyph_sheets;

+static float s_textScale;
+
 static u8 base_alpha = 0xFF;

 static u32 color_config[MAX_COLORS] = {0xFF000000};
@@ -158,6 +160,9 @@ void screen_init() {
         return;
     }

+       charWidthInfo_s* cwi = fontGetCharWidthInfo(fontGlyphIndexFromCodePoint(0x3042));
+       s_textScale = 20.0f / (cwi->glyphWidth); // 20 is glyphWidth in J machines
+
     for(int i = 0; i < glyphInfo->nSheets; i++) {
         C3D_Tex* tex = &glyph_sheets[i];
         tex->data = fontGetGlyphSheetTex(i);
@@ -562,6 +567,9 @@ static void screen_get_string_size_internal(float* width, float* height, const c
     float h = 0;
     float lineWidth = 0;

+       scaleX *= s_textScale;
+       scaleY *= s_textScale;
+
     if(text != NULL) {
         h = scaleY * fontGetInfo()->lineFeed;

@@ -653,6 +661,9 @@ static void screen_draw_string_internal(const char* text, float x, float y, floa

     int lastSheet = -1;

+       scaleX *= s_textScale;
+       scaleY *= s_textScale;
+
     const uint8_t* p = (const uint8_t*) text;
     const uint8_t* lastAlign = p;
     u32 code = 0;
````

and it looks better:
![t_atop](https://user-images.githubusercontent.com/1192577/34914859-3e849fca-f913-11e7-8998-8219a6eac832.png)
![t_bot](https://user-images.githubusercontent.com/1192577/34914860-3eafa666-f913-11e7-9585-470df46418b5.png)

**Comment by Steveice10** [comment]
@roytam1 Out of curiosity, why did you opt to use a different scale base and variable than the new-hbmemu solution? ("30 / cellHeight" instead of "25 / baselinePos")

**Comment by Steveice10** [comment]
Never mind, just found and read the latest posts on the new-hbmenu issue ticket.

**Comment by Steveice10** [comment]
Committed the fix, can you verify that the latest source works fine on your system?

**Comment by roytam1** [comment]
Fix confirmed, thanks!
