### ISSUE TITLE
Installs/upgrades/listed items have been reported as not sticking to entries.

### ISSUE THREAD

**Issue by ksanislo** [Steveice10/FBI#426]
Someone else mentioned it over on reddit, and I don't know the exact details. Can you take a look at things and figure out why FBI offered or installed a dupe title ID from an alternate project entry and see what you can do about maintaining a known state to prevent this in the future, be it by accident or someone intentionally using the bug to place malicious content where people will install it.

https://www.reddit.com/r/3dshacks/comments/7ui7fq/titledb_and_github_what_will_break_and_what_will/dtlr2c9/

**Comment by Steveice10** [comment]
I'm actually working on rewriting a bunch of the TitleDB code right now, which should resolve this problem. When I wrote the current code, I actually completely missed that there's an option to nest CIA/TDSX/etc inside entries, and that's been proving very helpful so far.

I've also been working on top support along with a solution for the Github TLS changes. It'll hopefully be coming very soon, time permitting.

**Comment by Steveice10** [comment]
@ksanislo Something I noticed while working on the new TitleDB code: for some reason there's an entry that's completely empty with ID 435.

**Comment by Steveice10** [comment]
Should be fixed in ongoing experimental branch. It's worth noting, though, that TitleDB for some reason has a lot of entries that don't contain any downloads, on top of that weird empty entry I mentioned before.

**Comment by ksanislo** [comment]
I'll look into the empty entries, as they should have been de-flagged as active when everything was removed from them.

Typically however, I'd think you want to pull the cia and 3dsx records and then just reference back to the entry fields to pick up the external data from them, as there's always going to be a probable entry which only contains file types which aren't supported by FBI at the time. If there's no CIA or other files, the entry should be disregarded as not applicable to the client.

**Comment by Steveice10** [comment]
Yeah, I'll probably add in a check to filter out entries without any supported files.
