### ISSUE TITLE
[Feature Request] Add ability to sort TitleDB by most recent update.

### ISSUE THREAD

**Issue by frozenLake** [Steveice10/FBI#428]
Homebr3w has this feature, and its currently the one thing that has me going back to that, instead of using FBI full time for all my homebrew downloading needs.

The relevant code in Homebr3w can be found at https://github.com/Wolvan/Homebr3w/blob/master/script/index.lua#L144 if that helps at all.

**Comment by Steveice10** [comment]
Added to experimental branch.
