### ISSUE TITLE
TLS 1.1 expires Thursday 2/22 - This will break most titleDB downloads

### ISSUE THREAD

**Issue by zoogie** [Steveice10/FBI#429]
https://gbatemp.net/threads/release-fbi-open-source-cia-installer.386433/page-202#post-7843530
Just trying to give you a heads up about this.

**Comment by Steveice10** [comment]
Already aware of this. TitleDB should be fine as the author plans to proxy downloads. However, the built-in updater and any QR/URL downloads will not work, at least for the time being.

**Comment by zoogie** [comment]
It's exactly how you said: FBI update broken, titleDB still works. 
The nice thing about that is you can just update FBI through titleDB : )

**Comment by Steveice10** [comment]
Yeah, I've been thinking about just changing the updater to pull from TitleDB.

**Comment by Steveice10** [comment]
Updater should work again after the next release.

**Comment by gingerbeardman** [comment]
Argh! I hadn't updated in a while, so now I guess I'll have to take out my SD and update manually by copying files?
