### ISSUE TITLE
Hangs on Title list

### ISSUE THREAD

**Issue by dogtopus** [Steveice10/FBI#43]
When I tried to open Title list, FBI tried to load all the titles installed on my 3DS, and will eventually hang before the loading was finished.

**Comment by Steveice10** [comment]
If you're referring to the rewrite, this is known.

**Comment by dogtopus** [comment]
@Steveice10 Yes, I mean the rewrite

**Comment by mariogamer2** [comment]
Me too

**Comment by Steveice10** [comment]
Fixed.
