### ISSUE TITLE
update available to lower version

### ISSUE THREAD

**Issue by Nuck-TH** [Steveice10/FBI#431]
For example for FBI 2.5.0 itself - it shows that there is update, but version on TitleDB is 2.4.14

**Comment by Steveice10** [comment]
Will look into it when I get the chance tomorrow.

**Comment by Steveice10** [comment]
Oh, are you talking about on the TitleDB list? That's because you have to install from TitleDB for it to update the cache with the latest CIA/3DSX ID.
