### ISSUE TITLE
Feature Request: Ability to sort titles in TitleDB by installed and/or by Update Available

### ISSUE THREAD

**Issue by Nomelas** [Steveice10/FBI#433]

**Comment by legoj15** [comment]
I feel like this (or something similar) has been suggested before and was put off for some reason or another, but I could be mistaken.

**Comment by suzsuzuki** [comment]
Just to add to this feature, I suggest an option to mark any/all installed homebrew as the latest ones, to avoid download all homebrew again from titledb (I have more than 50 installed)

**Comment by Steveice10** [comment]
Both suggestions have been implemented.
