### ISSUE TITLE
titledb issue

### ISSUE THREAD

**Issue by suzsuzuki** [Steveice10/FBI#434]
![20180227_192132](https://user-images.githubusercontent.com/20933693/36759112-1ff8b4f6-1bf5-11e8-9ec6-5ac6ca0bb158.jpg)
Titledb option shows all version you installed and not only the latest one like the previous version of FBI. I don't know if it is fixed with the last commits.

**Comment by Steveice10** [comment]
See https://github.com/Steveice10/FBI/issues/432
