### ISSUE TITLE
fbi.firm

### ISSUE THREAD

**Issue by thomleg50** [Steveice10/FBI#437]
hi,
can you create a .firm version of FBI to boot and install cia from ntrboot

THanks you in advance

**Comment by urherenow** [comment]
AFAIK, you can’t run FBI on arm 9 alone

**Comment by Steveice10** [comment]
Yeah, FBI is an ARM11 userland application.

**Comment by thomleg50** [comment]
thanks you for your help but if a day there a way to install cia via ntrboot, call me !!!
