### ISSUE TITLE
Unable to install cias

### ISSUE THREAD

**Issue by ruckus71472** [Steveice10/FBI#439]
`Result code : 0xD8A0A03C`
`Level : Permanent (27)`
`Summary : Invaild state (5)`
`Module : HTTP (40)`
`Desc : Failed to verify TLS certificate (60)`
Strangely, when I try to install a cia from a qr code or a url, just gives me the error above.  I tryed empty by sd card and used title db. However , using titletb, i couldn't find the latest version of cia. Is this a bug pr a fixable problem?

**Comment by legoj15** [comment]
This is due to the fact that GitHub dropped TLS 1.1 support which is what pretty much every QR code uses. The person who hosts the QR code will have to upload the CIA to a server that supports TLS 1.1 AFAIK

**Comment by ruckus71472** [comment]
Thanks!
