### ISSUE TITLE
incomplete push?

### ISSUE THREAD

**Issue by urherenow** [Steveice10/FBI#44]
There seems to be missing files in the latest commit:

X:\devkitPro\devkitARM\projects\FBI>make
build/source/default.shbin.c
process_begin: CreateProcess(NULL, /x/devkitPro/devkitARM/bin/picasso -o build/source/default.shbin source/default.v.pica, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [build/source/default.shbin.c] Error 2

**Comment by Steveice10** [comment]
I see no indication of missing files. Do you have a version of devkitARM with picasso included, and are your environment variables properly set?

**Comment by urherenow** [comment]
I have r45 installed, and there is a picasso binary in devkitARM/bin. But there is no default.shbin.c in your repo...

**Comment by urherenow** [comment]
Oh wait... It's using default.v.pica for that... I see no new devkitARM release. Can I simply run the current updater again?

**Comment by Steveice10** [comment]
If picasso is there, that shouldn't be the issue... something seems to be causing it to not find the picasso binary, in any case.

**Comment by urherenow** [comment]
It's definitely in my path:

X:\devkitPro\devkitARM\projects\FBI>picasso
picasso: no input files are specified
Usage: picasso [options] files...
Options:
  -o, --out=<file>        Specifies the name of the SHBIN file to generate
  -h, --header=<file>     Specifies the name of the header file to generate

X:\devkitPro\devkitARM\projects\FBI>make
build/source/default.shbin.c
process_begin: CreateProcess(NULL, /x/devkitPro/devkitARM/bin/picasso -o build/source/default.shbin source/default.v.pica, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [build/source/default.shbin.c] Error 2

**Comment by giveup** [comment]
same build problem.
make: *** [build/source/ui/section/task.o] Error 1
rm build/source/default.shbin.c
there is no task.o file!
some env info
picasso -v
picasso 2.4.0 - Built on Apr  3 2016 01:01:06
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/opt/devkitpro/devkitARM/bin

**Comment by Steveice10** [comment]
@urherenow Is picasso in the exact path that make is trying to use it from, though?

@giveup task.o is the file being created. Is there no error before that?

**Comment by urherenow** [comment]
@Steveice10 sure is. -> X:\devkitPro\devkitARM\bin\picasso.exe

I didn't have trouble building this during your last release. Don't have trouble building anything else. My environment is set up correctly.

**Comment by Steveice10** [comment]
Can you try manually running the command with the shader files, then?

**Comment by urherenow** [comment]
X:\devkitPro\devkitARM\projects\FBI>picasso -o build/source/default.shbin source/default.v.pica

This works to build default.shbin. Don't know what to do after that... Windows doesn't like your make_base, I guess :(

**Comment by Steveice10** [comment]
Two things, then:
* Try removing the "@" at the beginning of [this line](https://github.com/Steveice10/buildtools/blob/master/make_base#L200), and see what commands it prints to the console.
* Try using the *exact* command from the make process; down to the exact executable path, with directories and all.

**Comment by urherenow** [comment]
does no good because it fails at the same spot. Look at my error again... isn't it shbin.c that isn't found? There is no file anywhere in the tree with shbin in the name at all (until I manually made default.shbin).

**Comment by Steveice10** [comment]
It should at least print the command its trying to run before it fails. And no, the name printed out is the file being *made*, not the one its using.

picasso is executed to create build/source/default.shbin from source/default.v.pica, which is then turned into build/source/default.shbin.c, which is then compiled to default.shbin.o.

**Comment by urherenow** [comment]
can't figure out the command to go from default.shbin to default.shbin.c. Typing make  won't show that because it's still trying to make default.shbin and failing (even though manually typing that command works).

**Comment by Steveice10** [comment]
That's related to the internals of the make command, not the Makefile. The command to go from default.shbin to default.shbin.c is here: https://github.com/Steveice10/buildtools/blob/master/make_base#L189

**Comment by urherenow** [comment]
Solved! Had to update to gnu make 4.1 (using 64bit make at the moment. I was previously using gnu 32 make version 3.81, and perhaps most people following tutorials are as well. Downloaded from -> http://www.equation.com/servlet/equation.cmd?fa=make

if you'd like to add a note. Sorry for the trouble :P

**Comment by giveup** [comment]
@Steveice10 
full  log

make clean
Cleaned.

make 
build/source/default.shbin.c
build/source/default.shbin.o
build/source/lodepng.o
build/source/main.o
build/source/screen.o
build/source/util.o
build/source/libkhax/demo/main.o
build/source/ui/error.o
build/source/ui/list.o
build/source/ui/mainmenu.o
build/source/ui/progressbar.o
build/source/ui/prompt.o
build/source/ui/ui.o
build/source/ui/section/extsavedata.o
build/source/ui/section/files.o
build/source/ui/section/networkinstall.o
build/source/ui/section/pendingtitles.o
build/source/ui/section/systemsavedata.o
build/source/ui/section/task.o
In file included from /opt/devkitpro/libctru/include/3ds.h:13:0,
                 from source/ui/section/task.c:8:
source/ui/section/task.c: In function 'task_load_titles':
source/ui/section/task.c:328:34: warning: implicit declaration of function 'AM_GetTitleList' [-Wimplicit-function-declaration]
             if(R_SUCCEEDED(res = AM_GetTitleList(&titleCount, mediaType, titleCount, titleIds))) {
                                  ^
/opt/devkitpro/libctru/include/3ds/result.h:9:30: note: in definition of macro R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c:333:42: warning: implicit declaration of function 'AM_GetTitleInfo' [-Wimplicit-function-declaration]
                     if(R_SUCCEEDED(res = AM_GetTitleInfo(mediaType, titleCount, titleIds, titleInfos))) {
                                          ^
/opt/devkitpro/libctru/include/3ds/result.h:9:30: note: in definition of macro R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c: In function 'task_load_pending_titles':
source/ui/section/task.c:453:26: warning: implicit declaration of function 'AM_GetPendingTitleCount' [-Wimplicit-function-declaration]
     if(R_SUCCEEDED(res = AM_GetPendingTitleCount(&pendingTitleCount, mediaType, AM_STATUS_MASK_INSTALLING | AM_STATUS_MASK_AWAITING_FINALIZATION))) {
                          ^
/opt/devkitpro/libctru/include/3ds/result.h:9:30: note: in definition of macro R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c:453:81: error: 'AM_STATUS_MASK_INSTALLING' undeclared (first use in this function)
     if(R_SUCCEEDED(res = AM_GetPendingTitleCount(&pendingTitleCount, mediaType, AM_STATUS_MASK_INSTALLING | AM_STATUS_MASK_AWAITING_FINALIZATION))) {
                                                                                 ^
/opt/devkitpro/libctru/include/3ds/result.h:9:30: note: in definition of macro R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c:453:81: note: each undeclared identifier is reported only once for each function it appears in
     if(R_SUCCEEDED(res = AM_GetPendingTitleCount(&pendingTitleCount, mediaType, AM_STATUS_MASK_INSTALLING | AM_STATUS_MASK_AWAITING_FINALIZATION))) {
                                                                                 ^
/opt/devkitpro/libctru/include/3ds/result.h:9:30: note: in definition of macro R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c:453:109: error: 'AM_STATUS_MASK_AWAITING_FINALIZATION' undeclared (first use in this function)
     if(R_SUCCEEDED(res = AM_GetPendingTitleCount(&pendingTitleCount, mediaType, AM_STATUS_MASK_INSTALLING | AM_STATUS_MASK_AWAITING_FINALIZATION))) {
                                                                                                             ^
/opt/devkitpro/libctru/include/3ds/result.h:9:30: note: in definition of macro R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c:456:34: warning: implicit declaration of function 'AM_GetPendingTitleList' [-Wimplicit-function-declaration]
             if(R_SUCCEEDED(res = AM_GetPendingTitleList(&pendingTitleCount, pendingTitleCount, mediaType, AM_STATUS_MASK_INSTALLING | AM_STATUS_MASK_AWAITING_FINALIZATION, pendingTitleIds))) {
                                  ^
/opt/devkitpro/libctru/include/3ds/result.h:9:30: note: in definition of macro R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c:459:17: error: unknown type name 'AM_PendingTitleEntry'
                 AM_PendingTitleEntry* pendingTitleInfos = (AM_PendingTitleEntry*) calloc(pendingTitleCount, sizeof(AM_PendingTitleEntry));
                 ^
source/ui/section/task.c:459:60: error: 'AM_PendingTitleEntry' undeclared (first use in this function)
                 AM_PendingTitleEntry* pendingTitleInfos = (AM_PendingTitleEntry*) calloc(pendingTitleCount, sizeof(AM_PendingTitleEntry));
                                                            ^
source/ui/section/task.c:459:81: error: expected expression before ')' token
                 AM_PendingTitleEntry* pendingTitleInfos = (AM_PendingTitleEntry*) calloc(pendingTitleCount, sizeof(AM_PendingTitleEntry));
                                                                                 ^
In file included from /opt/devkitpro/libctru/include/3ds.h:13:0,
                 from source/ui/section/task.c:8:
source/ui/section/task.c:461:42: warning: implicit declaration of function 'AM_GetPendingTitleInfo' [-Wimplicit-function-declaration]
                     if(R_SUCCEEDED(res = AM_GetPendingTitleInfo(pendingTitleCount, mediaType, pendingTitleIds, pendingTitleInfos))) {
                                          ^
/opt/devkitpro/libctru/include/3ds/result.h:9:30: note: in definition of macro R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c:475:81: error: request for member 'version' in something not a structure or union
                                 pendingTitleInfo->version = pendingTitleInfos[i].version;
                                                                                 ^
In file included from /opt/devkitpro/libctru/include/3ds.h:13:0,
                 from source/ui/section/task.c:8:
source/ui/section/task.c: In function 'task_load_tickets':
source/ui/section/task.c:533:26: warning: implicit declaration of function 'AM_GetTicketCount' [-Wimplicit-function-declaration]
     if(R_SUCCEEDED(res = AM_GetTicketCount(&ticketCount))) {
                          ^
/opt/devkitpro/libctru/include/3ds/result.h:9:30: note: in definition of macro R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c:536:34: warning: implicit declaration of function 'AM_GetTicketList' [-Wimplicit-function-declaration]
             if(R_SUCCEEDED(res = AM_GetTicketList(&ticketCount, ticketCount, 0, ticketIds))) {
                                  ^
/opt/devkitpro/libctru/include/3ds/result.h:9:30: note: in definition of macro R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
source/ui/section/task.c: In function 'task_install_cia':
source/ui/section/task.c:844:37: warning: passing argument 1 of 'AM_CancelCIAInstall' makes pointer from integer without a cast [-Wint-conversion]
                 AM_CancelCIAInstall(ciaHandle);
                                     ^
In file included from /opt/devkitpro/libctru/include/3ds.h:30:0,
                 from source/ui/section/task.c:8:
/opt/devkitpro/libctru/include/3ds/services/am.h:74:8: note: expected 'Handle * {aka long unsigned int *}' but argument is of type 'Handle {aka long unsigned int}'
 Result AM_CancelCIAInstall(Handle *ciaHandle);
        ^
In file included from /opt/devkitpro/libctru/include/3ds.h:13:0,
                 from source/ui/section/task.c:8:
source/ui/section/task.c:845:41: error: too few arguments to function 'AM_FinishCiaInstall'
             } else if(R_SUCCEEDED(res = AM_FinishCiaInstall(ciaHandle))) {
                                         ^
/opt/devkitpro/libctru/include/3ds/result.h:9:30: note: in definition of macro R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)>=0)
                              ^
In file included from /opt/devkitpro/libctru/include/3ds.h:30:0,
                 from source/ui/section/task.c:8:
/opt/devkitpro/libctru/include/3ds/services/am.h:81:8: note: declared here
 Result AM_FinishCiaInstall(u8 mediatype, Handle *ciaHandle);
        ^
make: *** [build/source/ui/section/task.o] Error 1
rm build/source/default.shbin.c

libctru is up to date.

**Comment by Steveice10** [comment]
Build from my ctrulib fork. My pull request still hasn't been accepted for some reason.

**Comment by urherenow** [comment]
No, you myst use @Steveice10 's fork of ctrulib.

**Comment by urherenow** [comment]
Sorry... Ninjad. Using from my phone sucks...

**Comment by giveup** [comment]
@Steveice10 
aleady replace your libctru fork,but still failed to build.
build/source/libctru/source/services/ac.o
build/source/libctru/source/services/am.o
source/libctru/source/services/am.c:40:25: error: unknown type name 'FS_MediaType'
 Result AM_GetTitleCount(FS_MediaType mediatype, u32 *count)
                         ^
source/libctru/source/services/am.c:55:41: error: unknown type name 'FS_MediaType'
 Result AM_GetTitleList(u32* titlesRead, FS_MediaType mediatype, u32 titleCount, u64 *titleIds)
                                         ^
source/libctru/source/services/am.c:73:24: error: unknown type name 'FS_MediaType'
 Result AM_GetTitleInfo(FS_MediaType mediatype, u32 titleCount, u64 *titleIds, AM_TitleEntry *titleInfo)
                        ^
source/libctru/source/services/am.c:123:44: error: unknown type name 'FS_MediaType'
 Result AM_GetPendingTitleCount(u32 *count, FS_MediaType mediatype, u32 statusMask)
                                            ^
source/libctru/source/services/am.c:139:64: error: unknown type name 'FS_MediaType'
 Result AM_GetPendingTitleList(u32 *titlesRead, u32 titleCount, FS_MediaType mediatype, u32 statusMask, u64 *titleIds)
                                                                ^
source/libctru/source/services/am.c:158:47: error: unknown type name 'FS_MediaType'
 Result AM_GetPendingTitleInfo(u32 titleCount, FS_MediaType mediatype, u64 *titleIds, AM_PendingTitleEntry *titleInfo)
                                               ^
source/libctru/source/services/am.c:158:86: error: unknown type name 'AM_PendingTitleEntry'
 Result AM_GetPendingTitleInfo(u32 titleCount, FS_MediaType mediatype, u64 *titleIds, AM_PendingTitleEntry *titleInfo)
                                                                                      ^
source/libctru/source/services/am.c:190:27: error: unknown type name 'FS_MediaType'
 Result AM_StartCiaInstall(FS_MediaType mediatype, Handle *ciaHandle)
                           ^
source/libctru/source/services/am.c:219:8: error: conflicting types for 'AM_CancelCIAInstall'
 Result AM_CancelCIAInstall(Handle ciaHandle)
        ^
In file included from source/libctru/source/services/am.c:8:0:
/opt/devkitpro/libctru/include/3ds/services/am.h:74:8: note: previous declaration of 'AM_CancelCIAInstall' was here
 Result AM_CancelCIAInstall(Handle *ciaHandle);
        ^
source/libctru/source/services/am.c:233:8: error: conflicting types for 'AM_FinishCiaInstall'
 Result AM_FinishCiaInstall(Handle ciaHandle)
        ^
In file included from source/libctru/source/services/am.c:8:0:
/opt/devkitpro/libctru/include/3ds/services/am.h:81:8: note: previous declaration of 'AM_FinishCiaInstall' was here
 Result AM_FinishCiaInstall(u8 mediatype, Handle *ciaHandle);
        ^
source/libctru/source/services/am.c:247:23: error: unknown type name 'FS_MediaType'
 Result AM_DeleteTitle(FS_MediaType mediatype, u64 titleID)
                       ^
source/libctru/source/services/am.c:262:26: error: unknown type name 'FS_MediaType'
 Result AM_DeleteAppTitle(FS_MediaType mediatype, u64 titleID)
                          ^
source/libctru/source/services/am.c:291:30: error: unknown type name 'FS_MediaType'
 Result AM_DeletePendingTitle(FS_MediaType mediatype, u64 titleId)
                              ^
source/libctru/source/services/am.c:306:31: error: unknown type name 'FS_MediaType'
 Result AM_DeletePendingTitles(FS_MediaType mediatype, u32 flags)
                               ^
source/libctru/source/services/am.c:320:34: error: unknown type name 'FS_MediaType'
 Result AM_DeleteAllPendingTitles(FS_MediaType mediatype)
                                  ^
source/libctru/source/services/am.c:358:31: error: unknown type name 'FS_MediaType'
 Result AM_GetTitleProductCode(FS_MediaType mediatype, u64 titleId, char *productCode)
                               ^
source/libctru/source/services/am.c:376:45: error: unknown type name 'FS_MediaType'
 Result AM_GetTitleExtDataId(u64 *extDataId, FS_MediaType mediatype, u64 titleId)
                                             ^
source/libctru/source/services/am.c:393:26: error: unknown type name 'FS_MediaType'
 Result AM_GetCiaFileInfo(FS_MediaType mediatype, AM_TitleEntry *titleEntry, Handle fileHandle)
                          ^
make: *** [build/source/libctru/source/services/am.o] Error 1
rm build/source/default.shbin.c build/source/libctru/data/default_font.bin.c
which dependency or lib is wrong？
sorry for my bad English.

**Comment by Steveice10** [comment]
I would try completely removing your current install of ctrulib and building again.

**Comment by urherenow** [comment]
How did you replace the fork? Did you clone it, make, then "make install"?
