### ISSUE TITLE
FBI's TitleDB Listing lists incorrect update dates.

### ISSUE THREAD

**Issue by frozenLake** [Steveice10/FBI#440]
Well, the dates might be partially correct, but I digress: The date given for a listing is not equal to the dates given for the CIA/3DSX versions. Thus, when looking for updates, you will be unable to see the actual update date, unless you go into the listings to doublecheck the dates on the downloads manually.

**Comment by Steveice10** [comment]
The dates given are the dates on the TitleDB server.
