### ISSUE TITLE
Cant instal cias

### ISSUE THREAD

**Issue by SwaggyMudkip69** [Steveice10/FBI#442]
In the past my n3ds xl has not been able to read ANY sd card so i put it aside, but today i randomly opened it and my cias and my custom theme had loaded so i got excited and took out my sd card and put it i my pc to update my old files, when i put my sd card back into my n3ds I booted up the 3dsx FBI and went to install the cias, but it failed and gave this error
```
Failed to install CIA file.
Result Code: 0xC92044FA
Level: Status (25)
Summary: Cancled (9)
Module: FS (17)
Desc: FAT operation denied (250)
```
What does this mean and is there a fix?

EDIT: I am on latest firmware, luma3ds, b9s, and FBI

**Comment by deadair3210** [comment]
If I'm not mistaken, FAT operation denied means that for some reason the console couldn't write to the SD card.

**Comment by Steveice10** [comment]
Yeah, seems to be a SD card or SD filesystem issue.
