### ISSUE TITLE
Invalid ncch/Invalid size

### ISSUE THREAD

**Issue by deathavis12** [Steveice10/FBI#443]
I have been searching for a few days now to an answer to these issues please help

Failed to install from url
Https://3ds.titledb.com/v1/cia/169/...
Result code: 0xD8E08025
Level: permanent (27)
Summary: invalid argument (7)
Module: AM (32)
Desc: invalid NCCH (37)

**Comment by deathavis12** [comment]
Secondary error

Failed to install from url
Https://3ds.titledb.com/v1/cia/169/
Result code:0xE0E083EC
Summary: invalid argument (7)
Module: AM (32)
Desc: invalid size (1004)

**Comment by Steveice10** [comment]
Does this happen with every CIA from TitleDB, or just that one?

**Comment by deathavis12** [comment]
Every cia from titledb does both errors the first error being the ncch and when I retry after that it gives invalid size

**Comment by Steveice10** [comment]
According to other reports of this error, the problem may be your SD card. Make sure it isn't a counterfeit, try running a filesystem check on it, and if possible, try installing with a different SD card inserted.

**Comment by deathavis12** [comment]
Side note I'm using a 2ds on latest firmware luma3ds and bs9

**Comment by deathavis12** [comment]
It is the sd card thanks for the help
