### ISSUE TITLE
building fails on latest devkitpro (v2.2.0)

### ISSUE THREAD

**Issue by annson24** [Steveice10/FBI#446]
also, 3ds_portlibs is now deprecated by latest devkitpro.

EDIT: tied reverting back to v2.1.0, re-installed janssen but seems lik compiling still results with 

/bin/sh: bannertool: command not found

**Comment by Steveice10** [comment]
I'll look into this new version of devkitPro. With regards to building on the old version, you need to have a copies of bannertool and makerom installed to your PATH now.

**Comment by Steveice10** [comment]
jansson has just been added to the new devkitPro pacman repository. Building FBI should work on the latest devkitPro if you install 3ds-zlib and 3ds-jansson and put copies of bannertool and makerom in your PATH.
