### ISSUE TITLE
Failed to install CIA file.

### ISSUE THREAD

**Issue by MeIsZ** [Steveice10/FBI#448]
Failed to install CIA file.
Result code: 0xC92044EB
Level: Status (25)
Summary: Canceled (9)
Module: FS (17)
Desc: unknown (235)

**Comment by MeIsZ** [comment]
This is on my end I'm pretty sure

**Comment by Steveice10** [comment]
If it's an FS error, I would run a filesystem check on your SD card, and maybe try a different SD card if possible.
