### ISSUE TITLE
[Request] Load title names from external file

### ISSUE THREAD

**Issue by micah686** [Steveice10/FBI#45]
I would like you to add support for loading the names of games from an external file, such as the 3dsdb.com XML list. This would make it a lot easier to find the title in a list of games from the sd card, instead of having to find what titleid coresssponds to what game.

If implemented, it would also be nice to be able to load names of system titles/homebrew from an xml as well, which would make it a lot easier to find the title that you needed.

**Comment by Steveice10** [comment]
The rewrite already has support for showing titles from the SMDH, whenever it ends up finished.
