### ISSUE TITLE
Support TLSv1.2

### ISSUE THREAD

**Issue by noirscape** [Steveice10/FBI#450]
With various recent homebrew fixing the TLS issues (notably lumaupdater and multiupdater), it kinda stands out that at the moment, FBI doesn't support downloading from TLSv1.2 urls.

While the original concern was raised with TitleDB, the fix that is currently in place both heavily strains the TitleDB servers and doesn't 'fix' the problem that at the moment it is impossible to install with QR codes from TLSv1.2 urls.

I would like to ask/suggest adding TLSv1.2 support to FBI.

**Comment by Steveice10** [comment]
This has been tried before, but it's simply too slow, which is especially bad for larger CIA downloads. If someone can present a solution that's proven to work quickly, I'd be happy to include it.

**Comment by majuss** [comment]
https://github.com/KunoichiZ/lumaupdate/commit/aff02a9caa962c66657f0571de7f1e0c3ab7bbfe

In this commit, the Lumaupdater got TLS 1.2 support. Maybe it helps.

**Comment by Steveice10** [comment]
Looks like it would be very inefficient for larger downloads that can't fit in memory.

I do have a plan for how I might tackle this problem, once I get around to it. Probably sometime this summer.

**Comment by c-schuhmann** [comment]
I don't know If this could help, but BernardoGiordano released a new QR Code scanner and CIA downloader named QRaken, which is compatible with TLS1.2. I don't have an link for it atm but the source is hosted on GitHub.

**Comment by majuss** [comment]
Here it is: https://github.com/BernardoGiordano/QRaken

**Comment by Steveice10** [comment]
Yes, I am aware of this. No, it does not help. All solutions so far are using curl, which I already tried, and have the same limitations.

**Comment by 916253** [comment]
Have there been any more developments on this in more recent times?

**Comment by Steveice10** [comment]
Not yet; I still haven't gotten around to working on it.

**Comment by BernardoGiordano** [comment]
Too many people are reporting FBI TLS issues in the wrong places and troubleshooting has become really painful since. I would suggest releasing a patch supporting curl, even if it's slow. Slow is better than not working at all.

**Comment by Steveice10** [comment]
This issue is still open because I would ultimately like to see TLS 1.2 support in FBI eventually, but I've simply been unable to find the time and willpower to go about the task of implementing it properly. Given that the built-in HTTP stack can be queried to get data on-demand, versus curl's requirement of a write callback that can receive data at any time, changing how installation works to add curl support is not a particularly quick change to make, especially if I want them to be side-by-side for faster non-1.2 downloads.

Where exactly are people reporting these issues to, and why?

**Comment by BernardoGiordano** [comment]
First of all, I'm sorry if that felt entitled or anything, but I was just pissed off by the multiple 'issue reports' in my troubleshooting channels. Anyways, I understand time issues so we'll patiently wait.

Anyways, I collected last week's reports from my Discord server here. This happens almost daily and I would bet some bucks it happens in other developers channels too

![](https://i.imgur.com/bOpq85z.png)

**Comment by Steveice10** [comment]
Ah, so it's people trying to scan a QR code for something unrelated using FBI. Yeah, I'll see if I can finally get it done sometime during the next two weeks, if possible.

**Comment by imPRAGMA** [comment]
Also we cant update FBI now because of this (incase you don't realize)

**Comment by NovaPhoenix** [comment]
Now that titledb support has been removed, I think that it would be a very good idea to implement TLSv1.2 so self updates would actually work, as well as installing third party homebrew CIAs

**Comment by Steveice10** [comment]
Yes, this is still in my plans.

**Comment by Steveice10** [comment]
Update: Work has begun in the curl branch.

https://github.com/Steveice10/FBI/commit/0b259d900eb744cac8809168c1b551599c8e12ff

**Comment by mariohackandglitch** [comment]
May or may not help, but I'll post it here anyways: https://github.com/mariohackandglitch/CTGP-7_Launcher/blob/master/source/updater.c#L208-L307

With this implementation I get an average of 300KB/sec
I really hope you find a better implementation for it that is faster!

**Comment by Steveice10** [comment]
Seems to be working now, so here's a test build for anyone who wants to try it out and report bugs: https://www.dropbox.com/s/g0dhgxemff9pkng/FBI.zip?dl=1

Speeds for me are currently hovering around ~80kb/s, so I'd also like to know how fast it downloads for others. Note that only TLSv1.2 downloads (such as from GitHub) apply; otherwise, it will continue to use the 3DS's built-in HTTP stack.

**Comment by Steveice10** [comment]
Updated with some quality-of-life improvements, same link as before. Speeds seem to be the same, though. Notably, even if I comment out all the code in my write callback or change the CPU speed setting through Rosalina, the download speeds remain the same...

**Comment by kur1977** [comment]
in 2.6.0 the TitleDB is disappear from main menu (((
Will it be implemented in future releases?

**Comment by joel16** [comment]
TitleDB shutdown so no.

**Comment by mariohackandglitch** [comment]
@Steveice10 After installing the updated FBI version, the download speed of the CTGP-7 Launcher (which also uses curl and gets data from github.com) has dropped to 50Kb/s. This is very weird as my other 3DS where I didn't use the updated FBI version works perfectly. Not sure why this happened or if it is just a coincidence, but I think it's worth pointing out.

**Comment by Steveice10** [comment]
@mariohackandglitch I don't see how FBI could affect the download speeds of other applications. For what it's worth, I was testing using the 3DSX version, so it probably wouldn't have to do with installing the CIA version.

Did you turn off and on your 3DS between using FBI and your launcher, or was this the same "session"?

**Comment by mariohackandglitch** [comment]
I even removed the battery and still having the same problem. I posted it here as it could be github servers flagging the 3DS for whatever reason, when I updated my updater from a buggy socket custom one to curl I had also a similar problem (it took some days until the speed suddenly went from 50KB/sec to 250 KB/sec).

Again, this could just be a coincidence but if someone else reports similar behaviour then we know it's not.

**Comment by Steveice10** [comment]
Good point about it potentially being GitHub, I'll have to look into that.

**Comment by Steveice10** [comment]
Regarding it being GitHub, I don't seem to be able to replicate the problem outside of the 3DS by using an identical user agent, so it being a user agent problem can probably be ruled out.

**Comment by norman720** [comment]
How do I download fbi

**Comment by Steveice10** [comment]
Going to close this since it's probably as solved as it's going to be.
