### ISSUE TITLE
Failed to install cia files

### ISSUE THREAD

**Issue by Brandonhell** [Steveice10/FBI#452]
Having an issue installing FBI using homebrew launcher to launch fbi.3dsx to install fbi.cia and other cia files.
Failed to install CIA file.
Result code: 0xD900458A
Level: Permanent (27)
Summary: Wrong argument (8)
Module: FS (17)
Desc: <unknown> (394)

Please help me, I want to install pokemon ultra sun. (Be specific on how to fix.)

**Comment by Steveice10** [comment]
I'm not sure exactly what that error code is, but my best guess would be that there might be something wrong with your title database files? Can you try opening up data management in the 3DS settings and see if it loads properly?

**Comment by Brandonhell** [comment]
Where would I find that exactly? I'm in data management, but do I press 3ds dsi or streetpass?

**Comment by Steveice10** [comment]
Tap 3DS, then Software.

**Comment by Brandonhell** [comment]
It came up as I needed to format sd card.

**Comment by Brandonhell** [comment]
Never-mind, FIXED IT! I had to reformat my sd card using 3ds settings. After that, WORKED! Sorry to bother you guys. :)
