### ISSUE TITLE
Well...

### ISSUE THREAD

**Issue by JG-GIT** [Steveice10/FBI#454]
This happens to everyone: When you look at the titles you've installed, and go down to the NAND section, there is more than 100 unknown titles that take up a lot of space, and gives the 3DS integrated fatal error when launched. Try to fix those.

PS: What is the font used to make the FBI image?

**Comment by Steveice10** [comment]
...Huh? Not all system titles are supposed to be launchable, but they still need to be displayed for title management purposes.

As for your question, the logo text was drawn pixel-by-pixel, not using a font.

**Comment by JG-GIT** [comment]
Okay.
