### ISSUE TITLE
Requests: Pic viewer and Zip extractor (maybe CTRNand FTP?!)

### ISSUE THREAD

**Issue by CookieXD** [Steveice10/FBI#455]
I know that its possible to view pictures via a homebrew program.
It has been done multiple times before. (See [3DShell](https://github.com/joel16/3DShell/releases))

Also it would be very handy if FBI could extract zips (even better: open zips, delete files from zips, add to zip and create zips...)

Did you think about adding an FTP feature to FBI and would it be possible to let it run while doing other stuff with FBI.
Do you think that it might be possible to use FTP with the CTRNand? (Also with tricks like copying in a temp folder on the SD and than to CTRNand or similar stuff)

FBI is my favorite program for the 3ds by far, but I think that it could be even better :D

**Comment by Steveice10** [comment]
As @Nuck-TH said, FBI is not intended to be a generic file manager. I would recommend finding a different app if you need these kinds of features. I know ftpd in particular is a very good FTP client.
