### ISSUE TITLE
Error 0xD963F806 when checking for update in 2.5.0

### ISSUE THREAD

**Issue by sevansup** [Steveice10/FBI#456]
When checking for an update within FBI on version 2.5.0, I get error:
Failed to check for update.
Result code: 0xD963F806
Level: Permanent (27)
Summary: Internal (11)
Module: Application (254)
Desc: Bad data (6)

Is this normal? Can I fix it?

**Comment by Steveice10** [comment]
Should be fixed in https://github.com/Steveice10/FBI/commit/39b0db2aaff7c6c69af45b1da148cd18088e0aa1

For some reason, there's another entry on TitleDB with the name FBI for someone's translation, so I added the author tag to the filter.
