### ISSUE TITLE
[Request] Add support for TitleDB's category feature. 

### ISSUE THREAD

**Issue by frozenLake** [Steveice10/FBI#457]
To help explain: TitleDB has a category tag that assigns a numerical value, corresponding to a type of homebrew software, to each entry. To list them in order, you have Games, Utilities, CFW, Installers, Emulators, and Demos.

While this would not add any more homebrew to the selection avaliable, it would allow for users to locate the kind of homebrew they are looking for far easier.

**Comment by Steveice10** [comment]
No longer applies as TitleDB has been removed.
