### ISSUE TITLE
Ignoring macOS hidden files when installing all CIAs from a folder

### ISSUE THREAD

**Issue by zacchi4k** [Steveice10/FBI#459]
When copying files to a drive, [macOS/Mac OS X automatically creates a file containing some metadata with the same filename, but with "._" attached at the beginning](https://i.imgur.com/nOF3DUQ.png), making it hidden.
When going to the folder containing the CIA with FBI, since the file is hidden, it won't be shown in the list, however, if the user chooses to install all CIAs from the current directory, those files will be picked up too and added to the queue (before the actual CIAs), since they still have the .cia extension, resulting in the queue getting doubled and half the installations failing, since it tried to install files which weren't actually CIAs. Plus, when choosing to install and delete all CIAs in the current directory, those files won't be deleted, even though they're no longer needed since the original file is gome

**Comment by urherenow** [comment]
Sorry, I wasn't clear, but it's a config problem on your end. I use OS X in a VM to cimpile things for IOS, and it certainly does not create a ._ copy for every file. It's a config problem on your end.

**Comment by ihaveamac** [comment]
No, macOS does indeed create these files depending on some situations by default. There is no "config" for this.

**Comment by urherenow** [comment]
What situations? Like using an exfat USB vice fat32?

**Comment by ihaveamac** [comment]
It can happen anywhere, on any filesystem, including FAT32, HFS+ and APFS. It's done it on my SD cards many times.

Making a new folder on an APFS volume, then doing something in Finder (e.g. expanding it in list view) creates a .DS_Store file.

**Comment by urherenow** [comment]
sudo mdutil -i off -d /Volumes
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
defaults write com.apple.finder AppleShowAllFiles YES

**Comment by ihaveamac** [comment]
Using that mdutil command disables Spotlight for all volumes which I would never just suggest to any random user. That's changing a global setting on the system that affects system features, all just to prevent FBI from installing files beginning with "`._`"

I think it should also not install those automatically in the same way it doesn't show them in the list.

**Comment by urherenow** [comment]
You missed my edit. You SPECIFY the volume. In fact, I think it will error out if you don't.

**Comment by ihaveamac** [comment]
If you can also change those defaults to only disable them on specific volumes that would be a better idea than a global change.

**Comment by zacchi4k** [comment]
@urherenow still, a lot of people don't know about this, some don't even know macOS creates the hidden files to begin with, that's why I think FBI should handle it properly

**Comment by Sanaki** [comment]
A number of OSes create excess hidden files on removable media, but as far as I'm aware only OSX has this somewhat kludgey per-file behavior. That said, there may be merit to ensuring that hidden files are not queued as part of the current directory (regardless of their purpose) when displaying of hidden files is disabled, since that would be the natural expected behavior for the average end user.

A specific exemption for files beginning with ._ does seem like a poor choice because, among other reasons, there's no way to ensure that this is the only circumstance where that naming format would be used.

**Comment by Steveice10** [comment]
It seems I overlooked multi-file operations when I added filters to the files menu. I'll change it so they only consider currently visible files sometime soon.

**Comment by zacchi4k** [comment]
I've tried with the 3dsx, but it doesn't seem to solve the issue. Also the top screen still says 2.5.2

**Comment by Steveice10** [comment]
Just to make sure, the hidden files weren't showing in the file list when you tested it, correct?

**Comment by zacchi4k** [comment]
Yes, but they weren't showing in the stable release either

**Comment by Steveice10** [comment]
Working fine for me; I made a folder with "FBI.cia" and a hidden file "._FBI.cia", and it only installed the former. It only tried to install both when I enabled "Show hidden files" in the file list options.

Make sure your old copy of FBI actually got replaced by the new one. The version will still be 2.5.2, so don't be alarmed if that doesn't change. I've cleaned out all of the build files, rebuilt, and reuploaded just in case it was a mistake on my end: https://www.dropbox.com/s/mbqpa15hz2nz69r/FBI.zip?dl=0

**Comment by zacchi4k** [comment]
Still doesn't work for me

**Comment by Steveice10** [comment]
Could you take a video or something, then? I can't figure out what's wrong if it's working just fine in my test cases.

**Comment by zacchi4k** [comment]
https://www.youtube.com/watch?v=pG8bzRdxPTk

**Comment by Steveice10** [comment]
In your video, the dot files are visible in the file browser; the change only makes the CIA installation list match the files shown in the browser. Since they don't have the hidden attribute, they aren't treated as hidden files.

**Comment by zacchi4k** [comment]
Ah right, I thought the 3DS/FBI would've acted like Linux and just the dot would've made it hidden

**Comment by Steveice10** [comment]
Do the special macOS "._" files usually get created with the hidden attribute set? If not, I could go ahead and treat dot files as hidden, since I can't think of any problems that might cause otherwise.

**Comment by zacchi4k** [comment]
iirc they get created with the hidden attribute (I don't have access to a Mac a anymore tho)

**Comment by Steveice10** [comment]
In that case, I'll go ahead and consider this solved.
