### ISSUE TITLE
Problem deleting .cia files

### ISSUE THREAD

**Issue by Red86** [Steveice10/FBI#46]
I am using FBI 1.4.17, injected in the H&S application on a 3ds that is running a9loaderhax and, the latest version of aureinand.

FBI works great apart from a weird problem when it comes to delete a .cia files. If I install a .cia and after the installation is completed I try to delete it, FBI will give an error saying that no such file exists. If I close and reopen FBI then, I will be able to delete the .cia.

**Comment by Steveice10** [comment]
Pre-rewrite versions of FBI are no longer under development.
