### ISSUE TITLE
Is there a Mass/Automated seed import feature that i missed?

### ISSUE THREAD

**Issue by Wontell** [Steveice10/FBI#460]
I just installed 273 games, took me over 24 hours, now some games wont load, but i dont remember when ones so i go one by one and do seed import, is there a way to do it automatically just like I did automated installed of whole folder of games?

**Comment by Steveice10** [comment]
FBI attempts to automatically install seeds when CIAs finish installing.

**Comment by Steveice10** [comment]
Were you not connected to the internet at the time? It calls the exact same code as the Import Seed option.
