### ISSUE TITLE
Failed to bulid with the latest devkitpro (3.0.3)

### ISSUE THREAD

**Issue by Spmario233** [Steveice10/FBI#461]
```
make: git: Command not found
Building for 3DS...
build/3ds-arm/source/core/default.shbin.c
make: picasso: Command not found
make: *** [buildtools/make_base:553: build/3ds-arm/source/core/default.shbin.c] Error 127
```

**Comment by urherenow** [comment]
No it doesn’t. You fail to read instructions (and error messages). You haven’t installed the required dependencies. Have you even installed dkp-pacman?

**Comment by Steveice10** [comment]
You're missing git and picasso. Possibly other tools as well.

**Comment by Spmario233** [comment]
Still can't build. more details here: http://gbatemp.net/threads/help-falied-to-compile-fbi-with-devkitpro-3-0-3.514546/

**Comment by Steveice10** [comment]
Try looking for a usr/bin/xxd and copying that over, rather than usr/share/(...)/xxd

**Comment by urherenow** [comment]
I make a tutorial for him. There's something fishy about the path using the devkitPro installer, but I did something I probably shouldn't have to and the ONLY files that need to be copied anywhere is bannertool and makerom.

https://gbatemp.net/threads/help-falied-to-compile-fbi-with-devkitpro-3-0-3.514546/
