### ISSUE TITLE
"Can't install" any .cia - RSA/Hash verification failure.

### ISSUE THREAD

**Issue by shw** [Steveice10/FBI#463]
No installed cias are showing up on the screen. When I try to install any cia launching FBI using Download Play's Homebrew Launcher or with newest FBI injected to H&S with Godmode9 I get an error RSA/Hash verification failure.

But those cias do appear in Titles part of FBI - just not on the home screen. And I can launch them from that FBI menu - there's sometimes some kind of error popping up for a split second (from that I can make of it from that split second - some Applet error?) but they do run. They also appear in Setting's Data Management part.

I tried formatting the SD card, checking it with h2test tool and copying the backup from before the format again on the card. The card was positively verified by h2test so there's no corruption there.
I tried removing the `0000008f` (well - EURO version) of the folder but it doesn't help either.

I followed the 3ds.guide guide and at first it worked but I had some ARM11 crashes so I was trying few things, installing some other cia applications and ended up in that state. Not sure what I can do at this point - should I format the 3ds and go through the guide again (not sure if/how it would work if I did the guide already and have Luma3ds installed?)?

![img_1292](https://user-images.githubusercontent.com/146512/44030797-3629e5b6-9f02-11e8-86eb-4905ae54bd9c.JPG)
![img_1293](https://user-images.githubusercontent.com/146512/44030798-364a24ca-9f02-11e8-80ce-ba3c25745a51.JPG)
![img_1294](https://user-images.githubusercontent.com/146512/44030799-3665ed68-9f02-11e8-8dac-10a801fc2917.JPG)

**Comment by Steveice10** [comment]
If you are/were having ARM11 crashes, there might be a bigger underlying issue with your CFW setup. Not sure what else I can tell you, as these RSA errors come straight from the AM sysmodule, not FBI itself.

**Comment by shw** [comment]
The ARM11 crashes were from few (not all) freeshop downloads. Right when they start to download I believe.

**Comment by NinjaBoyLao** [comment]
just go through the guide again and come back and close this when you get time
