### ISSUE TITLE
Browsing save data for GBA VC titles.

### ISSUE THREAD

**Issue by d0k3** [Steveice10/FBI#464]
This simply doesn't work, we get "Failed to open file listing archive" as error message.

GBA VC titles use a different save format, using the same header as the `AGBSAVE` NAND savegame with the actual save (in GBA native format) attached to it.
http://3dbrew.org/wiki/3DS_Virtual_Console#NAND_Savegame

So, I don't expect you to make this browsable, but maybe a nicer error message would be possible?

**Comment by Steveice10** [comment]
Is there a way to detect a GBA title from userland? If I just hardcoded GBA VC title IDs for an error message, it wouldn't work for custom GBA VC injections.

**Comment by d0k3** [comment]
Depends on what you have access to. You can safely detect it from the NCCH ExHeader (via the core version, requires AGB_FIRM):
https://3dbrew.org/wiki/NCCH/Extended_Header#ARM11_Local_System_Capabilities

The savegame itself has '.SAV' as magic number.

**Comment by Steveice10** [comment]
I don't have access to the exheader or the raw save data.

**Comment by Steveice10** [comment]
Closing as I don't know of any way to get this done in userland.
