### ISSUE TITLE
source/core/screen.c:13:10: fatal error: default_shbin.h: No such file or directory

### ISSUE THREAD

**Issue by abdojapan** [Steveice10/FBI#465]
Hi,

I get this error code while making.

`source/core/screen.c:13:10: fatal error: default_shbin.h: No such file or directory`

I have the latest devkitARM and I installed both zlib and jansson.
I also have libctru which has shbin.h but not defautl_shbin.h

Thanks for advance.

**Comment by abdojapan** [comment]
I tried to replace line 13 with

`#include <3ds/gpu/shbin.h>`

Then the new error

`source/core/screen.c: In function 'screen_init':
source/core/screen.c:98:34: error: 'default_shbin' undeclared (first use in this function)
     dvlb = DVLB_ParseFile((u32*) default_shbin, default_shbin_len);
                                  ^~~~~~~~~~~~~
source/core/screen.c:98:34: note: each undeclared identifier is reported only once for each function it appears in
source/core/screen.c:98:49: error: 'default_shbin_len' undeclared (first use in this function)
     dvlb = DVLB_ParseFile((u32*) default_shbin, default_shbin_len);
                                                 ^~~~~~~~~~~~~~~~~
make: *** [buildtools/make_base:722: build/3ds-arm/source/core/screen.o] Error 1`

**Comment by urherenow** [comment]
This is not a support forum and there is no bug when compiling. Find me on GBAtemp and there is a link in my sig to a full tutorial I wrote.

**Comment by Steveice10** [comment]
There's definitely something wrong with your setup or how you're compiling FBI; the missing file in question is supposed to be generated from a shader file during the build process

**Comment by abdojapan** [comment]
even though both of you have a very negative attitude I will share with you what was wrong and how I fixed it

It seems that the files is generated, but is called '.h' at the root of the project with weird code inside.
I modified the last two lines in shader-as of make_base of buildtools sub repositories.

`$(eval CURH := $(shell echo $(CURBIN) | tr . _).h)
	$(eval CURHLine1 := $(shell echo $(notdir $(CURBIN)) | sed -e 's/^\([0-9]\)/_\1/' | tr . _))
	$(eval CURHLine2 := $(shell echo $(notdir $(CURBIN)) | sed -e 's/^\([0-9]\)/_\1/' | tr . _))
	echo $(CURH)
	echo "extern const u8" $(CURHLine1)"[];" >> $(CURH)
	echo "extern const u32" $(CURHLine2)_len";" >> $(CURH)`

I use msys2, perhaps that's why the behaviour is different, or perhaps the make tool version is different. However I think it makes sense to use 'shell echo' instead of 'echo' in that nested expression.

**Comment by urherenow** [comment]
Negative attitude? Dude, I wrote a tutorial specifically for people in your situation. I attempted to direct you to it. Zero modification is needed to the source to compile without errors. Again, github is not a support forum.

**Comment by abdojapan** [comment]
Thank you for your great information contributions to the community and FBI is definitely very useful tool, thank you both.
I hope my post and how I solved the problem might slightly help someone and be a little contribution to the community.
