### ISSUE TITLE
Failing to install any CIA files

### ISSUE THREAD

**Issue by darklink12** [Steveice10/FBI#466]
Since i updated to version 2.5.1 i can't dowload any CIA files whatsoever. I tried using QR codes, Urls or the programs own titledb, but none of it worked. The same error message keeps appearing. It states the following:
                                  Failed to install from URL.
                             ->especific program URL
                             Result code: 0xD963F99C
                             Level: Permanent (27)
                             Summary: internal (11)
                             Module: Application (254)
                              Desc: HTTP 404: Not Found (412)
Is this problem related to the update or is the issue on my own 3ds? I would appreciate if i could get a response, thanks in advance!

**Comment by ajmn0309** [comment]
I get the same error

**Comment by Manic020** [comment]
Same. Can't install from files or a URL. Had to revert back to 2.5.0 to fix it.

**Comment by ajmn0309** [comment]
I don't know how to revert... tried installing 2.5.0 but it says a new version already exists... am waiting for 2.5.2... (2.5.0 gave me a weird problem, it wasn't opening the TitleDB also)

**Comment by Steveice10** [comment]
Fixed in [2.5.2](https://github.com/Steveice10/FBI/releases/tag/2.5.2), thanks for the quick find.
