### ISSUE TITLE
Downloading CIA using QR code with FBI not working

### ISSUE THREAD

**Issue by jvhellraiser** [Steveice10/FBI#469]
Since soon there will be a release of a store using QR codes i believe is time for FBI team work on fixing
the QR, at this moment i haven't been able to download any CIA using  FBI to read the QR code, not sure whats wrong but please try to fix it. thanks in advance,thank you for your hard work

**Comment by Sanaki** [comment]
If you're attempting to download from github using QR, I don't believe TLS1.2 support has been added to FBI yet. In that case, try using [QRaken](https://github.com/BernardoGiordano/QRaken/) for the time being. It's not perfect, but it'll do the job until we have that update.

**Comment by jvhellraiser** [comment]
NO, FBI 2.5.2  just makes error on any Qr Code (ANY)
![40049695_2668801200012015_8169768799109644288_n](https://user-images.githubusercontent.com/16488761/44623147-c2682a00-a895-11e8-812f-24fc2c18e856.jpg)

**Comment by Steveice10** [comment]
That is bad data; "https://mega.nz/" does not point to a CIA.

**Comment by jvhellraiser** [comment]
Holy mother of god how is it possible https://mega.nz/#!d41XjYiL!hYmmkqgNNx5mEXFOBatjlLaQ--Elf8EQXiwqq0R4BdA thats the link thats in that QR code i use. test it.

**Comment by Steveice10** [comment]
That is not a CIA either, that is a MEGA download page. FBI needs direct download links.
