### ISSUE TITLE
Install failed while doing bunch install CIAs

### ISSUE THREAD

**Issue by lprot** [Steveice10/FBI#47]
I always install CIAs via X key (bunch install) and after installing about 12 titles get every time this error:
Install failed!
CIA name
Source: SOURCE_FSFILE_WRITE (0x1c)
Module: MODULE_NN_FS (0x11)
Level: LEVEL_PERMANENT (0x1b)
Summary: SUMMARY_OUT_OF_RESOURCE (0x3)
Description: <unknown> (0x26c)

After power off/on I repeat the same and it continues installing ok.  
Using A9LH aurei cfw and 64Gb fat32 card.

**Comment by Steveice10** [comment]
Pre-rewrite versions of FBI are no longer under development.
