### ISSUE TITLE
Constantly crashing on 11.7 with latest FBI, O3DS.

### ISSUE THREAD

**Issue by tempoacc69** [Steveice10/FBI#470]
So as title, when everytime you tries/after installing/removing CIA u will get crash. this seems to be time based.
this doesnt happens on non-latest FBI.

It returns ARM11 Translation Error Exception.

**Comment by tempoacc69** [comment]
Yes sure. i'll post dump coz i already removed latest version of FBI.

**Comment by tempoacc69** [comment]
https://www85.zippyshare.com/v/FwGx3iYV/file.html

**Comment by tempoacc69** [comment]
https://imgur.com/a/HNT5JNJ

**Comment by Steveice10** [comment]
Can you confirm whether this build fixes your issue?

https://www.dropbox.com/s/cgb0qngh3xlbui5/FBI.zip?dl=1

**Comment by tempoacc69** [comment]
yep it doesnt crashes anymore :) thanks!
