### ISSUE TITLE
Crash when accessing title list

### ISSUE THREAD

**Issue by lsonix** [Steveice10/FBI#473]
My system consistently returns an exception when selecting the “titles” option on the main page on v 2.5.2; this issue does not crop up on v 2.5.0

Exception = data abort
Fault status = translation - page

Every value for the stack dump on the lower screen is 00. I have a number of Japanese titles installed.

**Comment by Steveice10** [comment]
This issue has been fixed in the latest source. I'll go ahead and do another release with the fix.
