### ISSUE TITLE
failed to install cia

### ISSUE THREAD

**Issue by wewannaown** [Steveice10/FBI#474]
i am getting the following error when i try to install Pokemon Sun Eur.cia

Failed to install CIA file.
Result code:0xD8E0806A
Level: Permanent (27)
Summary: Invalid argument (7)
Module: AM (32)
Desc: Cert signature or hash check failed (106)

i am using an old 2ds with luma3ds & homebrew on 11.8.x
all other roms installed just fine.
Edit:
forgot to mention that i already redownloaded it. also from different downloadsources. no multidownload, no restart download or anything else.

**Comment by Steveice10** [comment]
I would make sure to check that you have enough free space on your SD card and that there aren't any filesystem errors. If possible, it might help to try installing to a different SD card as well. These kinds of errors are coming from the OS, and can have a multitude of causes.

**Comment by mosfilho** [comment]
I've the same error. In old 3DS XL.

**Comment by wewannaown** [comment]
Can be closed;
SD-Card was broken.
