### ISSUE TITLE
Fbi not working as intended

### ISSUE THREAD

**Issue by AcesGamingUK** [Steveice10/FBI#475]
Can't load titleDB nor check for updates.
'TitleDB error -
Failed to populate TitleDB list
Result code:0xD963F9FC
Level: Permanent (27)
Summery: Internal (11)
Module: Application (254)
Desc: HTTP 500: Internal Server Error (508)'

'Update Error
Failed to check for update
Result code:0xD963F9FC
Level: Permanent (27)
Summery: Internal (11)
Module: Application (254)
Desc: HTTP 500: Internal Server Error (508)'

**Comment by Steveice10** [comment]
Seems to be a TitleDB issue, not an FBI problem.
