### ISSUE TITLE
Failed to install CIA file.(0xD900458A)

### ISSUE THREAD

**Issue by iAmGrizzly** [Steveice10/FBI#476]
Having weird issue when trying to install CIAS and they all give me the same error

Failed to install CIA file.
Result code : 0xD900458A
Level: Permanent (27)
Summary: Wrong argument (8)
Module: FS (17)
Desc: <unknown> (394)

I've been following 3ds.hacks.guide and have done everything up to "Section IV - Installing CIAs" and this is where i am stuck. What is the issue?

**Comment by Steveice10** [comment]
Based on the error code, you may want to check your SD card for issues and, if possible, test installing with a different SD card inserted.

**Comment by iAmGrizzly** [comment]
i got it working now, skipped a step; Section II - Updating the System
