### ISSUE TITLE
failed to output 3dsx

### ISSUE THREAD

**Issue by giveup** [Steveice10/FBI#48]
As issue #44 ,I try to fresh install libctru(@Steveice10 fork).
But still get error,
Here is log:
build/source/ui/section/action/launchtitle.o
build/source/ui/section/action/pastefiles.o
build/source/libkhax/khaxinit.o
output/FBI.elf
output/3ds/FBI/FBI.smdh
output/3ds/FBI/FBI.3dsx
make: *** [output/3ds/FBI/FBI.3dsx] Error 95
rm build/source/default.shbin.c
It seems the build is sucessfuly but output failed.

**Comment by Steveice10** [comment]
Check if you can build a 3dsx from the outputted elf manually.

**Comment by giveup** [comment]
Yes, 3dsxtool input.elf output.3dsx works.Thank you！
Maybe build script need some fix.

**Comment by urherenow** [comment]
Nothing wrong with the build script. With my environment, and only updating to make v4.1, I get no issues at all. Still sad that so many other projects won't work withthe 4.1 make though, but work with v3.18. Had to revert to that just today to build Godmode9.

**Comment by damnnfo** [comment]
I had the same issue on my office PC. (Win7 64Bit + devkitARM_r45-win32)
But it's woking fine on my home PC. (Win10 32Bit + devkitARM_r45-win32)
The environment on both PCs should be the same.

**Comment by giveup** [comment]
@damnnfo Works fine.Thank you！
