### ISSUE TITLE
failed cias from sdcard install, but installed via network correctly?

### ISSUE THREAD

**Issue by hans0l0** [Steveice10/FBI#480]
I installed 115 cias, with a failure of 23 files (attempted twice upon failure), after, I send the same 23 failed files from their same file via network install with the included servefiles.py and all 23 install without failure.

Are their additional checks when files are installed via sdcard vs network, or is this a case of a possible sdcard read/write error either during install or original transfer over?

Thank you for your hard work and determination to the scene, your tools are unmatched.

**Comment by Steveice10** [comment]
I would check for problems with your SD card; the process shouldn't be much different. Do you have the error message the installations failed with?

**Comment by hans0l0** [comment]
Failed to install CIA file
Result code: 0xD8E0806A
Level: Permanent (27)
Summary: Invalid argument (7)
Module: AM (32)
Desc: Cert signature or hash check failed (106)

I have a new 256Gb samsung formatted for FAT32 with 32K allocation clusters.

**Comment by Steveice10** [comment]
See https://github.com/Steveice10/FBI/issues/486 as it's the same error code.
