### ISSUE TITLE
Update option don't work

### ISSUE THREAD

**Issue by skity007** [Steveice10/FBI#483]
Hi, the option "Update" don't work and say 
"Failed to check for update
Result code 0xD963F806
Level: Premanent (27)
Summary: Internal (11)
Module: Application (254)
Desc: Bad data (6)"

**Comment by Steveice10** [comment]
Looks like there's another duplicate entry for FBI in TitleDB now. The updater will be fixed in the next release, whenever I can finally get around to it.

**Comment by Steveice10** [comment]
Should be addressed in source.
