### ISSUE TITLE
failed to install cia file

### ISSUE THREAD

**Issue by nolie22** [Steveice10/FBI#484]
Result code: 0xD9004587
LEVEL: PERMANT (27)
SUMMARY: WRONG ARGUMENT (8)
MODULE: FS(17)
DECS: HASH VERIFICATION FAILURE (391)

**Comment by Steveice10** [comment]
Sounds likely to be a bad CIA file (see https://github.com/AuroraWright/Luma3DS/issues/750#issuecomment-318774117)
