### ISSUE TITLE
Request time out

### ISSUE THREAD

**Issue by kurocygnus** [Steveice10/FBI#485]
Failed to install from URL.
http://192.168.25.2:8080/yokai.cia
Result Code: 0xD820A069
Level: Permanent (27)
Summary: Nop (1)
Module: HTTP(40)
Desc: Request timed out (105)

I'm getting this with Boop (doesn't even start) and with servefiles (it starts but after a while, it gives me the same error)

**Comment by Steveice10** [comment]
Sounds like a network problem. Check your connection and make sure a firewall isn't preventing the 3DS from connecting to your PC.

**Comment by kurocygnus** [comment]
Tried uploading it to a server and using the direct link but It gave the same error in the middle of the download, don't think that it has something to do with my pc

**Comment by Steveice10** [comment]
Have you checked your 3DS's internet connection, then?

**Comment by kurocygnus** [comment]
Yes. It's full signal. I'm less than a meter away from the router.

**Comment by Steveice10** [comment]
Then I don't really have much else to say, other than maybe try running a connection test in the settings or downloading a demo from the eShop as a test.

**Comment by kurocygnus** [comment]
Did it now. Downloaded a Demo without any problem and the connection test executed succesful.

**Comment by kurocygnus** [comment]
You can close it, it was a router problem and not a FBI problem. Sorry for the inconvenience.

**Comment by josemiguel1999** [comment]
IF helps, Boop offers you multiple PC interfaces in Computer IP Address.
Do a cmd->ipconfig and check your ip
select the interface of your wireless
If any problem, temporally disable the firewall

**Comment by mo0nfish** [comment]
> IF helps, Boop offers you multiple PC interfaces in Computer IP Address.
> Do a cmd->ipconfig and check your ip
> select the interface of your wireless
> If any problem, temporally disable the firewall

Thank you so much, registered here just to tell you this 

٩(｡•́‿•̀｡)۶
--

**Comment by josemiguel1999** [comment]
> 
> 
> > IF helps, Boop offers you multiple PC interfaces in Computer IP Address.
> > Do a cmd->ipconfig and check your ip
> > select the interface of your wireless
> > If any problem, temporally disable the firewall
> 
> Thank you so much, registered here just to tell you this
> ## ٩(｡•́‿•̀｡)۶

Thanks for the feedbak!!
