### ISSUE TITLE
Failed to install CIA file.

### ISSUE THREAD

**Issue by tukeyh** [Steveice10/FBI#486]
Result code: 0xD8E0806A
Level: Permanent (27)
Summary: Invalid Argument (7)
Module: AM (32)
Desc: Cert signature or hash check failed (106)

This issue has been happening to multiple people I know. No CIA can be installed on latest version aside from tools. microsd card has been tested and no issues were discovered

**Comment by Steveice10** [comment]
* Have you made sure the CIAs are good?
* Have you tried with a different microSD card, if possible?

If so, maybe try with a different CIA installer, and if it still happens, it's not an FBI issue.

**Comment by Steveice10** [comment]
There hasn't been a new FBI release in months, so I would suspect the SD card is the problem. And, there's a search function in the GitHub issue tracker for that reason.

**Comment by tukeyh** [comment]
I changed my sd (formatted and tested with h2testw, all good). Yet the problem persists.

**Comment by Steveice10** [comment]
Have you tried with a different CIA installer on the same system?

**Comment by tukeyh** [comment]
I'll try.

**Comment by tukeyh** [comment]
I can't seem to find an alternative as everyone uses FBI. Can you suggest any?

**Comment by Steveice10** [comment]
If you know of a homebrew CIA that doesn't work and also provides a QR code, you could try scanning it with QRaken.

**Comment by tukeyh** [comment]
The CIAs I am using are from my o3ds which I'm attempting to move to n2dsxl. Tried to use boop for install but that didn't work either. I have been able to install tools as normal

**Comment by Steveice10** [comment]
How are you dumping them (assuming that's what you mean) to transfer from your O3DS? Wondering if maybe them working perfectly on the O3DS has something to do with them coming from the O3DS in the first place.

**Comment by tukeyh** [comment]
I mean, I can also pirate cias but they don't work either. Same thing no matter what, doesn't matter where they originate. I dumped them as intended, standard, and attempted install on n2dsxl

**Comment by Steveice10** [comment]
Not sure what to say at this point, then. I wish I had some definitive piece of advice I could give here, but I've seen people get errors like this for a variety of different reasons: SD card issues, SD card file issues, bad CIAs, etc. I recall some people ended up fixing their problems by simply redoing the steps to get set up with CFW. It's hard to pin down exactly why the 3DS OS rejects an installation sometimes.

**Comment by Steveice10** [comment]
I guess one more thing I should ask about is, did you test with a blank SD card when you tried a different one? Or did you copy over the 3DS files from the original SD first?

**Comment by tukeyh** [comment]
I bought a brand new one. Formatted it. Tested it. Moved my files on it and attempted to install the cia.

Just an update, a cia succesfully installed by remote install with boop, but I am not yet sure if this is a reliable method.

**Comment by Steveice10** [comment]
Okay. If remote installing works consistently, it may have been an issue getting the CIA on to your SD card correctly or reading it from the SD card when installing. If it doesn't, then for future reference, it may be a good idea to test with a blank SD card and no copied files, as that would rule out any issues with the 3DS's database files.

**Comment by tukeyh** [comment]
You are required some files for cfw to work though, yes? I'm not sure if turning the console on with no files can cause a brick.

**Comment by Steveice10** [comment]
Oh, yes, CFW files are fine. The main concern would probably be the .db files somewhere under the Nintendo 3DS folder.

**Comment by tukeyh** [comment]
I managed to boop another cia. It seems consistent. Thanks for all the help.

**Comment by Steveice10** [comment]
Great, glad it's working out.

**Comment by hans0l0** [comment]
Curious to see the size of SD cards involved with this issue. When I opened the other ticket closed above I had the same issue with my 256gb Samsung Evo originally formatted fat32 32k clusters. I backed up and reformat fat32 64k clusters and that corrected my errors. But I never had the errors streaming cias to FBI only while loading cias from the sdcard.
