### ISSUE TITLE
Error in installing pokemon y

### ISSUE THREAD

**Issue by Hargeehey** [Steveice10/FBI#487]
Please help me to fix this...
I can't install CIA file due to aome failure...

Failed to install CIA file
Result code: 0xD9004588
Summary: Wrong argument (8)
Module: FS (17)
Desc: RSA/Hash verification failure (392)

**Comment by Steveice10** [comment]
Make sure you're booting into CFW and that the CIA is valid. Also, test your SD card for problems and/or try using a different SD card, if possible.
