### ISSUE TITLE
Please implement my TitleDB clone

### ISSUE THREAD

**Issue by Multimegamander** [Steveice10/FBI#489]
It can be found at https://github.com/Multimegamander/TitleDB-2.0 all additions have to be manual, so that what happens to the original doesn't happen here.

**Comment by Steveice10** [comment]
Not something I plan on doing, sorry.

**Comment by pbanj** [comment]
I'm glad you said no as I wouldn't trust anything multi tries to do. He likes to make a bunch of shitty troll clones of stuff. So he has shown he isn't to be trusted with anything that's for a community
