### ISSUE TITLE
There's no way to back out of deleting ext savedata

### ISSUE THREAD

**Issue by kirbykirby56** [Steveice10/FBI#490]
"Any button" is the only option, and that includes both B and Start, and both buttons delete the file.

**Comment by Multimegamander** [comment]
hold the power button

**Comment by Steveice10** [comment]
Could you post a screenshot? I just tried on my 3DS with 2.6.0 and it shows Yes and No options as expected.

**Comment by kirbykirby56** [comment]
I didn't get a notification about this thread, sorry-- I don't know why, but there was a file that I was unable to back out of deleting. I'm trying it now, but it seems to work fine. Sorry about replying only four days later ^^; I poked around, and it's for Ext Save Data. I'll upload a phone screenshot, as pressing the buttons for my screenshot tool would, well, delete the save.

**Comment by kirbykirby56** [comment]
![ext](https://user-images.githubusercontent.com/12013191/50935287-834c0700-1439-11e9-96c8-6ec5dfe2bb1e.jpg)

**Comment by Steveice10** [comment]
Ah, so it's ext save data. I'll take a look.

**Comment by Steveice10** [comment]
Fixed in https://github.com/Steveice10/FBI/commit/cff055b71e94f980bc9ed024d09f178ec77f8bb0, thanks.
