### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by JinGalaxy** [Steveice10/FBI#491]
I'm new to all this, but, I've succesfully installed my Homebrew on the 3ds 11.9 through the SubWars thingy, and I think I did it all correctly, but the FBI just won't work, I try to install it but the 3ds is stuck on a yellow under-screen, and it does not continue, I can't leave it, only if I turn the device off, mind helping me? pls...

**Comment by Steveice10** [comment]
Are you running CFW, or just the homebrew launcher on OFW? Also, do other homebrew apps launch correctly?

**Comment by ruhanvohra** [comment]
Same problem for me, FBI gets stuck on a yellow screen when I try to install it. The video i used to get homebrew launcher is right here
https://www.youtube.com/watch?v=UJZYBS_eeLY
Is there any extra stuff I need to move on to the root of my SD card? I don't have any other files except for the one in the video and the default 3ds files.

**Comment by Changshire** [comment]
hey same problem here, btw followed exactly the same video, homebrew works just fine, i don't have other homebrew apps to test but 3dsx files seems to work just fine. i'm probably missing something but a little help can never hurt, thanks

**Comment by urherenow** [comment]
Look, github is not a support forum. Go to gbatemp for help. And stop using videos and actually read the guide. 

https://3ds.hacks.guide/

**Comment by Steveice10** [comment]
Have any of you tried earlier releases? It could be that something broke it when launched outside of CFW, if multiple people are experiencing this. I use Luma3DS's 3dsx support for testing, so I don't really have anything set up to test via other methods.

**Comment by Changshire** [comment]
no i'ts done now, i hadn't installed cfw, i just had homebrew, thinking it was cfw... a little bit embarrassing but i got there in the end, thanks ! i completed it this morning

**Comment by Macley-Kun** [comment]
Close issue?

Met vriendelijke groet,

Wesley de Vree
________________________________

**Comment by DanielOberlechner** [comment]
I've got the same issue with custom firmware ...

does anyone has any idea how to resolve this issue??

Greets
