### ISSUE TITLE
FBI v2.6.0 cannot be injected into Health & Safety

### ISSUE THREAD

**Issue by ShadowOne333** [Steveice10/FBI#492]
When trying to inject the FBI.cia using Universal Inject Generator and the hs.app file as the base, the latest cia of v2.6.0 of FBI throws a .app file above 1MB.

By using Decrypt9WIP and going through the SysNAND Options -> Miscellaneous -> H&S Inject, I get the "H&S inject app is too big!" message.

I've been doing the same process for all the FBI updates since 2.3.0 up to 2.6.0, and only 2.6.0 has given me this error.

**Comment by Steveice10** [comment]
Health and safety injection hasn't been officially supported for a long time. There are plenty of better ways to do an initial install of FBI, such as through Luma3DS's built-in homebrew launcher support.

**Comment by Ammako** [comment]
If you insist on using H&S injection, it should work with GM9 (I have done so myself very recently with 2.6.0, because Rosalina HBL doesn't work on 6.2 and updating was not an option.)

It's not an issue with FBI, regardless.

**Comment by urherenow** [comment]
6.2? Didn’t know FBI was made for the Switch... lol

**Comment by Ammako** [comment]
Talk about an useless (and misinformed) reply.

**Comment by urherenow** [comment]
@Ammako, go back and re-read your post very carefully a few times. You *might understand mine (and mine was a joke)
