### ISSUE TITLE
TinyDB Integration request

### ISSUE THREAD

**Issue by deadphoenix8091** [Steveice10/FBI#493]
Hello, I am the creator of TinyDB. It aims to be a full featured replacement of TitleDB with tons of automation in regards of Moderation.

Github URL: https://github.com/deadphoenix8091/tinydb
Page URL: https://tinydb.eiphax.tech
gbatemp post: https://gbatemp.net/threads/new-tinydb-a-titledb-replacement.528719/

I would like to talk to you about the possibility of getting an FBI integration. 

Would you be open for an integration? If so, is there anything you would like to see done differently?
I would start working on the required code reusing some of the - now removed - titledb integration and send you a pull request in the upcomming days. 

Really looking forward to hearing back from you. Thank you.

**Comment by LAX18** [comment]
I would like to see a replacement for TitleDB as the service was of great use to me. Look forward to see how this works out!

**Comment by Steveice10** [comment]
Looks interesting. Do have a public-facing API that FBI can use?

**Comment by deadphoenix8091** [comment]
Not yet, that's why I was asking if there is anything you would want that wasn't possible with the titledb api.

Otherwise I can have an api ready within the next 2 hours that would be identical to the titledb api.(except endpoint urls)

**Comment by Steveice10** [comment]
Nothing comes to mind at the moment in terms of features. One persistent issue with TitleDB was that there were many duplicates titles (e.g. there were three FBIs by the end), so it would be great if that was kept checked.

**Comment by deadphoenix8091** [comment]
I just finished implementing a first version of the api. 

It mostly resembles the api scheme that TitleDB had but was streamlined a bit. 

Available Endpoints:

- "/api/apps" : As one might expect, this returns a list of all apps including all releases. 
- "/api/apps?app_id=1" : Above endpoint can also be used with an app_id parameter to only get releases for 1 specific application. For example fbi has id 1. This filter can be used for automatic updates.
- "/api/apps?category_id=3" : By specifying the category_id parameter you only get apps and releases that are mapped to one specific category (NOTE: Can not be used in combination with the app_id, please only specify the app_id in that case)
- "/api/categories" : This endpoint returns a list of all categories with an app count for each category.

API Base URL: https://tinydb.eiphax.tech

Changes from the TitleDB Api:
- There is no seperate download url anymore, each cia entry has a download_url attribute.
- Instead of the category attribute on applications, there is now a categories attribute with all the category ids this application has been mapped to.

Regarding the app duplication issue of TitleDB:
TinyDB works on github repositories only instead of user uploads. Each repository/application submission gets checked by me or a few other people from the Nintendo Homebrew Discord. In the rare occasion that we would allow a fork of another application, we would make sure that the fork has a different unique name and titleid.

If there is anything you would like to see changed, just comment and I will try to take care of it asap.

Thank you very much!

**Comment by TermerMC** [comment]
I'm excited for this. It's been a long time since I did anything with homebrew, since TitleDB shutdown. I didn't even know it shutdown, all I knew was FBI could not update or download anything from TitleDB.

**Comment by AL3XPI** [comment]
It's been 8 days Steve, hurry up I want my tinydb

**Comment by LAX18** [comment]
Hey @AL3XPI, Don't be impatient. I am sure they are working to integrate TinyDB and you rushing them along does nothing but make you look like a fool.

**Comment by deadphoenix8091** [comment]
@Steveice10 Just wanted to ask if you had any chance of looking at the api yet?

**Comment by Steveice10** [comment]
I did take a look before, but I just haven't really had time to work on adding support to FBI yet. College has been keeping me fairly busy.

**Comment by deadphoenix8091** [comment]
@Steveice10

Henlo :) 

Just wanted to know if you had any time for this in the past month or will have in the forseable future?

If not I'd like to offer implementing tinydb myself again and shooting you a pull request to get the work off your chest. 

Thank you very much :)

**Comment by Steveice10** [comment]
My current plan is to get working on this in about 2 weeks, but if you want to try your hand at it before then, feel free.

**Comment by Steveice10** [comment]
A quick update on this.

This probably isn't what you've been hoping to hear, but I've been going back and forth on this for a while and have ultimately decided that I don't want to integrate a particular third-party service into FBI. I have no control over what might be served to users over a service I don't run. Plus, I'd like to keep FBI mostly offline so parts won't just stop working at some point in the future. I also probably wouldn't be able to do such a service justice in a simple sub-menu with limited functionality. It would probably be for the best for a service to provide it's own custom "store front" that either uses the QR installer or has it's own standalone app.

Super sorry it's taken me so long to get to this point; I've been kept pretty busy over the past few months.

**Comment by Steveice10** [comment]
As an added note, I feel that FBI has reached the point in its life where, going forward, there will pretty much just be bug fixes and no new significant features. Things have settled down a lot in the 3DS scene, and there isn't really much within scope that FBI can't already do. Plus, once again, time hasn't been as plentiful as it once was.

**Comment by mmarquezs** [comment]
Sad to hear that, I was going to suggest instead to use a common api (maybe the same titledb had to reduce development) and let the user point to the server they want. I wanted to use that to be able to have my own private repository and download from there, like I do with F-Droid on Android. 

To be honest my original Idea was to do my own standalone app for that but so far it's clearly over my head.

**Comment by InSimpleTermsJordan** [comment]
I was thinking, would it maybe be possible to fork FBI v2.5.3 and cut out everything except the TitleDB stuff, and develop it for the sole purpose of downloading and updating TinyDB software?
Sorry if that sounds like a dumb question; I'm not really familiar with that level of coding
