### ISSUE TITLE
[Feature Request] show the file name at the "installed successfully" dialog

### ISSUE THREAD

**Issue by pseiler** [Steveice10/FBI#497]
Simply what is written in the dialog. Could you show the file name in the dialog when an application is successfully installed. Especially when installing large files, you forgot which file you installed when you want to delete it afterwards.

**Comment by Steveice10** [comment]
Will take into consideration, although for what it's worth you could just use the option to automatically delete the CIA when it's finished installing.

**Comment by pseiler** [comment]
I know this but unfortunately it won't work sometimes. So a generic information when the installation is done would be nice.
Thank you

**Comment by Steveice10** [comment]
Closing as FBI feature additions have pretty much winded down at this point.

**Comment by pseiler** [comment]
*sad face*
But  I can understand
