### ISSUE TITLE
Getting a crash on exit when built from source.

### ISSUE THREAD

**Issue by ksanislo** [Steveice10/FBI#50]
When building from source, using the latest libctru from github and devkitPro from their update script, I'm getting a crash after pressing START to exit. I notice this doesn't happen with your released 2.0.0 build however, is there anything you have done differently in your build environment to resolve this somehow?

**Comment by dogtopus** [comment]
Cannot reproduce this on custom 2.0.1 build

**Comment by Steveice10** [comment]
I haven't done anything special with my build environment. Just make sure yours is set up properly.

**Comment by ksanislo** [comment]
Problem still happens for me in 2.0.1, no problems with building anything else that I've run across, so I'm trying to figure out what could be different for me with this... What OS are you guys building with? I'm on Linux if that might make a diffference.

**Comment by Steveice10** [comment]
Same, weird that that would happen. Can't just use the 2.0.1 pre-build zip?

**Comment by ksanislo** [comment]
Alright. I'm using citro3d from ctrulib I believe at the moment. I'll poke around for a newer version other than the default one and try that next.

**Comment by urherenow** [comment]
I just built the source after re-building and installing the current ctrulib and citrus from this repo (not sure if citrus matters) and citro3d from https://github.com/fincs/citro3d. I have no such crashing issues with either the home button or pressing start (using installed .cia version, of course).

**Comment by ksanislo** [comment]
It was the version of libcitro3d causing the crash on exit. I rebuilt the current github version from source, and now the problem is resolved. Apparently the version packaged with devkitPro r45 is incompatible with this.
