### ISSUE TITLE
Problem Installing .cia files (games) with my 3ds 

### ISSUE THREAD

**Issue by Digitalium111** [Steveice10/FBI#500]
hi i have been having this problem with my 3ds using different cia games and i always get this error
Failed to install CIA files.
Result code: 0xD8E0806A
Level: Permanent (27)
Summary: Invalid argument (7)
Module: AM (32)
Desc: Cert signature or hash check failed (106)
now my brother also has a n3dsxl like me and we installed cfw the same way last week
using the same cia files he was able to install these games while i keep getting this error
i am kind of at a lost here since i am a complete newbie at this and i could really use some help as to why this is happening
we both have new sd cards 32gb both of them tested and formatted as requested same cfw
now please like i said if you can give me dumbed down explinations i would appreciate it as i only started doing this a few days ago

also i would like to add
fbi doesnt recognize version or region of the cia files
nor does it display their logos
i dont know why this is happening as i stated the same files were used in my brothers 3ds and worked perfectly

as an additional measure i also did a clean check of the sd card again today
i moved out all of the files and did a write.test with h2wtest and still no issues with that
so when i put back all of the files with the cia files it still happened
no version no region no logo
and whenever i try to install the game it gets to the end of installation and then i get that error
like i said i used the same cia on pretty much the same n3dsxl of my brother which i both of them installed cfw one after the other without fault and i got this on mine and on his it works like a charm

**Comment by BpyH64** [comment]
One of the reasons is that the file name CIA is too long,Rename files to game.cia ,game2.cia

**Comment by Steveice10** [comment]
If it's not showing the info in the file menu, then the 3DS's AM service is probably not recognizing it as a valid CIA and is returning an error. All I can really suggest is that you double check your CFW is set up correctly and try a different SD card, if possible.

**Comment by Ammako** [comment]
If that file worked for your brother and you have confirmed that your SD card isn't fake or corrupted, then you need to confirm that the files themselves haven't been corrupted from the transfer, because that can happen. Compare the checksums from the original file on your pc and the file that's on your SD card after the transfer, if they differ then there's your problem. If the files keep getting corrupted every time you copy them over to the SD card, try a different card reader.
