### ISSUE TITLE
FBI Conflit with new super mario bros 2

### ISSUE THREAD

**Issue by StigiTT** [Steveice10/FBI#501]
Hello everyone I use fbi 2.6 and I found a beug with a particular game actually launch you new sueper mario bros 2 launch you a game and enjoy leaving you the game and launch you fbi and boom fbi crash fbi at launch it does its that with this game I have to test with 20 other games no problem is very annoying considering that when I leave the game I go directly to fbi and bim his crash here is it is you are all to bawl you can try to reproduce it you must fbi 2.6.0 and new super mario bros 2 thank you and good evening

**Comment by InSimpleTermsJordan** [comment]
![portrait man in wig look at computer monitor what the fuck](https://user-images.githubusercontent.com/6912435/56843503-51837280-6867-11e9-9200-ee410667911b.png)

**Comment by StigiTT** [comment]
What

**Comment by Steveice10** [comment]
This has been reported before and was determined to not be an FBI issue. See https://github.com/Steveice10/FBI/issues/382
