### ISSUE TITLE
not dump all mails 

### ISSUE THREAD

**Issue by pretech86** [Steveice10/FBI#502]
firstly, thanks for this tool and nice work 
but i can't dump all contacts ? 
my OS is kali linux not android

**Comment by urherenow** [comment]
What are you talking about? This is for the Nintendo 3DS

**Comment by Steveice10** [comment]
I think you have the wrong GitHub repository.

**Comment by pretech86** [comment]
Sorry i opened a wrong tool ,, sorry for that
