### ISSUE TITLE
error installing cia

### ISSUE THREAD

**Issue by megamanzteam** [Steveice10/FBI#504]
Top screeen:
Game title: Fire Emblem Warriors 1.1 update
Attributes: None
Size 29.45 MiB
Title ID: 0004000E0F70CC00
Version: 1056 (1.2.0)
Region: North America
Installed size: 29.59 MiB

Bottom Screen:
Failed to install CIA file.
Result Code: 0xd8e08065
Level: Permanent (27)
Summary: Invalid argument (7)
Module: AM (32)
Desc: Error type -1 (101)

I was unable to find a list of common errors and the methods to fix them. So I am posting here for any help you can provide. If you require more information, please let me know and I will do my best to provide it.

**Comment by Steveice10** [comment]
Seems like it might be a ticket issue? Is it just this CIA causing problems? Otherwise it might have to do with tickets on your system.

**Comment by megamanzteam** [comment]
I think I had one other update file that had an error during install, but I think it was a different error. I will double check it later. You will also have to forgive me as I am rather new to homebrew. I am unsure what you mean by tickets. Where do I find them and how do I fix them?

**Comment by Steveice10** [comment]
Tickets are basically licenses to use software, and are included inside the CIA. If you have the error for the other CIA, I might be able to help with that.
