### ISSUE TITLE
Allow resuming network installs

### ISSUE THREAD

**Issue by NieDzejkob** [Steveice10/FBI#515]
When the server sends the HTTP header `Accept-Ranges`, and the download is subsequently interrupted by a network error, it's possible to resume the download by sending a `Ranges` header in the request. This is documented [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) on MDN.

Implementing this functionality in FBI would greatly help when installing over flaky networks.

**Comment by MercuryGamer** [comment]
But I don't install with WI-FI, I prefer with .cia files
