### ISSUE TITLE
FBI 2.X can't physically delete ticket

### ISSUE THREAD

**Issue by MelonGx** [Steveice10/FBI#52]
I tried deleting DevMenu ticket (it's an illegal ticket with CID 00000000 & pre-installed flag) in FBI 2.X's ticket option.
FBI showed the DevMenu ticket properly.
After the deletion, the DevMenu ticket never appeared on FBI's ticket option.
BUT, when I dumped ticket.db and browsed it with GroovyCIA, the DevMenu ticket still existed.
It looked like that it was not a delete but a ticket hiding function - could not be viewed by still recorded inside the database.

**Comment by Steveice10** [comment]
The ticket database format isn't fresh in my mind right now; are you sure it isn't just left over data that isn't actually pointed to by the database, and will be overwritten by a new entry later.

**Comment by dogtopus** [comment]
+1 for the left over data.
These data will be overwritten by any new CIAs/eShop contents installation.
If you are really worried about these left over data, try to remember the IDs of the tickets you want to delete, then dump your ticket.db, locate the data by ticket IDs and fill them with zeroes/garbages/xorpads/f-words(😏)/etc. using a hex editor, and inject it back
Remember: ALWAYS MAKE BACKUPS!

**Comment by Steveice10** [comment]
Closing, then.

**Comment by stebrick** [comment]
Sorry for bringing up this closed issue.  I am a bit confused, how could we know for sure the left over data will be overwritten by new CIAs/eShop contents installation? Any test could we do for that?  

Please excuse me if this question sounds too noobish...

**Comment by MelonGx** [comment]
>dogtopus
Do you mean after "deleting" ticket with FBI 2.X, when you visit e-shop and do some purchase/download things, the "deleted" ticket will be vanished by browsing ticket.db with GroovyCIA?

If no, then your report answers nothing.

**Comment by MelonGx** [comment]
1) DevMenu / Homebrews have unavailable Title ID so they cannot be overwritten.
2) No matter whether it is the leftover or not, GroovyCIA can detect it, so can Nintendo.

**Comment by dogtopus** [comment]
For 1, Overwriting does not depend on title ID
For 2, I don't think Nintendo will do this because it may bring serious security issues (give NAND/raw ticket.db access permissions to userland programs, etc.)

**Comment by dogtopus** [comment]
@stebrick I did an experiment earlier. Basically just bunch of (un)installations.

**Comment by stebrick** [comment]
Thanks for the response!!

So, does it mean that devmenu / homebrews title can still be overwritten by subsequent installation?  And, when it had been overwritten, could it still be detected by GroovyCIA, or is it completely gone?

Thanks so much!

**Comment by dogtopus** [comment]
AFAIK yes, and GroovyCIA should not detect them since the data has been completely overwritten

**Comment by thaikhoa** [comment]
I've just tried to install DevMenu then using Tickets to delete it from there. Dump and decrypt ticket.db and figured out that it's still there. Again, tried to install something from eShop and dump & decrypt ticket.db and it's still there as well....

**Comment by dogtopus** [comment]
@thaikhoa Maybe it overwrites something else (like an older empty slot). Did you try to use a binary diff tool to see what was changed in your ticket.db?

**Comment by thaikhoa** [comment]
I did compare the two. They are completely different which are covered for a whole file.
