### ISSUE TITLE
i can't build the files

### ISSUE THREAD

**Issue by Vincysuper07** [Steveice10/FBI#520]
when i try building the cia with devkitpro, i get this error: /opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/9.1.0/../../../../arm-none-eabi/bin/ld: build/3ds-arm/source/fbi/task/listtitledb.o: in function `task_populate_titledb_thread':
/Users/vincysuper07/Desktop/fbitdb/fbi/source/fbi/task/listtitledb.c:364: undefined reference to `http_download'
collect2: error: ld returned 1 exit status
make: *** [output/3ds-arm/FBI.elf] Error 1
please help

**Comment by Steveice10** [comment]
Not sure if you're still having this issue, but I'm able to build fine on my end. Make sure you have all the right libraries set up.
