### ISSUE TITLE
Cannot install any .cia files, please help! 

### ISSUE THREAD

**Issue by killer1048** [Steveice10/FBI#521]
I was trying to install a cia game then this error popped up:

Result code: 0xC86044D2
Level: Status (25)
Summary: Out of resource (3)
Module: FS (17)
Desc: Partition full (210)

I have an OLD 11.12.0-44E Nintendo 3DS

I download .cia files from 3dscia.com
![15730581206008821814538777183041](https://user-images.githubusercontent.com/41374239/68317691-daebeb00-00bb-11ea-9aab-0a4528b9d3d9.jpg)

Game: Nintendogs + Cats labrador edition, i made it shorter cause i thought it was the problem

**Comment by Steveice10** [comment]
You don't have enough space on your SD card. Notice that the CIA's installed size is 455.94 MiB, but you only have 229.8 MiB free on your SD card.
