### ISSUE TITLE
Can't install from ftp.

### ISSUE THREAD

**Issue by TNTgamer71** [Steveice10/FBI#522]
I run a ftp server with .cia files in and would love to network install from ftp but whenever I try to install from ftp it does http://ftp://192.168.0.69/file.cia and then errors as it can't find it.

**Comment by Steveice10** [comment]
The network installer does not support the FTP protocol, only files served over HTTP.

**Comment by Steveice10** [comment]
If you're looking to send a local file from your PC, FBI comes bundled with a script called servefiles that can do this.

**Comment by TNTgamer71** [comment]
I want to be able to host a file from ftp and someone else outside my local network can download and install.

**Comment by urherenow** [comment]
That’s not how ftp works. That someone else can download the file from your ftp server using their computer. Then, using their computer, along with ftpd on the 3ds, send it to their 3ds using that same client. Then they can install it with fbi.

**Comment by TNTgamer71** [comment]
They don't have a pc tho
