### ISSUE TITLE
Error codes and some other problems in my 3DS

### ISSUE THREAD

**Issue by MercuryGamer** [Steveice10/FBI#523]
I have these problems in my FBI, and some issues in my 3DS:
- When I want to install a .cia, there is an error code, when I try to install it says:
   "Failed to install CIA file.
    Result code: 0xD9004588
    Level: Permanent (27)
    Summary: Wrong argument (8)
    Module: FS (17)
    Desc: RSA/Hash verification failure (392)"
- When I try to delete something that I couldn't in the 3DS Settings:
   "Failed to delete title.
    Result code: 0xD9004588
    Level: Permanent (27)
    Summary: Wrong argument (8)
    Module: FS (17)
    Desc: RSA/Hash verification failure (392)"

And I don't know how to fix them, and in my 3DS Settings appear some blanks and when I try to install other region or something replacing the game, it give me some problems, so, can I get some help, please? (I bought a Adata SD card two months earlier, thinking about to fix this, but it seems that no), any useful help is thanked

**Comment by Steveice10** [comment]
It sounds like there's probably an issue with the title database files on your SD card. A good way to confirm this would be to rename the "Nintendo 3DS" folder on your SD card to something else and let the system create a new one. If the problem persists, there could be a problem with the filesystem or the SD card itself.

**Comment by MercuryGamer** [comment]
Ohhh, I'll try it, thanks!

**Comment by MercuryGamer** [comment]
It looks like it worked (i think, there's no games in settings) what I have to do now?

**Comment by Steveice10** [comment]
Try installing some games. If you haven't already, you could try putting the original folder back and going into the data management settings to see if the 3DS will auto-repair the data, unless it didn't offer to do so before.
