### ISSUE TITLE
[Request] Allow Changeing Title Setting (Visibility, Other Things)

### ISSUE THREAD

**Issue by CatsLover2006** [Steveice10/FBI#525]
Can you make it so that we can modify the metadata of existing titles, particularly the ones at [https://www.3dbrew.org/wiki/SMDH#Flags](https://www.3dbrew.org/wiki/SMDH#Flags)
I am primarily interested in:
* Title Visibility
* SD Save Data Backups
* Application Usage Recording

**Comment by Steveice10** [comment]
This is out of scope, you'll need to make those edits before installing the title.
