### ISSUE TITLE
Red screen on homebrew when installing

### ISSUE THREAD

**Issue by GammaRay69** [Steveice10/FBI#526]
so i got homebrew and wanted to download FBI on it. But any time in the process it will turn from a command prompt to a red screen. i tried every trick but it didnt work. is there one way that i could fix it. i would tap the fbi installer in homebrew, then a command prompt. THEN A RED SCREEN. Please send me something.

**Comment by Wryyyong** [comment]
Do you have Luma3DS running?

FBI will not work at the userland level; it requires ARM11/ARM9 permissions (at least ARM11 for signed CIAs, and ARM9 for unsigned CIAs).
