### ISSUE TITLE
.3ds file no longer works after 2.5.0

### ISSUE THREAD

**Issue by PikachuR77** [Steveice10/FBI#527]
The .3ds file for 2.5.1+ no longer works from the Gateway menu. It just shows up as a white icon. 2.5.0 was the last version to work properly.

**Comment by urherenow** [comment]
Gateway isn’t even supported by Gateway anymore. Just use the .3dsx. Or install the .cia (initially using the .3dsx).

**Comment by PikachuR77** [comment]
Even so, it should either be fixed or not be included in the download if it's not possible to fix it.

**Comment by unresolvedsymbol** [comment]
I'm pretty sure this is a buildtools issue

**Comment by unresolvedsymbol** [comment]
Well for the time being... https://github.com/unresolvedsymbol/FBI-gw/releases
