### ISSUE TITLE
FBI Crash on Install CIA file

### ISSUE THREAD

**Issue by Foxxify1** [Steveice10/FBI#528]
**Model:**

old 2ds

**SysNAND Ver:**
(latest)
11.13.43-U

**Entrypoint:**
(latest)
B9S

**Luma 3ds Ver:**
(latest)
10.0.1

Upon installing the latest version of @RocketRobz TWiLight Menu.cia found in the 7z folder, my 2ds crashes. I've looked around, and it seems that I'm the only one having this issue... I have installed previous versions of this cia file and they worked. Now I don't see the previous version anywhere; it's not in the Settings > Data Management or even in the FBI titles list. Any help would be greatly appreciated. Thanks!

[crash_dump_00000005.zip](https://github.com/Steveice10/FBI/files/4123732/crash_dump_00000005.zip)

**Comment by MisterPrintf** [comment]
This is most likely a bad CIA. To get around it, try using the updater instead.
