### ISSUE TITLE
Over the network install doesn't work. It fails in pc but says it was succefull in 3ds.

### ISSUE THREAD

**Issue by poutros** [Steveice10/FBI#53]

**Comment by deadair3210** [comment]
Seconded. Just had SocketPunch fail while the 3ds said that the install had succeeded. Tried this with a small file and a 1.6 GB file

**Comment by poutros** [comment]
This release is supposed to work:

https://gbatemp.net/threads/release-socketpunch-fbi-network-cia-installer-for-android-pc.412174/page-16#post-6254075

**Comment by Steveice10** [comment]
Old utilities and older versions of sockfile are not supported.
