### ISSUE TITLE
Can't install DLC that has 711 files inside 

### ISSUE THREAD

**Issue by ExData7** [Steveice10/FBI#530]
Tried to install the Metal Max 4 dlc which has 711 files inside the cia but FBI only installs part of the dlc which leads to the game crashing when i try to access it ingame, since its all not installed properly, only about half is installed. 

Also FBI gets laggy and installation speeds for this particular dlc, even on a New 3DS

**Comment by Steveice10** [comment]
Are you certain you have a good CIA for this DLC? FBI just passes the bytes of a CIA file along to the 3DS OS's application management service, which is where all the actual unpacking and installation happens.

**Comment by ExData7** [comment]
Unless every place I got the cia from has a bad source, I'm not really sure. I verified it with godmode9 it said there was nothing wrong with it unless that's a false positive
