### ISSUE TITLE
FBI will not install cias

### ISSUE THREAD

**Issue by AnimeFloof** [Steveice10/FBI#531]
So I have two CIA's. One is from an off-site website (I grabbed the same one from different sites since I first thought it was the CIA) The other is from the OFFICAL site of the app.

FBI will not give me the option to install CIA's!

**Comment by urherenow** [comment]
Umm... yes it does install .cias. That’s its main purpose. 

If something won’t install, are you running Luma under b9s or fastboot 3ds? Do you have enough room on your nand or sd?

Need more information to help, starting with your environment (few version, entry point, etc).
