### ISSUE TITLE
Not exactly a issue, but a question

### ISSUE THREAD

**Issue by Legarad** [Steveice10/FBI#537]
I was installing a .cia from the SD, but there was a small blackout and the 3DS went out during the blackout because it has a almost damaged battery. The game was not installed but the space was consumed. How do I fix that?

**Comment by Steveice10** [comment]
If you try to install the CIA again it might just overwrite whatever is partially installed, reclaiming the space. Otherwise, perhaps find out the title ID of your CIA and try to find the folder it was being installed to on the SD, and then delete that folder.

**Comment by Legarad** [comment]
The strange thing is that in the SD memory there is not a folder with that game ID in the titles folder inside the Nintendo 3Ds folder. Still consumed the space.  In the FBI it says that the ticket was generated in tickets section.

**Comment by Steveice10** [comment]
I would just try installing the CIA again, then.

**Comment by Legarad** [comment]
I already installed it and I still have the lost 650 MB from the first installation

**Comment by Steveice10** [comment]
The best advice I can give you, then, is to look around the SD card for where it might've put the files while they were being installed, perhaps by checking folder sizes. I don't recall where exactly the 3DS puts them.

**Comment by Legarad** [comment]
Nintendo 3DS/ID0/ID1/title/

00040000 - Games
0004000e - Updates
0004008c - DLCs

In the folder 00040000 there is no folder of the game identification, although adding the spaces occupied plus the real memory space, it has still consumed space from the first installation.
