### ISSUE TITLE
Possibility to install multiple same titleID cia 

### ISSUE THREAD

**Issue by Theone5000** [Steveice10/FBI#539]
First of all I really enjoy the FBI application and all of the features. Used it on Gateway and now on Luma3DS. 

What i'm writing is not a issue, but rather a request"

- **Could you make it possible to write a feature that once you select and install a .cia the system checks if the a same TitleID is present and asks if you want to create another instance?**

For example you have 2 PkMn titles that have the same TitleID. But if you have different versions of the same game the FBI installer keeps overwriting the other. If you would press [Install CIA] you would get the *new option. 

Thanks. :) Hope to see new updates in the near future.

**Comment by urherenow** [comment]
Not possible, without changing the TitleID to a different one. FBI doesn’t create a .tid, it just passes it along to the system. Your only solution, would be to rebuild the cia yourself, with a different .tid. You may want to start by studying the use of makerom.
