### ISSUE TITLE
Abnormal behavior after enabling external theme

### ISSUE THREAD

**Issue by dogtopus** [Steveice10/FBI#54]
After ce821c7, when external theme enabled (place fbitheme on SD card root), FBI starts to behave weirdly. (Throws out of resource error when opening Title List, custom textures are only partially loaded, and most importantly, I got a hard crash when I tried to exit FBI with Home button)

**Comment by Steveice10** [comment]
What exactly do you have included in the external theme? (Just copying a few PNGs from the actual resources and putting them on the SD card doesn't seem to be helping to reproduce it)

**Comment by Steveice10** [comment]
Never mind, should be fixed now. (https://github.com/Steveice10/FBI/commit/2d8a117ed2b664266745f7d992c9af290b57d31b)
