### ISSUE TITLE
build specify target

### ISSUE THREAD

**Issue by giveup** [Steveice10/FBI#55]
In issue #48 ,Everytime i get error to output 3dsx.(I can manually convert to 3dsx)
Is possible to skip this and direct build specify file(like cia?)
eg, make cia make 3dsx.
Sorry for my ugly English.

**Comment by Steveice10** [comment]
There is currently no option to output specific build types, but you could manually open up buildtools/make_base and remove the 3dsx from the output list. As for fixing the issue, try updating your copy of 3dsxtool from the source repository.
