### ISSUE TITLE
Filesystem access (3dsx)

### ISSUE THREAD

**Issue by idgrepthat** [Steveice10/FBI#57]
Allow filesystem access on CTRNAND and TWLNAND for 3dsx build. NAND dumping as well if possible. (enhancement)

**Comment by Steveice10** [comment]
Impossible, at least for the moment. Would require ARM9 patching, as I can't control exheader ARM9 I/O access flags.

**Comment by idgrepthat** [comment]
That's what I thought. Damn. 
Thanks for the explanation.
