### ISSUE TITLE
Using with Unversal inject Genenerator

### ISSUE THREAD

**Issue by Chiejina** [Steveice10/FBI#58]
I'm using this FBI file with Universal Inject Generator Master. When injected and has replaced health and safety app, It hangs on the loading screen. Where it says Nintendo 3DS.

New 3DS 9.2  and New 3DS 10.7

**Comment by RShadowhand** [comment]
This is a known problem with an unknown cause. It's being investigated as we speak.

**Comment by Chiejina** [comment]
Ahh okay thank you. I kept googling the problem but couldn't find someone with the same problem. Thanks for the clearification.

**Comment by mariogamer2** [comment]
I think it's can be reopened until @Steveice10 has solved the problem.

**Comment by Steveice10** [comment]
It's already fixed on the inject generator side...
