### ISSUE TITLE
Quick Network install mode

### ISSUE THREAD

**Issue by gudenau** [Steveice10/FBI#6]
I would like a mode where it installs a cia that is sent over the network, after the cia is installed it would be launched. Hold Y when starting FBI to activate?

**Comment by Steveice10** [comment]
You... could just use the normal network installation, switch to launch, and launch it.

**Comment by gudenau** [comment]
It would be faster.

**Comment by Steveice10** [comment]
It wouldn't be all that faster. Plus, what's the point? Installation is generally a one-time thing, so once it's installed you can easily launch it as many times as you need

**Comment by gudenau** [comment]
Devolpment.
