### ISSUE TITLE
Ticket deletion 

### ISSUE THREAD

**Issue by thaikhoa** [Steveice10/FBI#61]
Hi,

I've tried to delete a ticket but it doesn't delete in ticket.db.

Are you going to support listing uninstalled tickets in ticket.db (currently only installed tickets will be displayed)?

Thanks for your amazing project and keep it up.

Regards.

**Comment by Steveice10** [comment]
I'm doing all I can right now with the commands available to me.

**Comment by dogtopus** [comment]
What tool did you use to browse tickets?
Some (probably all currently since the format of ticket.db isn't fully reversed yet) tools use pattern searching to find tickets, which means they will list garbages in the ticket.db

**Comment by thaikhoa** [comment]
I'm using Groovy.
