### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by MAXAITA** [Steveice10/FBI#64]
When install a large cia the programs freeze only can off

**Comment by Steveice10** [comment]
Can you be more... descriptive?

**Comment by MAXAITA** [comment]
thanks for your work is really good.

  yesterday I try to install the Pokemons x which has a size of 1.7 Gb when
I get to 32% frezee stayed when I try to cancel not allowed so I had to
turn it off. when lit the 3DS was installed but better desistale and
install it with the old version and let me install normally.

Sorry for my English I only speak Spanish.









2016-04-16 20:25 GMT-06:00 Steven Smith <notifications@github.com>:

**Comment by gunner007cd** [comment]
I've only seen it happen once with a random CIA. It really has nothing to do with the size as the only one I had was about 800MB.

It starts the install process fine, but at varying points (tried 3x) the console locks up. (no progress on screen, buttons stop responding) forcing power off. Installing with another CIA installer went fine though. Hard to reproduce - but happened once when I formatted my console and reinstalled a few CIA's.

**Comment by BPSpike** [comment]
Same thing happened to me, with a 320mb cia install, it worked fine after a reset.

Also, managed to freeze it after installing a cia, pressing the home button and returning to FBI after checking the home menu for the gift.

**Comment by Steveice10** [comment]
Can anyone verify if this still happens in v2.0.5?

**Comment by MAXAITA** [comment]
version 2.0.5 
name : pokemos Y
size 1723.58 MB
title id : 00040000055E00
version: 16
installed size : 1724.78 MB


error freeze in 
407.25 mB / 1723.58 Mb


the 3ds not working no responding but if you wait a some time and off the 3ds when you on the game is install.

**Comment by MAXAITA** [comment]
![img_20160417_160901 small](https://cloud.githubusercontent.com/assets/13879355/14590492/eb74221a-04b8-11e6-8309-77e1a5ce97f1.jpg)

**Comment by MAXAITA** [comment]
![img_20160417_164048 small](https://cloud.githubusercontent.com/assets/13879355/14590563/09d0f966-04bb-11e6-992d-df39daaaeac7.jpg)

**Comment by rinforzando** [comment]
I'm still getting some issues installing CIAs on v2.0.5.  Sometimes the screen freezes, and sometimes the bottom screen goes black.

**Comment by xadox-1st** [comment]
Also happens for me on N3DS on several files.
The bottom display gets dark and only hard reset helps to restart.

Also this freeze was occuring while only selecting some CIA's.

**Comment by Steveice10** [comment]
Does this issue still occur with this build?

https://www.dropbox.com/s/866yhujdg859mor/FBI.zip?dl=1

**Comment by ratmon19** [comment]
Yeah I get freezes to with some cias. Complete freeze only way to turn the power off.

**Comment by Steveice10** [comment]
@ratmon19 *With* the build I linked just now?

**Comment by Steveice10** [comment]
With the latest source, I just successfully installed a CIA of FBI enlarged to 943MB. Going to consider this fixed.

**Comment by xadox-1st** [comment]
Tested the https://www.dropbox.com/s/866yhujdg859mor/FBI.zip?dl=1 build today.
Until now no free while installing.

But already got two total black screens while starting from HomeMenu.

**Comment by zenkilye** [comment]
2.2.1 release still encounter this issue, black lower screen or progress freeze, need to power down. However only noticed this on New 3ds Old 3ds installed a lot cia without issue on 2.2.1
