### ISSUE TITLE
CJK support

### ISSUE THREAD

**Issue by jejer** [Steveice10/FBI#65]
If cia filename contains Chinese characters, The filename will not properly displayed and the filesize displayed as 0. this prevent FBI to install the cia file.

**Comment by jejer** [comment]
Also no CIA info for those files.

**Comment by Filo97** [comment]
well, you can just rename it

**Comment by Steveice10** [comment]
Fixed support for UTF-16 characters. Files with names in other languages should work fine for all operations as of the latest commit, however some, like Chinese, aren't supported by the 3DS font, and therefore will still show up as "?" boxes. Nothing I can really do about that.
