### ISSUE TITLE
last FBI release error

### ISSUE THREAD

**Issue by Casporro** [Steveice10/FBI#67]
I inject last FBI release in H&S (hs.app) but when I open it says that FBI has encountered a fatal error...
***Failed to open text color config: No such file or directory***

**Comment by CrashMan054** [comment]
Have you tried installing it as a normal CIA, without using h&s?

**Comment by Casporro** [comment]
Yes, works fine

**Comment by Steveice10** [comment]
Sounds like a RomFS issue. Either you aren't using the latest inject generator and the "with banner" version of the inject app, or there's likely another issue with the injector.

**Comment by EmuAGR** [comment]
This keeps happening on 2.4.2.
