### ISSUE TITLE
doesnt work on ninjahax 2.0

### ISSUE THREAD

**Issue by B1oodCobra66** [Steveice10/FBI#7]
will open and try to install but says 
Install failed!
Could not initalize AM service
Press Start to continue.

And whenyou press select to Install MSET ROP and try to install anything it says
ROP installation failed!
Raw Error: 0xd8e06406
Module: MODULE_NN_SRV (0x19)
Level: LEVEL_PERMANENT (0x1b)
Summary: SUMMARY_INVALID_ARGUMENT (0x7)
Dsescription: DESCRIPTION_ACCESS_DENIED (0x6)
Press Start to continue.  

I am running ninjahax 2.0 on firmware 9.9.0.26u

**Comment by d0k3** [comment]
Well, you wouldn't be believe ;). You know that Ninjhax 2.0 doesn't have the same capabilities that Ninjhax 1.x has? There's no way you can install CIAs on a FW bigger than 9.2.0, sorry.

**Comment by Steveice10** [comment]
As I've stated in multiple places, FBI cannot work with Ninjhax 2.0 as I can't gain access to the needed services.
