### ISSUE TITLE
Long title reloading time

### ISSUE THREAD

**Issue by Akurosia** [Steveice10/FBI#70]
When accessing the "Titles"menu option it sometimes take a long time till it run smoothly (most likly due to lots of cias installed).
Would it be possible to do it in a similar way as "JK's Save Manager" did it? e.g. loading all titles once into a list to speed up re-accessing time and only refresh list with a button or once something was deleted ect?

**Comment by Steveice10** [comment]
This is a result of loading title metadata for names and icons.
