### ISSUE TITLE
[Suggestion] Add FileZilla Support that NASA 1.6 has?

### ISSUE THREAD

**Issue by SirBeethoven** [Steveice10/FBI#71]
The recent NASA 1.6 release includes FileZilla Support and it's AMAZING! Please add if you can!

**Comment by Steveice10** [comment]
Can you elaborate on how FileZilla is used? I've never used NASA before.

**Comment by SirBeethoven** [comment]
You first boot the NASA CIA (here's the official link to it: http://adf.ly/1ZPPNv). Then you look at the IP on the top screen and take note of it. Then, you boot up FileZilla on your computer here: https://filezilla-project.org/ download the client. Then you click on the button under "File" and then type in the IP that was displayed on the top screen of NASA
![capture](https://cloud.githubusercontent.com/assets/16980168/14759343/99e870e6-08e5-11e6-9536-357dbe198e77.PNG)
![capture2](https://cloud.githubusercontent.com/assets/16980168/14759342/99e80e94-08e5-11e6-86f7-3850bb40895e.PNG)

**Comment by Steveice10** [comment]
Yes, but are you transferring files to the SD? Installing? Etc?

**Comment by SirBeethoven** [comment]
So after I type in the IP displayed on the 3DS's top screen, I can press the "Connect" button. Then in FileZilla, I have the option to open the "NAND" or "SDMC" folder. I double click into one of those and then drag the CIA that's on my computer (on the left) over into the right in the folder! 
![captur4e](https://cloud.githubusercontent.com/assets/16980168/14759421/79b1ae5c-08e8-11e6-8391-006c0ec21cd3.PNG)
![captur3e](https://cloud.githubusercontent.com/assets/16980168/14759420/79adc79c-08e8-11e6-8e98-cfab62d6f01a.PNG)

**Comment by SirBeethoven** [comment]
The CIA's are not on the SD card at all (although that is an option in NASA to do a direct install) This is more like a network install but works much better and works on a better platform. With this way, I can even delete files using the network!

**Comment by Steveice10** [comment]
Don't really see a purpose, then...especially with the QR code installation mode in the latest source, there are already plenty of ways to install remotely.

**Comment by SirBeethoven** [comment]
Ok thanks! Please give pointers to the creator of SocketPunch as there are still some incompatibilities and errors
