### ISSUE TITLE
Skip invalid ticket instalation automatically

### ISSUE THREAD

**Issue by poutros** [Steveice10/FBI#72]
I'm using CIAngel and it seems it creates loads of invalid tickets(~600 from my count) and it would be nice to just skip them all instead of constantly having to hit a key or the screen to continue.

Btw, the error message is always:
Failed to install ticket
[ticket location]
Result code: 0xD8E08019
Level: Permanent (27)
Summary: Invalid argument (7)
Module: AM (32)
Desc: `<unknown>` (25)

**Comment by poutros** [comment]
Linking this as it may be relevant: https://github.com/llakssz/CIAngel/issues/25

**Comment by Steveice10** [comment]
If a ticket is invalid, FBI is going to report the error. Not my problem if they're invalid.

**Comment by poutros** [comment]
Yeah, but it could be auto skiped.
