### ISSUE TITLE
Returning to the same position in the list after managing an entry?

### ISSUE THREAD

**Issue by d0k3** [Steveice10/FBI#73]
This is just a small feature request / idea. If I go through my list of CIAs for a cleanup now, and f.e. delete one entry, then go back, I'll end up back at the start of the list. I think it would be more convenient if we would return to the same place after any operation on an entry.

You'll need to be careful that the cursor doesn't up after the end of the list (with list size altering operations like deletions) and this will be a bit tricky when doing file name altering operations (in case of a rename, should the cursor be repositioned on the new name, or should it stay at the same position?).

**Comment by z235** [comment]
This would be fantastic for the ticket browser. It would make ticket deletion a whole lot faster and easier.

**Comment by Steveice10** [comment]
Done. I had to make a lot of internal adjustments to make this possible, so any bug testing you can do would be appreciated.

Here's a build with the changes in: https://www.dropbox.com/s/866yhujdg859mor/FBI.zip?dl=0

Closing this for now since the feature is at least implemented.

**Comment by d0k3** [comment]
Okay, tested it for a while, that feature works and I think it will be very useful. I also noticed no new problems. Thank you! Other stuff still has problems (like the titles screen freeze), but I assume that's not yet in that test build.

I'll give it a more thorough test once there is a new release version.
