### ISSUE TITLE
[Bug] Transfer CIAs game via Wifi

### ISSUE THREAD

**Issue by yonkishum** [Steveice10/FBI#76]
Ho everybody, I try to use the Network Instalation when I pushed (trought Socketpunch) in my 2DS I recieve the instalation but... never complete and start a infinite loop trying to install it, please fix it :+1: nice work guys (Sorry for my bad English :'( )

**Comment by Steveice10** [comment]
Have you tried with sockfile?

**Comment by yonkishum** [comment]
Hmmm I've never done before, some tutorial or guide :D! thanks for response :+1:

**Comment by Scrxtchy** [comment]
Thanks, Shall give this a try, I was getting a familiar issue with SocketPunch
There have been a few untitled commits to it's repo, with last updates a month ago

But I'll ping @Olmectron and see if there's an upcoming release

**Comment by Olmectron** [comment]
@Scrxtchy Yeah. It's a problem with SocketPunch. I'm releasing a new update, yes, but it's coming in some more days. Maybe next Saturday. Thanks for pinging.
