### ISSUE TITLE
Strange Crash when Idling during Install?

### ISSUE THREAD

**Issue by CrispyYoshi** [Steveice10/FBI#78]
Hi! I was installing a large game on my USA N3DS non-XL system using FBI.cia on 10.7 sysnand running AuReiNand (pre-Luma3DS)+A9LH, and I decided to let the game install while I ate dinner with my family.

When I came back, my 3DS hung on a complete black screen, but my wifi switch was still blinking. I tried pressing Home but it didn't do anything (I didn't hear anything either.) So I force-shut off my system. When it reboot, it turned out that the game had completely finished installing before the system crashed, so it must have crashed at some point while idling on the "Install Completed" screen.

**Comment by Steveice10** [comment]
Is this with the latest version? (2.1.1)

**Comment by CrispyYoshi** [comment]
Whoa, sorry. I thought I updated: I just checked in the app itself, and it says the version is "2.0.5".

**Comment by urherenow** [comment]
Depends... did you build it yourself or do you always download? If you build yourself, take a look at #79

**Comment by d0k3** [comment]
I actually had a crash with 2.1.1, installing a 2GB+ CIA yesterday. It just hung at ~850MB for an eternity, so I was forced to shutdown. I guess this might be a completely different issue though. Worked fine when I used FBI 1.4.17 afterwards, btw.

**Comment by CrispyYoshi** [comment]
I used the release. I think I installed it just before installing the .cia and reported it right when I got back, so whichever version was released 16 hours ago (at the time of this posting)

**Comment by MAXAITA** [comment]
the same i install 2 cias 

ther first ok

the second freeze but i restart and game is install ok

**Comment by MAXAITA** [comment]
![img_20160426_121830 small](https://cloud.githubusercontent.com/assets/13879355/14829610/93a57780-0ba9-11e6-9cfe-0dff1c74ca10.jpg)

**Comment by Steveice10** [comment]
Can you test if this happens in this build?

https://www.dropbox.com/s/866yhujdg859mor/FBI.zip?dl=0

**Comment by MAXAITA** [comment]
the last version no problems. it ok

**Comment by Steveice10** [comment]
Closing, then. Feel free to reply further if new information comes up.
