### ISSUE TITLE
[minor] Rolling your own doesn't update (displayed) version

### ISSUE THREAD

**Issue by urherenow** [Steveice10/FBI#79]
version number hardly ever changes. Building current source gives me 2.0.3. Just a minor annoyance...

**Comment by Steveice10** [comment]
Make sure you're pulling tags. Those are what provide the version number.

**Comment by urherenow** [comment]
Sorry. I may have mentioned this before. Made a simple batchfile and stuck it into devkitPro\msys\bin so it won't happen again. All I need to do now, is type "update" 😁 

git pull origin master
git submodule update --init --recursive
git fetch --all
make clean
make
