### ISSUE TITLE
add version number in title 

### ISSUE THREAD

**Issue by MAXAITA** [Steveice10/FBI#81]
You can see easy than version with problems like games

**Comment by Steveice10** [comment]
Not entirely sure what you mean. Are you talking about the FBI version, game versions, or something else entirely?

**Comment by MAXAITA** [comment]
![img_20160426_191426 small](https://cloud.githubusercontent.com/assets/13879355/14838937/b59cbeb8-0be3-11e6-9805-7b59be9858a4.jpg)
![img_20160426_191505 small](https://cloud.githubusercontent.com/assets/13879355/14838938/b5a181be-0be3-11e6-9f1f-d1f85b9412e1.jpg)

**Comment by MAXAITA** [comment]
to easily identify the version of your program and you see if the latest version

**Comment by Steveice10** [comment]
The version is already on the main menu, right under the logo.

**Comment by MAXAITA** [comment]
if I can but if you add in the title of every window you can control if people have the latest version when you report errors

**Comment by Steveice10** [comment]
Eh, I guess I don't see why not. Implemented.
