### ISSUE TITLE
Freeze on CIA folder install

### ISSUE THREAD

**Issue by xadox-1st** [Steveice10/FBI#85]
Yesterday used folder install and delete of 9 CIA's from 50 - 900MB. Freezed on the third one (CIA had 450MB size).

Both Screens show info, but no more progress is done.
Manually installing the CIA's was working fine.

Used FBI 2.1.1, CIA Version on N3DS XL A9LH+SysNAND.

CIA's were created by FunKeyCIA.
Tickets were not installed previosly.

**Comment by Steveice10** [comment]
Should already be fixed for the next release.
