### ISSUE TITLE
Would you post the .cia itself in the release again, instead of only the archive?

### ISSUE THREAD

**Issue by ksanislo** [Steveice10/FBI#86]
With the upcoming URL redirection working in v2.1.2 or whatever version is next released, it would be nice to be able to just scan a QR on the release page to upgrade, instead of needing to pull the SD and install manually.

I can volunteer some server space if you want to host the 2.1.2 upgrade itself somewhere that 2.1.0 and 2.1.1 can hit it directly instead of the github CDN, so people can scan to upgrade from them as well.

**Comment by Steveice10** [comment]
I've been wanting to do this, but I still need to see if there's a way to get a link that will always point to a file in the latest GitHub release, so I don't have to update the QR code all the time.

**Comment by yuukiw** [comment]
do you mean the relase itself or to the site?

if you mean the site you can just use:
https://github.com/Steveice10/FBI/releases/latest

**Comment by yuukiw** [comment]
alternatively you could crawl through that api text to get the newest version and put the version number in an variable which is used in the url 
https://github.com/Steveice10/FBI/releases/download/"VNumber"/FBI.cia

you could search for "  "tag_name" and parse the number next to it, currently 2.1.1.
(  "tag_name": "2.1.1",)

**Comment by ksanislo** [comment]
Since github doesn't seem to provide a simple redirect for this themselves, I was thinking that I could probably host a simple redirection/QR generation service that pulled from the github API that would allow for this. It would also provide an easy way for people to make a branded style QR with an FBI logo in it for their projects. Which might help newcomers more easily identify what to use to scan and install homebrew apps, instead of trying the stock browser QR scanner.

It could be a few days before I can get to writing something like this though, since I seem to be dying of the flu this weekend.

**Comment by svanheulen** [comment]
@ksanislo Using a third party to redirect is a security concern. A third party could easily redirect to a malicious CIA instead of the one you're expecting. Not that I'm saying you would do that, just that it's a concern.

@Steveice10 I know it's not ideal, but if you put the CIA in the repo, it will have a static URL.

**Comment by Xenosaiga** [comment]
Why not just program an "Update FBI" option in the menu and have that link point directly to the GitHub page where the CIA would be located. No need to redo a QR code every time would there?

**Comment by trohrt** [comment]
Why not just add the latest compiled version to the repo? Then you could just set the url to https://raw.githubusercontent.com/Steveice10/FBI/master/FBI.cia

**Comment by YodaDaCoda** [comment]
Actually trohrt's suggestion would probably work the best... though I suggest putting the cia alongside a text document containing just the version number. Then you can fetch the txt and check its contents against the internal version number, and conditionally download the cia. (probably put these two files in a different branch or repo though, just for better management)

This would give you a static URL which you can put into a QR code, and also allows for an internal update mechanism without messing around with parsing the github json. Just my 2¢.

**Comment by ksanislo** [comment]
I'd still settle for starting with the .cia itself /somewhere/ on the release page, so I could at least generate QR links directly for people who need to upgrade, without having to mirror the file elsewhere first...

**Comment by yuukiw** [comment]
but why letting the user go through that hassle? Simply automaticly scan for an updated cia this isnt so hard...

**Comment by Steveice10** [comment]
Added a CIA to the latest release downloads.
