### ISSUE TITLE
QR Code Install Freeze

### ISSUE THREAD

**Issue by Plailect** [Steveice10/FBI#87]
On v2.2.0, when attempting to select the "QR Code Install" option, the device freezes entirely (before the camera even shows up) and needs to be hard reset by holding the power.

**Comment by Steveice10** [comment]
Fixed.

**Comment by NinjaBoyLao** [comment]
still not fixed...

**Comment by Steveice10** [comment]
Did you get v2.2.1?

**Comment by NinjaBoyLao** [comment]
Yes, it only works about 2/3 of the time

**Comment by Steveice10** [comment]
Working fine here. Check and make sure your camera works just fine elsewhere, as I myself have a somewhat faulty camera on my old 3DS.
