### ISSUE TITLE
only show the free space that current driver

### ISSUE THREAD

**Issue by MAXAITA** [Steveice10/FBI#88]
is more confortable to see only free space that current driver. The letter is very small when show all driver

**Comment by Steveice10** [comment]
Certain times it could be relevant, such as when deleting titles, are not tied to any specific partition. Either way, it's fine as is.

**Comment by MAXAITA** [comment]
the font size is very small

**Comment by Steveice10** [comment]
It's good enough to be perfectly readable, though.

**Comment by MAXAITA** [comment]
ok tank you
