### ISSUE TITLE
Still getting the occasional freeze/black screen.

### ISSUE THREAD

**Issue by gunner007cd** [Steveice10/FBI#89]
Tried using FBI 2.2.0 to install 5-6 CIA's.

4 installed fine, 5th one (1720MB) froze at 80%.
Rebooted and tried again, 4th installed normally.
Tried to install 5th, and halfway through, the bottom screen went blank and locked up.

Rebooting and trying to install again was successful though.
Same thing happened whether was using the CIA or an injected FBI into H&S.

Referenced - https://github.com/Steveice10/FBI/issues/64

**Comment by Steveice10** [comment]
Try v2.2.1.

**Comment by Casporro** [comment]
Sometimes it happens that freezes or the bottom screen stays in black...
I'm using the latest version...

**Comment by copyitright** [comment]
Another 2.2.1 user facing the same problem when installing certain .cia's using H&S FBI

**Comment by cheatfreak47** [comment]
I'm experiencing freezes and black screens in the Title list sometimes

**Comment by MAXAITA** [comment]
yesterday intalling the black screen appeared

**Comment by EpicZ501** [comment]
Homebrew isn't 100% compatible with certain apps. Your best bet is to wait for an update or if you can code try fixing it yourself (but good luck).

**Comment by copyitright** [comment]
2.2.1 seems to have solved/eliminated my freezing/black screen issues (knock on wood) :-)

**Comment by MAXAITA** [comment]
No de 2.2.1 present the black screen sometimes

**Comment by zenkilye** [comment]
2.2.1 working fine on my A9LH Luma O3DS, but still get freeze and black screen frequently on my N3DS with same setup

**Comment by OTFree** [comment]
Running FBI 2.2.1 on N3DS and 2DS (Luma3DS CFW Sysnand 9.2/11). It seems that larger Cias (around 1GB or more) freeze more frequently, but I'll occasionally get a freeze regardless. I've successfully been able to install many cia files, but one in particular is having sporadic consistent freezes/black screens no matter how many attempts.

**Comment by Steveice10** [comment]
Out of curiosity, can the people experiencing this issue post what type of device (O3DS, 2DS, or N3DS) they specifically experienced this issue on?

**Comment by OTFree** [comment]
N3DS and N3DSXL, I haven't experienced this issue on my 2DS.

**Comment by MAXAITA** [comment]
my in n3ds xl

**Comment by OTFree** [comment]
Small update: I had a theory that maybe the installation stalls on N3DS
because the processor hangs. To test this, I would put it in sleep mode
during a CIA installation on occasion, just to keep the system active.

Since I've started doing this method, I have NEVER encountered this issue
again, even with install files over 1gb. It's a bit inconvenient until a
proper bug fix is found, but far less inconvenient than having FBI freezing
constantly, having to reboot, and trying again just for it to keep
happening.
On May 17, 2016 10:25 PM, "MAXAITA" <notifications@github.com> wrote:

my in n3ds xl

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/Steveice10/FBI/issues/89#issuecomment-219908625>

**Comment by Steveice10** [comment]
Looks like it might be N3DS related, which should help in narrowing it down.

**Comment by OTFree** [comment]
Definitely seems to be the recurring theme haha. In any case, thank you for
all your hard work! I hope a fix is something in the near future, but in
the meantime, my work around method shall suffice for bigger cia
installations.

**Comment by cheatfreak47** [comment]
Yeah I was having the issue on my New 3DS as well, so that seems to be it.

**Comment by Steveice10** [comment]
Might be worth it to try this build, which explicitly disables the N3DS cache/speed boost. https://www.dropbox.com/s/ufvyl5o7n4c4ykn/FBI.zip?dl=0

On that note, are any of you using a CFW's CPU clock speed-up options?

**Comment by OTFree** [comment]
Thank you for the link, I'll definitely give it a try and report back!

Yes, I'm running Luma3DS CFW and have Clock+L2 on by default.

Question, if I disable it myself in the Luma3DS config menu, can I stick
with the build of FBI I'm already using (2.2.1) or should I still download
the build you linked regardless?

**Comment by Steveice10** [comment]
@OTFree Could you try running your current build with clock speed/cache enhancements disabled, and run the build I posted if that doesn't help?

**Comment by OTFree** [comment]
Sure, I was considering that as well just for the sake of compare and
contrast. I'll report back here with my results as soon as I can get around
to it!

**Comment by Steveice10** [comment]
Thinking about it more, the build I posted might help with clock speed/cache enhancements being enabled, as, at least in Luma3DS, the patches seem target CPU configuration on title load, which means I can still disable it afterwards.

**Comment by OTFree** [comment]
Ohhh, I think I followed that right. So I should test this build with the
speed up cache still enabled and see if the problem is replicated?

**Comment by Steveice10** [comment]
I guess I would, in any order:
* Test to see how the old build fares with CPU speed patches disabled.
* Test to see how the new build fares with CPU speed patches enabled.

**Comment by MAXAITA** [comment]
no i used the normal speed

**Comment by OTFree** [comment]
@Steveice10/FBI Sounds like a plan, boss; will report back with results.

Quick question, what is the best way to go about updating FBI, or is the
only method to reinject it? (Sorry for the admittedly newbish question,
relatively new to 3DS CFW)

**Comment by Steveice10** [comment]
@OTFree You should be able to install a newer FBI CIA from within FBI itself.

**Comment by OTFree** [comment]
Gotcha, so just go to network install I'm assuming?

**Comment by Steveice10** [comment]
Yeah.

**Comment by OTFree** [comment]
Tried installing a 1.8gb cia on old build with speed up disabled, crashed
around 800mb in.

Trying to update to latest build via Network Install...but it's just stuck
on "waiting for connection". There's nothing wrong with my Wi-Fi.

Am I missing a step?

**Comment by Steveice10** [comment]
L2 is disabled as well, right?

**Comment by OTFree** [comment]
Yes. Still results in freeze crash.

But yeah, I'm willing to test the other build. Can I install the latest cia
using FBI itself?

**Comment by Steveice10** [comment]
Should be able to.

**Comment by OTFree** [comment]
Alright, I'm back with an update and the results are...mixed.

After updating FBI to the latest build and reenabling Clock+L2, I was able
to install the cia that gave me trouble on the first try with no issues.

However, I got the bottom black screen when trying to install a second cia
just as it was nearly finished.

So I guess it's safe to say the new build is slightly more stable, but the
bug is still present.

**Comment by zenkilye** [comment]
Alright guys,

Tried to install more CIA recently and noticed it is only GUI crash. When freeze happened, GUI stopped at 40%, I leave the 3DS and come back 1 hour later, GUI still freeze and I did a reboot. And surprisingly the cia was installed, app was able to run without issue

I also encounter a black out on lower screen in another cia installation, I did the same: estimate the waiting time, wait for it to complete. After reboot, cia was installed correctly.

Conclusion: GUI freeze on N3DS
Hope it help

**Comment by urherenow** [comment]
Hmmm... Problem with a buffer? But that wouldn't be limited to N3DS, unless there is separate code to take advantage of extra memory.

**Comment by xuefer** [comment]
exactly same as zenkilye happens here too. with more detail: the SocketPush client pushed everything saying 100%
i was not sure if the rom is installed completely as there're no way i know to verify that and i was thinking the possibility that client says 100% just because it sents everything not because FBI as write fully (when buffer come into play)
but if the client says 100% while FBI UI says far less than 100%, then it's not buffer that confuse. so can we assume it's GUI free on 3ds side?

**Comment by OTFree** [comment]
Sorry for the late reply, but I can also attest to this. I had two
consistent bottom black screens when installing two different cias, and
both times it happened, I just waited about a half hour each under the
assumption enough time for the installation had passed.

Just as @xuefer said, upon reboot, the cias installed correctly both times.
This seems to support the theory that it's just a N3DS GUI crash, but the
install isn't frozen.

**Comment by chinhodado** [comment]
Same here. Using N3DS on 11 with latest Luma and A9LH, installed 2 cia, one froze at 1.2/1.8GB, and one froze at 1.8/3.3GB. I left both running on for quite a while after they froze, and the cia were installed correctly both times. So definitely this is a GUI issue.

Edit: I'm installing a 1GB cia right now and just got a black screen. Will wait for about 30 minutes then reboot and see if the cia install correctly.

**Comment by Sebaatd** [comment]
I assume it's a GUI issue, mine froze installing too but I could see the orange light blink when a friend went online.
Now, I turned it off in the middle of the installation because the freeze, so it didn't finish. Is it harmful for the sd card or the console?

**Comment by xuefer** [comment]
This time it not just hang during transfer, but also crash. the device shows hang message (black background with white text, saying "home" something), when i press home it wait a few seconds before reboot into home

**Comment by OTFree** [comment]
Wait...so the update made the problem worse?

**Comment by xuefer** [comment]
maybe. i don't know if there's any backtrace/coredump like linux do. it happens twice in a row but success in the 3rd time, seems random

**Comment by xadox-1st** [comment]
Still freezing sometimes while installing CIA's using 2.2.3.

**Comment by dbw-holic** [comment]
This is an ongoing issue. I have been having this freeze issue, on occasion, started from 1.4.7
I normally install CIAs from memory card straightaway, to avoid unexpected network issues.
In fact, when you experience this screen freezing issue, if you can be a little patient, FBI is still running, but the GUI freezes. 
I help people install A9LHax, hence I have a number of samples of this occurrence. This issue happens regardless with console model, nor firmware / FBI version. It is more likely to get reproduced when you work on a o3DS, performing batch installation from a folder, say, install 15 CIA files at a time, cross finger, it will be very likely to surprise you with a freeze screen. 
When it freezes, it still respond to key buttons, I normally leave it for enough time, then Press button B, and cold reboot the console. You will find all the expected homebrews/games are installed correctly. I have seen it on more than 15 different consoles.

**Comment by Steveice10** [comment]
Can anyone verify if this issue still exists on 2.3.1? I haven't been able to reproduce after a few tries installing an FBI CIA inflated to 1GB.

**Comment by cheatfreak47** [comment]
I'll try to reproduce it myself, I haven't noticed any such issue since about 2.2 myself but I haven't been using FBI all that much, truth be told.

**Comment by OTFree** [comment]
Hey, long time no see! Safe to say this issue is fixed. I just updated to
2.3.1, and installed 10 cias back to back (some of which were over 2gb
individually), and not once was there a freeze.

**Comment by zephyrkun** [comment]
I am on FBI 2.4.8 and have this issue on an old 3dsxl, trying to install a csi over 2gb, have the issue were it crashes, haven't had the black screen tho. tried many times, will try the trick of leaving it to see if its only the gui that crashes.
