### ISSUE TITLE
CDN Install failing with "error 404"

### ISSUE THREAD

**Issue by NinjaBoyLao** [Steveice10/FBI#91]
I view a ticket, select install from cdn, then it shows a loading bar, the screen hangs a bit, then it freezes and says "failed to install cdn title, http server returned the response code 404", followed by an option for "okay (any button)". happens on all tickets

**Comment by Steveice10** [comment]
Can you try v2.2.1?

**Comment by NinjaBoyLao** [comment]
I'm on 2.2.1, it's still doing that. i know for a fact my internet works, im using sploit_installer just fine, as well as other online applications

**Comment by Steveice10** [comment]
What is the ID of the title you are trying to download?

**Comment by NinjaBoyLao** [comment]
LoZ Minish Cap initially, (see: Ambassador's Program), but it fails with SSB4 and ORaS too. I'm 100% sure i have enough space with a 16gb sd and emunands 64k partitioning

**Comment by Steveice10** [comment]
Working fine here, with one of the titles you mentioned. Are you *sure* you're on 2.2.1?

**Comment by NinjaBoyLao** [comment]
absolutely positive, i din't even bother with injecting that one just so i could test if it was being inside h&s that was killing it. might be my network but last i checked i had only filtered out malware sites and shit

**Comment by NinjaBoyLao** [comment]
It's still doing it.. i've cleared out health and safety and it's back to stock, and i'm using 2.2.1 from the home menu as a regular cia. the eshop works still, and if i install a ticket in fbi then it shows up in the eshop, and i can download the title. (colors! 3D because its near the top of /that page/). FunKeyCIA is pulling the cia just fine still, and i've tested it on several public networks as well as my home network. no weird settings in any of the wifi connections.
