### ISSUE TITLE
failed to compile on latest(5c13b54) on windows

### ISSUE THREAD

**Issue by al3x10m** [Steveice10/FBI#92]
libctru is updated and citro3d aswell
http://pastebin.com/3q0DpdFB

**Comment by urherenow** [comment]
Not really. There is a pending pull request for libctru. It might be needed...

**Comment by al3x10m** [comment]
hmm..i could wait :D

**Comment by usineur** [comment]
I can confirm, if you want to build the latest version of FBI, you need to use the ctrulib's fork of Steveice10

**Comment by al3x10m** [comment]
ok then...i guess this issue is closed :P
