### ISSUE TITLE
Can't copy files to CTR NAND from SD with FBI 2.1.1

### ISSUE THREAD

**Issue by thedax** [Steveice10/FBI#93]
I'm on a New 3DS XL, with ARM9LoaderHax and sysNAND 10.7, along with a 64GB uSD, formatted to FAT32 with 64k clusters.

Whenever I try to copy any files from the SD card to CTR NAND, FBI refuses with the following error:

Failed to paste content.
/injector.cxi (or any other file, it doesn't matter)
Result code: 0xC8804478
Level: Status (25)
Summary: Not found (4)
Module: FS (17)
Desc: Doesn't exist / Failed to open (120)

I don't really see how the file is "not found" when it's on the root of my SD card and I can open it just fine when my CFW loads, as well as when I view the contents of the SD card on my PC.

**Comment by Steveice10** [comment]
Try updating to 2.2.1. Copying to CTR NAND works fine for me there.

**Comment by thedax** [comment]
Oops, I didn't notice there's a new release. I'll try it now.

**Comment by thedax** [comment]
That worked. Sorry for the false alarm.
