### ISSUE TITLE
Features to prevent screen burn-in

### ISSUE THREAD

**Issue by RShadowhand** [Steveice10/FBI#94]
Implementing any of the following would be awesome and would prevent burn-ins on the screen:
- Continue installing when the lid is closed (for installing from SD)
- Make screens go pitch black(or turn off brightness) on (for installing from SD or through wifi)
 - Button press
 - After 1 or 3 minutes of inactivity

**Comment by Steveice10** [comment]
Implemented the former, pending a ctrulib pull request.

**Comment by RShadowhand** [comment]
I wish you had done the latter, that one would fix both remote and local installs.
