### ISSUE TITLE
Suggesting a switch button for advance functions or basic functions

### ISSUE THREAD

**Issue by liangziqi124** [Steveice10/FBI#95]
I haven't noticed for updates for quite a long time since  ver 1.4.17
I've heard that the issues about DLCs are fixed since a previous version, but now I think the latest versions have infalted too much... so many features like CTR dir, TWL dir, Tickets, Save data (for which i use savedatafiler instead) are, fairly, not so commonly used... Still, features like Titles managing, Network install are good things.
The version 2.2.1 I try this moment has really frightened me while the list showed up where the number of functions  has grown to be 13.
So, would it be better if there is a switch button like L/R that allows to hide/show some advanced functions?

**Comment by Steveice10** [comment]
Could you explain how this would be useful? If you're not looking to use a certain feature, you aren't being forced to.

**Comment by liangziqi124** [comment]
Well in fact, this would not be some kind of "useful" but "amical", to make the UI more "friendly".

**Comment by Steveice10** [comment]
But how would removing the options make the UI friendly? What exactly is the problem with them being present when you can just not use them.

**Comment by MAXAITA** [comment]
but one sometimes lends its 3ds their children then they can generate a problem


please thinking.

**Comment by deadair3210** [comment]
Perhaps not change the options, but would it be possible to set it so that FBI can be handled by the parental controls that are built into the 3ds?

**Comment by Steveice10** [comment]
Made it so parental controls will apply to launching FBI, requiring you to enter your PIN if it is enabled.
