### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by deadair3210** [Steveice10/FBI#97]
Would it be possible to add a selection to the ticket install menu that will make FBI delete the currently installed ticket before installing the one on the sd card? Installed tickets that are installed through one way or another makes future installs of the ticket fail

**Comment by Steveice10** [comment]
Why would you need to reinstall the ticket if you already have it installed?

**Comment by deadair3210** [comment]
To correct errors, such as when a cia is installed that has a bad ticket

**Comment by Steveice10** [comment]
Implemented in latest source.

**Comment by deadair3210** [comment]
Thank you

**Comment by deadair3210** [comment]
When is the next release going to be, I cannot build currently due to problems with my computer

**Comment by Steveice10** [comment]
I have no ETA.
