### ISSUE TITLE
Batch install of tickets will only accept 1048 tickets at a time.

### ISSUE THREAD

**Issue by deadair3210** [Steveice10/FBI#98]
If you have a folder of 1048+ tickets and attempt to install all the tickets in the folder using the option install and delete tickets, the install will only take up to the first 1048, and will not show the remaining tickets in the folder afterwards until you back out of and re-enter the folder

**Comment by ApacheThunder** [comment]
Why in gods name would you ever need that many tickets? I recall you can't even install more then 300 titles before new titles no longer show up on Home Menu... :P

**Comment by Steveice10** [comment]
As @ApacheThunder stated, you can't even have that many titles on the home menu.

**Comment by deadair3210** [comment]
Not installing the games themselves, just the tickets. I realize that there is a limit to how many actual titles you can have installed, but AFAIK there is no such limit on the amount of tickets installed

**Comment by Steveice10** [comment]
There's no point to having all of those tickets installed, though. If you *really* want to, just split your listing into two folders.

**Comment by deadair3210** [comment]
Thats what i have been doing, either that or just dealing with it and reentering the folder. Just figured i should report the bug either way

**Comment by ApacheThunder** [comment]
Doesn't the file that stores the tickets have a fixed size? You are probably also running up against a hard limit on the system as well and may not be an issue solely with FBI. :P

**Comment by deadair3210** [comment]
You might be right about the fixed file size. Do you know what file it is, i can check between my 3ds and one i just set up and see if the files are the same size

**Comment by ApacheThunder** [comment]
CTRNAND://dbs/ticket.db stores the tickets I believe. It's around 36 MB or so. I've never seen it deviate from that file size.

**Comment by deadair3210** [comment]
mine is 35.50 MB on my 3ds so you are probably right. surely they wouldnt use a fixed file size considering how important that file is, right?

**Comment by ApacheThunder** [comment]
Given the size of a single ticket. 35MB is pretty large. But yes I don't think the size changes. There is probably a fixed limit on how many it can store. Nintendo just assumed that no one in their right mind would ever be able to "purchase" enough games to hit that limit since the limit is probably in the thousands/the limit you just hit. :P

**Comment by deadair3210** [comment]
the only weird thing about your theory is that i can still install more tickets if i attempt to. it looks as though either something is amiss with the system call or FBI isnt parsing past a certain number of tickets in the folder

**Comment by Steveice10** [comment]
There's a limit on how big the buffer is for FBI to load file entries into. That's the limit you're hitting.

**Comment by deadair3210** [comment]
aah ok, i figured it was either a buffer issue, or something like that. Thanks for the explanation.
