### ISSUE TITLE
Ticket install does not replace existing ticket

### ISSUE THREAD

**Issue by kingiix** [Steveice10/FBI#99]
When installing a ticket that is already existing (ie. to replace a bad ticket with a good one) FBI will show a successful install yet will not actually replace the ticket, nor does it give any indicator of the fact. Need to delete the old ticket before installing the new one.

**Comment by urherenow** [comment]
I've always observed the same behavior when installing older firmware files as well. Get prompted to delete the old one first, but the install doesn't happen. Always have to install a second time (so the deleting part does work, in that case, just not the install after the delete.

**Comment by Steveice10** [comment]
Already taken care of in latest source.
